{
  "hash": "cb27fea3869370f35dbb2b658a50efb1",
  "result": {
    "markdown": "---\ntitle: 'Linear Regression with Categorical Variables'\n---\n\n\n\n\n\n## The Promise From Last Chapter\n\nThe last chapter said the outcome has to be quantitative but the predictors are far less picky, and that we would start feeding regression categorical variables on purpose.\n\nThis is that chapter.\n\nThe question is genuinely strange the first time you meet it. Regression multiplies a predictor by a slope, and you cannot multiply \"Texting\" by 0.34. So how does a model built entirely out of arithmetic handle a variable whose values are words?\n\nThe answer is that we translate the words into numbers, in a way specific enough that the slopes still mean something afterward. Do that and something quietly excellent falls out: the t-test you learned in Part 1 turns out to have been a regression the whole time, wearing a disguise.\n\n## Distracted Driving\n\nDriving requires constant attention. When something unexpected happens—such as a car braking suddenly—you must react quickly. Psychologists studying attention have shown that distractions slow reaction time. One of the most dangerous distractions is texting while driving.\n\nThe data in this chapter are simulated. Do not reproduce the study by handing undergraduates phones, placing them in actual traffic, and chasing the car with a chainsaw to improve ecological validity. Use a simulator and an ethics-approved protocol. The Institutional Review Board enjoys fewer surprises than the Probability Gods.\n\nIn this example we examine **braking reaction time** (seconds) under different driving conditions\n\nReaction time is measured in seconds. Larger values indicate slower reactions.\n\n### Dummy Coding\n\nWhen a predictor is categorical, regression cannot use the labels directly.  \nRegression requires numbers, so the categories must be translated into numeric variables. \n\nThis process is called **dummy coding**. It is the most common coding scheme, and the **default used by R** whenever it detects a factor.\n\n### Dummy Coding Details\n\nDummy coding compares each group to a **reference group**.\n\nThe reference group serves as the **baseline** or **zero point** for the model.  \nAll other groups are interpreted relative to that baseline.\n\nIn other words, the model asks: *How much does each group deviate from the reference group?*\n\n\n## Two-Level Example\n\nSuppose we conduct a study comparing two driving conditions: **No distraction** vs **Texting while driving**\n\nWe collect data for: $n = 30$ drivers per group (*dataframe = dat2*)  \n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\nWe have two driving conditions (and predict):\n\n| Condition | Reaction Time |\n|-----------|---------------|\n| No distraction | faster |\n| Texting | slower |\n\nTo represent this in regression, we create a dummy variable.\n\n| Variable | C1 |\n|---------|---|\n| No Distraction | 0 |\n| Texting | 1 |\n\nHere:\n\n- **0 represents the reference group**\n- **1 represents the comparison group**\n\nSo the dummy variable indicates whether a driver is texting.\n\n### How This Connects to Regression\n\nThe regression model becomes\n\n$$\nRT = b_0 + b_1C_1\n$$\n\nInterpretation:\n\n- $b_0$ = the mean reaction time for the **reference group**\n- $b_1$ = how much the **Texting** group differs from that reference group\n\n### Predicted Values\n\nFor **No Distraction**:\n\n$C_1 = 0$\n\n$$\nRT = b_0\n$$\n\nFor **Texting**:\n\n$C_1 = 1$\n\n$$\nRT = b_0 + b_1\n$$\n\nSo the regression coefficients directly reproduce the group means.\n\n### Important\n\nIn R, you usually **do not need to create dummy variables yourself**.\n\nWhen a predictor is stored as a **factor**, R automatically creates the dummy-coded variables internally when fitting the model.\n\nThe **first level of the factor becomes the reference group**.\n\nFor example:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat2$Condition <- factor(dat2$Condition,\n                         levels = c(\"No Distraction\", \"Texting\"))\n```\n:::\n\n\n\nBecause `\"No Distraction\"` appears first, it becomes the **reference group**.\n\nThis means:\n\n- the **intercept equals the mean reaction time for No Distraction**\n- the **ConditionTexting coefficient represents the difference between Texting and No Distraction**\n\n\n### Comparing the Groups with a t-test\n\nWe first test the hypothesis that texting increases reaction time.\n\nFirst we load the packages needed for this example.\n\n- **tidyverse**: used for data manipulation and summarizing the data  \n- **apa**: used to produce APA-style statistical output\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(apa)\nlibrary(tidyverse)\n```\n:::\n\n\n\n### Calculate Group Means and Standard Deviations\n\nBefore running a statistical test, it is always good practice to examine the descriptive statistics.\n\nThe code below calculates the **mean (M)** and **standard deviation (SD)** of reaction time for each condition.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat2 %>%\n  group_by(Condition) %>%\n  summarise(\n    M = mean(RT),\n    SD = sd(RT)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 x 3\n  Condition          M    SD\n  <fct>          <dbl> <dbl>\n1 No Distraction 0.664 0.137\n2 Texting        1.01  0.121\n```\n:::\n:::\n\n\n\nThis gives us a quick summary of how reaction time differs across the two driving conditions.\n\n\n### Run the Independent Samples t-test\n\nNext we test whether the difference between groups is statistically significant.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntexting.ttest <- t.test(RT ~ Condition,\n                        data = dat2,\n                        var.equal = TRUE)\n```\n:::\n\n\n\nReminder:\n\n- `RT ~ Condition` tells R we are predicting **reaction time** from the **driving condition**\n- `data = dat2` specifies which dataset to use\n- `var.equal = TRUE` assumes equal variances across groups (the standard Student t-test)\n\n\n### Print the Results in APA Format\n\nFinally, we format the results in **APA style** using the `apa` package.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napa(texting.ttest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"*t*(58) = -10.21, *p* < .001, *d* = -2.64\"\n```\n:::\n:::\n\n\n\n### APA write up\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nDrivers who texted while driving had significantly slower reaction times ($M =$ 1.01, $SD =$ 0.12) than drivers with no distraction ($M =$ 0.66, $SD =$ 0.14), $t(58) =$ -10.21, $p < .001$, $d =$ -2.64, indicating that texting substantially increased reaction time.\n\n**Small note**: the negative sign on $t$ simply reflects the order of subtraction (No Distraction minus Texting).\n\n::: {.callout-warning title=\"A d of 2.6 Should Be Making You Suspicious\"}\nBy now you have read the power chapter, so that effect size should raise an eyebrow. Real texting-while-driving effects are large, which is exactly why it is illegal, but they are not science-fiction large. Published estimates sit closer to $d$ of 0.5 to 1.\n\nI built this simulation to make the pictures come out clean. Simulated data lies politely, and it will happily calibrate your intuitions to a world that does not exist.\n:::\n\n### The Same Analysis Using Regression\n\nNow we run the equivalent regression model.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel2 <- lm(RT ~ Condition, data = dat2)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = RT ~ Condition, data = dat2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.31427 -0.09282 -0.00903  0.08735  0.34813 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       0.66388    0.02362   28.11  < 2e-16 ***\nConditionTexting  0.34115    0.03340   10.21 1.41e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1294 on 58 degrees of freedom\nMultiple R-squared:  0.6427,\tAdjusted R-squared:  0.6365 \nF-statistic: 104.3 on 1 and 58 DF,  p-value: 1.412e-14\n```\n:::\n:::\n\n\n\n### Why Are the t-values the Same?\n\nStop and compare two numbers before going any further, because this is the whole point of the section.\n\nIn the `ConditionTexting` row above: $t =$ 10.21, $p < .001$.\n\nBack in the t-test: $t =$ -10.21, $p < .001$.\n\nSame magnitude, opposite sign. Not similar. *Identical.*\n\nThe sign flip is bookkeeping: `t.test()` subtracted in the order No Distraction minus Texting, and the regression reports Texting relative to No Distraction. Everything else matches because the two procedures are doing the same arithmetic:\n\n- The regression slope **is** the difference between the group means.\n- Its standard error **is** the pooled standard error of that difference.\n- Dividing one by the other is precisely what the t-test did.\n\nOne condition on that equivalence, and it is worth naming. It holds because we ran the t-test with `var.equal = TRUE`. Ordinary regression assumes one common residual variance across groups, which is the same assumption the pooled Student t-test makes. Ask for Welch's version instead, which does not assume that, and the match breaks. This is the other side of the Welch discussion from the independent-samples chapter.\n\nThe regression equation is\n\n$$\nRT = b_0 + b_1X\n$$\n\nInterpretation:\n\n- $b_0$ = mean reaction time for **No Distraction**\n- $b_1$ = difference between **Texting** and **No Distraction**\n\nBecause the dummy variable for No Distraction is 0:\n\nFor No Distraction\n\n$$\nRT = b_0\n$$\n\nFor Texting\n\n$$\nRT = b_0 + b_1\n$$\n\nSo the intercept is simply the mean reaction time for the reference group.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     (Intercept) ConditionTexting \n       0.6638792        0.3411475 \n```\n:::\n:::\n\n\n\nWhich gives us:\n\n| Coefficient | Value |\n|--------------|------|\n| Intercept | 0.664 |\n| ConditionTexting | 0.341 |\n\nNow we can reconstruct the means.\n\n### No Distraction\n\n$$\nRT = b_0\n$$\n\n$$\nRT = 0.664\n$$\n\nSo the predicted mean reaction time is **0.664 seconds**.\n\n### Texting\n\n$$\nRT = b_0 + b_1\n$$\n\n$$\nRT = 0.664 + 0.341\n$$\n\n$$\nRT = 1.005\n$$\n\nSo the predicted mean reaction time is **1.005 seconds** for texting while driving.\n\nThese values match the observed group means from the data.\n\n**Regression coefficients are simply another way of expressing the group means and their differences.**\n\n\n### Extracting the Means with `emmeans`\n\nWe can also extract the model-estimated means so we do not have to reconstruct them manually from the regression equation.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\n\nemmeans(model2, ~ Condition)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Condition      emmean     SE df lower.CL upper.CL\n No Distraction  0.664 0.0236 58    0.617    0.711\n Texting         1.005 0.0236 58    0.958    1.052\n\nConfidence level used: 0.95 \n```\n:::\n:::\n\n\n\n### What the Code Does\n\n`library(emmeans)` loads the **emmeans** package. This package is designed to extract and compare means from statistical models such as regression.\n\n`emmeans(model2, ~ Condition)` tells R:\n\n- use the regression model **model2**\n- estimate the means for each level of **Condition**\n\nThe `~ Condition` part means:  \n*compute the means for the variable Condition.*\n\n\n### What \"Estimated Marginal Means\" Means\n\nThe name **emmeans** stands for **Estimated Marginal Means**.\n\nEstimated marginal means are the **means predicted by the statistical model**.\n\nWhy *marginal*? Before computers did all this instantly, people wrote the means in the margins of tables using actual pencils. They were Number 2 pencils, naturally---the same pencils you never remember to bring to my exams. iPads are new. Most of the old people who write R packages or statistics books were born in the 1900s and are older than the internet.\n\nIn this simple example, they correspond directly to the group means:\n\n| Condition | Predicted Mean |\n|-----------|---------------|\n| No Distraction | $b_0$ |\n| Texting | $b_0 + b_1$ |\n\nSo `emmeans()` is simply doing the same math we just performed manually:\n\n- extracting the intercept\n- adding the appropriate regression coefficients\n- reporting the predicted group means\n\n\n### Why This Is Useful\n\nFor simple models like this one, calculating the means by hand is straightforward.\n\nHowever, as models become more complex (for example, with multiple predictors or interactions), manually reconstructing the means becomes tedious.\n\n`emmeans` provides a convenient way to:\n\n- extract the model-based means\n- compare groups\n- obtain confidence intervals\n- perform additional tests\n\nAll while keeping the results tied directly to the regression model.\n\n\n### Testing the Difference with `emmeans`\n\nWe can also test the difference between groups directly from the regression model using `emmeans`.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairs(emmeans(model2, ~ Condition))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n contrast                 estimate     SE df t.ratio p.value\n No Distraction - Texting   -0.341 0.0334 58 -10.213 <0.0001\n```\n:::\n:::\n\n\n\n### What the Code Does\n\nThe function `emmeans(model2, ~ Condition)` first computes the **estimated marginal means** for each level of the factor **Condition** based on the regression model.\n\nThe function `pairs()` then compares those means to one another.\n\nIn this case, there are only two conditions, so the function tests the difference between:\n\n- **Texting**\n- **No Distraction**\n\n\n### How This Connects to the Regression Model\n\nRecall that the regression equation is\n\n$$\nRT = b_0 + b_1X\n$$\n\nwhere\n\n- $b_0$ = mean reaction time for **No Distraction**\n- $b_1$ = difference between **Texting** and **No Distraction**\n\nThe comparison performed by `pairs()` is therefore testing whether:\n\n$$\nb_1 = 0\n$$\n\nIf $b_1$ is significantly different from zero, the two groups have different mean reaction times.\n\n\n### Comparison to t-test\n\nEven though the output may look similar to a t-test, the comparison is now being computed **within the regression framework**.\n\nThe means and the group comparison are both derived directly from the fitted regression model.\n\n\n### APA Regression Write up\n\nDrivers who texted while driving had significantly slower reaction times than drivers with no distraction. Relative to this reference group (no distractions), the Texting condition increased reaction time by 0.34 seconds, $b =$ 0.34, $SE =$ 0.03, $t(58) =$ 10.21, $p < .001$. The model explained a substantial proportion of variance in reaction time, $R^2 =$ .64, $F(1, 58) =$ 104.31, $p < .001$, indicating that differences in driving condition accounted for about 64% of the variability in reaction times across drivers.\n\n\n### Plotting the Model-Estimated Means\n\nWe can also visualize the model-estimated means returned by `emmeans`.\n\nFirst we store the estimated means in an object.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmeans <- emmeans(model2, ~ Condition)\n\nmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Condition      emmean     SE df lower.CL upper.CL\n No Distraction  0.664 0.0236 58    0.617    0.711\n Texting         1.005 0.0236 58    0.958    1.052\n\nConfidence level used: 0.95 \n```\n:::\n:::\n\n\n\nTo make plotting easier, we convert the results into a data frame.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmeans_df <- as.data.frame(means)\n\nmeans_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Condition         emmean       SE df  lower.CL  upper.CL\n No Distraction 0.6638792 0.023619 58 0.6166006 0.7111577\n Texting        1.0050267 0.023619 58 0.9577482 1.0523053\n\nConfidence level used: 0.95 \n```\n:::\n:::\n\n\n\nThe data frame contains:\n\n- `emmean` = the estimated mean\n- `lower.CL` = lower confidence interval\n- `upper.CL` = upper confidence interval\n\nNow we can quickly plot these values using **ggplot**.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(means_df, aes(x = Condition, y = emmean)) +\n  geom_col() +\n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = .1) +\n  ylab(\"Reaction Time (seconds)\") +\n  xlab(\"Driving Condition\")+theme_bw()\n```\n\n::: {.cell-output-display}\n![Model-estimated mean reaction time in each condition, with 95% confidence intervals. The bars come straight out of the regression.](Chapter_Regression-with-Cat-Variables_files/figure-pdf/two-level-means-plot-1.pdf){fig-align='center' fig-alt='Bar chart with two bars, No Distraction at about 0.66 seconds and Texting at about 1.01 seconds, each with a narrow error bar. The Texting bar is clearly taller and the intervals do not overlap.'}\n:::\n:::\n\n\n\nThis plot shows the **model-estimated means and their 95% confidence intervals**.\n\nBecause the means come from `emmeans`, the figure directly represents the regression model we fit earlier.\n\n\n## Three-Level Example\n\nNow suppose we repeat the study but add a third condition:\n\n**Listening to a statistics lecture while driving to class.**\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n### Factoring the Three-Level Predictor\n\nAgain we convert the predictor to a factor.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat3$Condition <- factor(dat3$Condition,\n                         levels = c(\"No Distraction\",\n                                    \"Texting\",\n                                    \"Lecture\"))\n\nlevels(dat3$Condition)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"No Distraction\" \"Texting\"        \"Lecture\"       \n```\n:::\n:::\n\n\n\nThe first level becomes the reference group.\n\nSo again:\n\n```\nNoDistraction = reference (0)\n```\n\nR now creates **two dummy variables** internally.\n\nConceptually this looks like:\n\n| Condition | Texting | Lecture |\n|-----------|--------|--------|\n| No distraction | 0 | 0 |\n| Texting | 1 | 0 |\n| Lecture | 0 | 1 |\n\n\n### Multiple t-tests Problem\n\nIf we used t-tests, we would need three comparisons:\n\n1. No distraction vs texting  \n2. No distraction vs lecture  \n3. Lecture vs texting  \n\nRunning multiple tests increases the probability of a **Type I error**.\n\nIf $\\alpha = .05$, then the probability of at least one false positive ($1-(1-\\alpha)^j$) [$j$ = # of t-tests]: \n\n$$\n1 - (1 - .05)^3\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n1 - (1 - .05)^3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.142625\n```\n:::\n:::\n\n\n\nThis is about **14%**, much larger than the intended 5%.\n\nRegression helps here, but it is worth being precise about how, because the honest version is less magical than it sounds. Fitting one model does not delete the multiple-testing problem. What it does is organize every comparison under a single model and hand you a **gatekeeper**: one overall test of whether the group means differ at all, which you check *before* going looking for which pairs differ. That gate is the omnibus $F$, and we are about to meet it.\n\n\n### Regression with Three Groups\n\nRegression allows us to test all comparisons within a single model.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel3 <- lm(RT ~ Condition, data = dat3)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = RT ~ Condition, data = dat3)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.31427 -0.09670 -0.00662  0.07988  0.34813 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       0.66388    0.02380  27.898  < 2e-16 ***\nConditionTexting  0.34115    0.03365  10.137  < 2e-16 ***\nConditionLecture  0.19229    0.03365   5.714 1.52e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1303 on 87 degrees of freedom\nMultiple R-squared:  0.5429,\tAdjusted R-squared:  0.5323 \nF-statistic: 51.66 on 2 and 87 DF,  p-value: 1.63e-15\n```\n:::\n:::\n\n\n\n### The Gate: the Omnibus F\n\nLook at the very last line of that output, the one everybody scrolls past:\n\n`F-statistic: 51.66 on 2 and 87 DF`\n\nThat is the gatekeeper. It tests one null hypothesis: **all three group means are equal**. Not \"texting differs from no distraction,\" not any particular pair, just whether there is any difference anywhere in the set.\n\nOurs is $F(2, 87) =$ 51.66, $p < .001$, so the gate is open. Something in there differs, and we have earned the right to go find out what.\n\nHad that $F$ come back non-significant, the honest move is to stop. The means are not distinguishable, and hunting through pairs anyway is precisely the 14% problem we just calculated, now with extra steps.\n\nThe model is\n\n$$\nRT = b_0 + b_1(\\text{Texting}) + b_2(\\text{Lecture})\n$$\n\nInterpretation:\n\n- $b_0$ = mean reaction time for **No Distraction**\n- $b_1$ = difference between **Texting** and **No Distraction**\n- $b_2$ = difference between **Lecture** and **No Distraction**\n\n\n### Reconstructing the Group Means from the Regression Model\n\nRecall that the regression model is\n\n$$\nRT = b_0 + b_1(\\text{Texting}) + b_2(\\text{Lecture})\n$$\n\nFrom the model output we obtained the following coefficients:\n\n| Coefficient | Value |\n|-------------|------|\n| $b_0$ (Intercept) | 0.664 |\n| $b_1$ (Texting) | 0.341 |\n| $b_2$ (Lecture) | 0.192 |\n\nAgain, the intercept represents the **mean reaction time for the reference group**, which is **No Distraction**.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     (Intercept) ConditionTexting ConditionLecture \n       0.6638792        0.3411475        0.1922929 \n```\n:::\n:::\n\n\n\n\n### No Distraction\n\nFor the reference group, both dummy variables equal 0.\n\n$$\nRT = b_0\n$$\n\nSubstituting the coefficient:\n\n$$\nRT = 0.664\n$$\n\nSo the predicted mean reaction time for **No Distraction** is **0.664 seconds**.\n\n\n### Texting\n\nFor the texting group:\n\nTexting = 1  \nLecture = 0\n\n$$\nRT = b_0 + b_1\n$$\n\nSubstituting the coefficients:\n\n$$\nRT = 0.664 + 0.341\n$$\n\n$$\nRT = 1.005\n$$\n\nSo the predicted mean reaction time for **Texting** is **1.005 seconds**.\n\n\n### Lecture\n\nFor the lecture group:\n\nTexting = 0  \nLecture = 1\n\n$$\nRT = b_0 + b_2\n$$\n\nSubstituting the coefficients:\n\n$$\nRT = 0.664 + 0.192\n$$\n\n$$\nRT = 0.856\n$$\n\nSo the predicted mean reaction time for **Lecture** is **0.856 seconds**.\n\n\n### Prediction summarized\n\nThe regression coefficients allow us to **reconstruct the group means directly**.\n\n| Condition | Model Equation | Predicted Mean |\n|-----------|---------------|---------------|\n| No Distraction | $b_0$ | 0.664 |\n| Texting | $b_0 + b_1$ | 1.005 |\n| Lecture | $b_0 + b_2$ | 0.856 |\n\n**Regression is simply expressing the group means and their differences using an equation.**\n\n### Extracting the Model-Estimated Means\n\nJust like before, `emmeans` will do all of that reconstruction for us.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmeans3 <- emmeans(model3, ~ Condition)\nmeans3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Condition      emmean     SE df lower.CL upper.CL\n No Distraction  0.664 0.0238 87    0.617    0.711\n Texting         1.005 0.0238 87    0.958    1.052\n Lecture         0.856 0.0238 87    0.809    0.903\n\nConfidence level used: 0.95 \n```\n:::\n:::\n\n\n\nThese values represent the **means predicted by the regression model**, and they match the numbers we just assembled by hand.\n\n### Changing the Reference Group\n\nThe reference group is a choice, not a fact about the world. `factor(levels = )` sets it when you build the variable. To switch it afterwards, use `relevel()`:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat3$Condition2 <- relevel(dat3$Condition, ref = \"Texting\")\n\nmodel3b <- lm(RT ~ Condition2, data = dat3)\ncoef(model3b)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             (Intercept) Condition2No Distraction        Condition2Lecture \n               1.0050267               -0.3411475               -0.1488547 \n```\n:::\n:::\n\n\n\nEvery coefficient is now expressed relative to Texting. The intercept is Texting's mean, 1.005, and the other two rows are how much *slower or faster* the remaining conditions are compared to it. No Distraction now carries a negative coefficient, -0.341, because being undistracted is faster than texting.\n\nHere is the part worth watching, though. Nothing about the model actually moved:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Same variance explained, same omnibus test, same fitted means\nc(R2.original = summary(model3)$r.squared,\n  R2.releveled = summary(model3b)$r.squared)\n\nc(F.original = summary(model3)$fstatistic[1],\n  F.releveled = summary(model3b)$fstatistic[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n R2.original R2.releveled \n   0.5428557    0.5428557 \n F.original.value F.releveled.value \n         51.65595          51.65595 \n```\n:::\n:::\n\n\n\nIdentical. Releveling changed which comparisons the coefficients describe. It did not change the fit, the group means, the residuals, or the drivers.\n\n\n### APA Write-Up\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nA regression model was used to predict reaction time from driving condition. The overall model was significant, $R^2 =$ .54, $F(2, 87) =$ 51.66, $p < .001$, indicating that driving condition accounted for about 54% of the variability in reaction times.\n\nBecause **No Distraction** was entered as the first factor level, it served as the **reference group**, and the intercept represented the mean reaction time for that condition (*M* = 0.66, *SE* = 0.02, 95% CI [0.62, 0.71]).\n\nRelative to this reference group, texting significantly increased reaction time, $b =$ 0.34, $SE =$ 0.03, $t(87) =$ 10.14, $p < .001$. Listening to a statistics lecture also increased reaction time relative to the no-distraction condition, $b =$ 0.19, $SE =$ 0.03, $t(87) =$ 5.71, $p < .001$.\n\n\n### Testing Differences Between Groups\n\nWe can also test the differences between all pairs of conditions.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairs(means3, adjust=\"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n contrast                 estimate     SE df t.ratio p.value\n No Distraction - Texting   -0.341 0.0337 87 -10.137 <0.0001\n No Distraction - Lecture   -0.192 0.0337 87  -5.714 <0.0001\n Texting - Lecture           0.149 0.0337 87   4.423 <0.0001\n```\n:::\n:::\n\n\n\nThis compares the estimated means for:\n\n- No Distraction vs Texting\n- No Distraction vs Lecture\n- Lecture vs Texting\n\nAll comparisons are derived directly from the regression model. This contains the comparison we did not test earlier (texting vs. lecture). You can add that to your APA report as well.\n\n### About That `adjust=\"none\"`\n\nYou should be suspicious of that argument, because we spent a whole section calculating that three unadjusted tests inflate the error rate to 14%. So why are we allowed to run three unadjusted tests?\n\nBecause we checked the gate first. The omnibus $F$ was significant, which is what earns the right to look at individual pairs without adjusting each one. This is **Fisher's protected LSD**, and the word doing the work is *protected*: the $F$ is the protection, and it was bought before any pair was examined.\n\nThe protection has a hard expiry date, and it is worth memorizing, because it is a favorite exam question:\n\n::: {.callout-important title=\"The Protection Expires at Three Groups\"}\nWith exactly **three** groups, a significant omnibus $F$ followed by unadjusted pairwise tests keeps the familywise error rate at $\\alpha$. This is a genuine mathematical result, not a convention.\n\nWith **four or more** groups it stops working, and the error rate creeps back up. At that point you need a real correction (Tukey, Holm, Bonferroni), which is what the [Multiple Comparisons](Chapter_Multiple_Comparisons.qmd) chapter is for.\n\nSo `adjust = \"none\"` here is a defensible choice with three groups and a significant $F$. Pasted into a four-group analysis, it is just the 14% problem again.\n:::\n\n### APA for follow up test\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nIn addition, pairwise comparisons of the estimated marginal means showed that texting produced significantly slower reaction times than listening to a statistics lecture, $b =$ 0.15, $SE =$ 0.03, $t(87) =$ 4.42, $p < .001$. Thus, although both distractions impaired reaction time relative to the no-distraction condition, texting was associated with the greatest slowing of reactions.\n\n\n### Plotting the Model-Estimated Means\n\nWe can also visualize the results using a simple plot.\n\nFirst we convert the estimated means to a data frame.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmeans3_df <- as.data.frame(means3)\nmeans3_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Condition         emmean         SE df  lower.CL  upper.CL\n No Distraction 0.6638792 0.02379701 87 0.6165800 0.7111783\n Texting        1.0050267 0.02379701 87 0.9577276 1.0523259\n Lecture        0.8561720 0.02379701 87 0.8088729 0.9034712\n\nConfidence level used: 0.95 \n```\n:::\n:::\n\n\n\nNow we plot the estimated means and their 95% confidence intervals.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(means3_df, aes(x = Condition, y = emmean)) +\n  geom_col() +\n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = .1) +\n  ylab(\"Reaction Time (seconds)\") +\n  xlab(\"Driving Condition\")+theme_bw()\n```\n\n::: {.cell-output-display}\n![All three conditions, model-estimated means with 95% confidence intervals. Lecture sits between the other two.](Chapter_Regression-with-Cat-Variables_files/figure-pdf/three-level-means-plot-1.pdf){fig-align='center' fig-alt='Bar chart with three bars: No Distraction at about 0.66 seconds, Texting at about 1.01, and Lecture at about 0.86, each with a narrow error bar. Texting is tallest and No Distraction shortest.'}\n:::\n:::\n\n\n\nThis figure shows the **model-estimated mean reaction time for each driving condition** along with the 95% confidence intervals.\n\n## The Short Story\n\n- R represents a categorical predictor with numeric contrast variables.\n- Under ordinary treatment/dummy coding, the intercept is the reference-group mean.\n- Each category coefficient is that group's difference from the reference group.\n- With two groups, the regression test is equivalent to an independent-samples t-test under the matching variance assumptions.\n- With three or more groups, the overall model asks whether the group means are all equal; follow-ups ask which contrasts differ.\n- Changing the reference group changes the coefficient labels, not the fitted group means or the underlying data.\n- Set factor levels deliberately. Otherwise R may select a reference group alphabetically, because the alphabet has apparently been granted authority over your scientific question.\n\n::: {.callout-note title=\"Coding Changes the Coefficients, Not the People\"}\nChanging the reference group changes which comparison appears in each coefficient. It does not change the fitted group means, residuals, $R^2$, or the participants—who remain blissfully unaware that R renamed the argument.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}