{
  "hash": "ea83624b51752aa3ecc094162cc78b65",
  "result": {
    "markdown": "---\ntitle: \"Paired-Samples t-Test\"\n---\n\n\n\n\n::: {.callout-note title=\"The Same People Have Returned\"}\nUse a paired-samples t-test when the **same people are measured twice** or when observations form meaningful pairs. The two scores from one person know each other. Pretending they are independent is statistical identity theft.\n\nThe central idea is simple: turn each pair into one difference score, then ask whether the average difference is zero. That is the whole test. Nobody needs a random effect yet. The random effects are waiting in the next chapter with paperwork.\n:::\n\n## Why Pair the Scores?\n\nAn **independent-samples** design compares different people. Half the students receive chocolate during a lecture and half receive nothing except the lecture itself, which already seems cruel. Each student contributes one score.\n\nA **repeated-measures** design measures the same students twice. Every student attends one lecture without chocolate and one with chocolate. Each student is now their own control.\n\nA **matched-pairs** design uses different people who were deliberately matched on something important, such as age or baseline ability. This can help, but matched strangers are not magical clones. If you place two undergraduates beside each other because they have the same GPA, one may still be a morning person while the other communicates only through exhausted grunting. The analysis is identical (pair, difference, test), but matched strangers usually correlate far less than a person does with themself, so the power benefit is real and smaller. Watch for the $-2rS_1S_2$ term later in this chapter, because everything depends on that $r$.\n\nRepeated scores tend to be correlated because stable characteristics follow people into both conditions. A student who generally looks at the screen for a long time may do that with or without chocolate. Another student may stare out the window in both conditions while contemplating escape. Pairing lets us remove some of those stable person-to-person differences.\n\n## A Chocolate-Fixation Study\n\nSuppose we ask whether eating a small piece of chocolate during a lecture changes **fixation time**: the average number of seconds a student's eyes remain on the screen per glance. We measure 48 students twice:\n\n- once with no chocolate;\n- once with chocolate.\n\nThis example is simulated. Do not distribute mystery candy to human participants and announce that a textbook authorized it. Allergies, informed consent, and research ethics remain annoyingly real.\n\n::: {.callout-warning title=\"The Price of Measuring the Same Person Twice\"}\nMeasuring someone twice buys you statistical power, and it charges you for it. Three things ride along with that second measurement:\n\n- **Practice effects.** People get better at a task simply by having done it once.\n- **Fatigue effects.** Or they get worse, because they are tired and would like to go home.\n- **Carryover.** The first condition is still working on them when the second one starts.\n\nHere is the problem for our study. If every student sits through the no-chocolate lecture first and the chocolate lecture second, then \"chocolate increased fixation time\" and \"students settled down in the second session\" are the same sentence. No t-test can separate them, because nothing in the data distinguishes them.\n\nThe fix is **counterbalancing**. Half the students get chocolate first and half get it second. Order effects still happen, but now they land on both conditions equally and cancel out of the comparison. So assume we counterbalanced, because we are professionals.\n\nCounterbalancing does not fix everything. Chocolate eaten in the first session does not un-eat itself ten minutes later, so with sessions that close together the sugar is still in the room during the control condition. Spacing matters, and some carryover cannot be designed away at all.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nn <- 48\nparticipant_effect <- rnorm(n, mean = 0, sd = 1.20)\n\npaired_wide <- data.frame(\n  participant = factor(seq_len(n)),\n  no_chocolate = 5.00 + participant_effect + rnorm(n, 0, 0.80),\n  chocolate = 5.75 + participant_effect + rnorm(n, 0, 0.80)\n)\n\npaired_wide$difference <-\n  paired_wide$chocolate - paired_wide$no_chocolate\n\npaired_long <- tidyr::pivot_longer(\n  paired_wide,\n  cols = c(no_chocolate, chocolate),\n  names_to = \"condition\",\n  values_to = \"fixation\"\n)\n\npaired_long$condition <- factor(\n  paired_long$condition,\n  levels = c(\"no_chocolate\", \"chocolate\"),\n  labels = c(\"No chocolate\", \"Chocolate\")\n)\n```\n:::\n\n\nThe **wide data** have one row per person and one column per condition. This shape makes the pairing obvious and works nicely for a paired t-test. The **long data** have two rows per person. We use that shape for the picture below and will need it again when we reach mixed regression.\n\n## Look at the Pairs Before Testing Them\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n  paired_long,\n  aes(x = condition, y = fixation, group = participant)\n) +\n  geom_line(alpha = 0.30, color = \"gray55\") +\n  geom_point(alpha = 0.60, color = \"steelblue4\") +\n  stat_summary(\n    aes(group = 1), fun = mean, geom = \"line\",\n    color = \"firebrick\", linewidth = 1.3\n  ) +\n  stat_summary(\n    aes(group = 1), fun = mean, geom = \"point\",\n    color = \"firebrick\", size = 3\n  ) +\n  labs(\n    x = NULL,\n    y = \"Mean fixation time (seconds)\",\n    title = \"Every gray line is one exploited volunteer\"\n  ) +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![Each gray line is one student measured twice. The red line is the average change.](Chapter_Paired_t_test_files/figure-html/plot-pairs-1.png){fig-align='center' fig-pos='H' fig-alt='A paired line plot with two columns, no chocolate on the left and chocolate on the right. Forty-eight faint gray lines connect each student\\'s two fixation times, most sloping upward but several sloping down. A thick red line runs between the two condition means, rising from about 4.8 to about 5.6 seconds.' width=528}\n:::\n:::\n\n\nThe red line shows the mean change. The gray lines show something the means hide: some people change more than others, and a few may move in the opposite direction. If you plot only two bars, all those people are compressed into rectangular coffins.\n\n## The Paired t-Test Is a One-Sample t-Test in Disguise\n\nFor each person, compute a difference score:\n\n$$\nD_i=Y_{i,\\text{chocolate}}-Y_{i,\\text{no chocolate}}\n$$\n\nThen ask whether the population mean difference is zero:\n\n$$\nt=\\frac{M_D-0}{S_D/\\sqrt{n}}\n$$\n\nThis is the one-sample t-test from the earlier chapter. The paired t-test does not compare two unrelated piles of scores. It reduces every pair to one difference and tests the set of differences.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npaired_result <- t.test(\n  paired_wide$chocolate,\n  paired_wide$no_chocolate,\n  paired = TRUE\n)\n\npaired_result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  paired_wide$chocolate and paired_wide$no_chocolate\nt = 4.3366, df = 47, p-value = 7.597e-05\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.4209697 1.1495099\nsample estimates:\nmean difference \n      0.7852398 \n```\n:::\n:::\n\n\n### R Has Become Picky About the Formula Method\n\nThe formula method of `t.test()` does not accept `paired = TRUE`, so this will fail:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(fixation ~ condition, data = paired_long, paired = TRUE)\n```\n:::\n\n\nUse the two paired vectors, as above. Even better, make the pairing visible by calculating the differences yourself:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndifference_result <- t.test(paired_wide$difference, mu = 0)\ndifference_result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  paired_wide$difference\nt = 4.3366, df = 47, p-value = 7.597e-05\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 0.4209697 1.1495099\nsample estimates:\nmean of x \n0.7852398 \n```\n:::\n:::\n\n\nThe t statistic, degrees of freedom, and p-value match. R has not discovered two separate truths. We asked the same question twice.\n\n::: {.callout-important title=\"The Unit of Analysis Is the Pair\"}\nWe began with 96 scores, but the test has 48 difference scores. Therefore, $df=n-1=47$. Counting every measurement as an independent person would double the apparent sample size and create confidence unsupported by the design. The spreadsheet may have 96 rows. The study still has 48 humans.\n:::\n\n## Effect Size\n\nA common standardized effect for paired data is Cohen's $d_z$:\n\n$$\nd_z=\\frac{M_D}{S_D}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd_z <- mean(paired_wide$difference) /\n  sd(paired_wide$difference)\n\nd_z\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6259363\n```\n:::\n:::\n\n\nThis standardizes the mean change by the standard deviation of the **difference scores**. Say which version of $d$ you used because repeated-measures effect sizes have several possible denominators. Calling all of them \"Cohen's d\" and wandering away is how future readers begin sharpening office supplies.\n\n## Why Pairing Can Help\n\nThe variance of a difference score is:\n\n$$\nS_D^2=S_1^2+S_2^2-2rS_1S_2\n$$\n\nWhen the two measurements are positively correlated, the last term subtracts variability. Stable person differences cancel: the consistently attentive student is compared with themself, and the student planning an elaborate escape is also compared with themself.\n\nThis often gives a smaller standard error than an independent-samples analysis. Pairing does not guarantee more power, however. If the repeated scores barely correlate, little stable variation is removed. Pairing also cannot repair a terrible measure. Measuring attention by counting how often someone blinks at the ceiling remains a terrible plan in both conditions.\n\n### How Much Does Pairing Actually Buy You?\n\nWe have the data, so we do not have to speculate. First, how correlated are the two measurements? Then we run the analysis **incorrectly on purpose**, treating our 96 scores as if they came from 96 different students who happened to wander in:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# How much do a person's two scores agree with each other?\ncor(paired_wide$chocolate, paired_wide$no_chocolate)\n\n# The WRONG test, run deliberately: the same numbers with the pairing thrown away.\n# Do not copy this into your homework.\nunpaired_result <- t.test(paired_wide$chocolate, paired_wide$no_chocolate)\n\nunpaired_result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4638286\n\n\tWelch Two Sample t-test\n\ndata:  paired_wide$chocolate and paired_wide$no_chocolate\nt = 3.2144, df = 88.988, p-value = 0.001822\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n 0.2998481 1.2706316\nsample estimates:\nmean of x mean of y \n 5.551277  4.766037 \n```\n:::\n:::\n\n\nSame numbers. Same two means. The same mean difference of 0.79 seconds. Nothing about the data changed, only what we told R about where the numbers came from.\n\nThe paired test gave $t(47) =$ 4.34. Ignoring the pairing gives $t(89) =$ 3.21, roughly 1.35 times smaller. The standard error tells the same story: 0.18 seconds when we keep the pairing, 0.24 seconds when we discard it.\n\nWhere did the extra error come from? From the students. Some people simply stare longer than others, in both conditions, for reasons that have nothing to do with chocolate. The paired test subtracts that stable personal tendency out and never looks at it again. The unpaired test has no idea those students are the same humans, so all of that person-to-person variability gets dumped into the error term, where it makes the difference between conditions look less trustworthy than it is.\n\nThat is the whole argument for within-subjects designs, and it is why the design chapter of every methods book keeps yelling about them. It is also, in this case, a correlation of only 0.46. A stronger correlation would have bought even more.\n\n## Assumptions That Actually Matter\n\nFor the paired-samples t-test:\n\n- the observations form genuine pairs;\n- different pairs are independent of one another;\n- the outcome is quantitative;\n- the **difference scores** have no severe outliers;\n- for small samples, the population distribution of difference scores is reasonably normal.\n\nThe test does **not** require the two condition variances to be equal. It operates on one set of differences. Inspect those differences, not two separate normality tests performed as ritual offerings.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(paired_wide, aes(x = difference)) +\n  geom_histogram(binwidth = 0.35, color = \"white\", fill = \"steelblue4\") +\n  geom_vline(xintercept = 0, linetype = 2, color = \"firebrick\") +\n  labs(\n    x = \"Chocolate minus no-chocolate fixation time\",\n    y = \"Number of students\"\n  ) +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![The 48 difference scores. This is the distribution the test actually looks at.](Chapter_Paired_t_test_files/figure-html/inspect-differences-1.png){fig-align='center' fig-pos='H' fig-alt='Histogram of 48 difference scores, chocolate minus no chocolate, roughly mound-shaped and centered a little below one second. A dashed red vertical line marks zero, with most of the distribution sitting to its right and a handful of students falling to the left.' width=528}\n:::\n:::\n\n\n## Reporting the Result\n\nFor the present study, a concise report could be:\n\n> Students showed longer fixation times during the chocolate condition ($M =$ 5.55, $SD =$ 1.33) than during the no-chocolate condition ($M =$ 4.77, $SD =$ 1.05). The mean paired difference was 0.79 seconds, 95% CI [0.42, 1.15], $t(47) =$ 4.34, $p$ < .001, $d_z =$ 0.63.\n\nThe statistic cannot prove that chocolate *caused* better attention unless the study was properly randomized and alternative explanations were controlled. It certainly cannot prove that replacing every lecture with a bucket of candy is sound educational policy.\n\n## When Two Measurements Are Not Enough\n\nOne difference score works beautifully when each person has two measurements and the question is about their average change. With three or more occasions, missing observations, both within-person and between-person predictors, or people who change at different rates, one difference score cannot represent the whole design.\n\nThat is where [mixed regression](Chapter_Mixed_Regression.qmd) begins. It keeps the repeated observations, tells the model which rows belong to the same human, and allows people to differ without creating one indicator variable for every person who wandered into the study.\n\n## The Short Story\n\n- Use a paired-samples t-test when observations form genuine pairs.\n- The same person measured twice is the most common paired design.\n- Compute one difference score for each pair.\n- A paired-samples t-test is a one-sample t-test on those differences.\n- The unit of analysis is the pair, not the individual measurement.\n- Inspect the distribution and outliers of the **differences**.\n- Report the mean change, confidence interval, p-value, and the specific paired effect size you used.\n- When the design grows beyond one clean pair of scores, continue to the mixed-regression chapter.\n\nThe grand lesson is not \"memorize another command.\" It is \"keep the two scores attached to the human who produced them.\" The humans already know they are the same person. R needs paperwork.\n",
    "supporting": [
      "Chapter_Paired_t_test_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}