{
  "hash": "a974c37d1e68cb7868d96b266958779f",
  "result": {
    "markdown": "---\ntitle: \"Power and Effect Size\"\nfontsize: 11pt\ngeometry: margin=.5in\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n---\n\n\n\n\n\n::: {.callout-note title=\"Some of Today's Code Is Not Your Problem\"}\nA few figures in this chapter are generated with genuinely unpleasant code. Where you see a plot appear without the code attached, that is deliberate: I hid it because you are not expected to learn it. Every function you *are* expected to learn is shown, explained, and used more than once.\n\nIf you find yourself reading the hidden code anyway, welcome. Dorkaos, the Ancient Greek God of Statistics, is watching, and He approves.\n:::\n\n## Probability Is Fickle\n\nBefore we can talk about power, we have to admit something uncomfortable about small samples.\n\nRecall that the standard error is the standard deviation of sample means. Let us build a population for children's hyperactivity scores, the same population from the one-sample t-test chapter, with $\\mu = 50$ and $\\sigma = 5$.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/population-pdf-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nAbout 95% of children score between 40.2 and 59.8. Fine. Now let us collect some data.\n\n### Ten Small Studies\n\nSuppose we run ten separate studies, each with $n = 13$ children. Ten data collections, thirteen children each, one hyperactivity score per child.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/ten-samples-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nThe mean of those ten sample means was 49.721, comfortably close to $\\mu = 50$. Good.\n\nNow check the *spread*. Our formula predicts a standard error of\n\n$$\n\\sigma_M = \\frac{\\sigma}{\\sqrt{n}} = \\frac{5}{\\sqrt{13}} = 1.39.\n$$\n\nIn reality, those ten studies produced $SD(\\text{sample means}) =$ 0.73.\n\nThose are not the same number. **Why?**\n\n### The Answer Is Unpleasant\n\nOur samples were small. With only thirteen children, we are most likely to grab people from the fat middle of the distribution, because that is where most people live. The extremes are rare, so small samples usually miss them. Miss the extremes, and your estimate of spread comes out too small.\n\nLet us prove it with brute force. We will repeat the entire ten-study exercise 5,000 times and look at the distribution of the standard errors we get.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/sem-fickle-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nThe red line is the theoretical standard error. Notice the histogram is **not symmetric around it**. In this simulation, 55.8% of the estimates fall *below* the theoretical value and only 44.2% fall above.\n\nSmall samples systematically underestimate variability. This is the problem Gosset walked into when he stopped using a known $\\sigma$ and started using a sample $S$ as an approximation, and it is why we have a t-distribution at all.\n\n::: {.callout-important title=\"This Is the Whole Reason Power Exists\"}\nYour sample gives you one guess about the mean and one guess about the spread. Both guesses wobble, and the smaller the sample, the more they wobble, in a direction that flatters you.\n\nThe solution is not to stop guessing. The solution is to work out, **before you collect data**, how likely you are to detect an effect given your specific sample size and how big the effect probably is.\n\nThat calculation is called power. Everything else in this chapter is machinery for doing it.\n:::\n\n## Type I and Type II Error\n\nEvery hypothesis test ends in a decision, and every decision can be wrong in exactly two ways.\n\n|  | Treatment works ($H_0$ FALSE) | Treatment does nothing ($H_0$ TRUE) |\n|-----------------|------------------------|------------------------|\n| **Reject $H_0$** | Correct decision (**power**) | **Type I error** ($\\alpha$) |\n| **Fail to reject $H_0$** | **Type II error** ($\\beta$) | Correct decision |\n\n**Type I error** is a false alarm. There is no effect, and you claim there is one. Its long-run rate is $\\alpha$, and you choose $\\alpha$ yourself, usually .05, by simple decree.\n\n**Type II error** is a miss. There *is* an effect, and you fail to find it. Its rate is $\\beta$, and you do **not** get to choose it directly. You have to earn your way out of it.\n\n**Power** is $1 - \\beta$: the probability of detecting an effect that is genuinely there.\n\nNotice the asymmetry. Alpha is a decision you make in about four seconds. Power is something you buy, with participants, and it is expensive.\n\n::: {.callout-warning title=\"What Alpha Does Not Mean\"}\nSetting $\\alpha = .05$ does **not** mean any of the following:\n\n- there is a 5% probability that this particular rejected null is true;\n- 5% of published findings are wrong;\n- your result has a 95% chance of replicating.\n\nIt means that *if* the null hypothesis and its assumptions hold, this **procedure** falsely rejects about 5% of the time in the long run. The p-value is a statement about a procedure. It cannot read the hidden state of the universe, and it has never once tried.\n:::\n\n### The Errors Are Not Symmetric in Cost\n\nA Type I error means we run around telling everyone that cookies make children hyperactive when they do not. Parents ban cookies. A generation grows up sad.\n\nA Type II error means cookies *do* make children hyperactive, we fail to notice, and we spend the next decade blaming the children.\n\nWhich error is worse depends entirely on what happens next, which is a question statistics cannot answer for you. A false alarm on a cancer screening costs a biopsy. A miss costs considerably more.\n\nPsychology and neuroscience have historically obsessed over Type I error and treated Type II error as somebody else's problem. Button and colleagues surveyed the neuroscience literature and estimated median statistical power at around 21% [@button2013], which means the typical study had roughly a one-in-five chance of finding an effect that was genuinely there. This is one of several reasons the replication crisis arrived carrying luggage and expecting to stay a while.\n\n## Signal Detection Theory\n\nGiven that I must estimate my standard error from a wobbly $S$, I need a way to say how \"big\" an effect is in the first place.\n\nCohen borrowed the idea from signal detection theory, developed alongside radio and radar. The question there was: how strong must a signal be before you can detect it over the noise? For us, the noise is the control condition and the signal is the effect of the treatment.\n\nThe hearing-test version of the table above is worth keeping in your head, because it is the same table:\n\n|  | There **was** a beep | There was **no** beep |\n|-------------|---------------|-------------------|\n| You said **YES** | Hit | False alarm |\n| You said **NO** | Miss | Correct rejection |\n\nHit, miss, false alarm, correct rejection. Power, Type II error, Type I error, correct decision. Same 2×2, different lab coat.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/sdt-figure-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\n$$\nd = \\frac{\\mu_{(Noise+Signal)} - \\mu_{(Noise)}}{\\sigma_{(Noise)}}\n$$\n\nNote the implicit assumption hiding in that denominator:\n\n$$\n\\sigma_{(Noise)} = \\sigma_{(Noise+Signal)}\n$$\n\nWe are assuming the treatment shifts the distribution without changing its spread. Sometimes that is true. Sometimes a treatment helps some people enormously and others not at all, which changes the spread, and then this formula is quietly describing a world that does not exist.\n\n### Cohen's $d$\n\nCohen worked out that we can apply the same logic to experiments, to say how easy it is to distinguish the signal from the noise:\n\n$$\nd = \\frac{M_{H1} - \\mu_{H0}}{S_{H1}}\n$$\n\nYou have seen this formula before, wearing a different hat:\n\n$$\nZ = \\frac{M - \\mu}{S}\n$$\n\nSo Cohen's $d$ is in standard deviation units.\n\n| Size | $d$ |\n|--------|------|\n| Small | .2 |\n| Medium | .5 |\n| Large | .8 |\n| Huge | 1.2 |\n\n::: {.callout-note title=\"You Have Met These Curves Already\"}\nThe visualizations of small, medium, large, and huge effects appear in the [one-sample t-test chapter](Chapter_OneSample_t_test.qmd), along with the observation that even a huge effect leaves the two distributions substantially overlapping.\n\nThat overlap is the point. Two groups can differ by a \"large\" amount and still contain enormous numbers of people who look exactly like each other. An effect size is a statement about distributions, not about individuals, and it has never promised you a clean separation.\n:::\n\n::: {.callout-warning title=\"These Adjectives Are Conventions, Not Laws\"}\nCohen proposed small, medium, and large as rough guidance for a field that had none, and then spent years watching people treat them as physical constants.\n\nA $d$ of .2 for a cheap public health intervention delivered to forty million people may matter enormously. A $d$ of 1.1 in a study of twelve undergraduates may matter not at all. Interpret magnitude in context, or do not interpret it.\n:::\n\n## Power\n\nPower is the likelihood that a study will detect an effect when there genuinely is one. Power $= 1 - \\beta$, where $\\beta$ is the Type II error rate [@cohen1962; @cohen1988; @cohen1992].\n\nHere is the whole thing in one picture.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/power-figure-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nRead it left to right. The black curve is the world where the null is true. The red curve is the world where the effect is real. The dashed line is your critical value, the point past which you will reject the null.\n\n- Everything to the right of the dashed line **under the black curve** is $\\alpha/2$: rejecting when you should not have.\n- Everything to the left of the dashed line **under the red curve** is $\\beta$: the effect was real and you missed it.\n- Everything to the right of the dashed line **under the red curve** is power.\n\nMove the dashed line left and you gain power while buying more Type I error. Move it right and the reverse. Push the red curve further right, or make both curves narrower, and power improves without that trade. Which is the entire game.\n\n### Uses of Power\n\n**A priori power** means setting a target likelihood of success (say, power = .80) at a given $\\alpha$ (say, .05), assuming a *true* effect size, and solving for the sample size you need [@cohen1962; @cohen1988; @cohen1992]. This is the useful one. It is also the hard one, because it requires knowing the true effect size, which is the thing you are running the study to find out.\n\nWe used to tell people to go find a meta-analysis. Then it turned out meta-analytic effect sizes are inflated by publication bias [@kicinski2015], because studies that found nothing were never published and therefore never averaged in. A rule of thumb: assume your effect is small-to-medium, $d = .3$ or $.4$, and be pleasantly surprised rather than catastrophically wrong.\n\n**Post-hoc power** means estimating the power you achieved using the effect size you *observed*, your sample size, and your $\\alpha$.\n\nPost-hoc power is meaningless. It is worse than meaningless, because it looks like information.\n\n::: {.callout-important title=\"Post-Hoc Power Is a Ghost\"}\nObserved power is a one-to-one function of your p-value. A significant result *always* yields high observed power; a non-significant result *always* yields low observed power. It cannot tell you anything your p-value did not already tell you, and it is frequently used to argue \"our null result was just underpowered,\" which is circular reasoning with a calculator [@hoenig2001].\n\nWorse, the effect size feeding it is biased. As we saw at the start of this chapter, small samples underestimate $\\sigma$. A smaller denominator makes $d$ bigger. Your observed effect is flattering you, and post-hoc power then launders the flattery into a number with a decimal point.\n\nCompute power **before** you run the study. Afterwards, report the confidence interval and let it speak.\n:::\n\n## Power and Significance Testing\n\nThere is a subtlety here that trips up nearly everyone, so we will be slow about it.\n\nEverything above drew the curves in **standard deviation** units. But significance testing does not happen in standard deviation units. It happens in **standard error** units. And the standard error shrinks as $N$ grows, because $S_M = S/\\sqrt{n}$.\n\nThe distance between the peaks is the effect size, and it does **not** change with sample size. What changes is how *wide* the curves are.\n\n::: {.callout-tip title=\"Homer Simpson and the Statistically Significant Hair\"}\nIn \"Simpson and Delilah\" (The Simpsons, S7:E2), Homer takes Dimoxinil and wakes up the next morning with a full luscious head of hair. That is an enormous effect size.\n\nIn reality, Minoxidil grows back very little hair, after months of twice-daily application, in a subset of men, most of whom keep checking the mirror hopefully. The effect is genuinely small. It is also statistically significant, because \"most men experience *some* growth beyond noise,\" and noise here is defined in standard error units, not standard deviation units.\n\nStatistically significant is not the same as clinically significant. It is not even the same as noticeable. Homer's hair is a story about effect size. The clinical trial is a story about standard errors.\n:::\n\nWatch the curves narrow while the peaks stay exactly where they are. The effect below is a medium one, $d = .5$, in all four pictures.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/se-narrowing-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nThe area representing $1 - \\beta$ grows as we add participants, because the curves get thinner while the distance between them stays fixed.\n\nThis is why effect size is described as independent of sample size and significance is not. That statement is true if you know the population standard deviation $\\sigma$. We never do. We approximate it with $S$, so our observed effect size is itself another guess, subject to the same fickleness we opened this chapter with. Which is why we hope meta-analysis, averaging over many studies, gives a steadier estimate, right up until publication bias mugs it in an alley.\n\n## Estimating A Priori Power in R\n\nBase R ships with a power function for t-tests. No package required.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nargs(power.t.test)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfunction (n = NULL, delta = NULL, sd = 1, sig.level = 0.05, power = NULL, \n    type = c(\"two.sample\", \"one.sample\", \"paired\"), alternative = c(\"two.sided\", \n        \"one.sided\"), strict = FALSE, tol = .Machine$double.eps^0.25) \nNULL\n```\n:::\n:::\n\n\n\nIt works by solving for whatever you leave as `NULL`. Give it any four of `n`, `delta`, `sd`, `sig.level`, and `power`, and it returns the fifth.\n\n::: {.callout-tip title=\"How to Make power.t.test Speak Cohen's d\"}\n`power.t.test()` wants a raw mean difference (`delta`) and a standard deviation (`sd`), not a $d$.\n\nThe trick: **set `sd = 1` and put your $d$ in `delta`.** Because $d = \\delta / \\sigma$, setting $\\sigma = 1$ makes the raw difference and the standardized difference the same number.\n\n```r\npower.t.test(delta = 0.4, sd = 1, ...)   # this is d = .4\n```\n\nEverything in this chapter uses that convention. If you ever want to work in raw units instead, supply both the real `delta` and the real `sd` and it will happily oblige.\n:::\n\nThe `type` argument picks which t-test you mean:\n\n| `type` | Design | What `n` means |\n|--------|--------|----------------|\n| `\"one.sample\"` | one group vs. a fixed value | total participants |\n| `\"two.sample\"` | two independent groups | participants **per group** |\n| `\"paired\"` | same people measured twice | number of **pairs** |\n\nGetting `n` wrong here is the single most common power mistake. A `two.sample` answer of 64 means **128 people**.\n\n### One-Sample: The Cookies Return\n\nRecall the one-sample study: we feed children cookies and compare their hyperactivity to a hypothesized population value of $\\mu = 50$.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nPopulation <- rnorm(1e6, mean = 50, sd = 5)\n\nset.seed(42)\nkids.1 <- sample(Population, 36, replace = TRUE) + 2\n\nM_kids <- mean(kids.1)\nS_kids <- sd(kids.1)\nd_kids <- (M_kids - 50) / S_kids\n\nround(c(M = M_kids, SD = S_kids, n = length(kids.1), d = d_kids), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     M     SD      n      d \n53.035  4.356 36.000  0.697 \n```\n:::\n:::\n\n\n\nSuppose we are designing this study fresh and expect a small-to-medium effect, $d = .4$. How many children do we need for 80% power?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAt.Power.80 <- power.t.test(n = NULL, delta = .4, sd = 1,\n                            sig.level = 0.05, power = .80,\n                            type = \"one.sample\",\n                            alternative = \"two.sided\")\nAt.Power.80\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     One-sample t test power calculation \n\n              n = 51.00957\n          delta = 0.4\n             sd = 1\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n:::\n:::\n\n\n\nWe always **round up**: 52 children. You cannot recruit a fractional child, and rounding down leaves you below your target.\n\nNow the same question at 95% power, which some people have started demanding.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAt.Power.95 <- power.t.test(n = NULL, delta = .4, sd = 1,\n                            sig.level = 0.05, power = .95,\n                            type = \"one.sample\",\n                            alternative = \"two.sided\")\nceiling(At.Power.95$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 84\n```\n:::\n:::\n\n\n\n84 children. Going from 80% to 95% power cost us 32 additional participants for the same effect. Cohen suggested 80% precisely because it is economical. 95% is called *high power*, and now you can see why it is unpopular with anyone who has to pay for it.\n\n### Solving for Power Instead of N\n\nIf the sample size is already fixed, perhaps because that is how many children were available, or how much money you had, run it the other way.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAP.Power.N36 <- power.t.test(n = 36, delta = .4, sd = 1,\n                             sig.level = 0.05, power = NULL,\n                             type = \"one.sample\",\n                             alternative = \"two.sided\")\nround(AP.Power.N36$power, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.646\n```\n:::\n:::\n\n\n\nWith 36 children and a true $d$ of .4, we had a 64.6% chance of detecting the effect. Which means we had a 35.4% chance of missing it entirely, publishing nothing, and concluding cookies are harmless.\n\n### Solving for the Effect Size You Could Detect\n\nThe third useful question: given my sample, what is the *smallest* effect I could reliably find?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nEff.Power.N36 <- power.t.test(n = 36, delta = NULL, sd = 1,\n                              sig.level = 0.05, power = .80,\n                              type = \"one.sample\",\n                              alternative = \"two.sided\")\nround(Eff.Power.N36$delta, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.48\n```\n:::\n:::\n\n\n\nWith 36 children, the smallest effect we can detect 80% of the time is $d =$ 0.48. Anything smaller than that, we will usually miss.\n\nThis is the calculation to run when a reviewer asks why your null result should be believed. \"We had 80% power to detect effects of $d \\geq$ 0.48, so we can reasonably rule out effects of that size, but not smaller ones\" is a defensible sentence. \"It wasn't significant\" is not.\n\n## Sample Size and Power Are Not Linear\n\nAt a fixed effect size, adding participants buys you power, but not at a constant rate.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/power-curves-n-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nThe blue line is 80% power; the red line is 95%. Notice how far right the curve for $d = .2$ has to travel before it crosses either one, and how quickly $d = .8$ gets there.\n\n**The larger the effect, the fewer participants you need.** Which is a comforting sentence until you remember that you do not control the effect size, and that most real psychological effects are small.\n\n### Effect Size and Power Are Also Not Linear\n\nFlip it around: hold the sample size fixed and vary the effect.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/power-curves-d-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nWith 25 people you need a whopping effect before you are likely to find anything. With 100, medium effects come into range. The curves are S-shaped, not straight, which means there is a region where adding a few participants helps enormously and a region where it barely matters at all.\n\n## Power for the Independent-Samples t-Test\n\nNow two separate groups. The function is the same; only `type` changes, and `n` now means **per group**.\n\nBack to the CTA study from the [independent-samples chapter](Chapter_Independent_t_test.qmd): what happens to how much people like the CTA if the trains actually arrive every seven minutes?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\nn <- 30\n\nCTA.Control      <- rnorm(n, 3, 1)   # regular timing\nCTA.Experimental <- rnorm(n, 5, 1)   # every 7 minutes\n\nCTA.t.test <- t.test(CTA.Experimental, CTA.Control)\nround(c(t = unname(CTA.t.test$statistic),\n        df = unname(CTA.t.test$parameter),\n        p = CTA.t.test$p.value), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      t      df       p \n10.2133 57.0929  0.0000 \n```\n:::\n:::\n\n\n\nFor two independent groups, Cohen originally suggested $d = \\frac{M_{exp} - M_{control}}{S_{control}}$, on the reasoning that $S_{control} = S_{exp}$. Later it was agreed we should use the **pooled** standard deviation instead:\n\n$$\nd = \\frac{M_{exp} - M_{control}}{S_{pooled}},\n\\qquad\nS_{pooled} = \\sqrt{\\frac{SS_1 + SS_2}{df_1 + df_2}}\n$$\n\nWhy is the corrected version better? Because the control group's $S$ is just one wobbly estimate, and we have a second one sitting right there. Pooling uses all the information instead of throwing half of it away out of tradition.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nM1 <- mean(CTA.Experimental); S1 <- sd(CTA.Experimental)\nM2 <- mean(CTA.Control);      S2 <- sd(CTA.Control)\n\nSp <- sqrt(((n - 1)*S1^2 + (n - 1)*S2^2) / (2*n - 2))\nd_cta <- (M1 - M2) / Sp\n\nround(c(M_exp = M1, M_ctl = M2, Sp = Sp, d = d_cta), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nM_exp M_ctl    Sp     d \n5.034 2.759 0.862 2.637 \n```\n:::\n:::\n\n\n\nNow the design question. If we wanted to replicate this, how many riders would we need per group?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nID.Power.80 <- power.t.test(n = NULL, delta = d_cta, sd = 1,\n                            sig.level = 0.05, power = .80,\n                            type = \"two.sample\",\n                            alternative = \"two.sided\")\nceiling(ID.Power.80$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4\n```\n:::\n:::\n\n\n\n4 riders **per group**, so 8 people total.\n\nThat number should make you deeply suspicious, and it should.\n\n::: {.callout-warning title=\"Simulated Data Lies to You, Politely\"}\nOur simulated CTA effect is $d =$ 2.64. That is not a large effect. That is not even a huge effect. That is two distributions in different postal codes, and it happens because I *built* the simulation with a two-point gap and a standard deviation of exactly 1.\n\nReal psychological effects essentially never look like this. If a power analysis tells you that four people per group is sufficient, you have not discovered a cheap study. You have discovered that your assumed effect size is fictional.\n\nWatch what a believable effect costs instead:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsapply(c(0.2, 0.5, 0.8, d_cta),\n       function(dd) ceiling(power.t.test(delta = dd, sd = 1, power = .80,\n                                         type = \"two.sample\")$n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 394  64  26   4\n```\n:::\n:::\n\n\n\nSmall, medium, large, and whatever we simulated. **That first number is the one to internalize.** Most of the effects you actually care about live near it.\n:::\n\nTrains every seven minutes really would change lives. The statistics agree, but only because I told them to.\n\n::: {.callout-warning title=\"Per Group Means Per Group\"}\nFor `type = \"two.sample\"`, the `n` that comes back is the number of participants **in each group**. Double it for your recruitment target.\n\nStudents report this number as their total sample roughly half the time, which halves their actual power and turns an 80% study into something closer to a coin flip with extra steps.\n:::\n\n### Hedges' Correction\n\nCohen's $d$ is biased upward in small samples, for exactly the reason we opened this chapter with: small samples underestimate $\\sigma$, and $\\sigma$ is in the denominator. Smaller denominator, bigger $d$.\n\nHedges proposed a correction factor [@hedges1981]:\n\n$$\ng = d \\times \\left(1 - \\frac{3}{4(n_1 + n_2) - 9}\\right)\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhedges_g <- function(d, n1, n2) {\n  d * (1 - 3 / (4 * (n1 + n2) - 9))\n}\n\ng_cta <- hedges_g(d_cta, n, n)\nround(c(d = d_cta, g = g_cta), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     d      g \n2.6371 2.6028 \n```\n:::\n:::\n\n\n\nWith 30 per group the correction is small. With 8 per group it is not.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nround(sapply(c(5, 10, 20, 50, 200),\n             function(k) hedges_g(0.8, k, k)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7226 0.7662 0.7841 0.7939 0.7985\n```\n:::\n:::\n\n\n\nA true $d$ of .8 estimated from five people per group is meaningfully inflated. This is the arithmetic behind your instinct to distrust a huge effect from a tiny study, and it is a real correction, not a vibe.\n\n## Power for the Paired-Samples t-Test\n\nNow the same people measured twice. From the [paired-samples chapter](Chapter_Paired_t_test.qmd): does eating chocolate during a lecture change fixation time?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\nn <- 48\nparticipant_effect <- rnorm(n, mean = 0, sd = 1.20)\n\nno_chocolate <- 5.00 + participant_effect + rnorm(n, 0, 0.80)\nchocolate    <- 5.75 + participant_effect + rnorm(n, 0, 0.80)\n\ndifference <- chocolate - no_chocolate\n\nd_z <- mean(difference) / sd(difference)\nround(c(M_diff = mean(difference), SD_diff = sd(difference), d_z = d_z), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n M_diff SD_diff     d_z \n  0.785   1.255   0.626 \n```\n:::\n:::\n\n\n\nFor paired data the relevant effect size is $d_z$, the mean difference divided by the standard deviation of the **difference scores**. That is also exactly what `power.t.test()` wants when you set `type = \"paired\"`.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nPaired.Power.80 <- power.t.test(n = NULL, delta = d_z, sd = 1,\n                                sig.level = 0.05, power = .80,\n                                type = \"paired\",\n                                alternative = \"two.sided\")\nceiling(Paired.Power.80$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 23\n```\n:::\n:::\n\n\n\n23 **pairs**, meaning 23 people, each measured twice.\n\n### Why Pairing Is Cheaper\n\nHere is the payoff for repeated measures. Compare the sample sizes required to detect the *same* effect in the two designs.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_independent <- ceiling(power.t.test(delta = d_z, sd = 1, power = .80,\n                                      sig.level = .05,\n                                      type = \"two.sample\")$n)\n\nn_paired <- ceiling(power.t.test(delta = d_z, sd = 1, power = .80,\n                                 sig.level = .05,\n                                 type = \"paired\")$n)\n\nc(independent_per_group = n_independent,\n  independent_total     = 2 * n_independent,\n  paired_people         = n_paired)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nindependent_per_group     independent_total         paired_people \n                   42                    84                    23 \n```\n:::\n:::\n\n\n\nThe paired design needs far fewer humans, because pairing removes the stable person-to-person differences from the denominator:\n\n$$\nS_D^2 = S_1^2 + S_2^2 - 2rS_1S_2\n$$\n\nWhen the two measurements are positively correlated, that last term subtracts variability.\n\n::: {.callout-important title=\"This Comparison Is Fair Only If You Are Careful\"}\nThe numbers above compare designs at the same $d_z$, and $d_z$ is not on the same scale as the independent-samples $d$. A paired design with a strong within-person correlation can produce a large $d_z$ from a modest raw change, because the denominator shrank.\n\nSo: repeated measures usually *do* buy power, sometimes dramatically. But do not report a $d_z$ of 1.2 and let a reader believe it means what a between-groups $d$ of 1.2 would mean. **Say which effect size you used.** Every time. Repeated-measures effect sizes have several possible denominators, and pretending otherwise is how future readers begin sharpening office supplies.\n:::\n\n## The Short Story\n\n- Small samples underestimate variability, in a direction that flatters you.\n- Type I error is a false alarm and its rate is $\\alpha$, which you choose. Type II error is a miss and its rate is $\\beta$, which you must earn your way out of.\n- Power is $1 - \\beta$: the probability of finding a real effect. It depends on the effect size, the sample size, and $\\alpha$.\n- Effect size lives in standard deviation units. Significance lives in standard error units. Adding participants narrows the curves without moving the peaks.\n- Compute power **before** you run the study. Post-hoc power is a restatement of your p-value wearing a disguise.\n- `power.t.test()` solves for whatever you leave `NULL`. Set `sd = 1` and put $d$ in `delta`.\n- For `two.sample`, `n` is per group. Double it.\n- For `paired`, `n` is the number of pairs, and `delta` is $d_z$.\n- Non-significant does not mean no effect. Very often it means no chance.\n\n---\n\n# Advanced Topics {.unnumbered}\n\nEverything above is what you need to design a study and defend it. What follows is the part that explains *why the field got this so wrong for so long*. You are not required to master it. You are required to know it exists.\n\n## The Observed Effect Size Is Also a Guess\n\nRunning one small pilot study to estimate an effect size used to be standard practice. It is a catastrophe, and we can show exactly how bad it is.\n\nConsider a Mozart-effect study: compare spatial reasoning right after listening to Mozart's Sonata for Two Pianos in D Major, K. 448, against a control group who listened to Bach's Brandenburg Concerto No. 6, matched on modality, tempo, and duelling voices. If the effect is specific to Mozart, Bach should do nothing.\n\nSimulate $\\mu_{Mozart} = 109$, $\\mu_{Bach} = 110$, $\\sigma = 15$ in both, with $n = 30$ per group. The true effect is\n\n$$\nd_{true} = \\frac{110 - 109}{15} = 0.067,\n$$\n\nwhich is to say, nothing. There is no Mozart effect in this simulated world. Now watch what a single study reports.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(666)\nn <- 30\nMozart.Sample <- rnorm(n, 109, 15)\nBach.Sample   <- rnorm(n, 110, 15)\n\nSp_mb <- sqrt(((n-1)*sd(Mozart.Sample)^2 + (n-1)*sd(Bach.Sample)^2) / (2*n - 2))\nObs.d <- abs(mean(Mozart.Sample) - mean(Bach.Sample)) / Sp_mb\nround(Obs.d, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.428\n```\n:::\n:::\n\n\n\nOur one study observed $d =$ 0.428, against a truth of $0.067$.\n\nNow re-run that same study 5,000 times and look at the distribution of observed effect sizes.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Power_Effect_Size_files/figure-pdf/mozart-sim-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nThe red line is the truth. Look at how much of the distribution sits far to the right of it.\n\nIn this simulation, an observed $d$ at least as large as our one study's 0.428 occurred 10.62% of the time. Worse, there was a 46.32% chance of observing something above the \"small effect\" threshold of $d = .2$, **in a world where the true effect is essentially zero**.\n\n::: {.callout-warning title=\"Why Pilot Studies Cannot Estimate Effect Sizes\"}\nA small pilot gives you a draw from that histogram. Not the red line. A draw.\n\nIf you then feed that draw into a power analysis, you will compute the sample size needed to detect an effect that does not exist, feel rigorous about it, and run a study doomed before recruitment began.\n\nPilot studies are for testing whether your procedure works, whether participants understand the instructions, and whether the software crashes. They are not for estimating effect sizes. They are far too small to do that, which is what makes them pilots.\n:::\n\n## Safeguard Power\n\nIf you must use an observed effect size from a previous study, do not use the point estimate. Use the **lower bound of its confidence interval**. This is called *safeguard power* [@perugini2014], and it asks the only sensible question: what if the original study was lucky?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# CI for d, using the standard large-sample approximation\nd_ci <- function(d, n1, n2) {\n  se <- sqrt((n1 + n2)/(n1 * n2) + d^2 / (2 * (n1 + n2)))\n  c(lower = d - 1.96 * se, d = d, upper = d + 1.96 * se)\n}\n\npublished <- d_ci(0.50, 80, 80)\nround(published, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlower     d upper \n0.185 0.500 0.815 \n```\n:::\n:::\n\n\n\nA published effect of $d = .50$ from a reasonably sized study, 80 per group, still has a confidence interval reaching down to 0.185. Powering for the point estimate and powering for that lower bound produce very different studies:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(powered_for_point_estimate =\n    ceiling(power.t.test(delta = 0.50, sd = 1, power = .80,\n                         type = \"two.sample\")$n),\n  powered_for_lower_bound =\n    ceiling(power.t.test(delta = published[\"lower\"], sd = 1, power = .80,\n                         type = \"two.sample\")$n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npowered_for_point_estimate    powered_for_lower_bound \n                        64                        459 \n```\n:::\n:::\n\n\n\nIf the original estimate was accurate, both studies find the effect. If the original was a lucky draw from the high end of its own sampling distribution, only the second one does. The first returns a null result, and everybody spends eighteen months arguing about whether the replication was competent.\n\n::: {.callout-warning title=\"Now Try It With a Small Original Study\"}\nRun the same calculation on a $d = .50$ reported from 25 participants per group:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nround(d_ci(0.50, 25, 25), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n lower      d  upper \n-0.063  0.500  1.063 \n```\n:::\n:::\n\n\n\nThe lower bound is **negative**. The confidence interval includes zero, and no honest safeguard-power calculation is possible, because the original study is compatible with an effect in the opposite direction.\n\nThis is not a defect in the method. It is the method working correctly and telling you something you did not want to hear: **that study never established an effect size at all.** It established a range so wide that it contains \"helps a lot,\" \"does nothing,\" and \"actively harms.\"\n\nPowering a replication off a point estimate like that is not a calculation. It is a wish with decimal places.\n:::\n\n## When the Formula Will Not Do: Simulate\n\n`power.t.test()` handles t-tests. The moment your design gets more complicated, unequal group sizes, non-normal outcomes, planned attrition, an outcome measured on a bounded scale, the closed-form solution runs out.\n\nThe general-purpose answer is to simulate. Build the world you expect, run your analysis on it thousands of times, and count how often you win.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimulate_power <- function(n_per_group, true_d, n_sims = 2000, alpha = .05) {\n  hits <- replicate(n_sims, {\n    g1 <- rnorm(n_per_group, mean = true_d, sd = 1)\n    g2 <- rnorm(n_per_group, mean = 0,      sd = 1)\n    t.test(g1, g2)$p.value < alpha\n  })\n  mean(hits)\n}\n\nset.seed(343)\nsimulate_power(n_per_group = 30, true_d = 0.5)\n\n# compare to the closed-form answer\npower.t.test(n = 30, delta = 0.5, sd = 1, type = \"two.sample\")$power\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4735\n[1] 0.477841\n```\n:::\n:::\n\n\n\nThe simulation agrees with the formula, which is how you know the simulation is trustworthy. Now you can change the generating model to anything you like, skewed outcomes, 20% dropout, a ceiling effect, and get an answer where no formula exists.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimulate_power_with_dropout <- function(n_per_group, true_d,\n                                        dropout = 0.20, n_sims = 2000) {\n  keep <- round(n_per_group * (1 - dropout))\n  replicate(n_sims, {\n    g1 <- rnorm(keep, mean = true_d, sd = 1)\n    g2 <- rnorm(keep, mean = 0,      sd = 1)\n    t.test(g1, g2)$p.value < .05\n  }) |> mean()\n}\n\nset.seed(343)\nsimulate_power_with_dropout(n_per_group = 30, true_d = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4115\n```\n:::\n:::\n\n\n\nTwenty percent attrition costs real power. Plan for it before it happens, not in the limitations section afterwards.\n\n## Other Tools\n\n`power.t.test()` is deliberately limited. For anything beyond t-tests:\n\n- the **`pwr`** package covers correlations, proportions, chi-square, ANOVA, and regression with the same solve-for-`NULL` logic;\n- **G\\*Power** is free stand-alone software and remains the standard for grant applications;\n- **`simr`** does simulation-based power for mixed models;\n- and for genuinely novel designs, the `simulate_power()` pattern above generalizes to anything you can write down.\n\nNIH and NSF require a power analysis with every grant application. In practice it is difficult, because you must estimate an effect size you do not yet know. Assume small, plan for attrition, and remember that the most expensive study is the underpowered one that answers nothing.\n\n::: {.callout-important title=\"Cohen's Compromise\"}\nCohen's recommendation was simple: do the significance test **and** report the effect size.\n\nTwo pieces of information. First, is the result distinguishable from sampling error? Second, does the effect mean anything at all?\n\nHe proposed this in 1962. APA made it standard in 2010.\n\nForty-eight years. Please do not make it take any longer.\n:::\n\n::: {.callout-note title=\"Figure Credit\"}\nThe power and signal-detection illustrations in this chapter are adapted from Kristoffer Magnusson's [textbook-illustration walkthrough](http://rpsychologist.com/creating-a-typical-textbook-illustration-of-statistical-power-using-either-ggplot-or-base-graphics), updated for current ggplot2 syntax because the original was written back when `size` still meant line width.\n:::\n",
    "supporting": [
      "Chapter_Power_Effect_Size_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}