<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An accessible, example-driven introduction to psychological statistics and R.">

<title>4&nbsp; Distributions and their Moments – Psychological Statistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ch_05_Standard_Error.html" rel="next">
<link href="./Ch_03_Probability.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6aaad9ee1f70880fa5715553a7f5f012.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_01_Introduction.html">The Necessary Slog</a></li><li class="breadcrumb-item"><a href="./Ch_04_Distributions.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions and their Moments</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Psychological Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/apd217/Textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Psychological_Statistics_with_R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">The Necessary Slog</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_01_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why You Have to Learn Statistics (Sorry not sorry)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_02_R_Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R: The Extremely Short Survival Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_03_Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability: The Gods Are Fickle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_04_Distributions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions and their Moments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_05_Standard_Error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Standard Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_06_One_Sample_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Sample t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_07_Power_Effect_Size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Power and Effect Size</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_08_Independent_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independent Samples t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_09_Paired_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Paired-Samples t-Test</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Putting Lines Through Things</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_10_Covariance_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Covariance and Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_11_Intro_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_12_Categorical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Regression with Categorical Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_13_Multiple_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Multiple Regression: Statistical Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_14_Hierarchical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hierarchical Regression: Testing Whether Your Model Improves</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_15_Statistical_Control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Statistical Control: What Are We Actually Removing?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_16_Continuous_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_17_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Categorical-by-Categorical Interactions: The 2-by-2 Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_18_Mixed_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mixed Regression: Between People and Within People</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Okay, But What If It’s Complicated?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_19_Regression_Diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Advanced: Regression Diagnostics and Influential Weirdos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_20_Multiple_Comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">P-Values and Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_21_Advanced_Interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Advanced: Continuous and Higher-Order Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_22_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_23_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Mediation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_24_Moderated_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Moderated Mediation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">ANOVA is dead, Long Live ANOVA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_25_ANOVA_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Historical ANOVA Lectures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_26_One_Way_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Introduction to Analysis of Variance (ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_27_One_Way_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Follow-Ups to One-Way ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_28_Two_Way_Between_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Calculating the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_29_Two_Way_Between_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Following Up the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_30_One_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">From the Paired <em>t</em>-Test to the One-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_31_Two_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Two-Way Within-Subjects ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_32_Two_Way_Within_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Follow-Ups to the Two-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_33_Mixed_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Two-Way Mixed-Design ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Other Statistical Creatures</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_34_Chi_Square.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Pearson’s Chi-Square</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_35_Nonparametric_Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Nonparametric Tests: When the Data Refuse to Behave</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_36_Bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Advanced: Bootstrapping, the Jackknife, and Resampling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">When R Inevitably Betrays You</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_37_Reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Reporting Models Without Making the Reader Solve a Puzzle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_38_Tidyverse_Review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">R Help and Review: Tidyverse Without Tears</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_01_Introduction.html">The Necessary Slog</a></li><li class="breadcrumb-item"><a href="./Ch_04_Distributions.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions and their Moments</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions and their Moments</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="what-is-a-distribution" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="what-is-a-distribution"><span class="header-section-number">4.1</span> What is a distribution?</h2>
<p>A <strong>distribution</strong> is a picture of how values spread out in a population:</p>
<ul>
<li>Where do most observations fall?</li>
<li>How much do they vary?</li>
<li>Is it symmetric, or does it have a long tail?</li>
</ul>
<p>The average alone cannot answer these questions. Two groups can have the same mean while one forms a tidy hill and the other consists of people at both extremes glaring across an empty middle. A mean without its distribution is a witness who has omitted several important details.</p>
<section id="a-real-distribution" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="a-real-distribution"><span class="header-section-number">4.1.1</span> A real distribution</h3>
<p>Income in the US is a classic <strong>positively-skewed</strong> distribution: most households cluster around moderate incomes, with a few earning <em>very</em> large amounts.</p>
<p>This plot uses binned Census data <span class="citation" data-cites="uscensus2024">(<a href="#ref-uscensus2024" role="doc-biblioref">U.S. Census Bureau 2024</a>)</span>, so the mean and median are approximations. Also: the $200k+ bin is <em>everything</em> from $200k to infinity—so if it’s the tallest bar, that doesn’t mean $200k is the most common income. It just means rich people got lumped together.</p>
<p>That open-ended bin also means our mean below is too <em>low</em>. We estimate each bin by its midpoint, and “$200,000 to infinity” has no midpoint, so those households get dropped. Census reports a higher mean than we compute here for exactly that reason. The richest households are the ones you cannot put a midpoint on, and they are precisely the ones dragging the real mean upward.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/income-distribution-1.png" class="img-fluid figure-img" alt="Histogram of U.S. household income by bin, with a long right tail. Vertical lines mark the approximate mode near thirty thousand dollars, the median near eighty thousand, and the mean well to the right of both, past one hundred thousand." width="624"></p>
<figcaption>U.S. household income. The mean sits well to the right of the median, which is what skew does to an average.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Think about it:</strong></p>
<ol type="1">
<li>Why is there a positive skew (the tail points right on the x-axis, toward the larger numbers)?</li>
<li>Which number—mean = $110K, median = $80K, or mode = $32K—best represents the “average” American? Why?</li>
<li>Notice the three numbers are not close to each other. If a politician wanted to claim Americans are doing great, which one would they quote? If they wanted to claim the opposite?</li>
</ol>
</section>
<section id="a-sidenote-for-the-curious" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="a-sidenote-for-the-curious"><span class="header-section-number">4.1.2</span> A sidenote for the curious</h3>
<p>Suppose a policy substantially reduced the highest incomes and moved that money into schools, housing, and infrastructure.</p>
<p><strong>Predict:</strong> how would the income distribution shift? What would happen to the mean, median, and mode? Be explicit about why each one would (or would not) change. This is a distribution question, not a political one—the same reasoning works if you run the policy backward.</p>
</section>
<section id="distributions-have-meaning" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="distributions-have-meaning"><span class="header-section-number">4.1.3</span> Distributions have meaning</h3>
<p>Governments tend to use median income to decide who qualifies for financial aid, housing assistance, school lunch programs, tax credits, and healthcare subsidies.</p>
<p>When a distribution is highly skewed, these numbers tell very different stories. A rising <em>mean</em> can make a country look richer even when <strong>most</strong> households see no change—the median may stay flat. Understanding the shape helps us see who’s actually benefiting from policy decisions.</p>
<div class="callout callout-style-default callout-important callout-titled" title="The Mean Can Be Correct and Still Mislead You">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The Mean Can Be Correct and Still Mislead You
</div>
</div>
<div class="callout-body-container callout-body">
<p>In a strongly skewed distribution, a small number of enormous values can drag the mean upward.</p>
<p>That does not make the mean mathematically wrong. It may simply describe the US income inequality problem rather than the experience of a typical person.</p>
<p>Always inspect the distribution before allowing the mean to speak for everyone.</p>
</div>
</div>
</section>
</section>
<section id="gaussian-normal-distribution" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="gaussian-normal-distribution"><span class="header-section-number">4.2</span> Gaussian (Normal) Distribution</h2>
<p>Imagine a general cognitive measure influenced by many small factors: sleep, attention, schooling, mood, caffeine, random neural noise, and whether a bat-wielding researcher was standing behind the participant. When many small influences add together, scores can form a smooth, symmetric hill. That hill is the <strong>normal distribution</strong>.</p>
<p>The Gaussian distribution (named after Carl Friedrich Gauss, 1777–1855) is the foundation of classical parametric statistics because (<em>we pretend</em>) it describes a huge range of psychological phenomena.</p>
<p>Two parameters fully define it:</p>
<ul>
<li><span class="math inline">\(\mu\)</span> (mean)—where the center is</li>
<li><span class="math inline">\(\sigma\)</span> (standard deviation)—how spread out it is</li>
</ul>
<p>A normal distribution has skewness of zero and excess kurtosis of zero. However, those two values alone do <strong>not</strong> prove that a distribution is normal; very strange distributions can share the same moments. The mean, variance, skewness, and kurtosis are commonly described through the distribution’s <strong>moments</strong>. They summarize important features, but they are not a magical distribution-identification scanner.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Normality Is a Model, Not a Moral Achievement">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Normality Is a Model, Not a Moral Achievement
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Normal” describes a mathematical distribution. It does not mean healthy, desirable, typical, or free from bat-wielding researchers.</p>
<p>A normal distribution has zero skewness and zero excess kurtosis, but matching those two values does not prove that your data are normal. Plot the distribution. Numbers are capable of lying by omission.</p>
</div>
</div>
<section id="simulating-a-population-in-r" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="simulating-a-population-in-r"><span class="header-section-number">4.2.1</span> Simulating a Population in R</h3>
<div class="callout callout-style-default callout-note callout-titled" title="You Do Not Know These Words Yet, and That Is Fine">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>You Do Not Know These Words Yet, and That Is Fine
</div>
</div>
<div class="callout-body-container callout-body">
<p>The code below asks for a mean and a standard deviation, and I have not taught you either one. On purpose.</p>
<p>Right now this is just a machine for manufacturing a million fake people so we have something to look at. By the end of this chapter you will know exactly what every term in it means, and you can come back and read it again with the smug satisfaction of someone who understands the joke the second time.</p>
</div>
</div>
<p>We’ll use the normal distribution as our population. R makes this easy with <code>rnorm()</code>.</p>
<p>Let’s create a population with:</p>
<ul>
<li><span class="math inline">\(\mu = 100\)</span> points (cognitive score)</li>
<li><span class="math inline">\(\sigma = 15\)</span> points</li>
<li><span class="math inline">\(N = 1,000,000\)</span></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)  <span class="co"># so your million fake people are the same as my million fake people</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>n  <span class="ot">&lt;-</span> <span class="fl">1e6</span>     <span class="co"># 1e6 is scientific notation for 1,000,000</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>Mu <span class="ot">&lt;-</span> <span class="dv">100</span>     <span class="co"># population mean</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>S  <span class="ot">&lt;-</span> <span class="dv">15</span>      <span class="co"># population SD</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># rnorm() = "random normal". Draw n scores from a normal distribution</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># with the mean and SD we just specified.</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>Normal.Sample<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> Mu, <span class="at">sd =</span> S)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="histogram-base-r" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="histogram-base-r"><span class="header-section-number">4.2.2</span> Histogram (Base R)</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Normal.Sample<span class="fl">.1</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">col    =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">border =</span> <span class="st">"black"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">main   =</span> <span class="st">"Raw Score Histogram"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab   =</span> <span class="st">"Population Distribution"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab   =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> Mu, <span class="at">col =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/raw-score-histogram-1.png" class="img-fluid figure-img" alt="Histogram of one million simulated scores, forming a symmetric bell shape centered on 100, with a vertical line marking the population mean and almost all scores falling between 55 and 145." width="480"></p>
<figcaption>One million simulated cognitive scores. This is what we mean by a population: everybody, not a sample of them.</figcaption>
</figure>
</div>
</div>
</div>
<p>Looks normal. Now let’s describe its shape using the 4 moments.</p>
</section>
</section>
<section id="moments" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="moments"><span class="header-section-number">4.3</span> Moments</h2>
<p>Four numbers capture the important features of a distribution: center, spread, symmetry, and peakiness.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Pedantic Fine Print for Graduate Students">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Pedantic Fine Print for Graduate Students
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Calling all four of these “the moments” is teaching shorthand. Strictly, the mean is the first <em>raw</em> moment, the variance is the second <em>central</em> moment, and skewness and kurtosis are the third and fourth <em>standardized</em> moments. Nobody at a party cares.</p>
</div>
</div>
</div>
<section id="moment-1-central-tendency" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="moment-1-central-tendency"><span class="header-section-number">4.3.1</span> Moment 1: Central Tendency</h3>
<p>The center of a distribution can be described three ways:</p>
<p><strong>Mean</strong> (the average):</p>
<ul>
<li>Standard measure of central tendency</li>
<li>Heavily influenced by outliers</li>
<li>Most stable estimate from sample to sample</li>
</ul>
<p><strong>Median</strong> (the middle number):</p>
<ul>
<li>Not sensitive to outliers</li>
<li>Best measure when the distribution is skewed</li>
</ul>
<p><strong>Mode</strong> (most common number):</p>
<ul>
<li>Least stable from sample to sample</li>
</ul>
</section>
<section id="mean" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="mean"><span class="header-section-number">4.3.2</span> Mean</h3>
<p><span class="math display">\[M = \frac{\Sigma X}{N}\]</span></p>
<p>Add up every score, divide by how many there are. You have done this since grade school.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Two Symbols for the Mean, and You Will Only Ever Have One of Them">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Two Symbols for the Mean, and You Will Only Ever Have One of Them
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is a mean of the <strong>population</strong>, written <span class="math inline">\(\mu\)</span> (the Greek letter <em>mu</em>, said “mew”), and a mean of your <strong>sample</strong>, written <span class="math inline">\(M\)</span>.</p>
<p>They are not two names for the same thing. <span class="math inline">\(\mu\)</span> is the real answer, the average of every person in the population, and <strong>you will almost certainly never know it.</strong> It exists, it is a fixed number, and it is none of your business. <span class="math inline">\(M\)</span> is what you get when you grab a handful of people and average them. It is your estimate of <span class="math inline">\(\mu\)</span>, and it is the only one of the two you will ever hold in your hand.</p>
<p>This chapter is a rare exception, because I built the population myself and can therefore cheat. I told R that <span class="math inline">\(\mu = 100\)</span>. In a real study nobody hands you that number, which is exactly why the next several chapters exist.</p>
<p>The same split is coming for spread: <span class="math inline">\(\sigma\)</span> for the population, <span class="math inline">\(S\)</span> for your sample. Same relationship, same problem, same resignation.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>SumX <span class="ot">&lt;-</span> <span class="fu">sum</span>(Normal.Sample<span class="fl">.1</span>)         <span class="co"># add up every score</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>N    <span class="ot">&lt;-</span> <span class="fu">length</span>(Normal.Sample<span class="fl">.1</span>)      <span class="co"># count how many scores there are</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>M    <span class="ot">&lt;-</span> SumX <span class="sc">/</span> N                     <span class="co"># divide: that is the mean</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>M</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100.0086</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Or all at once:</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">sum</span>(Normal.Sample<span class="fl">.1</span>) <span class="sc">/</span> <span class="fu">length</span>(Normal.Sample<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The mean was 100.01—close to our target <span class="math inline">\(\mu\)</span> of 100, though notice it is not <em>exactly</em> 100 even with a million people. But just use the built-in:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Normal.Sample<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100.0086</code></pre>
</div>
</div>
</section>
<section id="median" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="median"><span class="header-section-number">4.3.3</span> Median</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(Normal.Sample<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100.0208</code></pre>
</div>
</div>
<p>Want to do it by hand? This is a good excuse to explain what a <strong>function</strong> actually is, because you have been using them since Chapter 2 without anyone defining the word.</p>
<p>A function is a machine you build once and then use forever. You hand it something, it does its work, it hands something back. <code>mean()</code> is a function: you hand it numbers, it hands back their average. So is <code>sort()</code>, and <code>length()</code>, and every other word in this book followed by parentheses.</p>
<p>You can build your own with <code>function()</code>. The thing in the parentheses is the <strong>argument</strong>, the placeholder for whatever gets handed in. Here is the median, built from scratch:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function called calculate_median that takes one input, x.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>calculate_median <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  sorted_x <span class="ot">&lt;-</span> <span class="fu">sort</span>(x)         <span class="co"># step 1: put the scores in order, smallest to largest</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(sorted_x)       <span class="co"># step 2: count how many there are</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (n <span class="sc">%%</span> <span class="dv">2</span> <span class="sc">==</span> <span class="dv">1</span>) {          <span class="co"># step 3: is n odd? (%% gives the remainder after dividing)</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    sorted_x[(n <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">2</span>]     <span class="co"># odd, so there is one number dead in the middle. Take it.</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># even, so there is no single middle. Take the two middle numbers</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># and average them.</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    (sorted_x[n <span class="sc">/</span> <span class="dv">2</span>] <span class="sc">+</span> sorted_x[(n <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="dv">1</span>]) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Now USE the machine we just built.</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="fu">calculate_median</span>(Normal.Sample<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100.0208</code></pre>
</div>
</div>
<p>Two bits of syntax worth naming, because they show up constantly:</p>
<ul>
<li><strong><code>sorted_x[3]</code></strong> means “the 3rd item in <code>sorted_x</code>.” Square brackets pull items out by position.</li>
<li><strong><code>%%</code></strong> is the remainder operator. <code>7 %% 2</code> is 1, because 7 divided by 2 leaves 1 over. So <code>n %% 2 == 1</code> is R’s way of asking “is n odd?”</li>
</ul>
<p>Same answer as <code>median()</code>. Lots of code. This is why R has built-in functions!</p>
</section>
<section id="mode" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="mode"><span class="header-section-number">4.3.4</span> Mode</h3>
<p>No built-in mode function in R for continuous data—and it’s almost never used for normal distributions. Note: <code>mode()</code> in R tells you the <em>type</em> of an object (numeric, factor, etc.), not the statistical mode.</p>
</section>
<section id="moment-2-spread" class="level3" data-number="4.3.5">
<h3 data-number="4.3.5" class="anchored" data-anchor-id="moment-2-spread"><span class="header-section-number">4.3.5</span> Moment 2: Spread</h3>
<p>Variance describes how spread out a distribution is. In psychology we mostly use <strong>variance</strong> and <strong>standard deviation</strong> because they work well with normal distributions and parametric statistics.</p>
<p>Variability comes from:</p>
<ul>
<li>Individual differences (genetics, mood, experience—what they ate for lunch that day)</li>
<li>Research/environment factors (testing conditions, context—the researcher wearing a blood-soaked white coat)</li>
<li>Measurement effects (fatigue, questions priming answers—don’t think about a pink elephant)</li>
</ul>
<p>When estimating variance from a sample, we divide by <span class="math inline">\(N - 1\)</span> instead of <span class="math inline">\(N\)</span> to get an unbiased estimate. This is called <strong>degrees of freedom</strong>.</p>
<p>That sentence is true and completely unhelpful, so let us do better. There are two questions hiding in it, and students ask both of them every single year.</p>
</section>
<section id="why-square-the-deviations" class="level3" data-number="4.3.6">
<h3 data-number="4.3.6" class="anchored" data-anchor-id="why-square-the-deviations"><span class="header-section-number">4.3.6</span> Why Square the Deviations?</h3>
<p>Start with the obvious idea: to measure spread, average how far each score sits from the mean. Try it.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x <span class="sc">-</span> <span class="fu">mean</span>(x)        <span class="co"># each score's distance from the mean</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3 -1 -1 -1  0  0  2  4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(x <span class="sc">-</span> <span class="fu">mean</span>(x))   <span class="co"># add them all up</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Zero. Not close to zero—zero. It will be zero for every data set you will ever collect, because that is what a mean <em>is</em>: the balance point where the negatives and positives cancel exactly.</p>
<p>So the honest average distance is useless as a measure of spread. Squaring fixes it: every squared deviation is positive, nothing cancels, and bigger deviations count for disproportionately more.</p>
</section>
<section id="why-divide-by-n-1-and-not-n" class="level3" data-number="4.3.7">
<h3 data-number="4.3.7" class="anchored" data-anchor-id="why-divide-by-n-1-and-not-n"><span class="header-section-number">4.3.7</span> Why Divide by <span class="math inline">\(N-1\)</span> and Not <span class="math inline">\(N\)</span>?</h3>
<p>Here is the intuition. Once you know the mean and all but one of the deviations, the last deviation is not free—it is forced to be whatever makes the sum come out to zero. Eight numbers, but only seven of them can vary independently once the mean is fixed. You have <span class="math inline">\(N-1\)</span> independent pieces of information, so you divide by <span class="math inline">\(N-1\)</span>.</p>
<p>That is the explanation. Here is the proof, because code is an awesome way to settle an argument.</p>
<p>This uses a function you will see constantly from here on: <strong><code>replicate()</code></strong>. It does exactly what the name says. You give it a number and a block of code, and it runs that code that many times, collecting every answer. <code>replicate(10000, ...)</code> means “do this ten thousand times and keep all ten thousand results.” It is how we run a study over and over without recruiting a single human.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">343</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The truth: a population with variance of exactly 25 (because SD = 5, and 5^2 = 25).</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>truth <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the following block 10,000 times, keeping every answer.</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>estimates <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, {</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">8</span>, <span class="at">mean =</span> <span class="dv">100</span>, <span class="at">sd =</span> <span class="dv">5</span>)   <span class="co"># grab a tiny sample of 8 people</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  deviations <span class="ot">&lt;-</span> (s <span class="sc">-</span> <span class="fu">mean</span>(s))<span class="sc">^</span><span class="dv">2</span>       <span class="co"># squared distance of each score from ITS OWN mean</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Compute the variance two ways and return both.</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">divide_by_N   =</span> <span class="fu">sum</span>(deviations) <span class="sc">/</span> <span class="dv">8</span>,   <span class="co"># the tempting way</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">divide_by_N_1 =</span> <span class="fu">sum</span>(deviations) <span class="sc">/</span> <span class="dv">7</span>)   <span class="co"># the N-1 way</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co"># estimates now holds 10,000 answers of each kind. Average them.</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rowMeans</span>(estimates), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  divide_by_N divide_by_N_1 
        21.80         24.91 </code></pre>
</div>
</div>
<p>Dividing by <span class="math inline">\(N\)</span> gives an answer that is systematically too small. Dividing by <span class="math inline">\(N-1\)</span> lands closer to the truth. Ten thousand samples do not lie, and now you never have to wonder whether that <span class="math inline">\(-1\)</span> is a typo. I will have lots of typos in other places for you to find.</p>
</section>
<section id="variance-and-sd" class="level3" data-number="4.3.8">
<h3 data-number="4.3.8" class="anchored" data-anchor-id="variance-and-sd"><span class="header-section-number">4.3.8</span> Variance and SD</h3>
<p>Population variance (when we have the entire population and know <span class="math inline">\(\mu\)</span>): <span class="math display">\[\sigma^2 = \frac{\Sigma (X-\mu)^2}{N}\]</span></p>
<p>Sample variance, using <span class="math inline">\(N-1\)</span> to estimate population variance: <span class="math display">\[S^2 = \frac{\Sigma (X-M)^2}{N-1}\]</span></p>
<div class="callout callout-style-default callout-important callout-titled" title="Greek Letters Are the Truth; Roman Letters Are Your Guess">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Greek Letters Are the Truth; Roman Letters Are Your Guess
</div>
</div>
<div class="callout-body-container callout-body">
<p>You just met the second pair, so here is the rule that runs through the entire rest of this book.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Population (the truth)</th>
<th>Sample (your estimate)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td><span class="math inline">\(\mu\)</span> (mu)</td>
<td><span class="math inline">\(M\)</span></td>
</tr>
<tr class="even">
<td>Variance</td>
<td><span class="math inline">\(\sigma^2\)</span> (sigma squared)</td>
<td><span class="math inline">\(S^2\)</span></td>
</tr>
<tr class="odd">
<td>Standard deviation</td>
<td><span class="math inline">\(\sigma\)</span> (sigma)</td>
<td><span class="math inline">\(S\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Greek letters describe the population.</strong> They are fixed, real, and almost always unknowable.</p>
<p><strong>Roman letters describe your sample.</strong> They are computed from data you actually collected, they change every time you collect new data, and they are your best available guess at the Greek letter sitting behind them.</p>
<p>So <span class="math inline">\(M\)</span> is your guess at <span class="math inline">\(\mu\)</span>, and <span class="math inline">\(S\)</span> is your guess at <span class="math inline">\(\sigma\)</span>. When you see a Greek letter in a formula, ask yourself where that number is supposed to come from, because in real research the answer is usually “nowhere, and that is the problem we are about to solve.”</p>
</div>
</div>
<p>R vectorizes this for you (turns into a string of numbers), but watch your parentheses. The built-in <code>var()</code> uses <span class="math inline">\(M\)</span> and <span class="math inline">\(N-1\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Variance.M <span class="ot">&lt;-</span> <span class="fu">var</span>(Normal.Sample<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sample variance = 225.47</p>
<p><span class="math display">\[S = \sqrt{S^2}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>SD.calc <span class="ot">&lt;-</span> <span class="fu">sd</span>(Normal.Sample<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sample <em>SD</em> = 15.02</p>
<div class="callout callout-style-default callout-note callout-titled" title="Variance Has Weird Units; SD Comes Back Home">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Variance Has Weird Units; SD Comes Back Home
</div>
</div>
<div class="callout-body-container callout-body">
<p>Variance is measured in <strong>squared units</strong>.</p>
<ul>
<li>If reaction time is measured in seconds, variance is measured in seconds squared.</li>
<li>If exam scores are measured in points, variance is measured in points squared.</li>
<li>If cookie-dough devotion is measured in questionable rating units, variance uses questionable rating units squared.</li>
</ul>
<p>Standard deviation takes the square root of variance, returning to the original units. That is one reason SD is easier to interpret.</p>
</div>
</div>
</section>
<section id="a-dot-plot-where-does-one-standard-deviation-live" class="level3" data-number="4.3.9">
<h3 data-number="4.3.9" class="anchored" data-anchor-id="a-dot-plot-where-does-one-standard-deviation-live"><span class="header-section-number">4.3.9</span> A Dot Plot: Where Does One Standard Deviation Live?</h3>
<p>The standard deviation is a measure of the <strong>typical distance of scores from the mean</strong>. It is calculated from every score’s distance from the mean. It is not defined by capturing a particular percentage of people. But what does <strong>typical distance</strong> mean? <em>What do truth and god mean, for that matter? Well, to quote the great teacher G’Kar, truth is a river and god is the mouth of that river. Note: if you got that joke, you are a super nerd and we can be friends.</em></p>
<p>The <strong>typical distance</strong> concept applies really only when the distribution is approximately normal and the standard deviations divide the distribution in a very useful and predictable way:</p>
<ul>
<li>About 34% of scores fall between the mean and one SD <strong>below</strong> the mean.</li>
<li>About 34% fall between the mean and one SD <strong>above</strong> the mean.</li>
<li>Put those pieces together, and about 68% fall within one SD of the mean.</li>
<li>About 95% fall within two SDs of the mean.</li>
</ul>
<p>Let us make that visible with an extremely central psychological construct: love of cookie-dough ice cream.</p>
<p>We ask 240 people:</p>
<blockquote class="blockquote">
<p><strong>How much do you like cookie-dough ice cream?</strong></p>
</blockquote>
<p>They answer on a 1–10 unipolar rating scale:</p>
<ul>
<li><strong>1 = Not at all</strong></li>
<li><strong>10 = I would trade my mother for cookie-dough ice cream</strong></li>
</ul>
<p>The scale is <strong>unipolar</strong> because it begins with none of the feeling and moves in one direction toward more of it. The opposite endpoint is not “I hate cookie-dough ice cream with the fire of a thousand suns.” That would be a bipolar scale and clearly a cry for professional help.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/cookie-dough-sd-1.png" class="img-fluid figure-img" alt="A jittered dot plot of 240 cookie-dough ratings on a 1 to 10 scale. A solid vertical line marks the mean, dashed lines mark one standard deviation on each side, and dotted lines mark two. Shaded bands label about 34 percent between the mean and each one-SD boundary, about 68 percent within one SD, and about 95 percent within two SDs." width="672"></p>
<figcaption>Simulated cookie-dough ratings. The dots are people; the lines mark the mean and standard-deviation boundaries. The 34%, 68%, and 95% values describe an approximately normal distribution.</figcaption>
</figure>
</div>
</div>
</div>
<p>In this particular simulated sample, 76.2% of ratings fall within one SD of the mean and 93.3% fall within two SDs. Those values will not equal exactly 68% and 95%. These are discrete ratings from one sample, not obedient dots hired to impersonate a perfect normal curve. Chance is fickle, and a 1–10 scale also has walls at both ends.</p>
<p>The important visual intuition is this: <strong>one SD takes us from the mean through the thick central part of a normal distribution. Two SDs cover nearly everybody.</strong> A score farther than two SDs from the mean is unusual, although “unusual” does not automatically mean impossible, important, fraudulent, or possessed by evil spirits.</p>
</section>
<section id="relationship-between-m-and-s" class="level3" data-number="4.3.10">
<h3 data-number="4.3.10" class="anchored" data-anchor-id="relationship-between-m-and-s"><span class="header-section-number">4.3.10</span> Relationship between <span class="math inline">\(M\)</span> and <span class="math inline">\(S\)</span></h3>
<p>The standard deviation is expressed in the same units as the scores, and it does not automatically grow just because the mean grows—although annoyingly, it tends to. For positive <strong>ratio-scale</strong> variables, the <strong>coefficient of variation</strong> can compare spread relative to the mean:</p>
<p><span class="math display">\[CV = \frac{S}{|M|}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>CV <span class="ot">&lt;-</span> SD.calc <span class="sc">/</span> <span class="fu">abs</span>(M)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><span class="math inline">\(CV\)</span> = 0.15.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="The CV Needs a Mean Worth Dividing By">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The CV Needs a Mean Worth Dividing By
</div>
</div>
<div class="callout-body-container callout-body">
<p>A problem occurs when the mean is close to zero. Dividing by a tiny mean can produce an enormous and unstable CV. If the mean is zero, the CV is undefined.</p>
<p>Therefore, interpret the CV most confidently when zero has a meaningful interpretation, ratios are sensible, and the mean is not hovering near zero while laughing at you.</p>
</div>
</div>
</section>
<section id="moment-3-skewness" class="level3" data-number="4.3.11">
<h3 data-number="4.3.11" class="anchored" data-anchor-id="moment-3-skewness"><span class="header-section-number">4.3.11</span> Moment 3: Skewness</h3>
<p>Skewness is how asymmetrical the hill is. Generally, the farther the value is from zero, the more skewed the distribution. Human data will almost always be somewhat asymmetrical, like most of our faces. When people’s ears or eyes are slightly asymmetrical, we generally choose to ignore the problem for reasons—assumptions, really—that we hope are true. More on that later.</p>
<p>The skewness formula is below for completeness. Almost nobody reports the metric.</p>
<p><span class="math display">\[Skewness = \frac{\Sigma(X-M)^3 /N}{S^{3}}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>SK.Calc <span class="ot">&lt;-</span> <span class="fu">skewness</span>(Normal.Sample<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Skewness = 0</p>
</section>
<section id="moment-4-kurtosis" class="level3" data-number="4.3.12">
<h3 data-number="4.3.12" class="anchored" data-anchor-id="moment-4-kurtosis"><span class="header-section-number">4.3.12</span> Moment 4: Kurtosis</h3>
<p>This is peakiness! You can have flattish, longish hills (<strong>platykurtic</strong>) or skinny, tall hills (<strong>leptokurtic</strong>). I would be remiss to my mother if I did not point out that these are Greek words. <em>I would also like to point out that nobody has ever confused my body shape with leptokurtotic.</em></p>
<p>The kurtosis formula is below for completeness. Not only does almost nobody report it, I do not think many people know how to make sense of the numbers it spews out.</p>
<p><span class="math display">\[Kurtosis = \frac{\Sigma(X-M)^4 /N}{S^{4}} - 3\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>K.Calc <span class="ot">&lt;-</span> <span class="fu">kurtosis</span>(Normal.Sample<span class="fl">.1</span>) <span class="sc">-</span> <span class="dv">3</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Kurtosis = 0</p>
</section>
<section id="all-four-moments-via-tidyverse" class="level3" data-number="4.3.13">
<h3 data-number="4.3.13" class="anchored" data-anchor-id="all-four-moments-via-tidyverse"><span class="header-section-number">4.3.13</span> All Four Moments via Tidyverse</h3>
<p>The tidyverse is a collection of R packages that makes data work readable and consistent. Think of it as data operations in near-plain English: take this data, group it, summarize it, done.</p>
<p>We need three verbs for now:</p>
<ul>
<li><code>group_by()</code>—split data into groups</li>
<li><code>summarise()</code>—compute statistics per group</li>
<li><code>filter()</code>—keep only rows we want</li>
</ul>
<p>First, put our vector into a <strong>data frame</strong> (R’s version of a spreadsheet—rows are observations, columns are variables):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">X =</span> Normal.Sample<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now compute all four moments at once:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)   <span class="co"># loads dplyr, ggplot2, and friends</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)     <span class="co"># gives us skewness() and kurtosis()</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>Desc.table <span class="ot">&lt;-</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  DF <span class="sc">|&gt;</span>                        <span class="co"># take the data frame, then...</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">N    =</span> <span class="fu">n</span>(),                 <span class="co"># count the rows</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">M    =</span> <span class="fu">mean</span>(X),             <span class="co"># moment 1: center</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">S    =</span> <span class="fu">sd</span>(X),               <span class="co"># moment 2: spread</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">CV   =</span> S <span class="sc">/</span> <span class="fu">abs</span>(M),          <span class="co"># spread relative to the mean</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">Skew =</span> <span class="fu">skewness</span>(X),         <span class="co"># moment 3: lopsidedness</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">Kurt =</span> <span class="fu">kurtosis</span>(X) <span class="sc">-</span> <span class="dv">3</span>)     <span class="co"># moment 4: tails (minus 3 = "excess")</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(Desc.table, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      N      M     S   CV Skew Kurt
1 1e+06 100.01 15.02 0.15    0    0</code></pre>
</div>
</div>
<p>That <code>|&gt;</code> is a <strong>pipe</strong>. Read it as the word “then.” It takes whatever is on its left and feeds it into the function on its right, so <code>DF |&gt; summarise(...)</code> means “take DF, <em>then</em> summarise it.” It saves you from writing <code>summarise(DF, ...)</code> with everything crammed inside one set of parentheses, and it gets very handy once you are stacking four or five operations.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="About All Those Plots I Keep Making Without Explaining Them">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>About All Those Plots I Keep Making Without Explaining Them
</div>
</div>
<div class="callout-body-container callout-body">
<p>You have now seen several figures built with <code>ggplot()</code>, and I have never once told you how it works. That is deliberate. Explaining the grammar of graphics in the middle of a chapter about variance would help nobody.</p>
<p>There is a whole chapter on <code>ggplot()</code> and the tidyverse at the end of the book. When you want to make your own plots rather than read mine, go there. For now, feel free to copy any plotting code you see, change the variable names, and see what happens. That is how everyone learns it anyway.</p>
</div>
</div>
</section>
</section>
<section id="distributions-and-probability" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="distributions-and-probability"><span class="header-section-number">4.4</span> Distributions and Probability</h2>
<p>A distribution isn’t just a picture of data—it lets us make <strong>probability statements</strong>.</p>
<p>The height of the curve at any point tells us how likely values near that point are. This is the <strong>Probability Density Function</strong> (PDF).</p>
<section id="probability-density-function-pdf" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="probability-density-function-pdf"><span class="header-section-number">4.4.1</span> Probability Density Function (PDF)</h3>
<p><span class="math display">\[f(x) = \frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{(x - \mu)^2}{2 \sigma^2}}\]</span></p>
<p>Looks scary. The concept is simple:</p>
<ul>
<li>Values near the mean <span class="math inline">\(\rightarrow\)</span> highest density</li>
<li>Values far from the mean <span class="math inline">\(\rightarrow\)</span> lower density</li>
<li>Shape is fully determined by <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span></li>
</ul>
<p>In practice, we convert to <strong>z-scores</strong> so that mean = 0 and <em>SD</em> = 1, which makes everything easier.</p>
</section>
<section id="z-scores" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="z-scores"><span class="header-section-number">4.4.2</span> Z-scores</h3>
<p>A <strong>z-score</strong> tells you how far a value is from the mean in standard deviation units:</p>
<ul>
<li>z = 0 <span class="math inline">\(\rightarrow\)</span> exactly at the mean</li>
<li>z = 1 <span class="math inline">\(\rightarrow\)</span> one SD above the mean</li>
<li>z = −1 <span class="math inline">\(\rightarrow\)</span> one SD below the mean</li>
</ul>
<p>Converting to z-scores does <strong>not change the shape</strong> of the distribution—it just re-labels the axis.</p>
<p><span class="math display">\[Z = \frac{X - M}{S}\]</span></p>
<div class="callout callout-style-default callout-important callout-titled" title="A z-Score Is Not a Probability">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>A z-Score Is Not a Probability
</div>
</div>
<div class="callout-body-container callout-body">
<p>A z-score tells us how far a score is from the mean in standard-deviation units.</p>
<p>It does <strong>not</strong> directly tell us the percentage of people below that score. To obtain a percentile, we must use the appropriate distribution—usually with <code>pnorm()</code> when normality is a reasonable model.</p>
<p>A z-score of 1 means one SD above the mean. It does not mean 1%, 10%, or that the participant has won statistics.</p>
</div>
</div>
</section>
<section id="making-z-scores-in-r" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="making-z-scores-in-r"><span class="header-section-number">4.4.3</span> Making Z-scores in R</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>Normal.Sample.Z <span class="ot">&lt;-</span> <span class="fu">scale</span>(Normal.Sample<span class="fl">.1</span>, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>DF.Z <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">X =</span> Normal.Sample.Z)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>Desc.table.Z <span class="ot">&lt;-</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  DF.Z <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">N =</span> <span class="fu">n</span>(), <span class="at">M =</span> <span class="fu">mean</span>(X), <span class="at">S =</span> <span class="fu">sd</span>(X))</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(Desc.table.Z, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      N M S
1 1e+06 0 1</code></pre>
</div>
</div>
<p>The shape doesn’t change:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(Normal.Sample.Z,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">col    =</span> <span class="st">"lightblue"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">border =</span> <span class="st">"black"</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">main   =</span> <span class="st">"Z Score Histogram"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab   =</span> <span class="st">"Population Distribution"</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab   =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/z-score-histogram-1.png" class="img-fluid figure-img" alt="Histogram of the same one million scores converted to z-scores. The bell shape is unchanged from the previous figure, but the horizontal axis now runs from about negative four to positive four and is centered on zero." width="480"></p>
<figcaption>The same one million people after z-scoring. Identical shape, new axis labels. Standardizing moves the ruler, not the data.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="finding-probability-from-z-scores" class="level3" data-number="4.4.4">
<h3 data-number="4.4.4" class="anchored" data-anchor-id="finding-probability-from-z-scores"><span class="header-section-number">4.4.4</span> Finding Probability from Z-scores</h3>
<p>Two functions to know:</p>
<ul>
<li><code>dnorm()</code> <span class="math inline">\(\rightarrow\)</span> height of the curve (density) at a value</li>
<li><code>pnorm()</code> <span class="math inline">\(\rightarrow\)</span> area under the curve to the left of a value (probability)</li>
</ul>
<p>The PDF <code>dnorm()</code> implements:</p>
<p><span class="math display">\[f(x) = \frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{(x - \mu)^2}{2 \sigma^2}}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/z-score-density-1.png" class="img-fluid figure-img" alt="Histogram of z-scores plotted on a density scale, with a smooth bell-shaped curve drawn over it and a vertical line at zero. The curve follows the tops of the bars closely." width="480"></p>
<figcaption>The same histogram with the density curve laid over it. <code>dnorm()</code> draws that curve; <code>pnorm()</code> measures the area underneath it.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="how-much-of-the-population-is-below-the-mean" class="level3" data-number="4.4.5">
<h3 data-number="4.4.5" class="anchored" data-anchor-id="how-much-of-the-population-is-below-the-mean"><span class="header-section-number">4.4.5</span> How much of the population is below the mean?</h3>
<p>Exactly 50%—the normal distribution is symmetric. Confirm it:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5</code></pre>
</div>
</div>
<p>What proportion falls between 1 and 2 SDs above the mean?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">2</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1359051</code></pre>
</div>
</div>
<p>No calculus. Just area under the curve.</p>
</section>
<section id="going-the-other-way" class="level3" data-number="4.4.6">
<h3 data-number="4.4.6" class="anchored" data-anchor-id="going-the-other-way"><span class="header-section-number">4.4.6</span> Going the Other Way</h3>
<p><code>pnorm()</code> takes a score and hands back a proportion. Half the questions you will actually be asked run the other direction: <em>what score do you need to be in the top 10%?</em> That is <code>qnorm()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(.<span class="dv">90</span>)   <span class="co"># the z-score that cuts off the top 10%</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.281552</code></pre>
</div>
</div>
<p>A z of 1.28. Convert back to raw cognitive-score units with <span class="math inline">\(M + zS\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span> <span class="sc">+</span> <span class="fu">qnorm</span>(.<span class="dv">90</span>) <span class="sc">*</span> <span class="dv">15</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 119.2233</code></pre>
</div>
</div>
<p>So you need about 119 points to crack the top 10%. Cutoffs for gifted programs, clinical screening thresholds, and “we only interview the top 5% of applicants” are all this calculation wearing different toupees.</p>
<p>You can also ask the data directly instead of the theoretical curve. <code>quantile()</code> finds the actual score at a given percentile in your sample:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(Normal.Sample<span class="fl">.1</span>, .<span class="dv">90</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     90% 
119.2508 </code></pre>
</div>
</div>
<p>Nearly identical, because we built this population to be normal. On real data the two can disagree, and when they do, the data is right and the curve was an assumption.</p>
</section>
</section>
<section id="real-world-example-mental-rotation-test" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="real-world-example-mental-rotation-test"><span class="header-section-number">4.5</span> Real-World Example: Mental Rotation Test</h2>
<p>We now know how to:</p>
<ul>
<li>Describe distributions</li>
<li>Standardize scores with z-scores</li>
<li>Convert z-scores to probabilities</li>
</ul>
<p>Let’s apply all of it to a real psychological measure.</p>
<p>The <strong>Mental Rotations Test (MRT)</strong> measures spatial visualization ability. Peters et al.&nbsp;developed a redrawn version and examined factors affecting performance <span class="citation" data-cites="peters1995">(<a href="#ref-peters1995" role="doc-biblioref">Peters et al. 1995</a>)</span>. Here’s a summary by field and gender:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 41%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Sciences</th>
<th></th>
<th></th>
<th></th>
<th>Social Sciences &amp; Humanities</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>n</td>
<td>M</td>
<td>SD</td>
<td></td>
<td>n</td>
<td>M</td>
<td>SD</td>
</tr>
<tr class="even">
<td>M</td>
<td>817</td>
<td>15.23</td>
<td>4.42</td>
<td></td>
<td>517</td>
<td>12.74</td>
<td>4.87</td>
</tr>
<tr class="odd">
<td>F</td>
<td>392</td>
<td>11.18</td>
<td>4.37</td>
<td></td>
<td>1358</td>
<td>8.75</td>
<td>4.18</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled" title="Advanced Code Has Arrived Early">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Advanced Code Has Arrived Early
</div>
</div>
<div class="callout-body-container callout-body">
<p>The code below is more advanced; you do not need to understand it yet. Why am I showing you crazy code now? To make you feel bad about yourself and the terrible life choices you made when you took a statistics class!</p>
<p>Actually, I want you to see what R can do. I can go from a table to simulation, graphs, and analysis without a lot of code. Simulating data is my favorite way to make graduate students cry when they propose dissertations because it is the fastest way to discover whether the theory and hypotheses they proposed make any sense. When they do not, the students cry and Dorkaos, our God of Statistics, gains more strength.</p>
</div>
</div>
<section id="step-1-simulate-the-population-distributions" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="step-1-simulate-the-population-distributions"><span class="header-section-number">4.5.1</span> Step 1: Simulate the population distributions</h3>
<p>We only have summary stats, but because MRT scores are approximately normal we can <strong>simulate each group</strong> using <code>rnorm()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>params <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>Field,            <span class="sc">~</span>Group, <span class="sc">~</span>n,    <span class="sc">~</span>mean,  <span class="sc">~</span>sd,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Sciences"</span>,        <span class="st">"M"</span>,    <span class="dv">817</span>,   <span class="fl">15.23</span>,  <span class="fl">4.42</span>,</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Sciences"</span>,        <span class="st">"F"</span>,    <span class="dv">392</span>,   <span class="fl">11.18</span>,  <span class="fl">4.37</span>,</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Social Sciences"</span>, <span class="st">"M"</span>,    <span class="dv">517</span>,   <span class="fl">12.74</span>,  <span class="fl">4.87</span>,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Social Sciences"</span>, <span class="st">"F"</span>,    <span class="dv">1358</span>,   <span class="fl">8.75</span>,  <span class="fl">4.18</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>MRT<span class="fl">.2</span> <span class="ot">&lt;-</span> params <span class="sc">|&gt;</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">data =</span> <span class="fu">pmap</span>(<span class="fu">list</span>(n, mean, sd), rnorm)) <span class="sc">|&gt;</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(data) <span class="sc">|&gt;</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Field, Group, <span class="at">Value =</span> data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Check that our simulation matches published values:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>MRT.table <span class="ot">&lt;-</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  MRT<span class="fl">.2</span> <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Field, Group) <span class="sc">|&gt;</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">N =</span> <span class="fu">n</span>(), <span class="at">M =</span> <span class="fu">mean</span>(Value), <span class="at">S =</span> <span class="fu">sd</span>(Value))</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>MRT.table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 x 5
# Groups:   Field [2]
  Field           Group     N     M     S
  &lt;chr&gt;           &lt;chr&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Sciences        F       392 11.4   4.47
2 Sciences        M       817 15.3   4.34
3 Social Sciences F      1358  8.74  4.16
4 Social Sciences M       517 12.9   4.88</code></pre>
</div>
</div>
</section>
<section id="step-2-visualize-the-distributions" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="step-2-visualize-the-distributions"><span class="header-section-number">4.5.2</span> Step 2: Visualize the distributions</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(MRT<span class="fl">.2</span>, <span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">fill =</span> Group, <span class="at">color =</span> Group)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Field) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Overlaid Histograms &amp; Density Plots"</span>, <span class="at">x =</span> <span class="st">"Score"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/mrt-raw-scores-1.png" class="img-fluid figure-img" alt="Two side-by-side panels, one for Sciences and one for Social Sciences. Each shows overlapping histograms and density curves for two groups on raw mental rotation scores. In both panels the male distribution sits to the right of the female distribution, with substantial overlap between them." width="480"></p>
<figcaption>Raw MRT scores by field and group. The two groups sit in different places on the score axis, and the gap is bigger in the sciences.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="step-3-convert-to-z-scores-within-groups" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="step-3-convert-to-z-scores-within-groups"><span class="header-section-number">4.5.3</span> Step 3: Convert to z-scores (within groups)</h3>
<p>Standardize within each group—critical because each group has a different mean and SD.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>MRT<span class="fl">.2</span> <span class="ot">&lt;-</span> MRT<span class="fl">.2</span> <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Field, Group) <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Z =</span> <span class="fu">scale</span>(Value))</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>MRT<span class="fl">.2</span> <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 x 4
# Groups:   Field, Group [1]
  Field    Group Value   Z[,1]
  &lt;chr&gt;    &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;
1 Sciences M      12.8 -0.583 
2 Sciences M      14.2 -0.247 
3 Sciences M      22.1  1.58  
4 Sciences M      15.5  0.0594
5 Sciences M      15.8  0.119 
6 Sciences M      22.8  1.73  </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(MRT<span class="fl">.2</span>, <span class="fu">aes</span>(<span class="at">x =</span> Z, <span class="at">fill =</span> Group, <span class="at">color =</span> Group)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Field) <span class="sc">+</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Overlaid Histograms &amp; Density Plots"</span>, <span class="at">x =</span> <span class="st">"Z-Score"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/mrt-z-scores-1.png" class="img-fluid figure-img" alt="The same two panels as the previous figure, but on a z-score axis. All four distributions now center on zero and overlap almost completely, because each group has been standardized against its own mean and standard deviation." width="480"></p>
<figcaption>The same scores after z-scoring <em>within</em> each group. The distributions now sit on top of each other, because every group is now measured against its own mean.</figcaption>
</figure>
</div>
</div>
</div>
<p>Why do the curves overlap now? Because standardizing compares <em>relative position within each group</em>, not raw scores.</p>
</section>
<section id="step-4-z-score-to-probability" class="level3" data-number="4.5.4">
<h3 data-number="4.5.4" class="anchored" data-anchor-id="step-4-z-score-to-probability"><span class="header-section-number">4.5.4</span> Step 4: Z-score to probability</h3>
<p>Alex (male, social sciences) got a score of 10. How did he do relative to his peers? (Males, Social Sciences: <span class="math inline">\(M\)</span> = 12.74, <span class="math inline">\(S\)</span> = 4.87)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Z.Alex <span class="ot">&lt;-</span> (<span class="dv">10</span> <span class="sc">-</span> <span class="fl">12.74</span>) <span class="sc">/</span> <span class="fl">4.87</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>Z.Alex</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.5626283</code></pre>
</div>
</div>
<p>A little over half an SD below the mean. Visually:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>MRT.<span class="fl">2.</span>Males.Social.Sciences <span class="ot">&lt;-</span> MRT<span class="fl">.2</span> <span class="sc">|&gt;</span> <span class="fu">filter</span>(Group <span class="sc">==</span> <span class="st">"M"</span> <span class="sc">&amp;</span> Field <span class="sc">==</span> <span class="st">"Social Sciences"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(MRT.<span class="fl">2.</span>Males.Social.Sciences, <span class="fu">aes</span>(<span class="at">x =</span> Z)) <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Males in the Social Sciences"</span>, <span class="at">x =</span> <span class="st">"Z-Score"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> Z.Alex, <span class="at">color =</span> <span class="st">'red'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/alex-position-1.png" class="img-fluid figure-img" alt="Histogram and density curve of z-scores for males in the social sciences, centered on zero. A vertical red line sits a little over half a standard deviation below zero, marking Alex's score." width="480"></p>
<figcaption>Alex’s place among male social scientists. The red line is him. Most of the distribution is to the right of it.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(Z.Alex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.286844</code></pre>
</div>
</div>
<p>Only better than 28.7% of peers. That’s also called a <strong>percentile</strong>.</p>
</section>
<section id="step-5-same-raw-score-different-meaning" class="level3" data-number="4.5.5">
<h3 data-number="4.5.5" class="anchored" data-anchor-id="step-5-same-raw-score-different-meaning"><span class="header-section-number">4.5.5</span> Step 5: Same raw score, different meaning</h3>
<p>Emma also scored a 10, but she’s in a different group (Female, Social Sciences: <span class="math inline">\(M\)</span> = 8.75, <span class="math inline">\(S\)</span> = 4.18).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>Z.Emma <span class="ot">&lt;-</span> (<span class="dv">10</span> <span class="sc">-</span> <span class="fl">8.75</span>) <span class="sc">/</span> <span class="fl">4.18</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>Z.Emma</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2990431</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(Z.Emma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6175464</code></pre>
</div>
</div>
<p>Emma scored better than 61.8% of her peers.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(pnorm, <span class="at">from =</span> <span class="sc">-</span><span class="dv">10</span>, <span class="at">to =</span> <span class="dv">10</span>,</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Cumulative Density Function"</span>,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"z-score"</span>, <span class="at">ylab =</span> <span class="st">"Probability"</span>,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.25</span>, <span class="fl">3.25</span>))</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> Z.Emma, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> Z.Alex, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_04_Distributions_files/figure-html/cdf-alex-emma-1.png" class="img-fluid figure-img" alt="An S-shaped cumulative probability curve rising from zero to one across z-scores of about negative three to positive three. A blue vertical line sits left of center at Alex's z-score, crossing the curve at roughly 0.29. A red vertical line sits right of center at Emma's z-score, crossing at roughly 0.62." width="480"></p>
<figcaption>The same raw score of 10, read against two different reference groups. Emma (red) lands above the middle; Alex (blue) lands below it. The score never moved. The comparison group did.</figcaption>
</figure>
</div>
</div>
</div>
<p>Same raw score. Emma is above average for her group; Alex is below average for his. Raw scores mean nothing without context.</p>
</section>
<section id="big-idea" class="level3" data-number="4.5.6">
<h3 data-number="4.5.6" class="anchored" data-anchor-id="big-idea"><span class="header-section-number">4.5.6</span> Big idea</h3>
<ul>
<li>Raw scores mean nothing without context.</li>
<li>Distributions give scores meaning.</li>
</ul>
</section>
</section>
<section id="the-short-story" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="the-short-story"><span class="header-section-number">4.6</span> The Short Story</h2>
<ul>
<li>A distribution shows which values occur and how often.</li>
<li>The mean locates the center; variance and standard deviation describe spread.</li>
<li>Skewness describes asymmetry; kurtosis describes tail weight and peak shape relative to a reference distribution.</li>
<li>Zero skewness and zero excess kurtosis do not prove normality. Strange distributions are capable of wearing fake mustaches.</li>
<li>z-scores translate raw scores into standard-deviation units.</li>
<li>The same raw score can mean very different things in different reference groups.</li>
<li>Always inspect the distribution before asking one summary number to represent several hundred people without supervision.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-peters1995" class="csl-entry" role="listitem">
Peters, Michael, Bruno Laeng, K. Latham, M. Jackson, R. Zaiyouna, and C. Richardson. 1995. <span>“A Redrawn Vandenberg and Kuse Mental Rotations Test: Different Versions and Factors That Affect Performance.”</span> <em>Brain and Cognition</em> 28 (1): 39–58. <a href="https://doi.org/10.1006/brcg.1995.1032">https://doi.org/10.1006/brcg.1995.1032</a>.
</div>
<div id="ref-uscensus2024" class="csl-entry" role="listitem">
U.S. Census Bureau. 2024. <em>Historical Income Tables: Households</em>. <a href="https://www.census.gov/data/tables/time-series/demo/income-poverty/cps-hinc/hinc-01.2024.html">https://www.census.gov/data/tables/time-series/demo/income-poverty/cps-hinc/hinc-01.2024.html</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/apd217\.github\.io\/Textbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Ch_03_Probability.html" class="pagination-link" aria-label="Probability: The Gods Are Fickle">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability: The Gods Are Fickle</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ch_05_Standard_Error.html" class="pagination-link" aria-label="Standard Error">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Standard Error</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Alexander P. Demos. Licensed <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/apd217/Textbook/blob/main/Ch_04_Distributions.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/apd217/Textbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>