<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An accessible, example-driven introduction to psychological statistics and R.">

<title>6&nbsp; One Sample t-Test – Psychological Statistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ch_07_Power_Effect_Size.html" rel="next">
<link href="./Ch_05_Standard_Error.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6aaad9ee1f70880fa5715553a7f5f012.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_01_Introduction.html">The Necessary Slog</a></li><li class="breadcrumb-item"><a href="./Ch_06_One_Sample_t.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Sample t-Test</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Psychological Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/apd217/Textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Psychological_Statistics_with_R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">The Necessary Slog</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_01_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why You Have to Learn Statistics (Sorry not sorry)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_02_R_Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R: The Extremely Short Survival Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_03_Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability: The Gods Are Fickle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_04_Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions and their Moments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_05_Standard_Error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Standard Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_06_One_Sample_t.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Sample t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_07_Power_Effect_Size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Power and Effect Size</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_08_Independent_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independent Samples t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_09_Paired_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Paired-Samples t-Test</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Putting Lines Through Things</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_10_Covariance_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Covariance and Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_11_Intro_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_12_Categorical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Regression with Categorical Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_13_Multiple_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Multiple Regression: Statistical Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_14_Hierarchical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hierarchical Regression: Testing Whether Your Model Improves</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_15_Statistical_Control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Statistical Control: What Are We Actually Removing?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_16_Continuous_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_17_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Categorical-by-Categorical Interactions: The 2-by-2 Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_18_Mixed_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mixed Regression: Between People and Within People</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Okay, But What If It’s Complicated?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_19_Regression_Diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Advanced: Regression Diagnostics and Influential Weirdos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_20_Multiple_Comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">P-Values and Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_21_Advanced_Interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Advanced: Continuous and Higher-Order Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_22_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_23_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Mediation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_24_Moderated_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Moderated Mediation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">ANOVA is dead, Long Live ANOVA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_25_ANOVA_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Historical ANOVA Lectures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_26_One_Way_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Introduction to Analysis of Variance (ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_27_One_Way_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Follow-Ups to One-Way ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_28_Two_Way_Between_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Calculating the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_29_Two_Way_Between_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Following Up the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_30_One_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">From the Paired <em>t</em>-Test to the One-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_31_Two_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Two-Way Within-Subjects ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_32_Two_Way_Within_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Follow-Ups to the Two-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_33_Mixed_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Two-Way Mixed-Design ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Other Statistical Creatures</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_34_Chi_Square.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Pearson’s Chi-Square</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_35_Nonparametric_Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Nonparametric Tests: When the Data Refuse to Behave</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_36_Bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Advanced: Bootstrapping, the Jackknife, and Resampling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">When R Inevitably Betrays You</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_37_Reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Reporting Models Without Making the Reader Solve a Puzzle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_38_Tidyverse_Review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">R Help and Review: Tidyverse Without Tears</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_01_Introduction.html">The Necessary Slog</a></li><li class="breadcrumb-item"><a href="./Ch_06_One_Sample_t.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Sample t-Test</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Sample t-Test</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="experimental-logic" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="experimental-logic"><span class="header-section-number">6.1</span> Experimental Logic</h2>
<p>In psychology, we test claims by making comparisons:</p>
<blockquote class="blockquote">
<p>Sometimes we compare a group to a known value: <em>Do more frequent train rides increase CTA liking above the neutral baseline of 3?</em> <span class="math inline">\(\rightarrow\)</span> one-sample <em>t</em>-test.</p>
</blockquote>
<blockquote class="blockquote">
<p>Sometimes we compare two groups: <em>Does CTA liking differ between people in quiet vs.&nbsp;regular subway cars?</em> <span class="math inline">\(\rightarrow\)</span> independent samples <em>t</em>-test.</p>
</blockquote>
<blockquote class="blockquote">
<p>Finally, we also compare people to themselves groups: <em>Do you like to ride the CTA more in the summer or winter?</em> <span class="math inline">\(\rightarrow\)</span> paired samples <em>t</em>-test.</p>
</blockquote>
<p>Either way, the logic is the same: <strong>are the differences we observe larger than we’d expect from random sampling noise alone?</strong></p>
<section id="logic-behind-hypothesis-testing-the-blind-men-and-the-elephant" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="logic-behind-hypothesis-testing-the-blind-men-and-the-elephant"><span class="header-section-number">6.1.1</span> Logic behind Hypothesis testing: The Blind Men and the Elephant</h3>
<p>A group of blind men were traveling together when they encountered a strange object blocking their path. Each man touched a different part of the object and described what he thought it was, based entirely on his limited experience.</p>
<p>One man, feeling the elephant’s trunk, exclaimed, <em>“This must be a thick branch of a tree!”</em> Another, grasping the elephant’s leg, disagreed: <em>“No, it’s clearly a pillar!”</em> A third, holding the elephant’s ear, insisted, <em>“You’re both wrong—it’s obviously a fan!”</em></p>
<p>Each man was convinced he was right, believing his own perspective represented the full truth. Their disagreement quickly escalated into an argument, with each trying to prove the others wrong. Eventually, the elephant, thoroughly unimpressed, grew irritated by their foolishness and tossed them all into a nearby river for disturbing its peace.</p>
<p>— <strong>A paraphrased ancient Indian parable</strong></p>
<p>This story is a useful reminder when trying to understand the world, and especially when building theories from data. Our perspectives are almost always limited, shaped by where we stand, what we’ve experienced, and what we want to believe. Just as each blind man grasped only one part of the elephant, our samples and hypotheses capture only small pieces of a much larger reality.</p>
<p>Statistical testing exists precisely because of this limitation: <em>it gives us a disciplined way to ask whether our small, noisy glimpses are consistent with the bigger picture, or whether we might just be arguing over trunks, legs, and ears.</em></p>
</section>
<section id="experimental-example" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="experimental-example"><span class="header-section-number">6.1.2</span> Experimental Example</h3>
<ul>
<li><em>Step 1</em>: Begin with a theory.</li>
<li><em>Step 2</em>: Develop a hypothesis derived logically from your theory.</li>
<li><em>Step 3</em>: Design a method to test your hypothesis, including measurements, sample recruitment, and analytical tools.</li>
<li><em>Step 4</em>: Collect data and compare it with your prediction.</li>
</ul>
<p>When Step 4 fails, meaning the data don’t match the prediction, we face a classic scientific dilemma. It is often difficult to determine why things went wrong:</p>
<ul>
<li>Was the theory flawed?</li>
<li>Was the hypothesis poorly specified?</li>
<li>Or were the methods inadequate?</li>
</ul>
<p>This problem is well known in psychology and has been discussed extensively <span class="citation" data-cites="meehl1978">(<a href="#ref-meehl1978" role="doc-biblioref">Meehl 1978</a>)</span>.</p>
<section id="bad-theory-example" class="level4" data-number="6.1.2.1">
<h4 data-number="6.1.2.1" class="anchored" data-anchor-id="bad-theory-example"><span class="header-section-number">6.1.2.1</span> (Bad) Theory Example</h4>
<p>Reinforcing good behavior in children makes them happy because it signals that they have pleased the adults around them. However, rewarding children with something they <em>perceive</em> as a forbidden treat, such as cookies, may have unintended consequences. Children know that cookies are usually off-limits and therefore associate them with rule-breaking. Receiving such a reward may overexcite them, pushing their self-control beyond its limits and leading to hyperactive behavior as they struggle to regulate their impulses.</p>
</section>
<section id="hypothesis" class="level4" data-number="6.1.2.2">
<h4 data-number="6.1.2.2" class="anchored" data-anchor-id="hypothesis"><span class="header-section-number">6.1.2.2</span> Hypothesis</h4>
<p>Based on this theory, we hypothesize that giving children cookies will cause them to lose control of their impulses and become monsters climbing the walls and terrorizing the cat.</p>
<p>To test this hypothesis, we design a simple study in which children are rewarded with chocolate chip cookies and their behavior is observed.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Science Proves Nothing!">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Science Proves Nothing!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Regardless of the study’s outcome, it would not rule out other plausible explanations. For example, one alternative account <em>(and totally wrong argument I think I heard some one say in the supermarket)</em> is that the refined sugar in cookies is rapidly metabolized, producing a temporary spike in blood glucose that leads to increased activity levels.</p>
<p>This is the main difficulty of experimental inference: a single result rarely tells us which explanation is correct. It only tells us which explanations are still plausible. Thus we have theories with evidence for or against. Never Proof! Only in mathematics can you have “proof” and remember math is not science.</p>
</div>
</div>
</section>
</section>
<section id="logic-of-hypothesis-tests" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="logic-of-hypothesis-tests"><span class="header-section-number">6.1.3</span> Logic of Hypothesis Tests</h3>
<p>If X is true, then Y should also be true.</p>
<ul>
<li>We assume X is true.</li>
<li>Therefore, we <em>expect</em> to observe Y.</li>
</ul>
<p>However:</p>
<ul>
<li>If we observe Y, this does not necessarily prove that X is true, because Y could result from other factors.</li>
<li>If we do <em>not</em> observe Y this only <em>suggests</em> that our theory may be flawed or incomplete.</li>
</ul>
<p>So back to our example!</p>
<p><strong>Theory:</strong> Reinforcing good behavior in children with treats leads to increased hyperactivity because children perceive the treat as a forbidden reward, triggering an excited and poorly controlled response</p>
<p><strong>Hypothesis:</strong> Giving children chocolate chip cookies as a reward will result in increased hyperactivity compared to children who do not receive such rewards.</p>
<p><strong>Testing the Hypothesis:</strong> If children who receive cookies show increased hyperactivity (Y is observed), this outcome is consistent with the theory but does not conclusively prove it, since alternative explanations (e.g., sugar content) could also account for the behavior.</p>
<p><em>However,</em> if children <strong>do not</strong> show increased hyperactivity (Y is not observed), this challenges the theory, suggesting it may be incorrect or incomplete. At that point, we must re-examine the theory, the methods, and consider alternative explanations.</p>
<p>In hypothesis testing, <strong>falsification</strong> plays a central role. Supporting evidence increases our confidence in a theory, but evidence that contradicts our predictions undermines it. Scientific progress depends on continuously testing and attempting to falsify our theories, refining them through scrutiny and new evidence.</p>
</section>
<section id="steps-for-hypothesis-testing" class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="steps-for-hypothesis-testing"><span class="header-section-number">6.1.4</span> 4 Steps for Hypothesis Testing</h3>
<ul>
<li>State the hypothesis</li>
<li>Set the Criteria Decision</li>
<li>Collect Data and Compute Sample Statistics</li>
<li>Make a Decision</li>
</ul>
</section>
<section id="the-null-hypothesis-h_0" class="level3" data-number="6.1.5">
<h3 data-number="6.1.5" class="anchored" data-anchor-id="the-null-hypothesis-h_0"><span class="header-section-number">6.1.5</span> The Null Hypothesis (<span class="math inline">\(H_0\)</span>)</h3>
<ul>
<li>The null hypothesis (<span class="math inline">\(H_0\)</span>) asserts that in the general population, there is no change, no difference, or no relationship.
<ul>
<li>In an experiment, <span class="math inline">\(H_0\)</span> predicts that the independent variable (e.g., treatment—cookies) will have no effect on the dependent variable (e.g., hyperactivity) for the population.</li>
</ul></li>
<li><span class="math inline">\(H_0\)</span> is the hypothesis that is subject to a final decision: to either <em>reject</em> or <em>fail to reject</em>.</li>
</ul>
</section>
<section id="the-scientific-or-alternative-hypothesis-h_1" class="level3" data-number="6.1.6">
<h3 data-number="6.1.6" class="anchored" data-anchor-id="the-scientific-or-alternative-hypothesis-h_1"><span class="header-section-number">6.1.6</span> The Scientific or Alternative Hypothesis (<span class="math inline">\(H_1\)</span>)</h3>
<ul>
<li>The alternative hypothesis (<span class="math inline">\(H_1\)</span>) suggests that there is a change or a relationship in the general population.
<ul>
<li>In an experiment, <span class="math inline">\(H_1\)</span> predicts that the independent variable (e.g., treatment—cookies) will influence the dependent variable (e.g., hyperactivity) for the population.</li>
</ul></li>
<li>We are not actually directly testing <span class="math inline">\(H_1\)</span> which is why we either <em>reject</em> or <em>fail to reject</em> <span class="math inline">\(H_0\)</span>.</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled" title="Accepting the Null or Proving the Alternative?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Accepting the Null or Proving the Alternative?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why do we use that bizarre lingo: reject or fail to reject the null? Is it cause statisticians have the personalities of androids? Well, partially. Why can’t we say <em>accept null</em> or <em>accept/prove the alternative</em>, or just say in plain English, “Yo dude, this study shows we got nothing!”</p>
<p>To explain, let’s use those very scientifically informed ghost hunting TV shows which are so much fun to watch <em>(don’t judge me)</em>. Two hosts creep around an old house. The EMF meter spikes, one of them feels a cold spot, and they decide the place is haunted by Ronald Fisher, the statistician who invented ANOVA, who presumably cannot rest because people keep trashing his equations. Then the spirit box, which scans radio stations at random, coughs up …static… “Analysis”…static…“Variance”…static… They run out convinced.</p>
<p>What is wrong with our hosts? Damaged pre-frontal cortex? No, they are just normal people making normal people errors of logic. First, humans want a <em>cause</em> for what they just experienced (see probability chapter). Second, it is impossible to prove that nothing is there. You cannot see a ghost or touch one, so the disproof never arrives, and the EMF meter, the cold spot, and the spirit box all get promoted to evidence. There were 1001 other explanations available: wires in the wall, a draft in an old house, a psychosomatic chill, and pareidolia, which is humans finding patterns out of randomness. But they theorized Fisher, they heard Fisher’s favorite words, so it must be Fisher. They <strong>accepted the alternative</strong>.</p>
<p>Now have I proven there are no ghosts? Absolutely not! There could indeed be ghosts. Seriously, not a joke. No scientist can ever prove there are no ghosts. We cannot prove anything. If a scientist says they can, they are liars who forgot the basis of the scientific method. Remember, we can only provide evidence toward our theory.</p>
</div>
</div>
</section>
<section id="directional-hypothesis" class="level3" data-number="6.1.7">
<h3 data-number="6.1.7" class="anchored" data-anchor-id="directional-hypothesis"><span class="header-section-number">6.1.7</span> Directional Hypothesis</h3>
<ul>
<li><strong><span class="math inline">\(H_0\)</span></strong>: Chocolate chip cookies do not make children hyper.</li>
<li><strong><span class="math inline">\(H_1\)</span></strong>: Chocolate chip cookies do make children hyper.</li>
</ul>
<p>Written symbolically, where <span class="math inline">\(\mu\)</span> is the population mean hyperactivity score and 50 is the value we expect without cookies:</p>
<ul>
<li><span class="math inline">\(H_0: \mu \le 50\)</span></li>
<li><span class="math inline">\(H_1: \mu &gt; 50\)</span></li>
</ul>
</section>
<section id="non-directional-hypothesis" class="level3" data-number="6.1.8">
<h3 data-number="6.1.8" class="anchored" data-anchor-id="non-directional-hypothesis"><span class="header-section-number">6.1.8</span> Non-directional Hypothesis</h3>
<ul>
<li><strong><span class="math inline">\(H_0\)</span></strong>: Chocolate chip cookies do not change children’s level of hyperactivity.</li>
<li><strong><span class="math inline">\(H_1\)</span></strong>: Chocolate chip cookies do change children’s level of hyperactivity.</li>
</ul>
<p>Written symbolically:</p>
<ul>
<li><span class="math inline">\(H_0: \mu = 50\)</span></li>
<li><span class="math inline">\(H_1: \mu \neq 50\)</span></li>
</ul>
<p><em>Note: The default in psychology is to choose the non-directional test, for reasons we need to come back to later, so we will only talk about that version for the rest of below.</em></p>
</section>
<section id="set-the-decision-criteria" class="level3" data-number="6.1.9">
<h3 data-number="6.1.9" class="anchored" data-anchor-id="set-the-decision-criteria"><span class="header-section-number">6.1.9</span> Set the Decision Criteria</h3>
<ul>
<li>The decision criteria depend on the type of test, the number of tests conducted, the sample size you have, and whether the hypothesis is directional or non-directional.</li>
<li>A key decision is determining how far sample means need to be from the population mean to reject the null hypothesis (<span class="math inline">\(H_0\)</span>).</li>
<li>The challenge is identifying what constitutes <em>abnormal</em> behavior in the population.</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled" title="Abnormal Is Not a Moral Judgment">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Abnormal Is Not a Moral Judgment
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Abnormal” is a technical term used by statisticians to describe when a score occurs outside of the “norm”. Go back to the distribution chapter to find out what the technical term <em>normal</em> means.</p>
<p>Typical rule is anything outside of 2 SD (for a person) or 2 SE for sample mean is often described as “abnormal”, meaning a score that would occur outside of the 95% range that most of the people or sample means tend to fall in by chance.</p>
</div>
</div>
<p>Before I show you with a picture what I mean, I need to explain another small problem. Can I assume in small samples that the mean I get will be accurate? We already know the answer from the standard error chapter, no. I know in small samples I can be very uncertain about the mean. But also, I will be uncertain about its variance (spread). <em>Think about this example:</em></p>
<blockquote class="blockquote">
<p>You collect 10 people in Giordano’s eating deep dish pizza. By chance 9 of the 10 people are from Chicago, love deep dish and give high scores, 8 to 9.5 out of 10 with an average around 9 of 10. But that last person is a tourist from New York City. They rate it 0 out of 10 and ask if they can actually give it a -1000 out of 10. <em>In fact, my visiting college friend from NYC, who is a Medical Doctor, told the waitress that pizza was not only an affront to pizza but a serious health hazard and suggested they close their doors and save people’s taste buds and arteries.</em></p>
</blockquote>
<p>What happens to the mean with that rating of 0 out of 10? Let’s take a look at the scores with the tourist and without:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">242</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Chicagoan <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">9</span>, <span class="at">mean =</span> <span class="dv">9</span>, <span class="at">sd =</span> .<span class="dv">5</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>NewYorker <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Full.Data <span class="ot">&lt;-</span> <span class="fu">c</span>(Chicagoan, NewYorker)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_06_One_Sample_t_files/figure-html/pizza-histogram-1.png" class="img-fluid figure-img" alt="Histogram of ten pizza ratings on a 0 to 10 scale. Nine grey bars cluster between 8 and 9.6, and a single red bar sits alone at 0, far to the left of everyone else." width="432"></p>
<figcaption>Ten pizza ratings at Giordano’s. Nine Chicagoans, and one visitor in red.</figcaption>
</figure>
</div>
</div>
</div>
<p>The mean with just Chicagoan is 9.03 and if you add my friend, 8.12. So it drops</p>
<p>But look what happens to the SD:</p>
<p>The SD with just Chicagoan is 0.49 and if you add my friend, 2.89.</p>
<p>Well that is very different.</p>
<p>Recall our estimate of the standard error of the mean is estimated as follows: <span class="math inline">\(S_M = \frac{S}{\sqrt{N}}\)</span></p>
<p>SO with all 10 people, the <span class="math inline">\(S_M\)</span> = 0.91</p>
<p>If that one tourist had never walked in and only the 9 Chicagoans were measured, we would have found a very different and much <em>smaller</em> standard error, <span class="math inline">\(S_M\)</span> = 0.16</p>
<p>We are back to which is right? Take for example now you want to compare how people rate Giordano’s to the national average for pizza, which is 7.5 out of 10. In the case of only sampling Chicagoans you would ask: is Chicago pizza “better” (i.e., abnormal) than the average American pizza? Here is the same question asked twice, once with each standard error.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_06_One_Sample_t_files/figure-html/pizza-two-se-1.png" class="img-fluid figure-img" alt="Two stacked bell curves, both centered on 7.5. The top curve, built from only the nine Chicagoans, is tall and narrow, and a red line at 9.03 falls far outside its shaded abnormal region. The bottom curve, built from all ten raters, is short and wide, and a red line at 8.12 falls comfortably inside it." width="624"></p>
<figcaption>The same question asked twice. Both curves are centered on the national average of 7.5; only the standard error differs. The red line is what Giordano’s actually scored.</figcaption>
</figure>
</div>
</div>
</div>
<p>As we can see, in one case Chicago pizza is in the abnormal range, outside of 95% of our estimates of the average American pizza score. In the other case, that one New Yorker makes Chicago pizza seem average. We are back to which is true?</p>
<p>Well, this problem was solved in 1908 to test Guinness Beer!</p>
</section>
<section id="accounting-for-sample-size-the-transition-to-the-t-distribution" class="level3" data-number="6.1.10">
<h3 data-number="6.1.10" class="anchored" data-anchor-id="accounting-for-sample-size-the-transition-to-the-t-distribution"><span class="header-section-number">6.1.10</span> Accounting for Sample Size: The Transition to the <span class="math inline">\(t\)</span>-Distribution</h3>
<p>We also have to account for the sample size of our study, since in small samples, we know we will not get the best estimate of the population numbers (as we saw above). So, we apply a correction by moving from the standard true Normal (<span class="math inline">\(z\)</span>) distribution to the Student’s <span class="math inline">\(t\)</span>-distribution.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Student's t-Test Was Created Because of Beer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Student’s t-Test Was Created Because of Beer
</div>
</div>
<div class="callout-body-container callout-body">
<p>The word <em>Student</em> does not refer to an undergraduate who invented a test between classes. It was the pen name of William Sealy Gosset, a chemist and brewer at Guinness. Guinness used small samples to study ingredients and production, and company policy restricted employees from publishing their work. Gosset therefore published <em>The Probable Error of a Mean</em> as “Student” in 1908 cause he was not allowed to release trade secrets <span class="citation" data-cites="student1908 lehmann1999student">(<a href="#ref-student1908" role="doc-biblioref">Student 1908</a>; <a href="#ref-lehmann1999student" role="doc-biblioref">Lehmann 1999</a>)</span>.</p>
<p>In other words, one of the most famous tools in statistics exists because a brewer wanted to make better beer without pretending a tiny sample was a giant one. Statistics has rarely produced a more convincing origin story.</p>
</div>
</div>
</section>
<section id="why-the-t-distribution" class="level3" data-number="6.1.11">
<h3 data-number="6.1.11" class="anchored" data-anchor-id="why-the-t-distribution"><span class="header-section-number">6.1.11</span> Why the <span class="math inline">\(t\)</span>-Distribution?</h3>
<p>We will never know the population standard deviation (<span class="math inline">\(\sigma\)</span>), so we must estimate it using the sample standard deviation (<span class="math inline">\(S\)</span>). We know that small samples are more prone to extreme fluctuations (as you saw). Because our estimate of the population variance is less reliable when <span class="math inline">\(n\)</span> is small, the <span class="math inline">\(t\)</span>-distribution is “heavier” in the tails than the normal distribution. So the shape of the <span class="math inline">\(t\)</span>-distribution is determined by the degrees of freedom, calculated as <span class="math inline">\(df = n - 1\)</span>. As <span class="math inline">\(n\)</span> (and thus <span class="math inline">\(df\)</span>) increases, the <span class="math inline">\(t\)</span>-distribution approaches the shape of the standard normal distribution. As <span class="math inline">\(n\)</span> decreases, the tails become “fatter”, so the range holding 95% of the distribution is now much wider than 2 standard errors (actually it’s 1.96, but who needs to be exact!).</p>
</section>
<section id="adjusting-the-critical-region-the-regions-we-call-abnormalweird" class="level3" data-number="6.1.12">
<h3 data-number="6.1.12" class="anchored" data-anchor-id="adjusting-the-critical-region-the-regions-we-call-abnormalweird"><span class="header-section-number">6.1.12</span> Adjusting the Critical Region (the regions we call abnormal/weird)</h3>
<p>Because the <span class="math inline">\(t\)</span>-distribution has more area in its tails, the “cut-off” points (called alpha (<span class="math inline">\(\alpha\)</span>) level) move further away from the mean. This means:</p>
<ul>
<li>It is harder to reject the null hypothesis with a small sample.</li>
<li>We are being conservative to account for the increased risk of error when we don’t have a large amount of data.</li>
</ul>
<p>The <span class="math inline">\(t\)</span>-distribution acts as a “safety buffer.” It ensures that we only label a result as “statistically significant” if the effect is strong enough to overcome the inherent noise of a small sample size.</p>
</section>
<section id="determining-the-cut-off-points-for-two-tailed-tests" class="level3" data-number="6.1.13">
<h3 data-number="6.1.13" class="anchored" data-anchor-id="determining-the-cut-off-points-for-two-tailed-tests"><span class="header-section-number">6.1.13</span> Determining the Cut-Off Points for Two-Tailed Tests</h3>
<p>For a two-tailed test with <span class="math inline">\(\alpha = 0.05\)</span> (i.e., 1 - .05 = .95, or 95% of the population), the cut-offs depend on sample size. For our study with 10 people that would look like this:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_06_One_Sample_t_files/figure-html/t-critical-regions-1.png" class="img-fluid figure-img" alt="A symmetric bell-shaped t-distribution curve centered on zero. The two tails beyond about negative and positive two are shaded red, and dashed vertical lines mark those cut-offs." width="432"></p>
<figcaption>The t-distribution for df = 9 (n = 10). The shaded red areas represent the critical regions where we reject the null hypothesis.</figcaption>
</figure>
</div>
</div>
</div>
<p>Our cut-off (<span class="math inline">\(t_{critical}\)</span>) values for <span class="math inline">\(df = 9\)</span> would be:</p>
<ul>
<li><span class="math inline">\(t_{lower}\)</span> &lt; -2.262</li>
<li><span class="math inline">\(t_{upper}\)</span> &gt; 2.262</li>
</ul>
</section>
<section id="the-impact-of-sample-size-on-critical-regions" class="level3" data-number="6.1.14">
<h3 data-number="6.1.14" class="anchored" data-anchor-id="the-impact-of-sample-size-on-critical-regions"><span class="header-section-number">6.1.14</span> The Impact of Sample Size on Critical Regions</h3>
<p>If we were to increase our sample size from <span class="math inline">\(n = 10\)</span> to <span class="math inline">\(n = 100\)</span>, our degrees of freedom would increase to <span class="math inline">\(df = 99\)</span>.</p>
<p>As <span class="math inline">\(n\)</span> increases, our confidence in our estimate of the population standard deviation also increases. Mathematically, the <span class="math inline">\(t\)</span>-distribution begins to pull its “fat tails” inward, looking more and more like the standard Normal (<span class="math inline">\(z\)</span>) distribution.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_06_One_Sample_t_files/figure-html/t-dist-sample-size-1.png" class="img-fluid figure-img" alt="Two overlapping bell-shaped curves centered on zero. The red curve for 10 people has slightly fatter tails than the blue curve for 100 people, and dotted vertical lines show the blue cut-offs sitting just inside the red ones." width="432"></p>
<figcaption>Two t-distributions overlaid. The larger sample has thinner tails, so its cut-offs sit closer to the middle.</figcaption>
</figure>
</div>
</div>
</div>
<p>New Cut-Off (<span class="math inline">\(t_{critical}\)</span>) Points (<span class="math inline">\(n = 100\)</span>):</p>
<ul>
<li><span class="math inline">\(t_{lower}\)</span> &lt; -1.984</li>
<li><span class="math inline">\(t_{upper}\)</span> &gt; 1.984</li>
</ul>
<p>Why the boundaries are smaller: with 100 people instead of 10, our sample mean is a much more reliable “anchor” for the population mean. We don’t need as much of a “safety buffer.”</p>
<p>Here is how the boundaries shift with different sample sizes:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>How Sample Size Changes the Threshold for Significance</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Sample Size (n)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Degrees of Freedom (df)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Absolute Critical Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">9</td>
<td style="text-align: right;">2.262</td>
</tr>
<tr class="even">
<td style="text-align: left;">100</td>
<td style="text-align: left;">99</td>
<td style="text-align: right;">1.984</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Infinity (z)</td>
<td style="text-align: left;">Inf-1</td>
<td style="text-align: right;">1.960</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="collect-data-and-compute-sample-statistics" class="level3" data-number="6.1.15">
<h3 data-number="6.1.15" class="anchored" data-anchor-id="collect-data-and-compute-sample-statistics"><span class="header-section-number">6.1.15</span> Collect Data and Compute Sample Statistics</h3>
<p>Back to our study on the kids. Remember we wanted to feed them cookies to test our theory that giving them a forbidden treat will make them hyperactive? To test this, we get a sample of children, <span class="math inline">\(n = 10\)</span>, and feed them a bunch of cookies! We collected that data and in R stored their hyperactivity scores in an object called <code>kids.1</code></p>
<p><strong>Dependent Variable (DV):</strong> We will measure the children’s hyperactivity, which we expect the cookies to raise.</p>
<p>Here is a plot of kids.1:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fl">1e6</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Population <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>kids.sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(Population, n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># every kid gets a 2-point cookie boost (the true effect)</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>kids<span class="fl">.1</span> <span class="ot">&lt;-</span> kids.sample <span class="sc">+</span> <span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_06_One_Sample_t_files/figure-html/kids-histogram-1.png" class="img-fluid figure-img" alt="Histogram of 10 hyperactivity scores, centered in the low fifties, with values spanning from about 46 to about 59." width="432"></p>
<figcaption>Hyperactivity scores for our 10 cookie-fed children.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sample-results" class="level3" data-number="6.1.16">
<h3 data-number="6.1.16" class="anchored" data-anchor-id="sample-results"><span class="header-section-number">6.1.16</span> Sample Results</h3>
<p>The children who received cookies showed a mean of <span class="math inline">\(M = 53.049\)</span> with a standard deviation of <span class="math inline">\(SD = 3.995\)</span>. Based on prior theory and past research, we hypothesize that the population mean is <span class="math inline">\(\mu = 50\)</span></p>
<p>We can then ask whether the data we observed are consistent with that claim, or whether the difference between the sample mean and the hypothesized population mean is larger than we would expect from random sampling error alone.</p>
</section>
<section id="compute-sample-statistics" class="level3" data-number="6.1.17">
<h3 data-number="6.1.17" class="anchored" data-anchor-id="compute-sample-statistics"><span class="header-section-number">6.1.17</span> Compute Sample Statistics</h3>
<p>The test statistic is computed using the following formula:</p>
<p><span class="math display">\[
t_{test} = \frac{M - \mu}{S_M}
\]</span></p>
<p>where the denominator is the standard error of the mean:</p>
<p><span class="math display">\[
S_M = \frac{s}{\sqrt{n}}
\]</span></p>
<p>We can do the math by hand, or use the <em>t</em>-test function in R. <em>t</em>-test by hand:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">=</span> <span class="fu">mean</span>(kids<span class="fl">.1</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">=</span> <span class="fu">sd</span>(kids<span class="fl">.1</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>Mu <span class="ot">=</span> <span class="dv">50</span> <span class="co"># given to you from the population</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>t.kids <span class="ot">&lt;-</span> (M <span class="sc">-</span> Mu) <span class="sc">/</span> (s<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>t.kids</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.413795</code></pre>
</div>
</div>
<p>one sample <em>t</em>-test in R:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Kids.t.test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(<span class="at">x =</span> kids<span class="fl">.1</span>, <span class="co">#we put the vector of scores in</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="co">#the abnormal value can be on the left or right side</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">mu =</span> <span class="dv">50</span>, <span class="co">#hypothesized population mean</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">conf.level =</span> <span class="fl">0.95</span>)  <span class="co"># .95 is the default; shown here so you can see it</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>Kids.t.test</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  kids.1
t = 2.4138, df = 9, p-value = 0.03901
alternative hypothesis: true mean is not equal to 50
95 percent confidence interval:
 50.19156 55.90708
sample estimates:
mean of x 
 53.04932 </code></pre>
</div>
</div>
</section>
<section id="reading-what-r-just-handed-you" class="level3" data-number="6.1.18">
<h3 data-number="6.1.18" class="anchored" data-anchor-id="reading-what-r-just-handed-you"><span class="header-section-number">6.1.18</span> Reading What R Just Handed You</h3>
<p>That is the first real block of R output in this book, and it is a wall. Here is every line of it, in order, in English.</p>
<pre><code>    One Sample t-test          &lt;- which test R decided to run

data:  kids.1                  &lt;- the object you handed it

t = 2.4138, df = 9,            &lt;- the test statistic and its degrees of freedom
p-value = 0.03901              &lt;- the p-value, exact, not rounded to stars

alternative hypothesis: true mean is not equal to 50
                               &lt;- your H1, in words. R is repeating your
                                  mu = 50 and your "two.sided" back to you

95 percent confidence interval:
 50.19156 55.90708             &lt;- the interval around the SAMPLE mean

sample estimates:
mean of x
 53.04932                      &lt;- the mean of your data</code></pre>
<p>Five things worth noticing, because these are the five things students get wrong:</p>
<ol type="1">
<li><strong><code>t = 2.4138</code> is the number you just computed by hand.</strong> Scroll up. It matches. R did not do anything mysterious, it did the same division faster.</li>
<li><strong><code>df = 9</code>, not 10.</strong> Degrees of freedom are <span class="math inline">\(n - 1\)</span>. You have ten children and nine degrees of freedom, and this is the number you take to the t-table, not your sample size.</li>
<li><strong>The <code>alternative hypothesis</code> line is R repeating your own instructions back to you.</strong> It says “not equal to 50” because you typed <code>mu = 50</code> and <code>alternative = "two.sided"</code>. If that line does not describe the test you meant to run, you typed the wrong thing, and this is the line that tells you so. Read it every single time.</li>
<li><strong>The confidence interval is around your sample mean, not around 50.</strong> It runs from 50.19 to 55.91, and the interesting thing is what it does <em>not</em> contain: 50, our hypothesized value, sits just outside the bottom end. That is the same conclusion as the <em>p</em>-value, arriving by a different road.</li>
<li><strong><code>sample estimates: mean of x</code> is just the mean of your data.</strong> R labels it <code>x</code> because that is the argument name you filled in. It is not a new quantity, it is <code>mean(kids.1)</code>.</li>
</ol>
<p>What R does <em>not</em> give you: an effect size. There is no <span class="math inline">\(d\)</span> anywhere in that output. That absence is the whole reason for the next chapter.</p>
</section>
<section id="test-statistic-result" class="level3" data-number="6.1.19">
<h3 data-number="6.1.19" class="anchored" data-anchor-id="test-statistic-result"><span class="header-section-number">6.1.19</span> Test Statistic Result</h3>
<p>We get a <span class="math inline">\(t_{test} =\)</span> 2.414. Now, the question is: <strong>does this value fall in the tail of the population distribution</strong>?</p>
<p>Let’s check our critical value.</p>
<p>Our <span class="math inline">\(t_{critical}\)</span> values for <span class="math inline">\(df = 9\)</span> would be:</p>
<ul>
<li><span class="math inline">\(t_{lower}\)</span> &lt; -2.262</li>
<li><span class="math inline">\(t_{upper}\)</span> &gt; 2.262</li>
</ul>
<p>This <em>t</em>-test value is greater than our upper value.</p>
<p>Further from the R <em>t</em>-test function, we can see our exact <em>p</em>-value which is below <span class="math inline">\(p &lt; .05\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled" title="The p-Value, Actually Defined (That IOU from Chapter 1)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The p-Value, Actually Defined (That IOU from Chapter 1)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Back in Chapter 1 I promised you a real definition of statistical significance once you had some probability theory. Here it is, at the first moment you actually need it.</p>
<p><strong>The <em>p</em>-value is the probability of getting a test statistic at least this far from the null value, <em>if</em> the null hypothesis and the model’s assumptions were true.</strong></p>
<p>Look back at the shaded red tails in the figure above. Your observed <span class="math inline">\(t\)</span> lands somewhere on that curve, and the <em>p</em>-value is the area past it in both directions. Small p means your data sit far out in a region the null model rarely produces.</p>
<p>Note what the definition does not say. It is a statement about the data given an assumption, not a statement about the assumption given the data. It is not the probability that the null hypothesis is true, not the probability that you are wrong, and not the probability that the result will replicate.</p>
</div>
</div>
<p>We can also see the 95 percent confidence interval from our R <em>t</em>-test function, and that range does NOT include <span class="math inline">\(\mu = 50\)</span>, which is another way of seeing that our result is bigger than chance alone would produce.</p>
</section>
<section id="make-a-decision" class="level3" data-number="6.1.20">
<h3 data-number="6.1.20" class="anchored" data-anchor-id="make-a-decision"><span class="header-section-number">6.1.20</span> Make a Decision</h3>
<p>There are two possible outcomes:</p>
<ul>
<li><strong>Reject the null hypothesis:</strong> This decision is reached when the data fall within the critical region.
<ul>
<li>This indicates the sample mean is farther from the hypothesized value than random sampling error can comfortably explain. Whether the <em>cookies</em> did it is a design question, not a statistics question. See the Important Note above.</li>
<li><strong>We reject the null</strong> because it is generally easier to demonstrate that something is false than to prove it true. (For the other way of weighing evidence, see the Bayes section of the <a href="./Ch_03_Probability.html">Probability chapter</a>.)</li>
</ul></li>
<li><strong>Fail to reject the null hypothesis:</strong> If the data do not provide strong evidence (i.e., they do not fall within the critical region), then the treatment is <em>assumed</em> to have no effect.</li>
</ul>
</section>
<section id="decision-outcome" class="level3" data-number="6.1.21">
<h3 data-number="6.1.21" class="anchored" data-anchor-id="decision-outcome"><span class="header-section-number">6.1.21</span> Decision Outcome</h3>
<p><strong>YES, our <span class="math inline">\(t_{test}\)</span> &gt; <span class="math inline">\(t_{critical}\)</span>, so we REJECT the null hypothesis.</strong></p>
<ul>
<li>We report: <span class="math inline">\(t_{test}\)</span> = 2.414, <span class="math inline">\(p =\)</span> 0.039 (since we know the exact <em>p</em>-value).</li>
<li>In modern APA format, it is recommended to report the exact <em>p</em>-value.</li>
</ul>
</section>
<section id="one-sample-t-test-in-apa-format" class="level3" data-number="6.1.22">
<h3 data-number="6.1.22" class="anchored" data-anchor-id="one-sample-t-test-in-apa-format"><span class="header-section-number">6.1.22</span> One-sample <em>t</em>-test in APA format</h3>
<p>Written the way it would appear in a paper, our result looks like this:</p>
<blockquote class="blockquote">
<p><span class="math inline">\(t(9) =\)</span> 2.41, <span class="math inline">\(p\)</span> = 0.039, 95% CI [50.19, 55.91], <span class="math inline">\(d =\)</span> 0.76</p>
</blockquote>
<p>Wait, what is the <span class="math inline">\(d\)</span> thing at the end? The problem with significance testing is it does not tell you how “big” the effect is. It just tells you the result is probably not due to chance.</p>
<div class="callout callout-style-default callout-note callout-titled" title="The d Is a Cliffhanger, and the Next Chapter Is the Payoff">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The d Is a Cliffhanger, and the Next Chapter Is the Payoff
</div>
</div>
<div class="callout-body-container callout-body">
<p>That <span class="math inline">\(d\)</span> is <strong>Cohen’s d</strong>, an <em>effect size</em>. All you need for now is the one-sentence version: it reports how far apart things are in standard deviation units, so a <span class="math inline">\(d\)</span> of 0.76 means our cookie-fed children sit about that many standard deviations above the value we tested against.</p>
<p>Report it beside your <em>p</em>-value, every time. A <em>p</em>-value tells the reader that <em>something</em> is there. Only the effect size tells them whether it is worth crossing the room for.</p>
<p>Where it comes from, why radar operators invented it, what counts as small or large, and what it costs you to detect one, all of that is the <a href="./Ch_07_Power_Effect_Size.html">next chapter</a>. It is the reason the next chapter exists.</p>
</div>
</div>
</section>
</section>
<section id="apa-style-report" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="apa-style-report"><span class="header-section-number">6.2</span> APA Style Report</h2>
<p>Children who received cookies showed higher hyperactivity scores (<span class="math inline">\(M =\)</span> 53.05, <span class="math inline">\(SD =\)</span> 3.99) than the hypothesized population value (<span class="math inline">\(\mu = 50\)</span>), <span class="math inline">\(t(9) =\)</span> 2.41, <span class="math inline">\(p\)</span> = 0.039, 95% CI [50.19, 55.91], <span class="math inline">\(d =\)</span> 0.76. The standardized difference describes magnitude; whether the effect is practically meaningful requires context and better evidence than our imaginary cookie operation.</p>
</section>
<section id="uncertainty-and-error-in-hypothesis-testing" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="uncertainty-and-error-in-hypothesis-testing"><span class="header-section-number">6.3</span> Uncertainty and Error in Hypothesis Testing</h2>
<p>Hypothesis testing is an inferential process because we do <strong>not</strong> know the actual population data, and our samples could be in error. When we infer, we can make at least two types of errors (though there are others).</p>
<section id="type-i-error" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="type-i-error"><span class="header-section-number">6.3.1</span> Type I Error</h3>
<p>Type I Error, also called a “false alarm” or “alpha error” occurs when a researcher rejects a null hypothesis that is actually <strong>true</strong>. In other words, we reject the null even though the treatment does <strong>nothing</strong>. Before observing the data, the <span class="math inline">\(\alpha\)</span> level sets the long-run Type I error rate for the testing procedure when the null hypothesis and its assumptions hold. Choosing <span class="math inline">\(\alpha=.05\)</span> does not mean there is a 5% probability that this particular rejected null hypothesis is true. The <em>p</em>-value cannot read the hidden state of the universe.</p>
<p><strong>Example:</strong> Testing zinc or ColdEase on colds using self-report as a measure of improvement. Colds get better on their own, and people who paid for zinc lozenges want to believe they helped. So the study can happily “detect” an improvement that is really just the cold ending on schedule plus some hopeful self-report. The null was true and we rejected it anyway.</p>
</section>
<section id="type-ii-error" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="type-ii-error"><span class="header-section-number">6.3.2</span> Type II Error</h3>
<p>Type II Error, also called a “miss” or “beta error”occurs when a researcher fails to reject the null hypothesis that is actually <strong>false</strong>. In other words, a Type II error occurs when the treatment has an effect, but it seems like the treatment has had no effect because the hypothesis test fails to detect it. This can occur when the treatment has an effect but the study has too little power to detect it (i.e., too few parcipants to see the effect given how much noise/chance you have at getting a sample mean and SD from the sample). That happens when the effect size is small, the measurement is noisy, or the sample is small.</p>
<ul>
<li><strong>Example:</strong> Taking kava tea to reduce stress. Kava may genuinely calm people down a little. But give it to ten stressed undergraduates, measure them with a mood scale they fill out between classes, and the effect is too quiet to hear over the noise. The null was false and we failed to reject it.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="The Courtroom Version, Which Your TA Will Use">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The Courtroom Version, Which Your TA Will Use
</div>
</div>
<div class="callout-body-container callout-body">
<p>A defendant is presumed innocent, which is the null hypothesis. The jury either convicts or fails to convict.</p>
<ul>
<li><strong>Type I error:</strong> convicting an innocent person. You rejected a true null.</li>
<li><strong>Type II error:</strong> acquitting a guilty person. You failed to reject a false null.</li>
</ul>
<p>Notice that “not guilty” is not the same verdict as “innocent.” The jury is saying the evidence was not strong enough, which is exactly what “fail to reject” means. This is also why raising the standard of proof trades one error for the other. Make conviction harder and fewer innocent people go to prison, while more guilty ones walk.</p>
<p>You met the extreme version of this in the <a href="./Ch_03_Probability.html">Probability chapter</a>, where we fired the doctors and let a 95% accurate test convict people Judge Dredd style. It got 84% of them wrong.</p>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 39%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Your decision</th>
<th>Treatment does not work (<span class="math inline">\(H_0\)</span>=TRUE)</th>
<th>Treatment does work (<span class="math inline">\(H_0\)</span>=FALSE)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reject <span class="math inline">\(H_0\)</span></td>
<td>Type 1</td>
<td>Correct Decision</td>
</tr>
<tr class="even">
<td>Fail to reject <span class="math inline">\(H_0\)</span></td>
<td>Correct Decision</td>
<td>Type II</td>
</tr>
</tbody>
</table>
</section>
<section id="the-short-story" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="the-short-story"><span class="header-section-number">6.3.3</span> The Short Story</h3>
<ul>
<li>A one-sample <em>t</em>-test compares a sample mean with a hypothesized population value.</li>
<li>The t statistic is the observed difference divided by its standard error.</li>
<li>A <em>p</em>-value measures compatibility with the null model; it is not the probability that the null is true.</li>
<li>“Fail to reject” does not mean “prove no effect.” Sometimes the study simply arrived carrying a tiny sample and no flashlight.</li>
<li>Report the estimate, confidence interval, <em>p</em>-value, and effect size. The asterisk cannot do all the talking.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="The t Statistic Is Signal Divided by Noise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The t Statistic Is Signal Divided by Noise
</div>
</div>
<div class="callout-body-container callout-body">
<p>The numerator is how far the sample mean sits from the null value. The denominator is the standard error of that mean. A large t statistic can come from a large difference, a precise estimate, or both, so report the effect and its uncertainty, not merely the ceremonial <em>p</em>-value.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="What Comes Next?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What Comes Next?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Straight ahead</strong> is the <a href="./Ch_07_Power_Effect_Size.html">power and effect size chapter</a>, and it is not optional scenery. It explains the <span class="math inline">\(d\)</span> we just dangled in front of you, it covers Type I and Type II error, and it answers the only question anyone actually asks before running a study: how many people do I need? Read it before the other two <em>t</em>-tests, because both of them assume it.</p>
<p>After that, the remaining two <em>t</em>-tests are variations on what you already know.</p>
<p>Use the one-sample <em>t</em>-test when one group is being compared with one number. If you want to ask whether <strong>Group A differs from Group B</strong>, continue to the <a href="./Ch_08_Independent_t.html">independent-samples <em>t</em>-test chapter</a>. For example, you might compare the running speed of one group of undergraduates chased by a goose with a completely different group chased by two geese. The ethics board will compare your application with a paper shredder.</p>
<p>If you measure the <strong>same people twice</strong>, continue to the <a href="./Ch_09_Paired_t.html">paired-samples <em>t</em>-test chapter</a>. For example, you might measure the same students’ stress before and after telling them that the group presentation they forgot about has been moved to today. Same humans, two measurements, one sudden desire to transfer universities.</p>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-lehmann1999student" class="csl-entry" role="listitem">
Lehmann, E. L. 1999. <span>“<span><span>‘Student’</span></span> and Small-Sample Theory.”</span> <em>Electronic Journal of Probability</em> 4 (11): 1–33.
</div>
<div id="ref-meehl1978" class="csl-entry" role="listitem">
Meehl, Paul E. 1978. <span>“Theoretical Risks and Tabular Asterisks: Sir Karl, Sir Ronald, and the Slow Progress of Soft Psychology.”</span> <em>Journal of Consulting and Clinical Psychology</em> 46 (4): 806–34. <a href="https://doi.org/10.1037/0022-006X.46.4.806">https://doi.org/10.1037/0022-006X.46.4.806</a>.
</div>
<div id="ref-student1908" class="csl-entry" role="listitem">
Student. 1908. <span>“The Probable Error of a Mean.”</span> <em>Biometrika</em> 6 (1): 1–25. <a href="https://doi.org/10.1093/biomet/6.1.1">https://doi.org/10.1093/biomet/6.1.1</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/apd217\.github\.io\/Textbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Ch_05_Standard_Error.html" class="pagination-link" aria-label="Standard Error">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Standard Error</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ch_07_Power_Effect_Size.html" class="pagination-link" aria-label="Power and Effect Size">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Power and Effect Size</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Alexander P. Demos. Licensed <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/apd217/Textbook/blob/main/Ch_06_One_Sample_t.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/apd217/Textbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>