<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An accessible, example-driven introduction to psychological statistics and R.">

<title>8&nbsp; Independent Samples t-Test – Psychological Statistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ch_09_Paired_t.html" rel="next">
<link href="./Ch_07_Power_Effect_Size.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6aaad9ee1f70880fa5715553a7f5f012.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_01_Introduction.html">The Necessary Slog</a></li><li class="breadcrumb-item"><a href="./Ch_08_Independent_t.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independent Samples t-Test</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Psychological Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/apd217/Textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Psychological_Statistics_with_R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">The Necessary Slog</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_01_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why You Have to Learn Statistics (Sorry not sorry)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_02_R_Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R: The Extremely Short Survival Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_03_Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability: The Gods Are Fickle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_04_Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions and their Moments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_05_Standard_Error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Standard Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_06_One_Sample_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Sample t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_07_Power_Effect_Size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Power and Effect Size</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_08_Independent_t.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independent Samples t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_09_Paired_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Paired-Samples t-Test</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Putting Lines Through Things</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_10_Covariance_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Covariance and Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_11_Intro_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_12_Categorical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Regression with Categorical Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_13_Multiple_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Multiple Regression: Statistical Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_14_Hierarchical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hierarchical Regression: Testing Whether Your Model Improves</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_15_Statistical_Control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Statistical Control: What Are We Actually Removing?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_16_Continuous_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_17_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Categorical-by-Categorical Interactions: The 2-by-2 Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_18_Mixed_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mixed Regression: Between People and Within People</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Okay, But What If It’s Complicated?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_19_Regression_Diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Advanced: Regression Diagnostics and Influential Weirdos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_20_Multiple_Comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">P-Values and Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_21_Advanced_Interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Advanced: Continuous and Higher-Order Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_22_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_23_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Mediation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_24_Moderated_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Moderated Mediation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">ANOVA is dead, Long Live ANOVA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_25_ANOVA_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Historical ANOVA Lectures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_26_One_Way_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Introduction to Analysis of Variance (ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_27_One_Way_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Follow-Ups to One-Way ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_28_Two_Way_Between_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Calculating the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_29_Two_Way_Between_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Following Up the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_30_One_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">From the Paired <em>t</em>-Test to the One-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_31_Two_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Two-Way Within-Subjects ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_32_Two_Way_Within_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Follow-Ups to the Two-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_33_Mixed_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Two-Way Mixed-Design ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Other Statistical Creatures</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_34_Chi_Square.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Pearson’s Chi-Square</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_35_Nonparametric_Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Nonparametric Tests: When the Data Refuse to Behave</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_36_Bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Advanced: Bootstrapping, the Jackknife, and Resampling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">When R Inevitably Betrays You</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_37_Reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Reporting Models Without Making the Reader Solve a Puzzle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_38_Tidyverse_Review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">R Help and Review: Tidyverse Without Tears</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_01_Introduction.html">The Necessary Slog</a></li><li class="breadcrumb-item"><a href="./Ch_08_Independent_t.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independent Samples t-Test</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independent Samples t-Test</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Two Groups, and Now Both of Them Bounce">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Two Groups, and Now Both of Them Bounce
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use an independent-samples <em>t</em>-test when <strong>two different sets of people</strong> are each measured once and you want to know whether the groups differ.</p>
<p>This is the workhorse of experimental psychology. Two groups, one measurement each, and random assignment deciding who went where. A very large share of the experiments you will read are exactly this shape, which means you will spend far more of your career reading this test than running it.</p>
<p>Chapter 6 compared one group against a number someone handed us. That number was fixed and given to us, something that rarely occurs in real research. Now both sides of the comparison are estimates, both of them jump around a little, and the standard error has to carry the uncertainty of two means instead of one. That is the entire structural change. Everything else you already learned still applies.</p>
</div>
</div>
<section id="the-research-question" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="the-research-question"><span class="header-section-number">8.1</span> The Research Question</h2>
<p>The CTA already paid me once to ask riders how they feel about the CTA. The answer came back somewhere around “fine, I guess,” which is the most Chicago answer available. Now they want to know whether they can buy a better answer.</p>
<p>So: what happens if the trains actually show up every 7 minutes?</p>
<section id="design" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="design"><span class="header-section-number">8.1.1</span> Design</h3>
<p>Two groups of riders, assigned by chance, not by preference.</p>
<ul>
<li><strong>Control</strong>: regular CTA timing, where “scheduled” is a flexible concept.</li>
<li><strong>Experimental</strong>: trains every 7 minutes. Like clockwork. Almost suspiciously efficient.</li>
</ul>
<p>Nobody rides both schedules. Each rider contributes one number and goes home. That is what makes these groups <em>independent</em>, and it is the entire reason this chapter’s test is the right one.</p>
</section>
<section id="dependent-variable" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="dependent-variable"><span class="header-section-number">8.1.2</span> Dependent Variable</h3>
<p>The same question I asked back in the standard error chapter, on the same <strong>1-5 bipolar Likert scale</strong>, so that the two studies can actually talk to each other:</p>
<p><em>How much do you typically like traveling on the CTA?</em></p>
<ul>
<li>1 = Strongly dislike</li>
<li>2 = Dislike</li>
<li>3 = Neither dislike nor like</li>
<li>4 = Like</li>
<li>5 = Strongly like (you now defend the CTA on the internet)</li>
</ul>
<p>We expect the control group to land near <strong>3</strong>, which is exactly where Chapter 5 found riders sitting, and the experimental group near <strong>4</strong>, assuming the manipulation works at all.</p>
<p>I know those numbers because I am about to simulate them, which is the only situation in which I ever know the truth in advance. In a real study we can only hypothesize that the experimental group will be different from the control group, and then go find out.</p>
</section>
</section>
<section id="step-1-state-the-hypotheses" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="step-1-state-the-hypotheses"><span class="header-section-number">8.2</span> Step 1: State the Hypotheses</h2>
<p><span class="math display">\[
H_0: \mu_1 = \mu_2
\]</span></p>
<p><span class="math display">\[
H_1: \mu_1 \neq \mu_2
\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\mu_1\)</span> = Experimental (7-minute trains)</li>
<li><span class="math inline">\(\mu_2\)</span> = Control (regular timing)</li>
</ul>
<p>Under the null, <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>. Why? Cause if nothing is happening, <span class="math inline">\(3 - 3 = 0\)</span>.</p>
</section>
<section id="step-2-collect-the-data" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="step-2-collect-the-data"><span class="header-section-number">8.3</span> Step 2: Collect the Data</h2>
<p>Two groups, thirty riders each. Those two <code>rnorm()</code> lines are the entire experiment. <em>I mean I could go out and really get data, but again I would have to actually talk to people.</em></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">343</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">30</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>CTA.SD <span class="ot">=</span> <span class="fl">0.5</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Control group (mean ~ 3, the neutral answer Chapter 5 found)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>CTA.Control <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">3</span>, CTA.SD)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Experimental group (mean ~ 4)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>CTA.Experimental <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">4</span>, CTA.SD)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We also stack the two groups into one data frame, because that is the shape R wants when you use formula syntax later (and the shape your lab data will arrive in).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>CTA.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Condition =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Control</span><span class="sc">\n</span><span class="st">(regular timing)"</span>, n),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">rep</span>(<span class="st">"Experimental</span><span class="sc">\n</span><span class="st">(every 7 min)"</span>, n)),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Liking =</span> <span class="fu">c</span>(CTA.Control, CTA.Experimental)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># R subtracts groups in factor-level order, so we put Experimental first</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># to match the way we wrote the hypotheses in Step 1.</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>CTA.df<span class="sc">$</span>Condition <span class="ot">&lt;-</span> <span class="fu">factor</span>(CTA.df<span class="sc">$</span>Condition,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Experimental</span><span class="sc">\n</span><span class="st">(every 7 min)"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"Control</span><span class="sc">\n</span><span class="st">(regular timing)"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_08_Independent_t_files/figure-html/cta-histograms-1.png" class="img-fluid figure-img" alt="Two overlaid histograms of CTA liking on a 1 to 5 axis. The control group piles up around 3 and the experimental group around 4, with a band near 3.5 where the two overlap." width="576"></p>
<figcaption>Both groups on one axis. The overlap in the middle is the part a t-test has to argue about.</figcaption>
</figure>
</div>
</div>
</div>
<p>Already you should see separation. But eyeballing histograms is not a statistical test (even if it seems obvious). Notice the overlap in the middle: some control riders liked the CTA more than some experimental riders did. A group difference is about where the two piles sit, not about every person in one group beating every person in the other. Group differences are what we care about here, and we do not actually concern ourselves with the feelings of individual people. What are we, psychologists?! <em>Oh wait…we are…okay, let me rephrase that…</em></p>
<p>Individual commoners, I mean subway riders, all have very different experiences and attitudes toward the subway and toward the new schedule. Maybe some people like the chaos of the old system, or are freaked out by clockwork timing. What are we, Switzerland?! Each person has their reasons, and we are not clinical psychologists (well, I am not, that is for sure) who need to unpack why any one of them feels that way.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Who Are We Doing Research to Explain?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Who Are We Doing Research to Explain?
</div>
</div>
<div class="callout-body-container callout-body">
<p>The goal of most experimental research is to understand how a treatment would affect the <em>average</em> person. Remember that average person from the distribution chapter? That is who our result is about, and it is worth stopping to ask who they actually are.</p>
<p>This is not easy here, cause I am randomly sampling subway riders. Does the time of day matter? What if I collected at rush hour instead of 3am on the Red Line? What if I only rode the Brown Line above the Loop, in the more affluent neighborhoods? Never forget who your sample is and who your average represents. It is what limits the scope of your results and how far they generalize.</p>
</div>
</div>
</section>
<section id="step-3-compute-the-standard-error" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="step-3-compute-the-standard-error"><span class="header-section-number">8.4</span> Step 3: Compute the Standard Error</h2>
<p>For <strong>Welch’s <em>t</em>-test</strong>, which R uses by default, the standard error is:</p>
<p><span class="math display">\[
S_{M_1-M_2}=\sqrt{\frac{S_1^2}{n_1}+\frac{S_2^2}{n_2}}
\]</span></p>
<div class="callout callout-style-default callout-important callout-titled" title="The Subscript Is a Name Tag, Not an Instruction">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The Subscript Is a Name Tag, Not an Instruction
</div>
</div>
<div class="callout-body-container callout-body">
<p>That <span class="math inline">\(M_1-M_2\)</span> hanging off the bottom of the <span class="math inline">\(S\)</span> is not telling you to subtract anything. Nothing is being subtracted. It is a label.</p>
<p>Back in the standard error chapter we wrote <span class="math inline">\(S_M\)</span>, meaning “the standard error of <span class="math inline">\(M\)</span>,” or in plain English, how much a sample mean bounces around from study to study. The subscript names <em>which</em> statistic we are describing. Same idea here. The statistic we care about now is no longer a single mean, it is the gap between two means, so the label is <span class="math inline">\(M_1 - M_2\)</span>. Read the whole symbol out loud as “the standard error of the difference between the means” and it stops being intimidating.</p>
<p>Now look at what the formula actually does, because this is the part worth stopping for. The label says <em>difference</em>, but the arithmetic <strong>adds</strong>. Both variances go in with a plus sign.</p>
<p>That is not a typo. Group 1 is a guess and bounces around (varies due to chance). Group 2 is also a guess and bounces around. When you subtract two “bouncy” numbers, the bounce does not politely cancel out, it piles up like two waves at the beach. You are now uncertain about where the first mean sits <em>and</em> uncertain about where the second one sits, and both of those doubts make the gap between them harder to trust. Uncertainty accumulates.</p>
</div>
</div>
<p>Welch’s test does not assume equal population variances. In other words, we do not have to assume that people riding the chaotic subway and people riding the clockwork subway have the same amount of variance. Why would that matter, and why would the variances be different?</p>
<p>Imagine the chaotic subway causes more varied feelings: some riders LOVE it and some HATE it. The clockwork one does not draw opinions that strong, so people give a narrower range of ratings. Now suppose that by pure luck you sampled too many of the HATE it crowd on the chaotic subway. It would make you think the chaotic system was more hated than it really is.</p>
<p>So Welch’s <em>t</em>-test corrects this problem by shrinking our estimate of the degrees of freedom (<em>df</em>). Remember that our <em>df</em> sets the critical values of the <em>t</em>-distribution. By shrinking our <em>df</em>, we push those critical values further out into the tails of the distribution, so a result has to be more extreme before we are allowed to make our decision. Thus we make our test more conservative, harder to say something is there when it is not. Remember type I error, which is a bad thing to do.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Layers of Knowledge, and Why Your Brain Is Not Broken">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Layers of Knowledge, and Why Your Brain Is Not Broken
</div>
</div>
<div class="callout-body-container callout-body">
<p>Have you noticed that in this one section I had to call back to degrees of freedom, the <em>t</em>-distribution, type I error, and several other concepts? This is the part about statistics that freaks people out. You have to actually remember what you learned before.</p>
<p>So if you are lost, go back to those chapters and review. <strong>It is normal to need to go back.</strong> I keep the regression bible written by Cohen on my desk and have to refer to it all the time.</p>
</div>
</div>
<p>So how do we actually <em>shrink</em> our degrees of freedom? We use the Welch–Satterthwaite approximation, which R will calculate because we have suffered enough.</p>
<p>For fun, here is that formula. It is a crazy formula that you never want to calculate by hand:</p>
<p><span class="math display">\[
df \approx \frac{\left(\dfrac{S_1^2}{n_1}+\dfrac{S_2^2}{n_2}\right)^2}
{\dfrac{\left(S_1^2/n_1\right)^2}{n_1-1}+\dfrac{\left(S_2^2/n_2\right)^2}{n_2-1}}
\]</span></p>
<p>Notice the <span class="math inline">\(\approx\)</span>. This one does not even pretend to land on a whole number, which is why Welch’s degrees of freedom for our study come out as 57.09 instead of a respectable integer. Nobody sits down and computes this. R does it, and we let it.</p>
<p>What if you do not have access to R and have to do all the calculations the old fashioned way, by hand, with a pencil and paper? <em>Gasp, the horror.</em></p>
<p>What we do instead is use the classical pooled-variance version, the standard error is:</p>
<p><span class="math display">\[
S_{M_1-M_2}=\sqrt{S_p^2\left(\frac{1}{n_1}+\frac{1}{n_2}\right)}
\]</span></p>
<p>This represents how much variability we expect in the <strong>difference between means</strong> due to sampling error. The pooled version combines the two sample variances:</p>
<p><span class="math display">\[
S^2_p =  \frac{SS_1 + SS_2}{df_1 + df_2}
\]</span></p>
</section>
<section id="step-4-compute-the-t-statistic" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="step-4-compute-the-t-statistic"><span class="header-section-number">8.5</span> Step 4: Compute the <em>t</em> Statistic</h2>
<p><span class="math display">\[
t = \frac{M_1 - M_2 - (\mu_1 - \mu_2)}{S_{M1 - M2}}
\]</span></p>
<p>For the pooled-variance test, the degrees of freedom are:</p>
<p><span class="math display">\[
df = (n_1 - 1) + (n_2 - 1)
\]</span></p>
<p>Those formulas are not decoration, so let’s run them. This is the same arithmetic you would do on paper:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(CTA.Experimental)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(CTA.Control)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>S1 <span class="ot">&lt;-</span> <span class="fu">sd</span>(CTA.Experimental)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>S2 <span class="ot">&lt;-</span> <span class="fu">sd</span>(CTA.Control)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>SS1 <span class="ot">&lt;-</span> <span class="fu">sum</span>((CTA.Experimental <span class="sc">-</span> M1)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>SS2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((CTA.Control      <span class="sc">-</span> M2)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>Sp2       <span class="ot">&lt;-</span> (SS1 <span class="sc">+</span> SS2) <span class="sc">/</span> ((n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> (n <span class="sc">-</span> <span class="dv">1</span>))   <span class="co"># pooled variance</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>SE_pooled <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(Sp2 <span class="sc">*</span> (<span class="dv">1</span><span class="sc">/</span>n <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>n))             <span class="co"># SE of the difference</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>t_by_hand <span class="ot">&lt;-</span> (M1 <span class="sc">-</span> M2) <span class="sc">/</span> SE_pooled</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">Sp2 =</span> Sp2, <span class="at">SE_pooled =</span> SE_pooled, <span class="at">t_by_hand =</span> t_by_hand)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Sp2  SE_pooled  t_by_hand 
 0.1859524  0.1113410 10.2132925 </code></pre>
</div>
</div>
<p>Now let R do the same arithmetic. Here it is in <strong>formula syntax</strong>, <code>outcome ~ group</code>, which is what you will do in lab (if you take more courses, that is) and what every regression in Part 2 of the book will use:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The classical pooled test: matches the hand calculation above</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Liking <span class="sc">~</span> Condition, <span class="at">data =</span> CTA.df, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  Liking by Condition
t = 10.213, df = 58, p-value = 1.412e-14
alternative hypothesis: true difference in means between group Experimental
(every 7 min) and group Control
(regular timing) is not equal to 0
95 percent confidence interval:
 0.9142852 1.3600318
sample estimates:
mean in group Experimental\n(every 7 min) 
                                 4.016756 
  mean in group Control\n(regular timing) 
                                 2.879597 </code></pre>
</div>
</div>
<p>Same number. The machine just does math faster.</p>
<p>R uses <strong>Welch’s <em>t</em>-test</strong> by default because it does not require the two populations to have equal variances. That is usually the safer choice. The pooled formula above is still useful because it makes the basic machinery visible, but we should not force equal variances merely because ancient papers did it that way. Also, we have these things called computers now. We do not do this by hand anymore.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Welch: drop var.equal and R defaults to the safer test</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>CTA.t.test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(Liking <span class="sc">~</span> Condition, <span class="at">data =</span> CTA.df)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>CTA.t.test</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Liking by Condition
t = 10.213, df = 57.093, p-value = 1.693e-14
alternative hypothesis: true difference in means between group Experimental
(every 7 min) and group Control
(regular timing) is not equal to 0
95 percent confidence interval:
 0.9142098 1.3601072
sample estimates:
mean in group Experimental\n(every 7 min) 
                                 4.016756 
  mean in group Control\n(regular timing) 
                                 2.879597 </code></pre>
</div>
</div>
<p>Look at what changed between the two outputs, and what did not. The <span class="math inline">\(t\)</span> statistic is <em>identical</em> here, because both groups have exactly 30 people. Only the degrees of freedom moved, from a tidy 58 down to Welch’s fractional 57.09. Welch spends a fraction of a degree of freedom as insurance against unequal variances. When the groups are the same size and the spreads are similar, that insurance is nearly free, which is a good reason to just leave it on.</p>
<p>If trains truly arrive every 7 minutes, we should see a statistically significant increase in liking.</p>
</section>
<section id="what-this-test-assumes" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="what-this-test-assumes"><span class="header-section-number">8.6</span> What This Test Assumes</h2>
<p>Four things, and they are not equally dangerous.</p>
<p><strong>Independence.</strong> Each rider answers alone. If you survey five friends traveling together, you have one opinion wearing five coats, and the model, which believes it met five strangers, becomes confident in ways it has not earned. This is the assumption that actually kills studies, and no amount of statistical fanciness resurrects them. When you genuinely cannot avoid it, because you measured the same person twice or sampled whole classrooms, you need a model that knows about the grouping, which is where mixed models come in later.</p>
<p><strong>Random assignment.</strong> Nothing about the arithmetic knows how riders ended up in their groups. The reason we can talk about the 7-minute schedule <em>causing</em> anything is that chance built the groups, so the schedule is the only systematic difference between them. Let people choose their own condition and you have a quasi-experiment, the same <em>t</em>-test, and a much weaker sentence at the end of it.</p>
<p><strong>Normality, roughly.</strong> The test assumes the <em>sampling distribution of each mean</em> is approximately normal. With 30 people per group the Central Limit Theorem does most of that work for you. Look at the histograms anyway.</p>
<p><strong>Equal variances.</strong> Only the pooled test needs this one. Welch shrugs, which is precisely why it is the default.</p>
</section>
<section id="step-5-visual-reporting---means-95-ci" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="step-5-visual-reporting---means-95-ci"><span class="header-section-number">8.7</span> Step 5: Visual Reporting - Means + 95% CI</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggbarplot</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  CTA.df,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="st">"Condition"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="st">"Liking"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">add =</span> <span class="fu">c</span>(<span class="st">"mean_ci"</span>, <span class="st">"jitter"</span>),   <span class="co"># mean + 95% CI, plus the raw ratings</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="st">"Condition"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"grey80"</span>, <span class="st">"grey60"</span>),   <span class="co"># light enough that the dots stay visible</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="cn">NULL</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Mean CTA liking (1-5)"</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"CTA liking by timing condition"</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_08_Independent_t_files/figure-html/cta-barplot-1.png" class="img-fluid figure-img" alt="Bar chart of mean CTA liking for the two conditions with 95 percent confidence interval whiskers. The experimental bar sits near 4 and the control bar near 3, and individual jittered dots are scattered over each bar showing the spread of the 30 raters in each group." width="480"></p>
<figcaption>The bars are the summary; the dots are the humans.</figcaption>
</figure>
</div>
</div>
</div>
<p>The bars would look exactly the same if every rider in a group had given the identical score. The dots are there so you can check that they did not.</p>
</section>
<section id="step-6-extract-the-values-for-the-apa-write-up" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="step-6-extract-the-values-for-the-apa-write-up"><span class="header-section-number">8.8</span> Step 6: Extract the Values for the APA Write-Up</h2>
<p>Formatting packages can be convenient, but some do not support Welch’s <em>t</em>-test. We can extract the values directly and avoid letting a package bully us back into an equal-variance assumption.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The $ pulls one piece out of the t.test object by name.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># unname() strips the label R attaches to it: without it, the t column</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># would come out headed "t.t" because the statistic arrives carrying</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># its own name tag. We want a clean column, so we take the tag off.</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>apa_values <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">t       =</span> <span class="fu">unname</span>(CTA.t.test<span class="sc">$</span>statistic),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">df      =</span> <span class="fu">unname</span>(CTA.t.test<span class="sc">$</span>parameter),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">p       =</span> CTA.t.test<span class="sc">$</span>p.value,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">CI_low  =</span> CTA.t.test<span class="sc">$</span>conf.int[<span class="dv">1</span>],   <span class="co"># [1] = first value in the interval</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">CI_high =</span> CTA.t.test<span class="sc">$</span>conf.int[<span class="dv">2</span>]    <span class="co"># [2] = second value</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>apa_values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         t       df            p    CI_low  CI_high
1 10.21329 57.09293 1.692969e-14 0.9142098 1.360107</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Never Write p = 0">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Never Write p = 0
</div>
</div>
<div class="callout-body-container callout-body">
<p>Modern APA wants the exact <em>p</em>-value, reported to two or three decimal places: <span class="math inline">\(p = .03\)</span>, <span class="math inline">\(p = .008\)</span>. The one exception is when p is very small. Below .001 you stop counting zeros and write <span class="math inline">\(p &lt; .001\)</span>, which is what our output above deserves.</p>
<p>What you must never write is <span class="math inline">\(p = 0\)</span>. A <em>p</em>-value is the probability of data at least this extreme under the null, and that probability is never exactly zero. Your software prints <code>2e-16</code> because it ran out of decimal places, not because the universe ruled the possibility out. Rounding that to zero claims something no test can deliver.</p>
</div>
</div>
</section>
<section id="step-7-cohens-d" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="step-7-cohens-d"><span class="header-section-number">8.9</span> Step 7: Cohen’s d</h2>
<p>Statistical significance tells us whether the effect is likely non-zero.</p>
<p>Effect size tells us <strong>how big it is</strong>.</p>
<p>For independent samples with equal variances:</p>
<p><span class="math display">\[
d = \frac{M_1 - M_2}{S_p}
\]</span></p>
<p>Where:</p>
<p><span class="math display">\[
S_p = \sqrt{\frac{SS_1 + SS_2}{df_1 + df_2}}
\]</span></p>
<p>Let’s calculate it manually so you see where it comes from. We already built the pooled variance back in Step 4, so <span class="math inline">\(S_p\)</span> is just its square root.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Sp <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(Sp2)              <span class="co"># Sp2 came from the hand calculation in Step 4</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>cohens_d <span class="ot">&lt;-</span> (M1 <span class="sc">-</span> M2) <span class="sc">/</span> Sp</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">M_experimental =</span> M1, <span class="at">M_control =</span> M2, <span class="at">Sp =</span> Sp, <span class="at">d =</span> cohens_d)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>M_experimental      M_control             Sp              d 
     4.0167558      2.8795973      0.4312219      2.6370608 </code></pre>
</div>
</div>
<p>The value tells us how far apart the two means are in pooled standard-deviation units. Context still matters. A conventional adjective cannot tell us whether the change matters for actual riders, budgets, access, or the continued emotional survival of anyone waiting for a bus in February.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Yes, We Just Pooled the Variances We Refused to Pool">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Yes, We Just Pooled the Variances We Refused to Pool
</div>
</div>
<div class="callout-body-container callout-body">
<p>Earlier we ran Welch precisely so we would not have to assume equal variances, and now the effect size pools them anyway. That is standard practice, and it is not hypocrisy, because the two numbers have different jobs. The test is an inference and needs to protect itself against unequal spreads. The effect size is a description, and pooling gives a reasonable yardstick when the spreads are similar, as they are here (0.4 and 0.46).</p>
<p>If the two spreads are very different, standardize by the control group’s SD instead. That is <strong>Glass’s</strong> <span class="math inline">\(\Delta\)</span>, and it answers a cleaner question: how far did the treatment move people, in units of how much they varied before you touched them?</p>
</div>
</div>
<p>Because let’s be honest, trains every 7 minutes would change lives, and the data say it would be a huge effect.</p>
</section>
<section id="step-8-apa-results-paragraph" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="step-8-apa-results-paragraph"><span class="header-section-number">8.10</span> Step 8: APA Results Paragraph</h2>
<p>Participants in the every-7-minutes condition (<span class="math inline">\(M =\)</span> 4.02, <span class="math inline">\(SD =\)</span> 0.40) reported greater liking of the CTA than those in the regular-timing control condition (<span class="math inline">\(M =\)</span> 2.88, <span class="math inline">\(SD =\)</span> 0.46), Welch’s <span class="math inline">\(t(57.09) =\)</span> 10.21, <span class="math inline">\(p\)</span> &lt; .001, 95% CI [0.91, 1.36], <span class="math inline">\(d =\)</span> 2.64.</p>
<p>In this simulated experiment, increasing train frequency produced a very large difference in reported attitudes. In real life, the CTA has declined our invitation to be manipulated with <code>set.seed(343)</code>.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Welch by Default; Effect Size Beside It">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Welch by Default; Effect Size Beside It
</div>
</div>
<div class="callout-body-container callout-body">
<p>Welch’s <em>t</em>-test does not require the two population variances to be equal, so it is a sensible default for independent groups. Report the mean difference and its confidence interval, then add an effect size. The <em>p</em>-value cannot tell the reader how far apart the groups are.</p>
</div>
</div>
</section>
<section id="power-how-many-riders-would-you-actually-need" class="level2" data-number="8.11">
<h2 data-number="8.11" class="anchored" data-anchor-id="power-how-many-riders-would-you-actually-need"><span class="header-section-number">8.11</span> Power: How Many Riders Would You Actually Need?</h2>
<p>The <a href="./Ch_07_Power_Effect_Size.html">power chapter</a> did all of this for the one-sample test. The function is the same, and exactly one argument changes: <code>type = "two.sample"</code>.</p>
<p>One thing about the answer catches almost everybody, so brace for it now.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># delta takes the effect size; with sd = 1, that means Cohen's d.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Leave n = NULL and power.t.test() solves for the sample size.</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>ID.Power<span class="fl">.80</span> <span class="ot">&lt;-</span> <span class="fu">power.t.test</span>(<span class="at">n =</span> <span class="cn">NULL</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">delta =</span> cohens_d,      <span class="co"># our d, from Step 7</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sd =</span> <span class="dv">1</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                            <span class="at">power =</span> .<span class="dv">80</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                            <span class="at">type =</span> <span class="st">"two.sample"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>                            <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(ID.Power<span class="fl">.80</span><span class="sc">$</span>n)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>4 riders <strong>per group</strong>, so 8 people in total.</p>
<p>That number should make you deeply suspicious, and it should.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Per Group Means Per Group">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Per Group Means Per Group
</div>
</div>
<div class="callout-body-container callout-body">
<p>For <code>type = "two.sample"</code>, the <code>n</code> that comes back is the number of participants <strong>in each group</strong>. Double it for your recruitment target.</p>
<p>Students report this number as their total sample roughly half the time, which halves their actual power and turns an 80% study into something closer to a coin flip with extra steps.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Advanced: Simulated Data Lies to You, Politely">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Advanced: Simulated Data Lies to You, Politely
</div>
</div>
<div class="callout-body-container callout-body">
<p>Our simulated CTA effect is <span class="math inline">\(d =\)</span> 2.64. That is not a large effect. That is not even a huge effect. That is two distributions in different postal codes, and it happens because I <em>built</em> the simulation with a clean one-point gap and a standard deviation of exactly 0.5.</p>
<p>Real psychological effects essentially never look like this. If a power analysis tells you that four people per group is sufficient, you have not discovered a cheap study. You have discovered that your assumed effect size is fictional.</p>
<p>Watch what a believable effect costs instead:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What does each effect size cost, per group, for 80% power?</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.5</span>, <span class="fl">0.8</span>, cohens_d),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>       <span class="cf">function</span>(dd) <span class="fu">ceiling</span>(<span class="fu">power.t.test</span>(<span class="at">delta =</span> dd, <span class="at">sd =</span> <span class="dv">1</span>, <span class="at">power =</span> .<span class="dv">80</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">type =</span> <span class="st">"two.sample"</span>)<span class="sc">$</span>n))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 394  64  26   4</code></pre>
</div>
</div>
<p>Small, medium, large, and whatever we simulated. <strong>That first number is the one to internalize.</strong> Most of the effects you actually care about live near it.</p>
</div>
</div>
<section id="advanced-hedges-correction" class="level3" data-number="8.11.1">
<h3 data-number="8.11.1" class="anchored" data-anchor-id="advanced-hedges-correction"><span class="header-section-number">8.11.1</span> Advanced: Hedges’ Correction</h3>
<p>Cohen’s <span class="math inline">\(d\)</span> is biased upward in small samples, for the reason the power chapter opened with: small samples underestimate <span class="math inline">\(\sigma\)</span>, and <span class="math inline">\(\sigma\)</span> is in the denominator. Smaller denominator, bigger <span class="math inline">\(d\)</span>.</p>
<p>Hedges proposed a correction factor <span class="citation" data-cites="hedges1981">(<a href="#ref-hedges1981" role="doc-biblioref">Hedges 1981</a>)</span>:</p>
<p><span class="math display">\[
g = d \times \left(1 - \frac{3}{4(n_1 + n_2) - 9}\right)
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>hedges_g <span class="ot">&lt;-</span> <span class="cf">function</span>(d, n1, n2) {</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  d <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="dv">3</span> <span class="sc">/</span> (<span class="dv">4</span> <span class="sc">*</span> (n1 <span class="sc">+</span> n2) <span class="sc">-</span> <span class="dv">9</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>g_cta <span class="ot">&lt;-</span> <span class="fu">hedges_g</span>(cohens_d, n, n)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">d =</span> cohens_d, <span class="at">g =</span> g_cta), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     d      g 
2.6371 2.6028 </code></pre>
</div>
</div>
<p>With 30 per group the correction is small. With 8 per group it is not.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The same true d of .8, "measured" at five different group sizes</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sapply</span>(<span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">50</span>, <span class="dv">200</span>),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>             <span class="cf">function</span>(k) <span class="fu">hedges_g</span>(<span class="fl">0.8</span>, k, k)), <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7226 0.7662 0.7841 0.7939 0.7985</code></pre>
</div>
</div>
<p>A true <span class="math inline">\(d\)</span> of .8 estimated from five people per group is meaningfully inflated. This is the arithmetic behind your instinct to distrust a huge effect from a tiny study, and it is a real correction, not a vibe.</p>
</section>
</section>
<section id="the-short-story" class="level2" data-number="8.12">
<h2 data-number="8.12" class="anchored" data-anchor-id="the-short-story"><span class="header-section-number">8.12</span> The Short Story</h2>
<ul>
<li>An independent-samples <em>t</em>-test compares two separate groups: the difference between the means, divided by the standard error of that difference.</li>
<li>Welch’s version is R’s default and the better habit. The pooled version assumes equal variances and is what your lab computes by hand to show you the machinery.</li>
<li>Formula syntax (<code>Liking ~ Condition</code>) is the shape everything in Part 2 will use. R subtracts groups in factor-level order, so if the sign looks backwards, check your levels before you check your arithmetic.</li>
<li>Random assignment, not the <em>t</em>-test, is what licenses a causal sentence.</li>
<li>Cohen’s <span class="math inline">\(d\)</span> puts the gap in pooled standard-deviation units. Report the interval and the effect size; a lone <em>p</em>-value tells the reader nothing about size.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Which Test Comes Next?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Which Test Comes Next?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the independent-samples <em>t</em>-test when two <em>different</em> groups of people are compared on one measure.</p>
<p>If you measured the <strong>same people twice</strong>, the groups are not independent and this test is the wrong tool. Continue to the <a href="./Ch_09_Paired_t.html">paired-samples <em>t</em>-test chapter</a>, where the fact that Rider 12 appears in both columns stops being a problem and starts being the whole point.</p>
<p>If you have <strong>more than two groups</strong>, or a predictor that is a number rather than a label, the <em>t</em>-test runs out of road. Part 2 rebuilds all of this as regression, which handles both without complaint.</p>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-hedges1981" class="csl-entry" role="listitem">
Hedges, Larry V. 1981. <span>“Distribution Theory for <span class="nocase">Glass’s</span> Estimator of Effect Size and Related Estimators.”</span> <em>Journal of Educational Statistics</em> 6 (2): 107–28. <a href="https://doi.org/10.3102/10769986006002107">https://doi.org/10.3102/10769986006002107</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/apd217\.github\.io\/Textbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Ch_07_Power_Effect_Size.html" class="pagination-link" aria-label="Power and Effect Size">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Power and Effect Size</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ch_09_Paired_t.html" class="pagination-link" aria-label="Paired-Samples t-Test">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Paired-Samples t-Test</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Alexander P. Demos. Licensed <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/apd217/Textbook/blob/main/Ch_08_Independent_t.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/apd217/Textbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>