<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An accessible, example-driven introduction to psychological statistics and R.">

<title>16&nbsp; Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another – Psychological Statistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ch_17_Categorical_Interaction.html" rel="next">
<link href="./Ch_15_Statistical_Control.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6aaad9ee1f70880fa5715553a7f5f012.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_10_Covariance_Correlation.html">Putting Lines Through Things</a></li><li class="breadcrumb-item"><a href="./Ch_16_Continuous_Categorical_Interaction.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Psychological Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/apd217/Textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Psychological_Statistics_with_R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">The Necessary Slog</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_01_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why You Have to Learn Statistics (Sorry not sorry)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_02_R_Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R: The Extremely Short Survival Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_03_Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability: The Gods Are Fickle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_04_Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions and their Moments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_05_Standard_Error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Standard Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_06_One_Sample_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Sample t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_07_Power_Effect_Size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Power and Effect Size</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_08_Independent_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independent Samples t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_09_Paired_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Paired-Samples t-Test</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Putting Lines Through Things</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_10_Covariance_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Covariance and Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_11_Intro_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_12_Categorical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Regression with Categorical Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_13_Multiple_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Multiple Regression: Statistical Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_14_Hierarchical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hierarchical Regression: Testing Whether Your Model Improves</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_15_Statistical_Control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Statistical Control: What Are We Actually Removing?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_16_Continuous_Categorical_Interaction.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_17_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Categorical-by-Categorical Interactions: The 2-by-2 Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_18_Mixed_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mixed Regression: Between People and Within People</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Okay, But What If It’s Complicated?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_19_Regression_Diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Advanced: Regression Diagnostics and Influential Weirdos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_20_Multiple_Comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">P-Values and Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_21_Advanced_Interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Advanced: Continuous and Higher-Order Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_22_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_23_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Mediation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_24_Moderated_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Moderated Mediation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">ANOVA is dead, Long Live ANOVA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_25_ANOVA_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Historical ANOVA Lectures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_26_One_Way_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Introduction to Analysis of Variance (ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_27_One_Way_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Follow-Ups to One-Way ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_28_Two_Way_Between_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Calculating the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_29_Two_Way_Between_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Following Up the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_30_One_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">From the Paired <em>t</em>-Test to the One-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_31_Two_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Two-Way Within-Subjects ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_32_Two_Way_Within_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Follow-Ups to the Two-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_33_Mixed_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Two-Way Mixed-Design ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Other Statistical Creatures</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_34_Chi_Square.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Pearson’s Chi-Square</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_35_Nonparametric_Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Nonparametric Tests: When the Data Refuse to Behave</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_36_Bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Advanced: Bootstrapping, the Jackknife, and Resampling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">When R Inevitably Betrays You</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_37_Reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Reporting Models Without Making the Reader Solve a Puzzle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_38_Tidyverse_Review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">R Help and Review: Tidyverse Without Tears</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_10_Covariance_Correlation.html">Putting Lines Through Things</a></li><li class="breadcrumb-item"><a href="./Ch_16_Continuous_Categorical_Interaction.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="two-slopes-and-nothing-that-compares-them" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="two-slopes-and-nothing-that-compares-them"><span class="header-section-number">16.1</span> Two Slopes, and Nothing That Compares Them</h2>
<p>Here is a study you could run tomorrow. Closely follow 200 first-semester students wherever they go and video record all their social interactions for an entire semester, while you yell “<em>IGNORE ME</em>” every 30 seconds to ensure they know not to have their behaviors affected by you observing them 24/7 with a camera. Next, have a trained panel of clinical psychologists review all their interactions and rate how warm and agreeable each one is on a 0 to 10 scale. Since we know what they are doing at all times, we would also note whether they actually went out to parties and social events, or stayed home all semester. At the end of the semester we ask each victim, I mean each student who agreed to participate and signed all the IRB forms and waived all rights to their videos, how close a friendship they formed with one particular person they met in week one of the study, on a 0 to 100 “feelings” thermometer.</p>
<p>Below is the simulation of that study.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fl">0.05</span> <span class="sc">*</span> X <span class="sc">+</span> <span class="dv">0</span> <span class="sc">*</span> Z <span class="sc">+</span> <span class="dv">5</span> <span class="sc">*</span> X <span class="sc">*</span> Z <span class="sc">+</span> <span class="dv">15</span> <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">7</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Friend.Data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">BeingNice =</span> X, <span class="at">GoingOut =</span> Z, <span class="at">Closeness =</span> Y)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Friend.Data<span class="sc">$</span>GoingOut_ <span class="ot">&lt;-</span> <span class="fu">factor</span>(Friend.Data<span class="sc">$</span>GoingOut,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Stay in"</span>, <span class="st">"Go out"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Next, you then split the students into the ones who went out and the ones who stayed in, and run an ordinary regression in each half predicting closeness from niceness. Two groups, two regressions, nothing you have not already done a dozen times.</p>
<p>Stay in People:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Stay.In <span class="ot">&lt;-</span> <span class="fu">subset</span>(Friend.Data, GoingOut_ <span class="sc">==</span> <span class="st">"Stay in"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(Closeness <span class="sc">~</span> BeingNice, <span class="at">data =</span> Stay.In)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Estimate Std. Error    t value     Pr(&gt;|t|)
(Intercept) 14.6930979  1.2346357 11.9007558 1.017885e-21
BeingNice    0.1997669  0.2107005  0.9481084 3.450798e-01</code></pre>
</div>
</div>
<p>Go out People:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Go.Out  <span class="ot">&lt;-</span> <span class="fu">subset</span>(Friend.Data, GoingOut_ <span class="sc">==</span> <span class="st">"Go out"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(Closeness <span class="sc">~</span> BeingNice, <span class="at">data =</span> Go.Out)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept) 15.354310   1.550136  9.905138 1.149587e-15
BeingNice    4.904171   0.252405 19.429767 1.983002e-32</code></pre>
</div>
</div>
<p>Read the two slopes. Among students who stayed in, each point of niceness buys 0.2 points of closeness, which is nothing, and the <em>p</em>-value of 0.35 agrees that it is nothing. Among students who went out, each point of niceness buys 4.9 points, and its <em>p</em>-value has run off the bottom of the printout. Same trait, same outcome, same semester, same campus. Being nice appears to be worth something to one group and nothing at all to the other.</p>
<p>Great. Being nice only pays off if you leave the house. Write it up, submit it, wait.</p>
<p>Now defend it. A reviewer asks the one question anybody would ask: are those two slopes <em>actually</em> different, or did two numbers just bounce apart the way numbers sometimes do by chance? Now, go find that test in the output above. I will wait…</p>
<p>What, it is not there? Weird. You have two intercepts, two slopes, four standard errors and four <em>p</em>-values, and every single one of them is a statement about one group considered entirely on its own. You drew an inference based on two separate tables that have nothing to do with each other. You inferred, because the stay-in slope was smaller than the go-out slope, that being nice clearly does more for the people who go out. The comparison the whole study was built to make was never performed, and no amount of staring at <code>p = .35</code> and <code>p &lt; .001</code> will conjure it, because a small <em>p</em>-value next to a large one is not a test of the difference between them. <em>You cannot test a difference with two analyses that have never met.</em></p>
<p>That missing test is what this chapter is for. The tool is called an <strong>interaction</strong>, and by the end of it you will have these exact two slopes back, 0.2 and 4.9, living inside one model that also hands you a significance test for the gap between them.</p>
</section>
<section id="where-we-are-and-where-we-are-going" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="where-we-are-and-where-we-are-going"><span class="header-section-number">16.2</span> Where We Are and Where We Are Going</h2>
<p>So far in this book, you have learned to build regression models where each predictor has its own independent, additive effect on the outcome. Study hours helps exam scores. Test anxiety hurts them. Each predictor does its job, and we can interpret the effects one at a time.</p>
<p>But human behavior is rarely that tidy. In the real world, the effect of one variable often <em>changes</em> depending on the value of another variable. A new medication might be effective for women but not men. Praise for effort might motivate some students while leaving others cold. Practice might matter enormously for novices but very little for experts.</p>
<p>These situations, where the effect of one predictor <strong>depends on</strong> another predictor, are called <strong>interactions</strong>, or equivalently, <strong>moderation effects</strong>. In this chapter, you will learn to detect, estimate, visualize, and interpret an interaction between a continuous variable and a categorical one.</p>
<p>Before we touch any data, we need to build the concept carefully. That is where we will start.</p>
</section>
<section id="the-friendship-study" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="the-friendship-study"><span class="header-section-number">16.3</span> The Friendship Study</h2>
<p>You have probably heard the expression “right place, right time.” It turns out that this is not just a saying; it is backed by social psychological research. A classic study by Back, Schmukle, and Egloff (2008) found that the friendships people form in university are driven, in large part, by seating proximity. Literally, the people you end up sitting next to on the first day of class are the people most likely to become your close friends by the end of the semester. Chance determines who you sit near. <em>Geography becomes destiny</em>.</p>
<p>You decide to replicate and extend this work. You follow 200 first-semester students throughout their first semester, recording how close of a friendship they formed with one particular person (measured on a 0–100 feelings thermometer, where 0 = complete strangers and 100 = best friends). You also measure two things that might predict the quality of that friendship:</p>
<ul>
<li><strong>Being Nice:</strong> each person is rated on their general agreeableness and warmth by a trained panel, on a scale from 0 to 10. This is a continuous variable.</li>
<li><strong>Going Out:</strong> whether the student regularly attended social events and parties throughout the semester. This is a binary variable: <em>Stay in</em> (0) vs.&nbsp;<em>Go out</em> (1).</li>
</ul>
<p>The intuition behind your study is this: being a warm, friendly person should help you make a close friend. But being nice in your apartment, alone, does not do much for your social life. To turn niceness into friendship, you have to actually be around people. <strong>The effect of being nice might depend on whether you go out.</strong></p>
<p>That is your hypothesis. And testing it is the focus of this chapter.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Two IVs, One DV, and Nobody Measured Twice">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Two IVs, One DV, and Nobody Measured Twice
</div>
</div>
<div class="callout-body-container callout-body">
<p>Worth naming the parts before we model them, because from here on there is more than one of some of them.</p>
<p>The <strong>DV</strong> (dependent variable, the outcome) is friendship closeness, 0 to 100. There is exactly one.</p>
<p>The <strong>IVs</strong> (independent variables, the predictors) are Being Nice and Going Out. Two of them. That is what makes an interaction possible in the first place: you need two IVs before you can ask whether the effect of one depends on the other.</p>
<p>Both IVs are <strong>between subjects</strong>. Each student contributes one row, sits in one Going Out group, and is measured once. Nobody appears twice. That is worth saying out loud because it is not always true, and when the same person is measured repeatedly the model has to change to account for it. That is a later chapter.</p>
<p>One more thing, and it matters more than it looks. <strong>Regression does not care whether an IV was randomly assigned or merely observed.</strong> The arithmetic is identical either way. We did not assign anybody to be nice, and we certainly did not assign anybody to go to parties; we watched and wrote it down. So this is a quasi-experiment, the math will run exactly as if it were not, and every causal word you are tempted to write in the discussion section is on you, not on the model.</p>
</div>
</div>
<blockquote class="blockquote">
<p>Back, M. D., Schmukle, S. C., &amp; Egloff, B. (2008). Becoming friends by chance. <em>Psychological Science, 19</em>(5), 439–440.</p>
</blockquote>
</section>
<section id="what-is-an-interaction-the-concept-before-the-math" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="what-is-an-interaction-the-concept-before-the-math"><span class="header-section-number">16.4</span> What Is an Interaction? The Concept Before the Math</h2>
<section id="it-depends-as-a-scientific-statement" class="level3" data-number="16.4.1">
<h3 data-number="16.4.1" class="anchored" data-anchor-id="it-depends-as-a-scientific-statement"><span class="header-section-number">16.4.1</span> “It Depends” as a Scientific Statement</h3>
<p>In everyday conversation, “it depends” can sound like an evasion, a way of refusing to commit to an answer. In statistics, it is a precise and testable claim. When we say “the effect of X on Y depends on Z,” we mean something specific: <strong>the slope of X on Y is not the same across different values of Z.</strong> That is an interaction.</p>
<p>Let’s make this concrete. There are two fundamentally different ways the world could work in our friendship study.</p>
<p><strong>Possibility 1: Being nice always helps (no interaction).</strong> Whether you stay in or go out, being a nicer person leads to a closer friendship. The social opportunities provided by going out matter too: going out raises closeness overall, but the <em>benefit of being nice</em> is the same either way.</p>
<p><strong>Possibility 2: Being nice only pays off if you go out (interaction).</strong> For students who stay in all semester, niceness makes little difference; they simply do not have enough social contact for their personality to matter. For students who go out, however, being nice is powerful: it turns those social opportunities into genuine close friendships.</p>
<p>These two possibilities predict completely different patterns in the data. Before we analyze a single number, we can sketch out what each would look like.</p>
</section>
<section id="visual-hypotheses-sketching-what-we-expect-to-see" class="level3" data-number="16.4.2">
<h3 data-number="16.4.2" class="anchored" data-anchor-id="visual-hypotheses-sketching-what-we-expect-to-see"><span class="header-section-number">16.4.2</span> Visual Hypotheses: Sketching What We Expect to See</h3>
<p>One of the most useful habits in data analysis is to draw a picture of what you <em>expect</em> your results to look like before you run a single model. This keeps your hypotheses honest: you cannot accidentally convince yourself you predicted something after the fact. It also gives you an intuition for what you are looking for.</p>
<p>In our study, we want to predict <em>Friendship Closeness</em> (Y) from <em>Being Nice</em> (X) separately for people who <em>Stay in</em> and <em>Go out</em> (Z). This naturally produces two lines on a plot: one for each group. The question is what those two lines look like relative to each other.</p>
<p>Here are our two competing hypotheses, visualized:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_16_Continuous_Categorical_Interaction_files/figure-html/hypothesis-plots-1.png" class="img-fluid figure-img" alt="Two side-by-side line graphs, each with Being Nice from 0 to 10 on the x axis and predicted closeness from 0 to 75 on the y axis. In the left panel, labelled Hypothesis A No Interaction, two straight lines rise in parallel: the Stay in line from 15 to 35 and the Go out line from 40 to 60. In the right panel, labelled Hypothesis B Interaction Present, both lines start together near 15, but the Stay in line stays almost flat, ending near 17, while the Go out line climbs steeply to about 67." width="672"></p>
<figcaption>The two hypotheses drawn before any data are analysed. Left: the additive world, where both groups gain the same amount from being nice. Right: the interaction world, where only the Go out group gains anything.</figcaption>
</figure>
</div>
</div>
</div>
<p>Look at the difference between these two pictures:</p>
<ul>
<li><p>In <strong>Hypothesis A</strong>, the two lines are <strong>parallel</strong>. The “Go out” line is higher than the “Stay in” line (going out raises closeness overall), but the <em>slope</em> of both lines is the same. Being nice helps by about the same amount whether you go out or not. This is what a <strong>main effects only</strong> world looks like: each variable has an independent, additive effect.</p></li>
<li><p>In <strong>Hypothesis B</strong>, the two lines are <strong>not parallel</strong>. For people who <em>stay in</em>, the line is almost flat: being nice barely moves the needle. For people who <em>go out</em>, the line is steep: being nice strongly predicts closeness. The slope for “Go out” is much steeper than the slope for “Stay in.” This is an <strong>interaction</strong>: the slope of Being Nice <em>depends on</em> whether you go out.</p></li>
</ul>
<p>The key visual signature of an interaction is <strong>non-parallel lines</strong>. If you run an interaction model and your lines look parallel, the interaction is not doing anything. If the lines fan out, cross, or differ in steepness, you have an interaction.</p>
<p>We will use this visual intuition throughout this chapter to interpret the output.</p>
</section>
<section id="the-two-regressions-intuition" class="level3" data-number="16.4.3">
<h3 data-number="16.4.3" class="anchored" data-anchor-id="the-two-regressions-intuition"><span class="header-section-number">16.4.3</span> The Two-Regressions Intuition</h3>
<p>You have already met this idea, in the first thing we did in this chapter. Splitting the data by group and running a separate regression in each half gives you a slope per group:</p>
<ul>
<li><strong>Regression for Stay-in students:</strong> a slope for Being Nice. Call it <span class="math inline">\(b_{stay}\)</span>.</li>
<li><strong>Regression for Go-out students:</strong> a slope for Being Nice. Call it <span class="math inline">\(b_{go}\)</span>.</li>
</ul>
<p>If there is no interaction, <span class="math inline">\(b_{stay} \approx b_{go}\)</span>: the two slopes are about the same. If there is an interaction, <span class="math inline">\(b_{stay} \neq b_{go}\)</span>: the slopes differ.</p>
<p>That approach <em>shows</em> you an interaction and cannot <em>test</em> one, for the reason the cold open ran into: two estimates from two disconnected analyses, and no standard error anywhere for the quantity you care about, which is the gap.</p>
<p>An interaction model fits both slopes simultaneously in a single model and attaches a significance test to the <strong>difference</strong> between them. That test is the interaction term. When it is significant, the slopes differ by more than sampling variability would predict. When it is not, the data do not support the claim that the slopes differ at all.</p>
<p>So an interaction model is a formalized, simultaneous, significance-tested version of the two regressions you already ran. Hold onto that image; when we get to <span class="math inline">\(B_3\)</span> it stops being an analogy and starts being literally the same numbers.</p>
</section>
</section>
<section id="before-we-run-the-models-two-concepts-you-need-first" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="before-we-run-the-models-two-concepts-you-need-first"><span class="header-section-number">16.5</span> Before We Run the Models: Two Concepts You Need First</h2>
<section id="centering-making-zero-meaningful" class="level3" data-number="16.5.1">
<h3 data-number="16.5.1" class="anchored" data-anchor-id="centering-making-zero-meaningful"><span class="header-section-number">16.5.1</span> Centering: Making Zero Meaningful</h3>
<p>You have seen the intercept in every regression model we have run in this book, and you know it means “the predicted value of Y when X = 0.” That definition is simple enough. The problem is that zero is not always a meaningful value.</p>
<p>In our friendship study, <em>Being Nice</em> is measured on a 0–10 scale. Zero means “not nice at all,” a real value technically, but one that describes an essentially sociopathic person who presumably does not exist in our sample. When our regression model reports an intercept, it is making a prediction for a hypothetical person with zero niceness. That is not a very useful prediction.</p>
<p>Now consider what happens when we build an interaction model. The intercept will be the predicted closeness score for a person with zero niceness <em>who also stays in</em>. The coefficient for Going Out will be the gap between the two groups <em>at zero niceness</em>. These values are anchored to a strange and artificial point that nobody in our data actually occupies.</p>
<p><strong>Centering</strong> solves this by shifting the scale of a continuous variable so that zero has a meaningful interpretation: <strong>the average person in the sample.</strong></p>
<p>The process is simple: subtract the mean.</p>
<p><span class="math display">\[X_c = X - M\]</span></p>
<p>After centering:</p>
<ul>
<li>A score of <span class="math inline">\(X_c = 0\)</span> means this person is exactly average on Being Nice (relative to this sample).</li>
<li>A score of <span class="math inline">\(X_c = 2\)</span> means this person is 2 points <em>above</em> the average.</li>
<li>A score of <span class="math inline">\(X_c = -3\)</span> means this person is 3 points <em>below</em> the average.</li>
</ul>
<p>The scale is shifted, but nothing else changes. The <strong>distances between people are identical</strong>. The <strong>slope of the regression line is identical</strong>. The <strong><span class="math inline">\(R^2\)</span> is identical</strong>. The only thing that changes is the meaning of the intercept (and the meaning of some of the other coefficients in the interaction model, as we will see).</p>
<p><strong>Important distinction: centering is not the same as standardizing.</strong></p>
<p>You may recall from earlier in the book that we can also <em>standardize</em> (or <em>z-score</em>) a variable by subtracting the mean <em>and</em> dividing by the standard deviation:</p>
<p><span class="math display">\[Z = \frac{X - M}{S}\]</span></p>
<p>Standardizing changes the units of the variable: a standardized coefficient represents the change in Y for a one-standard-deviation increase in X. Centering does <strong>not</strong> change the units: a centered coefficient still represents the change in Y for a one-unit increase in X. In this chapter, we will only center, not standardize. We want to preserve the original units of our scale (a one-point increase in niceness = one point) while simply making zero mean “the average person.”</p>
<p>When we center <em>Being Nice</em>, the intercept in our interaction model will represent the predicted closeness score for a person of <strong>average niceness who stays in</strong>. That is a real, interpretable, meaningful prediction; a much better anchor than “a person with zero niceness.” We will do it to our data in a moment, as soon as the data exist.</p>
</section>
<section id="dummy-coding-a-quick-review" class="level3" data-number="16.5.2">
<h3 data-number="16.5.2" class="anchored" data-anchor-id="dummy-coding-a-quick-review"><span class="header-section-number">16.5.2</span> Dummy Coding: A Quick Review</h3>
<p>You already know how to dummy code a categorical variable for regression. When we use a binary categorical predictor like Going Out (Stay in vs.&nbsp;Go out), R automatically converts it into a dummy variable: one group is coded as 0 (the <strong>reference group</strong>) and the other as 1 (the <strong>comparison group</strong>). In our study, <em>Stay in</em> will be the reference group (coded 0), and <em>Go out</em> will be the comparison group (coded 1). We tell R which group comes first by setting the factor levels in the desired order.</p>
<p>With dummy coding in place:</p>
<ul>
<li>The <strong>intercept</strong> represents the predicted outcome for the reference group (Stay in) at whatever value the continuous predictor takes.</li>
<li>The <strong>coefficient for GoingOut</strong> represents the gap between the two groups, holding the continuous predictor constant.</li>
</ul>
<p>We will see exactly how this plays out, and how centering changes the interpretation, as we work through the models.</p>
</section>
</section>
<section id="the-data" class="level2" data-number="16.6">
<h2 data-number="16.6" class="anchored" data-anchor-id="the-data"><span class="header-section-number">16.6</span> The Data</h2>
<p>We collected data from 200 first-semester university students. Each student’s friendship closeness with one person they met at the start of the semester was recorded at the end of the semester using a 0–100 feelings thermometer. Their agreeableness and warmth was rated by a trained panel on a 0–10 scale, and we noted whether they regularly attended social events and parties throughout the semester.</p>
<p>Here is a summary of the sample broken down by social engagement:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>Friend.Data <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GoingOut_) <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n         =</span> <span class="fu">n</span>(),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">M_Nice    =</span> <span class="fu">round</span>(<span class="fu">mean</span>(BeingNice), <span class="dv">2</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">M_Close   =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Closeness), <span class="dv">2</span>),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD_Close  =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Closeness), <span class="dv">2</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 x 5
  GoingOut_     n M_Nice M_Close SD_Close
  &lt;fct&gt;     &lt;int&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1 Stay in     116   5.07    15.7     6.65
2 Go out       84   5.43    42.0    15.6 </code></pre>
</div>
</div>
<p>The “Go out” group sits far higher on the closeness thermometer on average. This makes sense: going out creates more social contact. But the standard deviations are large and similar across groups, meaning there is substantial individual variability within each group. Something beyond just whether you go out is driving that spread. That is what we will investigate.</p>
<p>The mean of <em>Being Nice</em> in our sample is:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span>(Friend.Data<span class="sc">$</span>BeingNice), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.22</code></pre>
</div>
</div>
<section id="how-to-center-in-r" class="level3" data-number="16.6.1">
<h3 data-number="16.6.1" class="anchored" data-anchor-id="how-to-center-in-r"><span class="header-section-number">16.6.1</span> How to Center in R</h3>
<p>Now that the data exist, we can center. We use the <code>scale()</code> function with <code>center = TRUE</code> and <code>scale = FALSE</code>. Setting <code>scale = FALSE</code> tells R to subtract the mean <em>without</em> dividing by the standard deviation, so we get the shift without the rescaling.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># as.numeric() matters here; see the warning below</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Friend.Data<span class="sc">$</span>BeingNice.C <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">scale</span>(Friend.Data<span class="sc">$</span>BeingNice,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                                            <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Always check it worked: a centered variable has a mean of (essentially) zero</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Friend.Data<span class="sc">$</span>BeingNice.C)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.779328e-16</code></pre>
</div>
</div>
<p>That is zero with a rounding error’s worth of dust on it, which is exactly what centering is supposed to produce. R prints it in scientific notation to be annoying; <code>1.78e-16</code> is a decimal point followed by fifteen zeros and then a rounding error. A centered value of 0 now corresponds to a person who scored approximately 5.22 on the original 0–10 scale.</p>
<p>Two things in that one line are waiting to bite you.</p>
<p><strong>Watch the <code>scale = FALSE</code>.</strong> Leave it out and <code>scale()</code> helpfully divides by the standard deviation as well, so you have silently z-scored instead of centered. Nothing errors. Your model runs, your plot draws, and every slope you report afterwards is in units nobody asked for.</p>
<p><strong>Watch the <code>as.numeric()</code>.</strong> <code>scale()</code> does not return a vector; it returns a one-column <em>matrix</em> with the mean bolted on as an attribute. <code>lm()</code> does not care, which is the problem, because it means you will not find out until three sections from now when some plotting package refuses to draw your model and says something incomprehensible about <code>nmatrix.1</code>. Wrap it in <code>as.numeric()</code> and the column is an ordinary number like everything else in your data frame.</p>
</section>
</section>
<section id="a-first-look-at-the-data" class="level2" data-number="16.7">
<h2 data-number="16.7" class="anchored" data-anchor-id="a-first-look-at-the-data"><span class="header-section-number">16.7</span> A First Look at the Data</h2>
<p>Before running any models, let’s visualize the relationships in the data. This is always step one.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_16_Continuous_Categorical_Interaction_files/figure-html/ggpairs-plot-1.png" class="img-fluid figure-img" alt="A three-by-three matrix of panels for Being Nice, Closeness, and Going Out. The Being Nice by Closeness scatterplot shows a weak upward trend with very wide vertical scatter, correlation about .41. The Closeness histogram is strongly right skewed, piling up near 15 with a long tail out past 70. The boxplots against Going Out show the Go out group sitting far higher on Closeness than the Stay in group, with a much taller box." width="528"></p>
<figcaption>The standard first look: every variable against every other variable. The Being Nice by Closeness scatterplot in particular has far more scatter than a correlation of .41 alone would suggest.</figcaption>
</figure>
</div>
</div>
</div>
<p>A few things stand out immediately:</p>
<ul>
<li><strong>Being Nice and Closeness</strong> have a moderate positive correlation overall. More agreeable people tend to form closer friendships.</li>
<li><strong>Going Out and Closeness</strong> show a clear difference: students who go out score much higher on the thermometer on average.</li>
<li>The <strong>overall correlation between Being Nice and Closeness</strong> is moderate, but look at the scatterplot: there is a lot of spread around the trend line. Something else might be going on.</li>
</ul>
<p>The key question is whether the relationship between Being Nice and Closeness looks <em>the same</em> for both groups. The pairs plot makes this hard to see directly. That is what the interaction model is for.</p>
</section>
<section id="building-the-models" class="level2" data-number="16.8">
<h2 data-number="16.8" class="anchored" data-anchor-id="building-the-models"><span class="header-section-number">16.8</span> Building the Models</h2>
<section id="model-1-the-additive-model" class="level3" data-number="16.8.1">
<h3 data-number="16.8.1" class="anchored" data-anchor-id="model-1-the-additive-model"><span class="header-section-number">16.8.1</span> Model 1: The Additive Model</h3>
<p>We start with the simpler model: the one that says each variable has its own independent effect, with no interaction. This is our <strong>main effects model</strong> or <strong>additive model</strong>.</p>
<p><span class="math display">\[\widehat{Closeness} = B_0 + B_1 \cdot BeingNice_C + B_2 \cdot GoingOut + \varepsilon\]</span></p>
<p>Note two things about how we set this up:</p>
<ol type="1">
<li>We use the <strong>centered</strong> version of Being Nice (<code>BeingNice.C</code>), so the intercept will be the predicted closeness score for an average-niceness person.</li>
<li>We use the <strong>factored</strong> GoingOut variable (<code>GoingOut_</code>), with <em>Stay in</em> as the reference group, so R handles the dummy coding automatically.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Model<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(Closeness <span class="sc">~</span> BeingNice.C <span class="sc">+</span> GoingOut_, <span class="at">data =</span> Friend.Data)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Closeness ~ BeingNice.C + GoingOut_, data = Friend.Data)

Residuals:
    Min      1Q  Median      3Q     Max 
-21.320  -7.209  -1.063   5.883  28.356 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      16.0242     0.8813  18.182   &lt;2e-16 ***
BeingNice.C       2.1281     0.2307   9.226   &lt;2e-16 ***
GoingOut_Go out  25.5128     1.3613  18.741   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.485 on 197 degrees of freedom
Multiple R-squared:  0.6996,    Adjusted R-squared:  0.6966 
F-statistic: 229.4 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="what-do-the-coefficients-mean" class="level3" data-number="16.8.2">
<h3 data-number="16.8.2" class="anchored" data-anchor-id="what-do-the-coefficients-mean"><span class="header-section-number">16.8.2</span> What do the coefficients mean?</h3>
<ul>
<li><p><strong>Intercept:</strong> The predicted closeness score for a person of <em>average niceness</em> (BeingNice.C = 0, i.e., roughly a 5.2 on the original scale) who <em>stays in</em> (GoingOut = reference group). This is a real, interpretable prediction: someone who is neither particularly nice nor antisocial, and who mostly stays home.</p></li>
<li><p><strong>BeingNice.C:</strong> Controlling for whether the student goes out or not, each additional point of niceness (above the average) is associated with about 2.13 more points of closeness. This is averaged across both groups.</p></li>
<li><p><strong>GoingOut_Go out:</strong> Controlling for how nice the student is, going out is associated with about 25.5 more points of closeness than staying in. This is the overall main effect of social engagement.</p></li>
</ul>
</section>
<section id="visualizing-the-additive-model" class="level3" data-number="16.8.3">
<h3 data-number="16.8.3" class="anchored" data-anchor-id="visualizing-the-additive-model"><span class="header-section-number">16.8.3</span> Visualizing the additive model</h3>
<p>The critical test of the additive model is whether it produces parallel lines when we plot the predicted values.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_16_Continuous_Categorical_Interaction_files/figure-html/additive-plot-1.png" class="img-fluid figure-img" alt="A scatterplot with Being Nice from 0 to 10 on the x axis and predicted closeness on the y axis, with two parallel rising prediction lines and confidence bands. The blue Stay in line runs from about 5 to about 25; the orange Go out line runs from about 31 to about 50, at the same angle. The faint raw data disagree with the lines: the blue points sit in a flat band near 15 across the whole x range, while the orange points fan steeply upward from about 15 on the left to about 70 on the right." width="432"></p>
<figcaption>The additive model’s predictions, with the raw data underneath. The lines are parallel because the model has no way to make them anything else.</figcaption>
</figure>
</div>
</div>
</div>
<p>The additive model forces the two lines to be parallel: that is built into the model’s assumptions when there is no interaction term. Notice how the lines run at the same angle, just shifted up for the “Go out” group. This model says: being nice helps equally, no matter what.</p>
<p>But does this model actually fit the data? Look at the raw data points (the faint dots). The “Go out” points (orange) seem to fan upward much more steeply as niceness increases, while the “Stay in” points (blue) look relatively flat. The parallel lines do not seem to capture that pattern. We need a model that lets the slopes differ.</p>
<p>And there is one more diagnostic concern with the additive model. Let’s look at the residuals:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_16_Continuous_Categorical_Interaction_files/figure-html/additive-residuals-1.png" class="img-fluid figure-img" alt="Two diagnostic panels for the additive model. On the left, residuals from about negative 21 to positive 28 are plotted against fitted values from about 5 to 52, and the red loess curve is clearly bowed rather than flat: it rises above zero at low fitted values, dips well below zero in the middle, and climbs again at the right. On the right, a quantile-quantile plot whose points bend away from the reference line at both ends." width="576"></p>
<figcaption>Diagnostics for the additive model. Left: residuals against fitted values, with a loess curve. Right: a normal quantile-quantile plot of the standardized residuals.</figcaption>
</figure>
</div>
</div>
</div>
<p>The residual plot on the left shows a clear curved pattern, a classic sign that the model is missing something systematic. The data have a structure that a straight-line additive model cannot capture. This is exactly what you would expect when a real interaction exists and you have not modeled it. Time to add the interaction term.</p>
</section>
<section id="model-2-the-interaction-model" class="level3" data-number="16.8.4">
<h3 data-number="16.8.4" class="anchored" data-anchor-id="model-2-the-interaction-model"><span class="header-section-number">16.8.4</span> Model 2: The Interaction Model</h3>
<p>Now we add the interaction term. The equation becomes:</p>
<p><span class="math display">\[\widehat{Closeness} = B_0 + B_1 \cdot BeingNice_C + B_2 \cdot GoingOut + B_3 \cdot BeingNice_C \times GoingOut + \varepsilon\]</span></p>
<p>The new term, <span class="math inline">\(B_3 \cdot BeingNice_C \times GoingOut\)</span>, is the product of our two predictors. This is what allows the slope of Being Nice to be <em>different</em> for each group. In R, we use the <code>*</code> operator, which automatically includes both main effects and the interaction:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Model<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(Closeness <span class="sc">~</span> BeingNice.C <span class="sc">*</span> GoingOut_, <span class="at">data =</span> Friend.Data)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Model<span class="fl">.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Closeness ~ BeingNice.C * GoingOut_, data = Friend.Data)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.2429  -4.4894  -0.2029   4.3964  17.9396 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  15.7363     0.6183  25.449   &lt;2e-16 ***
BeingNice.C                   0.1998     0.2106   0.949    0.344    
GoingOut_Go out              25.2284     0.9548  26.422   &lt;2e-16 ***
BeingNice.C:GoingOut_Go out   4.7044     0.3289  14.304   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.651 on 196 degrees of freedom
Multiple R-squared:  0.853, Adjusted R-squared:  0.8508 
F-statistic: 379.2 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Before we interpret these coefficients in detail, let’s ask the most important question first: <strong>does this more complex model actually fit the data better?</strong></p>
</section>
<section id="does-the-interaction-model-explain-more-variance" class="level3" data-number="16.8.5">
<h3 data-number="16.8.5" class="anchored" data-anchor-id="does-the-interaction-model-explain-more-variance"><span class="header-section-number">16.8.5</span> Does the Interaction Model Explain More Variance?</h3>
<p>Adding the interaction term uses up one additional degree of freedom. We need to check whether the improvement in model fit justifies this cost. We do this with an <strong>F-test for model comparison</strong>, the same logic as hierarchical regression. The null hypothesis is that the interaction explains zero additional variance:</p>
<p><span class="math display">\[H_0: \Delta R^2 = 0 \quad \text{(the interaction adds nothing)}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>Additive model R-squared:     0.7 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Interaction model R-squared:  0.853 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Change in R-squared:          0.153 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">anova</span>(Model<span class="fl">.1</span>, Model<span class="fl">.2</span>), <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Model Comparison: Additive vs. Interaction"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Model Comparison: Additive vs.&nbsp;Interaction</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Res.Df</th>
<th style="text-align: right;">RSS</th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum of Sq</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">197</td>
<td style="text-align: right;">17722.135</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: right;">196</td>
<td style="text-align: right;">8670.551</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9051.584</td>
<td style="text-align: right;">204.613</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The interaction model explains substantially more variance than the additive model. The <em>F</em>-test is significant, meaning that the improvement in <span class="math inline">\(R^2\)</span> (<span class="math inline">\(\Delta R^2 =\)</span> 0.153) is far larger than we would expect by chance. Adding the interaction term was worth it. The two lines are not parallel in the population.</p>
<p>Let’s also check the residuals from the interaction model:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_16_Continuous_Categorical_Interaction_files/figure-html/interaction-residuals-1.png" class="img-fluid figure-img" alt="Two diagnostic panels for the interaction model. On the left, residuals from about negative 18 to positive 18 are plotted against fitted values from about 15 to 64, and the red loess curve is close to flat along zero across the whole range, with none of the bowing seen in the additive model. On the right, a quantile-quantile plot whose points follow the reference line closely." width="576"></p>
<figcaption>The same two diagnostics for the interaction model. Compare the loess curve on the left with the bowed one from the additive model.</figcaption>
</figure>
</div>
</div>
</div>
<p>The residual pattern is now much healthier: the curved structure is gone, and the points are scattered more evenly around zero. This confirms that the interaction model is capturing what was actually going on in the data.</p>
</section>
</section>
<section id="interpreting-the-interaction-model" class="level2" data-number="16.9">
<h2 data-number="16.9" class="anchored" data-anchor-id="interpreting-the-interaction-model"><span class="header-section-number">16.9</span> Interpreting the Interaction Model</h2>
<section id="the-plot-first" class="level3" data-number="16.9.1">
<h3 data-number="16.9.1" class="anchored" data-anchor-id="the-plot-first"><span class="header-section-number">16.9.1</span> The Plot First</h3>
<p>Before reading the numbers, look at the picture. The plot below shows the predicted values from the interaction model:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_16_Continuous_Categorical_Interaction_files/figure-html/interaction-plot-1.png" class="img-fluid figure-img" alt="A scatterplot with Being Nice from 0 to 10 on the x axis and predicted closeness on the y axis, showing two clearly non-parallel prediction lines with confidence bands. The blue Stay in line is almost flat, running from about 15 to about 17 across the whole range. The orange Go out line starts near 16 on the left and climbs steeply to about 61 on the right. The faint raw points follow each line closely." width="432"></p>
<figcaption>The interaction model’s predictions on the same data. The model is now allowed to give each group its own slope, and it uses that freedom immediately.</figcaption>
</figure>
</div>
</div>
</div>
<p>This is <strong>Hypothesis B</strong> from our earlier sketch come to life in real data. The “Stay in” line (blue) is essentially flat: being nice does not seem to predict friendship closeness for students who spend the semester at home. The “Go out” line (orange) has a strong positive slope: among students who regularly attend social events, being a warmer and more agreeable person leads to substantially closer friendships. The two lines start at roughly the same point on the left and diverge dramatically as niceness increases.</p>
<p>Compare this to the parallel-lines plot from the additive model. The two models tell completely different stories. The additive model said: being nice helps equally for everyone. The interaction model says: being nice only really pays off if you are actually around people to be nice <em>to</em>.</p>
<p>Now let’s connect this picture to the numbers.</p>
</section>
<section id="walking-through-each-coefficient" class="level3" data-number="16.9.2">
<h3 data-number="16.9.2" class="anchored" data-anchor-id="walking-through-each-coefficient"><span class="header-section-number">16.9.2</span> Walking Through Each Coefficient</h3>
<p>Let’s go back to the model output and interpret each term carefully, using the plot as our guide.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Closeness ~ BeingNice.C * GoingOut_, data = Friend.Data)

Residuals:
     Min       1Q   Median       3Q      Max 
-18.2429  -4.4894  -0.2029   4.3964  17.9396 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  15.7363     0.6183  25.449   &lt;2e-16 ***
BeingNice.C                   0.1998     0.2106   0.949    0.344    
GoingOut_Go out              25.2284     0.9548  26.422   &lt;2e-16 ***
BeingNice.C:GoingOut_Go out   4.7044     0.3289  14.304   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.651 on 196 degrees of freedom
Multiple R-squared:  0.853, Adjusted R-squared:  0.8508 
F-statistic: 379.2 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="the-intercept" class="level3" data-number="16.9.3">
<h3 data-number="16.9.3" class="anchored" data-anchor-id="the-intercept"><span class="header-section-number">16.9.3</span> The Intercept</h3>
<p><strong>The intercept</strong> (<span class="math inline">\(B_0\)</span>) is the predicted closeness score when <em>both</em> predictors equal zero.</p>
<p>With our setup:</p>
<ul>
<li><code>BeingNice.C = 0</code> means a person of <strong>average niceness</strong> (the mean of 5.22 on the original scale)</li>
<li><code>GoingOut = "Stay in"</code> is the reference group (value = 0)</li>
</ul>
<p>So the intercept is the predicted closeness score for <strong>an average-niceness person who stays in</strong>. Looking at our model output, the intercept is approximately 15.7.</p>
<p>On the plot, this is the point on the blue “Stay in” line directly above the center of the x-axis (average niceness). It sits around 16 on the 0–100 thermometer: not strangers exactly, but nowhere near best friends. About what proximity alone buys you when you never leave the building.</p>
<p>The intercept also comes with a <em>p</em>-value, testing whether that predicted value differs from zero. It does. But “average students have a nonzero opinion of the person they sat next to” is not a finding anybody will publish. Intercept <em>p</em>-values are usually ignorable; the slope tests are where the questions live.</p>
</section>
<section id="b_1-the-slope-of-being-nice-for-the-stay-in-group" class="level3" data-number="16.9.4">
<h3 data-number="16.9.4" class="anchored" data-anchor-id="b_1-the-slope-of-being-nice-for-the-stay-in-group"><span class="header-section-number">16.9.4</span> <span class="math inline">\(B_1\)</span>: The Slope of Being Nice for the Stay-In Group</h3>
<p><strong><code>BeingNice.C</code></strong> (<span class="math inline">\(B_1 =\)</span> 0.2) tells you the slope of Being Nice <em>for the reference group</em>, that is, the slope of the blue line for students who <em>stay in</em>.</p>
<p>This is called a <strong>simple effect</strong> rather than a main effect, because it is not the effect of Being Nice <em>on average across groups</em>: it is the effect of Being Nice <em>within one specific group</em>. Specifically, it is the rate of change along the blue line.</p>
<p>The <em>p</em>-value for <code>BeingNice.C</code> tests: <strong>is the slope of the “Stay in” line significantly different from zero?</strong></p>
<p>Looking at the output, this slope is small and non-significant (<span class="math inline">\(p \approx\)</span> 0.344). This is exactly what the flat blue line in our plot tells you: for students who stay in, being nicer is not significantly predictive of closer friendships. There is essentially no relationship there.</p>
</section>
<section id="b_2-the-group-difference-at-average-niceness" class="level3" data-number="16.9.5">
<h3 data-number="16.9.5" class="anchored" data-anchor-id="b_2-the-group-difference-at-average-niceness"><span class="header-section-number">16.9.5</span> <span class="math inline">\(B_2\)</span>: The Group Difference at Average Niceness</h3>
<p><strong><code>GoingOut_Go out</code></strong> (<span class="math inline">\(B_2 =\)</span> 25.2) tells you the predicted difference between the “Go out” and “Stay in” groups <strong>at the centering point of Being Nice</strong>, that is, at average niceness (BeingNice.C = 0).</p>
<p>This is a <strong>main effect</strong> in the sense that it is evaluated at the mean of the continuous variable (thanks to centering). It tells you: for a person of average niceness, how much more closeness do they get by going out versus staying in?</p>
<p>On the plot, this is the vertical gap between the two lines at the center of the x-axis (average niceness). Students who go out score about 25 points higher on the thermometer than students who stay in, when both groups are at average niceness. This gap is highly significant.</p>
</section>
<section id="b_3-the-interaction-term" class="level3" data-number="16.9.6">
<h3 data-number="16.9.6" class="anchored" data-anchor-id="b_3-the-interaction-term"><span class="header-section-number">16.9.6</span> <span class="math inline">\(B_3\)</span>: The Interaction Term</h3>
<p><strong><code>BeingNice.C:GoingOut_Go out</code></strong> (<span class="math inline">\(B_3 =\)</span> 4.7) is the heart of the analysis. This coefficient represents <strong>how much steeper the “Go out” slope is compared to the “Stay in” slope.</strong></p>
<p>Think of it as the answer to: <em>by how many extra points of closeness, per niceness point, does the “Go out” group outpace the “Stay in” group?</em></p>
<ul>
<li>The slope for the “Stay in” group is <span class="math inline">\(B_1 =\)</span> 0.2 (essentially flat)</li>
<li>The slope for the “Go out” group is <span class="math inline">\(B_1 + B_3 =\)</span> 0.2 <span class="math inline">\(+\)</span> 4.7 <span class="math inline">\(=\)</span> 4.9</li>
</ul>
<p>Look at those two numbers, then scroll back to the two regressions we ran at the top of the chapter before we knew what an interaction was. They are the same numbers. 0.2 and 4.9, recovered to the last decimal place, because splitting the data by group and letting an interaction term do the splitting for you are the same arithmetic wearing different clothes.</p>
<p>What is new is <span class="math inline">\(B_3\)</span> itself. Two separate regressions could hand you both slopes and then shrug. This model hands you the <em>distance</em> between them, 4.7 points of closeness per point of niceness, with a standard error attached and a <em>p</em>-value underneath. That is the test the reviewer asked for, and it is emphatically significant.</p>
<p>Here is a summary table to tie everything together:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Value</th>
<th>What it represents</th>
<th>What it tests</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td>15.74</td>
<td>Predicted closeness for average-niceness, Stay-in student</td>
<td>Is this &gt; 0?</td>
</tr>
<tr class="even">
<td><strong>BeingNice.C</strong></td>
<td>0.2</td>
<td>Slope of Being Nice <em>for Stay-in group</em> (simple effect)</td>
<td>Is the Stay-in slope <span class="math inline">\(\neq\)</span> 0?</td>
</tr>
<tr class="odd">
<td><strong>GoingOut (Go out)</strong></td>
<td>25.23</td>
<td>Group gap at average niceness (main effect)</td>
<td>Is there a group difference at the mean?</td>
</tr>
<tr class="even">
<td><strong>BeingNice.C × GoingOut</strong></td>
<td>4.7</td>
<td>Difference in slopes between groups</td>
<td>Are the two slopes significantly different?</td>
</tr>
</tbody>
</table>
</section>
<section id="the-one-line-version" class="level3" data-number="16.9.7">
<h3 data-number="16.9.7" class="anchored" data-anchor-id="the-one-line-version"><span class="header-section-number">16.9.7</span> The One-Line Version</h3>
<p>The plot above was built by hand, and we will build a fully polished one at the end of the chapter. That is the right amount of effort when a figure is going into a manuscript. It is far too much effort when you are sitting in front of a model at 11pm wanting to know what shape it is.</p>
<p>For that, <code>sjPlot</code> does the whole thing in one line:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(Model<span class="fl">.2</span>, <span class="at">type =</span> <span class="st">"int"</span>)<span class="sc">+</span><span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_16_Continuous_Categorical_Interaction_files/figure-html/sjplot-quick-1.png" class="img-fluid figure-img" alt="A line graph titled Predicted values of Closeness, with centered Being Nice running from about negative 6.6 to positive 6.6 on the x axis and predicted closeness on the y axis. Two lines with confidence bands: the Stay in line is nearly flat, running from about 14 to 17 across the whole range, while the Go out line climbs steeply from about 9 on the left to about 73 on the right. The two lines cross near the left edge and diverge sharply." width="432"></p>
<figcaption>The same interaction, drawn by <code>plot_model()</code> with no formatting work at all. Non-parallel lines, same story, one line of code.</figcaption>
</figure>
</div>
</div>
</div>
<p>This is the exploratory version, and exploratory code is allowed to be fast and slightly ugly. Notice what it gives you and what it does not. The x-axis is <em>centered</em> niceness, running from about <span class="math inline">\(-6.6\)</span> to <span class="math inline">\(+6.6\)</span> rather than the original 0 to 10, so the reader has to know what centering is before the axis means anything. It labels the variable “Being Nice C”, because it is reading your column name and has no idea what you meant.</p>
<p>The hand-built version buys back the original axis and control over everything a reviewer will complain about.</p>
<p>Learn both. Use the fast one until the figure actually matters.</p>
</section>
</section>
<section id="simple-slopes-testing-each-groups-slope-separately" class="level2" data-number="16.10">
<h2 data-number="16.10" class="anchored" data-anchor-id="simple-slopes-testing-each-groups-slope-separately"><span class="header-section-number">16.10</span> Simple Slopes: Testing Each Group’s Slope Separately</h2>
<p>The interaction term tells us that the two slopes <em>differ significantly</em>. But we also want to know, for each group separately: <strong>is the relationship between Being Nice and Closeness significantly different from zero?</strong></p>
<p>We already have the answer for the “Stay in” group: the <code>BeingNice.C</code> coefficient is the “Stay in” slope, and it is non-significant. Being nice does not predict friendship closeness for students who stay in.</p>
<p>But what about the “Go out” group? We know the “Go out” slope (<span class="math inline">\(B_1 + B_3 \approx\)</span> 4.9) is large and positive, but we need a formal significance test.</p>
<p>We use the <code>emtrends()</code> function from the <code>emmeans</code> package, which extracts and tests the slope of Being Nice <em>separately within each level</em> of Going Out:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>simple.slopes <span class="ot">&lt;-</span> <span class="fu">emtrends</span>(Model<span class="fl">.2</span>, <span class="st">"GoingOut_"</span>, <span class="at">var =</span> <span class="st">"BeingNice.C"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># infer = TRUE shows both confidence intervals and significance tests in one table</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple.slopes, <span class="at">infer =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> GoingOut_ BeingNice.C.trend    SE  df lower.CL upper.CL t.ratio p.value
 Stay in                 0.2 0.211 196   -0.215    0.615   0.949  0.3439
 Go out                  4.9 0.253 196    4.406    5.402  19.412 &lt;0.0001

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>This output gives us what we need:</p>
<ul>
<li><p><strong>Stay in group:</strong> The slope of Being Nice is approximately 0.2, which is <em>not</em> significantly different from zero (<span class="math inline">\(p =\)</span> 0.344). For students who stay in, being nicer does not predict how close a friendship they form.</p></li>
<li><p><strong>Go out group:</strong> The slope of Being Nice is approximately 4.9, which is <em>significantly</em> positive (<span class="math inline">\(p &lt;\)</span> .001). For students who go out, every additional point of niceness is associated with about 5 more points of closeness.</p></li>
</ul>
<p>Notice that <code>emtrends()</code> has handed back the same two slopes for the third time: once from the separate regressions at the top of the chapter, once as <span class="math inline">\(B_1\)</span> and <span class="math inline">\(B_1 + B_3\)</span>, and now here. The estimates never move. What the interaction model buys you is not a better slope, it is one pooled error term across all 200 students instead of two error terms estimated from 116 and 84, and the ability to put a standard error on the <em>gap</em>. That gap is the only quantity in this chapter that the separate regressions could not produce at all.</p>
<p>This completes the picture. The effect of Being Nice on friendship closeness is <strong>conditional</strong>: it only emerges among students who are out there meeting people. For students who stay home, personality differences do not seem to matter much for friendship formation. Going out is what activates the effect of being a warm and agreeable person.</p>
</section>
<section id="apa-write-up" class="level2" data-number="16.11">
<h2 data-number="16.11" class="anchored" data-anchor-id="apa-write-up"><span class="header-section-number">16.11</span> APA Write-Up</h2>
<p>Here is how you would write up these results following APA style. Notice the structure: descriptive statistics first, overall model fit, the interaction test, then the simple slopes to unpack what the interaction means.</p>
<p>Prior to the main analysis, descriptive statistics were examined by group. Students who stayed in reported lower friendship closeness on average (<em>M</em> = 15.7, <em>SD</em> = 6.7) than students who went out regularly (<em>M</em> = 42, <em>SD</em> = 15.6).</p>
<p>A hierarchical multiple regression was conducted to examine whether going out moderated the relationship between agreeableness and friendship closeness. Being Nice (centered at the sample mean) and Going Out (dummy coded, <em>Stay in</em> as reference group) were entered in Step 1 as main effects; their product (the interaction term) was entered in Step 2. The additive model (Step 1) was statistically significant, <span class="math inline">\(F(2, 197) =\)</span> 229.42, <span class="math inline">\(p &lt; .001\)</span>, <span class="math inline">\(R^2 =\)</span> 0.7. Adding the interaction term (Step 2) produced a statistically significant improvement in model fit, <span class="math inline">\(\Delta R^2 =\)</span> 0.153, <span class="math inline">\(F(1, 196) =\)</span> 204.61, <span class="math inline">\(p &lt; .001\)</span>, indicating that the effect of agreeableness on friendship closeness differed significantly between students who stayed in and those who went out.</p>
<p>In the full interaction model (<span class="math inline">\(R^2 =\)</span> 0.853, adjusted <span class="math inline">\(R^2 =\)</span> 0.851), the interaction between agreeableness and going out was statistically significant, <span class="math inline">\(b =\)</span> 4.7, <span class="math inline">\(SE =\)</span> 0.33, <span class="math inline">\(t(196) =\)</span> 14.3, <span class="math inline">\(p &lt; .001\)</span>. To interpret the interaction, simple slopes for agreeableness were examined separately for each group. Among students who stayed in, agreeableness did not significantly predict friendship closeness, <span class="math inline">\(b =\)</span> 0.2, <span class="math inline">\(SE =\)</span> 0.21, <span class="math inline">\(t(196) =\)</span> 0.95, <span class="math inline">\(p =\)</span> 0.344. Among students who went out, agreeableness was a strong positive predictor of friendship closeness, <span class="math inline">\(b =\)</span> 4.9, <span class="math inline">\(SE =\)</span> 0.25, <span class="math inline">\(t(196) =\)</span> 19.41, <span class="math inline">\(p &lt; .001\)</span>. These results indicate that the benefit of agreeableness for friendship formation is conditional on social engagement: being a warm and agreeable person leads to closer friendships only among students who are regularly out meeting others.</p>
<p><strong>A few things to notice about this write-up:</strong></p>
<ul>
<li>We report the <strong>model comparison</strong> (the <span class="math inline">\(\Delta R^2\)</span> and its <em>F</em>-test) as the primary test of whether an interaction exists.</li>
<li>We then report the <strong>interaction coefficient</strong> (<span class="math inline">\(b\)</span>, <span class="math inline">\(SE\)</span>, <span class="math inline">\(t\)</span>, <span class="math inline">\(p\)</span>) from the full model.</li>
<li>We follow up with <strong>simple slopes</strong> (the slope of the continuous variable separately for each group) to explain <em>what</em> the interaction looks like. The interaction tells us the slopes differ; the simple slopes tell us how.</li>
<li>We use the phrase <strong>“the effect of X was conditional on Z”</strong> to describe an interaction in plain language.</li>
<li>We <strong>do not</strong> emphasize or interpret the main effects from the interaction model in isolation, because in the presence of a significant interaction, the main effects represent the effect at one specific value of the other variable (in this case, the reference group or the mean) and can be misleading to report without that context.</li>
</ul>
</section>
<section id="apa-style-figure" class="level2" data-number="16.12">
<h2 data-number="16.12" class="anchored" data-anchor-id="apa-style-figure"><span class="header-section-number">16.12</span> APA-Style Figure</h2>
<p>A well-constructed figure is often the clearest way to communicate an interaction. Below is a publication-ready interaction plot that you can adapt for your own write-ups. This figure shows the predicted values from the interaction model with 95% confidence bands, and nothing else.</p>
<p><em>Figure 1.</em> Predicted friendship closeness as a function of agreeableness and social engagement. Lines represent predicted values from the interaction model; shaded bands represent 95% confidence intervals. Among students who regularly went out (<em>Go out</em>; orange), agreeableness was a strong positive predictor of friendship closeness. Among students who stayed in (<em>Stay in</em>; blue), agreeableness was not significantly associated with friendship closeness.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- APA-Style Interaction Plot ---</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Get predicted values from the model using emmeans</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>Inter.Em.Fig <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(Model<span class="fl">.2</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">~</span> BeingNice.C <span class="sc">|</span> GoingOut_,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">at =</span> <span class="fu">list</span>(<span class="at">BeingNice.C =</span> <span class="fu">seq</span>(Min.BN, Max.BN, <span class="fl">0.25</span>)))</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>Fig.Data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(Inter.Em.Fig)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Transform centered x-axis back to original scale (0-10)</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>mean.BN <span class="ot">&lt;-</span> <span class="fu">mean</span>(Friend.Data<span class="sc">$</span>BeingNice)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>Fig.Data<span class="sc">$</span>BeingNice.orig <span class="ot">&lt;-</span> Fig.Data<span class="sc">$</span>BeingNice.C <span class="sc">+</span> mean.BN</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Build the plot</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Fig.Data, <span class="fu">aes</span>(<span class="at">x    =</span> BeingNice.orig,</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y    =</span> emmean,</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">color =</span> GoingOut_,</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill  =</span> GoingOut_,</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>                     <span class="at">group =</span> GoingOut_)) <span class="sc">+</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Confidence ribbons</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower.CL, <span class="at">ymax =</span> upper.CL),</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Regression lines</span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Formatting</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Stay in"</span> <span class="ot">=</span> <span class="st">"#5b8db8"</span>,</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Go out"</span>  <span class="ot">=</span> <span class="st">"#e07b54"</span>),</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Stay in"</span>, <span class="st">"Go out"</span>)) <span class="sc">+</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values  =</span> <span class="fu">c</span>(<span class="st">"Stay in"</span> <span class="ot">=</span> <span class="st">"#5b8db8"</span>,</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Go out"</span>  <span class="ot">=</span> <span class="st">"#e07b54"</span>),</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Stay in"</span>, <span class="st">"Go out"</span>)) <span class="sc">+</span></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">2</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x     =</span> <span class="st">"Agreeableness Rating (0-10)"</span>,</span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>       <span class="at">y     =</span> <span class="st">"Predicted Friendship Closeness (0-100)"</span>,</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Social Engagement"</span>,</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill  =</span> <span class="st">"Social Engagement"</span>) <span class="sc">+</span></span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position   =</span> <span class="st">"top"</span>,</span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title      =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text       =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title        =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor  =</span> <span class="fu">element_blank</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_16_Continuous_Categorical_Interaction_files/figure-html/apa-figure-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" alt="A publication-style figure with Agreeableness Rating 0 to 10 on the x axis and Predicted Friendship Closeness 0 to 100 on the y axis. Two non-parallel prediction lines with shaded 95 percent confidence bands. The blue Stay in line is essentially flat near 15 to 17 across the full range. The orange Go out line rises steeply from about 16 at the left to about 61 at the right. The legend, titled Social Engagement, sits above the plot." width="480"></p>
</figure>
</div>
</div>
</div>
<p><strong>Note:</strong> <em>I removed the raw data points here. In larger, more complex models where you have lots of controls, the raw points can conflict with the plotted slopes and confuse the reader.</em></p>
<div class="callout callout-style-default callout-warning callout-titled" title="Do Not Diagnose an Interaction by Staring at Two P-Values">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Do Not Diagnose an Interaction by Staring at Two P-Values
</div>
</div>
<div class="callout-body-container callout-body">
<p>One simple slope being significant while the other is not does <strong>not</strong> prove that the slopes differ. That was the whole problem the chapter opened with: two separate regressions handed us a significant slope and a non-significant one, and between them there was no test at all. The interaction coefficient is the direct test of that difference. The plot and simple slopes explain the interaction after it has been tested.</p>
</div>
</div>
</section>
<section id="the-short-story" class="level2" data-number="16.13">
<h2 data-number="16.13" class="anchored" data-anchor-id="the-short-story"><span class="header-section-number">16.13</span> The Short Story</h2>
<p>If you remember six things from this chapter, make it these.</p>
<ul>
<li><strong>An interaction means the slopes differ.</strong> “The effect of X depends on Z” is not a hedge, it is the claim that X’s slope is not the same at every level of Z. Non-parallel lines are the visual signature.</li>
<li><strong>Center the continuous predictor so that zero is a person who exists.</strong> Centering does not change the slope, the fit, or the <span class="math inline">\(R^2\)</span>. It changes what the intercept and <span class="math inline">\(B_2\)</span> are <em>about</em>, from a hypothetical zero-niceness person to the average person in your sample.</li>
<li><strong><span class="math inline">\(B_1\)</span> is the reference group’s slope, not an average.</strong> It is a simple effect. In a model with an interaction, it describes exactly one group, the one coded 0.</li>
<li><strong><span class="math inline">\(B_2\)</span> is the group gap at the mean of the centered predictor</strong>, not the group gap in general. Move the centering point and this number moves with it.</li>
<li><strong><span class="math inline">\(B_3\)</span> is the difference between the slopes, and it is the test.</strong> It is the one quantity that running two separate regressions cannot give you.</li>
<li><strong>Test first, explain second.</strong> The <span class="math inline">\(\Delta R^2\)</span> <em>F</em>-test asks whether an interaction exists. Simple slopes and the plot describe what it looks like. Doing this in the other order is how people talk themselves into interactions that are not there.</li>
</ul>
<p>And the reporting order, which is the same every time: <strong>model comparison test, then the interaction coefficient, then the simple slopes, then the figure.</strong> The test establishes that there is something to explain. Everything after it is the explanation.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/apd217\.github\.io\/Textbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Ch_15_Statistical_Control.html" class="pagination-link" aria-label="Statistical Control: What Are We Actually Removing?">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Statistical Control: What Are We Actually Removing?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ch_17_Categorical_Interaction.html" class="pagination-link" aria-label="Categorical-by-Categorical Interactions: The 2-by-2 Design">
        <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Categorical-by-Categorical Interactions: The 2-by-2 Design</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Alexander P. Demos. Licensed <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/apd217/Textbook/blob/main/Ch_16_Continuous_Categorical_Interaction.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/apd217/Textbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>