<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An accessible, example-driven introduction to psychological statistics and R.">

<title>11&nbsp; Linear Regression – Psychological Statistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Ch_12_Categorical_Regression.html" rel="next">
<link href="./Ch_10_Covariance_Correlation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6aaad9ee1f70880fa5715553a7f5f012.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_10_Covariance_Correlation.html">Putting Lines Through Things</a></li><li class="breadcrumb-item"><a href="./Ch_11_Intro_Regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Psychological Statistics</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/apd217/Textbook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Psychological_Statistics_with_R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">The Necessary Slog</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_01_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why You Have to Learn Statistics (Sorry not sorry)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_02_R_Basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R: The Extremely Short Survival Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_03_Probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability: The Gods Are Fickle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_04_Distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Distributions and their Moments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_05_Standard_Error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Standard Error</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_06_One_Sample_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Sample t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_07_Power_Effect_Size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Power and Effect Size</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_08_Independent_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Independent Samples t-Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_09_Paired_t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Paired-Samples t-Test</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Putting Lines Through Things</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_10_Covariance_Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Covariance and Correlation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_11_Intro_Regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_12_Categorical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Regression with Categorical Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_13_Multiple_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Multiple Regression: Statistical Control</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_14_Hierarchical_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hierarchical Regression: Testing Whether Your Model Improves</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_15_Statistical_Control.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Statistical Control: What Are We Actually Removing?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_16_Continuous_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Continuous-by-Categorical Interactions: When the Effect of One Variable Depends on Another</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_17_Categorical_Interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Categorical-by-Categorical Interactions: The 2-by-2 Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_18_Mixed_Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mixed Regression: Between People and Within People</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Okay, But What If It’s Complicated?</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_19_Regression_Diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Advanced: Regression Diagnostics and Influential Weirdos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_20_Multiple_Comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">P-Values and Multiple Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_21_Advanced_Interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Advanced: Continuous and Higher-Order Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_22_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_23_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Mediation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_24_Moderated_Mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Moderated Mediation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">ANOVA is dead, Long Live ANOVA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_25_ANOVA_Introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Historical ANOVA Lectures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_26_One_Way_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Introduction to Analysis of Variance (ANOVA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_27_One_Way_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Follow-Ups to One-Way ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_28_Two_Way_Between_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Calculating the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_29_Two_Way_Between_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Following Up the Two-Way Between-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_30_One_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">From the Paired <em>t</em>-Test to the One-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_31_Two_Way_Within_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Two-Way Within-Subjects ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_32_Two_Way_Within_Follow_Ups.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Follow-Ups to the Two-Way Within-Subjects ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_33_Mixed_ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Two-Way Mixed-Design ANOVA: Analysis and Graphing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Other Statistical Creatures</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_34_Chi_Square.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Pearson’s Chi-Square</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_35_Nonparametric_Tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Nonparametric Tests: When the Data Refuse to Behave</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_36_Bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Advanced: Bootstrapping, the Jackknife, and Resampling</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">When R Inevitably Betrays You</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_37_Reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Reporting Models Without Making the Reader Solve a Puzzle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ch_38_Tidyverse_Review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">R Help and Review: Tidyverse Without Tears</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Ch_10_Covariance_Correlation.html">Putting Lines Through Things</a></li><li class="breadcrumb-item"><a href="./Ch_11_Intro_Regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-number-correlation-refused-to-give-you" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="the-number-correlation-refused-to-give-you"><span class="header-section-number">11.1</span> The Number Correlation Refused to Give You</h2>
<p>The last chapter ended on a complaint. Correlation tells you that two things move together and how tightly they do it, and then refuses to say anything more. It will not tell you <em>why</em>, which is a problem for theory. It also will not tell you <em>how much</em>, which is a problem for almost everything else.</p>
<p>You can hear the gap the moment you ask a practical question. If a student studies one more hour a week, how many exam points does that buy? An <span class="math inline">\(r\)</span> of .45 cannot answer that, and not because it is being difficult. It threw the units away on purpose, back when we divided by both standard deviations to force the answer to sit politely between <span class="math inline">\(-1\)</span> and <span class="math inline">\(+1\)</span>.</p>
<p>Regression puts the units back. It answers in points per hour, dollars per year, and scoops of ice cream per unit of happiness. Same relationship, same arithmetic underneath, but now the number means something you could act on.</p>
<p>That is the upgrade, and it is why the next eight chapters are built on this one.</p>
</section>
<section id="introduction-to-regression" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="introduction-to-regression"><span class="header-section-number">11.2</span> Introduction to Regression</h2>
<p>Many psychological studies ask: how does X <em>predict</em> Y? How does ice cream (IV) predict happiness (DV)?</p>
<p>Unlike the <em>t</em>-test (which compares group averages), regression looks at the relationship between <strong>two continuous variables</strong>. <em>Predicting</em> just means making an educated guess—if I know how much ice cream you ate, I can guess how happy you are. The guess won’t be perfect, but it should be reasonably close.</p>
<p>Regression tells us <strong>how close those guesses tend to be</strong>.</p>
<p>Regression predicts. It does not automatically explain causes. If people who eat more ice cream report greater happiness, ice cream may help, happier people may seek ice cream, hot weather may increase both, or the entire pattern may be driven by one billionaire buying all the cookie dough. Design and theory decide which causal stories remain plausible.</p>
<p><strong>Note</strong>: The <em>outcome</em> in ordinary regression should be interval or ratio scale. In practice, psychologists use Likert scales all the time anyway and mostly get away with it, and there is more on that fight later. Predictors are far less picky. Over the next few chapters we will feed regression categorical variables on purpose, and it will thank us for it.</p>
<section id="the-experiment" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="the-experiment"><span class="header-section-number">11.2.1</span> The Experiment</h3>
<p>I bought several tubs of vanilla ice cream, scooped out different amounts, and handed them to students. After eating, they rated their happiness on a 0–10 “feelings thermometer.” Nobody got zero scoops, but some got barely a teaspoon.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_11_Intro_Regression_files/figure-html/simulate-1.png" class="img-fluid figure-img" alt="Scatterplot of happiness against scoops of ice cream for 80 students. Scoops run from 0 to 6, happiness from 0 to 10. The cloud drifts upward from left to right with a lot of vertical scatter." width="408"></p>
<figcaption>The raw data: 80 students, their scoops, and how happy they said they were afterward.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="why-not-just-use-correlation" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="why-not-just-use-correlation"><span class="header-section-number">11.2.2</span> Why not just use correlation?</h3>
<p>You can, and correlation is often the first step. But correlation only handles <strong>two variables at a time</strong>. Regression lets us add more predictors: ice cream <em>plus</em> hot fudge <em>plus</em> cookie dough. In other words, regression scales up in ways correlation can’t.</p>
<p>Here’s the correlation:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(apa)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apa</span>(<span class="fu">cor.test</span>(dat<span class="sc">$</span>Scoops, dat<span class="sc">$</span>Happiness))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "*r*(78) = .60, *p* &lt; .001"</code></pre>
</div>
</div>
<p>Strong positive correlation, as expected!</p>
</section>
</section>
<section id="regression-theory" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="regression-theory"><span class="header-section-number">11.3</span> Regression Theory</h2>
<p>Correlation and regression describe the <strong>same linear relationship</strong>, just differently.</p>
<ul>
<li><strong>Simple linear regression</strong> = 1 DV and 1 IV. The relationship is a straight line representing the <strong>expected mean of Y</strong> for each value of X.</li>
<li><strong>Multiple regression</strong> = 1 DV and 2+ IVs. (Coming later.)</li>
</ul>
<section id="the-regression-equation" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="the-regression-equation"><span class="header-section-number">11.3.1</span> The Regression Equation</h3>
<p>You probably remember from middle school: <span class="math inline">\(y = Mx + b\)</span></p>
<p>The modern version comes in two lines, and the difference between them matters more than almost anything else in this chapter.</p>
<p><span class="math display">\[Y = B_0 + B_1X + e\]</span></p>
<p>That is what the world does: model, plus miss.</p>
<p><span class="math display">\[\widehat{Y} = B_0 + B_1X\]</span></p>
<p>That is what the model predicts. No <span class="math inline">\(e\)</span>, because the model cannot know what it does not know.</p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(Y\)</span> = observed value, the score the person actually gave you</li>
<li><span class="math inline">\(\widehat{Y}\)</span> = predicted value, what the line says they should have given you</li>
<li><span class="math inline">\(B_1\)</span> = slope (change in prediction per one-unit increase in X)</li>
<li><span class="math inline">\(B_0\)</span> = intercept</li>
<li><span class="math inline">\(e\)</span> = residual, the gap between the two (<span class="math inline">\(Y - \widehat{Y}\)</span>)</li>
</ul>
<p>The hat is the whole distinction. <span class="math inline">\(Y\)</span> is a fact about a person. <span class="math inline">\(\widehat{Y}\)</span> is a guess about a person. Mixing them up is the single most common way to get lost in regression, and it will keep mattering all the way into the mixed models at the end of Part 2.</p>
</section>
</section>
<section id="the-ice-cream-model" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="the-ice-cream-model"><span class="header-section-number">11.4</span> The Ice Cream Model</h2>
<p>We fit regression models with <code>lm()</code> (linear model). Formula structure: <strong>DV ~ IV</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Happy.Model<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness <span class="sc">~</span> Scoops, <span class="at">data =</span> dat)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Happy.Model<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness ~ Scoops, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.1621 -0.9242  0.0332  1.0608  3.3565 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.9799     0.3863   7.715 3.35e-11 ***
Scoops        0.7524     0.1127   6.675 3.25e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.681 on 78 degrees of freedom
Multiple R-squared:  0.3636,    Adjusted R-squared:  0.3554 
F-statistic: 44.56 on 1 and 78 DF,  p-value: 3.246e-09</code></pre>
</div>
</div>
<section id="reading-the-output-without-panic" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="reading-the-output-without-panic"><span class="header-section-number">11.4.1</span> Reading the Output Without Panic</h3>
<p>That block is the most-stared-at object in your regression course. You will meet it in every remaining chapter, it will grow extra rows, and at 2 a.m. before an assignment it will look like a ransom note. So here is what each region is, top to bottom.</p>
<p><strong>Call.</strong> Your own formula, echoed back. Worth an actual glance, because this is where you find out you regressed the wrong variable.</p>
<p><strong>Residuals.</strong> A five-number summary of the leftovers, the <span class="math inline">\(e\)</span> from the equation above. You are looking for a median near zero and roughly symmetric ends. Ours run from -5.16 to 3.36, which means the model’s worst miss was about 5.2 happiness points. Nobody is being lied to catastrophically.</p>
<p><strong>Coefficients table.</strong> Four columns, one row per term:</p>
<ul>
<li><strong>Estimate</strong> is <span class="math inline">\(B\)</span>. The intercept row is <span class="math inline">\(B_0\)</span>, the <code>Scoops</code> row is <span class="math inline">\(B_1\)</span>.</li>
<li><strong>Std. Error</strong> is the standard error <em>of that estimate</em>. Same species as the SEM from the standard error chapter: run the study again with 80 different people and the slope would bounce around by roughly this much.</li>
<li><strong>t value</strong> is Estimate divided by Std. Error. That is the one-sample <em>t</em>-test logic, wearing a different kimono: how many standard errors is this estimate away from zero?</li>
<li><strong>Pr(&gt;|t|)</strong> is that <em>t</em>’s <em>p</em>-value, testing the null that this coefficient is really zero (no slope).</li>
</ul>
<p><strong>Residual standard error.</strong> The typical size of a miss, in the outcome’s own units. Ours is 1.68, so a typical prediction is off by about 1.7 happiness points. The <code>on 78 degrees of freedom</code> is the <span class="math inline">\(N-2\)</span> we paid for in the correlation chapter, and for the same reason: two parameters estimated, this time an intercept and a slope.</p>
<p><strong>Multiple R-squared.</strong> The proportion of outcome variance the model accounts for. There is a whole section on it below.</p>
<p><strong>F-statistic.</strong> The test of the entire model at once, rather than one coefficient at a time. With a single predictor it is telling you exactly what the slope’s <em>t</em>-test already told you, and we can prove that:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>t.for.slope <span class="ot">&lt;-</span> <span class="fu">summary</span>(Happy.Model<span class="fl">.1</span>)<span class="sc">$</span>coefficients[<span class="st">"Scoops"</span>, <span class="st">"t value"</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>t.for.slope<span class="sc">^</span><span class="dv">2</span>                          <span class="co"># square the slope's t</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44.55917</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Happy.Model<span class="fl">.1</span>)<span class="sc">$</span>fstatistic[<span class="dv">1</span>]   <span class="co"># the model's F</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   value 
44.55917 </code></pre>
</div>
</div>
<p>Identical. With one predictor, <span class="math inline">\(F = t^2\)</span>, because “is this one slope non-zero” and “does this model do anything at all” are the same question asked twice. That stops being true the moment we add a second predictor, which is precisely when <span class="math inline">\(F\)</span> starts earning its keep, in the hierarchical regression chapter.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="The Two Numbers Everyone Skips">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>The Two Numbers Everyone Skips
</div>
</div>
<div class="callout-body-container callout-body">
<p>Students read the Estimate and the <em>p</em>-value and stop. The two most useful numbers in that block are the ones they scroll past: the <strong>Std. Error</strong>, which tells you how much to trust the estimate, and the <strong>Residual standard error</strong>, which tells you in plain units how wrong a typical prediction is.</p>
<p>A slope of 0.75 with typical misses of 1.7 happiness points is a very different finding from the same slope with typical misses of 0.2. The <em>p</em>-value cannot tell those apart. You can.</p>
</div>
</div>
</section>
<section id="intercept" class="level3" data-number="11.4.2">
<h3 data-number="11.4.2" class="anchored" data-anchor-id="intercept"><span class="header-section-number">11.4.2</span> Intercept</h3>
<p>The intercept is the predicted happiness <strong>when ice cream = 0</strong>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(dat<span class="sc">$</span>Scoops)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02927577 5.88743768</code></pre>
</div>
</div>
<p>Nobody had zero scoops, so we can’t actually interpret this directly. <strong>Never predict outside the range of your data.</strong> (We can fix this by centering X, more on that later.)</p>
</section>
<section id="slope" class="level3" data-number="11.4.3">
<h3 data-number="11.4.3" class="anchored" data-anchor-id="slope"><span class="header-section-number">11.4.3</span> Slope</h3>
<p>The slope is 0.752. For each additional scoop, happiness changes by that amount.</p>
</section>
<section id="making-a-prediction" class="level3" data-number="11.4.4">
<h3 data-number="11.4.4" class="anchored" data-anchor-id="making-a-prediction"><span class="header-section-number">11.4.4</span> Making a prediction</h3>
<p>The equation: <span class="math inline">\(Y = B_0 + B_1X\)</span></p>
<p>What’s the predicted happiness for someone who eats <strong>5 scoops</strong>?</p>
<ul>
<li><span class="math inline">\(Y = 2.98 + (0.752 \times 5)\)</span></li>
<li><span class="math inline">\(Y = 6.742\)</span></li>
</ul>
</section>
</section>
<section id="predicted-values-and-residuals" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="predicted-values-and-residuals"><span class="header-section-number">11.5</span> Predicted Values and Residuals</h2>
<p>The line gives one predicted happiness score for every amount of ice cream. Real people do not sit perfectly on that line because humans are noisy, stubborn, and occasionally having a terrible day for reasons unrelated to dessert.</p>
<p>A <strong>residual</strong> is the distance between the observed score and the model’s prediction:</p>
<p><span class="math display">\[
e_i=Y_i-\widehat{Y}_i.
\]</span> - A positive residual means the person was happier than the model predicted. - A negative residual means the person was less happy than the model predicted. - A residual of zero means the prediction was exactly right, which is suspiciously cooperative behavior from a human.</p>
<p>R stores both pieces inside the fitted model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Predicted <span class="ot">&lt;-</span> <span class="fu">fitted</span>(Happy.Model<span class="fl">.1</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Residual <span class="ot">&lt;-</span> <span class="fu">residuals</span>(Happy.Model<span class="fl">.1</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat[<span class="fu">c</span>(<span class="st">"Scoops"</span>, <span class="st">"Happiness"</span>, <span class="st">"Predicted"</span>, <span class="st">"Residual"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Scoops Happiness Predicted   Residual
1 0.4874424  4.689709  3.346669  1.3430399
2 2.7996025  3.676425  5.086421 -1.4099958
3 4.1977287  7.669921  6.138422  1.5314991
4 4.7945917  6.331497  6.587523 -0.2560254
5 3.3393869  4.690570  5.492574 -0.8020041
6 5.2990277  7.685625  6.967079  0.7185465</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dat<span class="sc">$</span>Residual)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.283102e-17</code></pre>
</div>
</div>
<p>The residuals have a mean of approximately zero because ordinary least squares (i.e., math that finds the best line) tries to balance the line through the data such that the positive and negative mistakes cancel out.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x =</span> Scoops, <span class="at">y =</span> Happiness)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"gray45"</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">xend =</span> Scoops, <span class="at">yend =</span> Predicted, <span class="at">color =</span> Residual),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.7</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Residual), <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> Predicted), <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient2</span>(<span class="at">low =</span> <span class="st">"#0072B2"</span>, <span class="at">mid =</span> <span class="st">"white"</span>, <span class="at">high =</span> <span class="st">"#D55E00"</span>) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Residuals Are the Model's Vertical Mistakes"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Scoops of Ice Cream"</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Happiness"</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_11_Intro_Regression_files/figure-html/regression-residual-picture-1.png" class="img-fluid figure-img" alt="Scatterplot with a fitted regression line. Each observed point is joined to the line by a vertical coloured segment, blue where the person was less happy than predicted and orange where they were happier. Hollow points sit on the line at each prediction." width="672"></p>
<figcaption>Every vertical segment is one residual: the gap between what a student reported and what the line predicted for them.</figcaption>
</figure>
</div>
</div>
</div>
<p>The filled points are observed happiness. The hollow points are predicted happiness. Each vertical segment is one residual. This is the error the model did not explain.</p>
</section>
<section id="why-this-line-and-not-some-other-line" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="why-this-line-and-not-some-other-line"><span class="header-section-number">11.6</span> Why This Line and Not Some Other Line?</h2>
<p>Nothing so far has explained where the line came from. R drew one, we believed it. But an infinite number of straight lines could be drawn through that cloud of points, so something had to choose.</p>
<p>Here is the rule. Take any line you like. Measure every vertical miss, square each one, and add them all up. That total is the line’s score, and lower is better. The regression line is the line that makes that total as small as it can possibly be. That is the entire idea, and it is what <strong>least squares</strong> means.</p>
<p>We can check that R did its job. The fitted line’s squared misses:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">residuals</span>(Happy.Model<span class="fl">.1</span>)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 220.3025</code></pre>
</div>
</div>
<p>Now some rival lines. The first is the flattest possible one, a slope of zero, which ignores ice cream entirely and predicts the mean happiness for everybody. The other two keep our intercept but guess the slope wrong:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">coef</span>(Happy.Model<span class="fl">.1</span>)[<span class="dv">1</span>]</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Slope of 0: the mean-only model, ice cream tells us nothing</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((dat<span class="sc">$</span>Happiness <span class="sc">-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>Happiness))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 346.155</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Too steep</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((dat<span class="sc">$</span>Happiness <span class="sc">-</span> (b0 <span class="sc">+</span> <span class="fl">1.5</span><span class="sc">*</span>dat<span class="sc">$</span>Scoops))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 745.2635</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Too flat</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((dat<span class="sc">$</span>Happiness <span class="sc">-</span> (b0 <span class="sc">+</span> <span class="fl">0.3</span><span class="sc">*</span>dat<span class="sc">$</span>Scoops))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 412.5871</code></pre>
</div>
</div>
<p>The fitted line wins, and it is not close. Every wrong slope costs you, and the further off you guess, the more it costs.</p>
<p><strong>Why squared, and not just the raw misses?</strong> Because raw residuals sum to zero by construction, as we saw a moment ago. A criterion that adds up to zero for every possible line is a criterion that cannot choose between lines. Squaring kills the signs, which is exactly the trick variance pulled back in the distributions chapter, for exactly the same reason. It also means one enormous miss hurts far more than several small ones, which is a genuine design decision on the part of those who created regression.</p>
<p>Hold onto that mean-only number, 346.2. It is the score of a model with no predictor in it: your best guess before ice cream entered the room. The fitted line scores 220.3. The gap between those two numbers is what ice cream bought you, and turning that gap into a proportion is the entire content of the <span class="math inline">\(R^2\)</span> section coming up.</p>
</section>
<section id="the-assumptions-what-could-make-the-line-lie" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="the-assumptions-what-could-make-the-line-lie"><span class="header-section-number">11.7</span> The Assumptions: What Could Make the Line Lie?</h2>
<p>Regression assumptions are claims about the errors left after fitting the line. They are not personality tests that the raw variables must pass before R permits them into the building.</p>
<p>For now, focus on five questions:</p>
<ol type="1">
<li><strong>Linearity:</strong> Is a straight line a reasonable summary of the average relationship?</li>
<li><strong>Independence:</strong> Are the residuals from different observations reasonably independent?</li>
<li><strong>Constant variance:</strong> Is the vertical spread of residuals roughly similar across fitted values?</li>
<li><strong>Approximately normal residuals:</strong> Are the residuals reasonably bell-shaped, especially for small-sample tests and intervals?</li>
<li><strong>Influential observations:</strong> Is one strange person steering the entire line while everyone else watches?</li>
</ol>
<section id="residuals-versus-fitted-values" class="level3" data-number="11.7.1">
<h3 data-number="11.7.1" class="anchored" data-anchor-id="residuals-versus-fitted-values"><span class="header-section-number">11.7.1</span> Residuals Versus Fitted Values</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fitted</span>(Happy.Model<span class="fl">.1</span>),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">residuals</span>(Happy.Model<span class="fl">.1</span>),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Fitted happiness"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Residual"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> grDevices<span class="sc">::</span><span class="fu">adjustcolor</span>(<span class="st">"#1F4E79"</span>, <span class="at">alpha.f =</span> <span class="fl">0.55</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"#D55E00"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_11_Intro_Regression_files/figure-html/regression-residual-fitted-1.png" class="img-fluid figure-img" alt="Scatterplot of residuals against fitted happiness values, with a dashed horizontal line at zero. Points scatter above and below the line with no obvious curve or funnel shape." width="624"></p>
<figcaption>Residuals against fitted values. We want a boring cloud around the dashed line, and this one is reasonably boring.</figcaption>
</figure>
</div>
</div>
</div>
<p>The <strong>residuals-versus-fitted plot</strong> asks whether the model is making similar kinds of errors across the range of values it predicts. Each dot represents one observation.</p>
<ul>
<li><strong>X-axis, Fitted values:</strong> what the regression model <strong>predicted</strong> for each observation.</li>
<li><strong>Y-axis, Residuals:</strong> how wrong that prediction was: <strong>observed - predicted</strong>. A residual of 0 means the model predicted the observation perfectly. Positive residuals mean the observed value was higher than predicted; negative residuals mean it was lower than predicted.</li>
</ul>
<p>Ideally, we want a fairly boring cloud of points scattered around zero, with roughly the same vertical spread from left to right. <strong>Boring is good here.</strong> It means the model is not making errors in an obvious, systematic way.</p>
<p>A <strong>curve</strong> suggests that the straight-line model missed a nonlinear pattern. For example, if residuals tend to be positive, then negative, then positive again as fitted values increase, the relationship may have a bend that our straight regression line cannot capture.</p>
<p>A <strong>funnel</strong> suggests <strong>heterogeneity of variance</strong>, also called <strong>heteroscedasticity</strong>: the model’s errors are much more variable for some predicted values than for others. <em>Note: This is a word I have been teaching since about 2008 and still cannot reliably say out loud.</em></p>
<p>Why care? Ordinary regression calculates standard errors under the assumption that the residual variance is reasonably constant. Strong heteroscedasticity can therefore make standard errors and confidence intervals inaccurate.</p>
<p>But changing variance can also reveal something psychologically interesting. Perhaps ice cream affects people similarly at low doses but produces wildly different reactions after the fourth scoop. Some people achieve joy. Others remember lactose intolerance.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Heterogeneity May Be a Clue, Not Merely a Violation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Heterogeneity May Be a Clue, Not Merely a Violation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Changing residual spread can mean that uncertainty differs across people, conditions, or levels of the outcome. Do not immediately transform the outcome until the graph stops complaining. First ask what process could create the pattern.</p>
</div>
</div>
</section>
<section id="the-q-q-plot" class="level3" data-number="11.7.2">
<h3 data-number="11.7.2" class="anchored" data-anchor-id="the-q-q-plot"><span class="header-section-number">11.7.2</span> The Q-Q Plot</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(Happy.Model<span class="fl">.1</span>), <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#1F4E79"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(Happy.Model<span class="fl">.1</span>), <span class="at">col =</span> <span class="st">"#D55E00"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_11_Intro_Regression_files/figure-html/regression-qq-1.png" class="img-fluid figure-img" alt="Q-Q plot with sample residual quantiles on the vertical axis and theoretical normal quantiles on the horizontal axis. Points follow the diagonal reference line closely, with mild departure at the lower tail." width="528"></p>
<figcaption>A Q-Q plot of the residuals. Points near the line mean the residuals are behaving roughly normally.</figcaption>
</figure>
</div>
</div>
</div>
<p>A <strong>Q-Q plot</strong> asks whether the residuals have roughly the shape we would expect from a normal distribution. Each dot represents one residual, after the residuals have been sorted from smallest to largest.</p>
<ul>
<li><strong>X-axis:</strong> where a residual <em>should fall</em> if the residuals followed a perfect normal distribution. These are called <strong>theoretical quantiles</strong>.</li>
<li><strong>Y-axis:</strong> where the residual <em>actually falls</em> in our data. These are the <strong>observed residuals</strong> (or, depending on the software, standardized residuals).</li>
</ul>
<p>If the residuals are approximately normal, the observed values should line up with the values expected from a normal distribution, producing dots that fall roughly along a straight line. In other words, the x-axis says, “If these residuals were perfectly normal, how extreme should this observation be?” and the y-axis says, “How extreme was it actually?”</p>
<p>Do not expect perfection. Small wiggles and deviations are normal, because we collected data from humans, not from androids or clones. What we care about are <strong>systematic departures from the line</strong>: strong curves can indicate a distribution with the wrong shape, while points breaking away at either end can indicate unusually heavy tails or potential outliers. One observation escaping toward Canada probably means something went wrong for that one person. All of them running for the border means something went wrong with the whole model.</p>
<p>R can produce four standard diagnostic plots at once:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Happy.Model<span class="fl">.1</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Ch_11_Intro_Regression_files/figure-html/regression-four-diagnostics-1.png" class="img-fluid figure-img" alt="A two-by-two panel of regression diagnostics: residuals versus fitted, a normal Q-Q plot, a scale-location plot, and a residuals versus leverage plot with Cook's distance contours." width="672"></p>
<figcaption>The four diagnostic plots R gives you for free. The top two are the ones we just built by hand.</figcaption>
</figure>
</div>
</div>
</div>
<p>The first two are the residual-versus-fitted and Q-Q plots we just learned. The other two help identify unequal spread and influential observations. You do not need to master them yet. The advanced diagnostics chapter returns with more detail and several additional ways for data to misbehave.</p>
</section>
</section>
<section id="residual-variance-and-r2" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="residual-variance-and-r2"><span class="header-section-number">11.8</span> Residual Variance and <span class="math inline">\(R^2\)</span></h2>
<p>Before using ice cream to predict happiness, our best simple guess for everyone was the mean. The total variance describes how far scores spread around that mean. After fitting the model, residual variance describes how far scores spread around the regression line.</p>
<p>Those are the two lines we just raced. The mean-only model was the flat one that lost; the fitted line was the one that won. <span class="math inline">\(R^2\)</span> is simply that race expressed as a proportion: of all the spread we started with, what fraction did the line manage to account for?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>TotalVariance <span class="ot">&lt;-</span> <span class="fu">var</span>(dat<span class="sc">$</span>Happiness)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>ResidualVariance <span class="ot">&lt;-</span> <span class="fu">var</span>(<span class="fu">residuals</span>(Happy.Model<span class="fl">.1</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">TotalVariance =</span> TotalVariance,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ResidualVariance =</span> ResidualVariance,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">R_squared_from_variance =</span> <span class="dv">1</span> <span class="sc">-</span> ResidualVariance <span class="sc">/</span> TotalVariance,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">R_squared_from_model =</span> <span class="fu">summary</span>(Happy.Model<span class="fl">.1</span>)<span class="sc">$</span>r.squared)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          TotalVariance        ResidualVariance R_squared_from_variance 
              4.3817090               2.7886391               0.3635727 
   R_squared_from_model 
              0.3635727 </code></pre>
</div>
</div>
<p><span class="math inline">\(R^2\)</span> describes the proportion of observed outcome variance explained by the fitted model. It is an effect-size measure for the model, not proof that the model is causal, correct, or ready to be tattooed onto your arm.</p>
</section>
<section id="relationship-to-correlation" class="level2" data-number="11.9">
<h2 data-number="11.9" class="anchored" data-anchor-id="relationship-to-correlation"><span class="header-section-number">11.9</span> Relationship to Correlation</h2>
<p>Why did we start with correlation if regression is so great? To show they’re the same thing, just scaled differently. Run a regression on <strong>standardized</strong> (z-scored) variables:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Happiness.z <span class="ot">&lt;-</span> <span class="fu">scale</span>(dat<span class="sc">$</span>Happiness)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Scoops.z    <span class="ot">&lt;-</span> <span class="fu">scale</span>(dat<span class="sc">$</span>Scoops)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>std.reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(Happiness.z <span class="sc">~</span> Scoops.z, <span class="at">data =</span> dat)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(std.reg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness.z ~ Scoops.z, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.46608 -0.44152  0.01588  0.50675  1.60349 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.037e-16  8.976e-02   0.000        1    
Scoops.z     6.030e-01  9.033e-02   6.675 3.25e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8029 on 78 degrees of freedom
Multiple R-squared:  0.3636,    Adjusted R-squared:  0.3554 
F-statistic: 44.56 on 1 and 78 DF,  p-value: 3.246e-09</code></pre>
</div>
</div>
<section id="what-didnt-change" class="level3" data-number="11.9.1">
<h3 data-number="11.9.1" class="anchored" data-anchor-id="what-didnt-change"><span class="header-section-number">11.9.1</span> What didn’t change?</h3>
<p>The <strong>t-statistic and <em>p</em>-value</strong> for the slope. These don’t change under any <em>linear</em> rescaling: adding constants, multiplying by constants, z-scoring. Shift and stretch the axes all you like and the significance test is untouched.</p>
<p>Nonlinear transformations are a different animal. Logs, square roots, and powers change the model itself, along with <span class="math inline">\(t\)</span>, <span class="math inline">\(p\)</span>, and what the slope even means. The correlation chapter showed this the hard way with ice cream raised to the fourth power, where a perfectly good relationship fell apart the moment we bent the scale.</p>
</section>
<section id="what-changed" class="level3" data-number="11.9.2">
<h3 data-number="11.9.2" class="anchored" data-anchor-id="what-changed"><span class="header-section-number">11.9.2</span> What changed?</h3>
<p><strong>The intercept</strong> is now <strong>zero</strong>. When all variables are standardized (mean = 0), the regression line must pass through [0, 0]. And the slope changed numerically:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(std.reg), <span class="at">digits =</span> <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Happiness.z ~ Scoops.z, data = dat)

Residuals:
      Min        1Q    Median        3Q       Max 
-2.466080 -0.441520  0.015876  0.506753  1.603487 

Coefficients:
                Estimate   Std. Error t value   Pr(&gt;|t|)    
(Intercept) -2.03715e-16  8.97626e-02 0.00000          1    
Scoops.z     6.02970e-01  9.03290e-02 6.67527 3.2461e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.802862 on 78 degrees of freedom
Multiple R-squared:  0.363573,  Adjusted R-squared:  0.355413 
F-statistic: 44.5592 on 1 and 78 DF,  p-value: 3.24612e-09</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(dat<span class="sc">$</span>Happiness, dat<span class="sc">$</span>Scoops)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  dat$Happiness and dat$Scoops
t = 6.6753, df = 78, p-value = 3.246e-09
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4417814 0.7264454
sample estimates:
      cor 
0.6029699 </code></pre>
</div>
</div>
<p>The standardized slope equals the correlation. Not a coincidence.</p>
<p>When everything is standardized, one unit = one SD. So the correlation tells us: every time X increases by 1 SD, Y increases by <span class="math inline">\(r\)</span> SDs. Standardized regression slopes are called <strong>beta weights (<span class="math inline">\(\beta\)</span>)</strong>.</p>
</section>
<section id="converting-slope-back-to-raw-units" class="level3" data-number="11.9.3">
<h3 data-number="11.9.3" class="anchored" data-anchor-id="converting-slope-back-to-raw-units"><span class="header-section-number">11.9.3</span> Converting slope back to raw units</h3>
<p><span class="math display">\[B_1 = r \frac{sd_y}{sd_x} = \frac{Cov(x,y)}{Var(x)}\]</span></p>
<p>Your slope is just the correlation times the ratio of SDs. Makes sense, since slope is rise over run:</p>
<ul>
<li>Double Y → twice as much rise → <span class="math inline">\(B_1\)</span> doubles</li>
<li>Double X → twice as much run → <span class="math inline">\(B_1\)</span> is cut in half</li>
</ul>
</section>
<section id="what-about-the-intercept" class="level3" data-number="11.9.4">
<h3 data-number="11.9.4" class="anchored" data-anchor-id="what-about-the-intercept"><span class="header-section-number">11.9.4</span> What about the intercept?</h3>
<p>Once you know <span class="math inline">\(B_1\)</span>, you know the angle of the line. But the line must also pass through <strong>[mean(X), mean(Y)]</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dat<span class="sc">$</span>Scoops)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.993878</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dat<span class="sc">$</span>Happiness)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.232601</code></pre>
</div>
</div>
<p><span class="math display">\[Mean(Y) = B_0 + B_1 \times Mean(X)\]</span></p>
<p>Solve for <span class="math inline">\(B_0\)</span> and you’re done.</p>
</section>
</section>
<section id="apa-style-report" class="level2" data-number="11.10">
<h2 data-number="11.10" class="anchored" data-anchor-id="apa-style-report"><span class="header-section-number">11.10</span> APA Style Report</h2>
<p>Here is how the whole thing gets written up. Every number below is computed from the model rather than typed, which is why it cannot go stale when the data change.</p>
<blockquote class="blockquote">
<p>Ice cream consumption significantly predicted happiness, <span class="math inline">\(b =\)</span> 0.75, <span class="math inline">\(SE =\)</span> 0.11, <span class="math inline">\(\beta =\)</span> .60, <span class="math inline">\(t(78) =\)</span> 6.68, <span class="math inline">\(p &lt; .001\)</span>. The overall model explained 36.4% of the variance in happiness, <span class="math inline">\(R^2 =\)</span> .364, <span class="math inline">\(F(1, 78) =\)</span> 44.56, <span class="math inline">\(p &lt; .001\)</span>.</p>
</blockquote>
<p>Then say what it means in words a human would use:</p>
<blockquote class="blockquote">
<p>Each additional scoop predicted about 0.75 more points of happiness on the 0 to 10 thermometer.</p>
</blockquote>
<p>A few things to notice, because this paragraph is the template for every regression write-up in the rest of the book:</p>
<ul>
<li>Report <span class="math inline">\(b\)</span> <strong>and</strong> <span class="math inline">\(SE\)</span> <strong>and</strong> <span class="math inline">\(t\)</span> <strong>and</strong> <span class="math inline">\(p\)</span> for the predictor. The slope alone is not a result, it is half of one.</li>
<li>Report the model as a whole with <span class="math inline">\(R^2\)</span> and <span class="math inline">\(F\)</span>, including both degrees of freedom: <span class="math inline">\(F(1, 78)\)</span>. The 1 is the number of predictors, the 78 is <span class="math inline">\(N-2\)</span>.</li>
<li>That <span class="math inline">\(\beta\)</span> of .60 should look familiar. It is the correlation from the top of this chapter, which is the payoff we proved a section ago. In simple regression you can report either (or both), but never present them as two separate findings.</li>
<li>The plain-English sentence is not optional decoration. Being able to say what your slope means in the units your grandmother would understand is a graded skill, in this course and in every paper you will ever write.</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled" title="p < .001 Is a Claim, Not a Default">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>p &lt; .001 Is a Claim, Not a Default
</div>
</div>
<div class="callout-body-container callout-body">
<p>The write-up above says <span class="math inline">\(p &lt; .001\)</span> because this model’s <em>p</em>-value genuinely is 3.25e-09. Report the exact value to two or three decimals whenever it is larger than .001, and never copy <code>p &lt; .001</code> out of an example because it looked authoritative.</p>
</div>
</div>
</section>
<section id="the-short-story" class="level2" data-number="11.11">
<h2 data-number="11.11" class="anchored" data-anchor-id="the-short-story"><span class="header-section-number">11.11</span> The Short Story</h2>
<ul>
<li>Simple linear regression predicts a quantitative outcome from one predictor.</li>
<li>The intercept is the predicted outcome when <span class="math inline">\(X=0\)</span>.</li>
<li>The slope is the expected change in <span class="math inline">\(Y\)</span> for a one-unit increase in <span class="math inline">\(X\)</span>.</li>
<li>The line is chosen by <strong>least squares</strong>: of all possible lines, it is the one with the smallest total of squared vertical misses.</li>
<li>In the <code>summary()</code> output, Std. Error says how much to trust the estimate and Residual standard error says how wrong a typical prediction is. With one predictor, <span class="math inline">\(F = t^2\)</span>.</li>
<li>Residuals are observed outcomes minus predicted outcomes: the model’s leftovers.</li>
<li><span class="math inline">\(R^2\)</span> is the proportion of observed outcome variance explained by the fitted linear model.</li>
<li>With one predictor, the standardized slope equals Pearson’s <span class="math inline">\(r\)</span>.</li>
<li>Prediction is not causation. A straight line cannot randomize participants, control confounds, or stop Reviewer 2 from asking whether heat explains the ice cream.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="A Slope Always Has Units">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>A Slope Always Has Units
</div>
</div>
<div class="callout-body-container callout-body">
<p>The slope is the expected change in <span class="math inline">\(Y\)</span> for a one-unit increase in <span class="math inline">\(X\)</span>. Before deciding that it is large, small, heroic, or pathetic, say what one unit of <span class="math inline">\(X\)</span> and one unit of <span class="math inline">\(Y\)</span> actually mean.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Credit">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Credit
</div>
</div>
<div class="callout-body-container callout-body">
<p>I stole Ryne Estabrook way of explaining least squares cause it was better than mine. Also probably other things.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/apd217\.github\.io\/Textbook\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Ch_10_Covariance_Correlation.html" class="pagination-link" aria-label="Covariance and Correlation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Covariance and Correlation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Ch_12_Categorical_Regression.html" class="pagination-link" aria-label="Linear Regression with Categorical Variables">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Regression with Categorical Variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Alexander P. Demos. Licensed <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions"><ul><li><a href="https://github.com/apd217/Textbook/blob/main/Ch_11_Intro_Regression.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/apd217/Textbook/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>