{
  "hash": "12c92ee9ca8b1319c4c44f8719d1abb1",
  "result": {
    "markdown": "---\ntitle: 'Independent Samples t-Test'\n---\n\n\n\n\n\n::: {.callout-note title=\"Two Groups, and Now Both of Them Wobble\"}\nUse an independent-samples t-test when **two different sets of people** are each measured once and you want to know whether the groups differ.\n\nThis is the workhorse of experimental psychology. Two groups, one measurement each, and random assignment deciding who went where. A very large share of the experiments you will read are exactly this shape, which means you will spend far more of your career reading this test than running it.\n\nChapter 6 compared one group against a number someone handed us. That number was fixed and blameless. Now both sides of the comparison are estimates, both of them wobble, and the standard error has to carry the uncertainty of two means instead of one. That is the entire structural change. Everything else you already learned still applies.\n:::\n\n## The Research Question\n\nThe CTA already paid me once to ask riders how they feel about the CTA. The answer came back somewhere around \"fine, I guess,\" which is the most Chicago answer available. Now they want to know whether they can buy a better answer.\n\nSo: what happens if the trains actually show up every 7 minutes?\n\n### Design\n\nTwo groups of riders, assigned by chance, not by preference.\n\n- **Control**: regular CTA timing, where \"scheduled\" is a flexible concept.\n- **Experimental**: trains every 7 minutes. Like clockwork. Almost suspiciously efficient.\n\nNobody rides both schedules. Each rider contributes one number and goes home. That is what makes these groups *independent*, and it is the entire reason this chapter's test is the right one.\n\n### Dependent Variable\n\n<!-- ALEX: two continuity things now that the opener points explicitly back at Ch5.\n     (1) Ch5's CTA survey used a 1-5 scale; this chapter uses 1-7. Fine as a separate\n     study, but a sharp reader who just came from Ch5 will notice.\n     (2) On Ch5's 1-5 scale, 3 was exactly neutral and the finding was \"roughly neutral.\"\n     On this 1-7 scale, 4 is neutral, so a control mean of 3 is mild dislike. The story\n     still works, but \"classic Chicago baseline\" now means something slightly grumpier\n     than it did last chapter. Both are one-line fixes if they bother you. -->\n\nA **1-7 bipolar Likert scale** measuring how much participants like using the CTA to get around Chicago:\n\n- 1 = Absolutely hate using the CTA\n- 4 = Neutral / It's fine\n- 7 = Love it, I now defend the CTA on the internet\n\nWe expect the control group to land near **3** (mild frustration, classic Chicago baseline) and the experimental group near **5** (\"Wait... this works?\").\n\nI know those numbers because I am about to simulate them, which is the only situation in which I ever know the truth in advance.\n\n\n## Step 1: State the Hypotheses\n\n$$\nH_0: \\mu_1 = \\mu_2 \n$$\n\n$$\nH_1: \\mu_1 \\neq \\mu_2 \n$$\n\nWhere:\n\n- $\\mu_1$ = Experimental (7-minute trains)\n- $\\mu_2$ = Control (regular timing)\n\nUnder the null, $\\mu_1 - \\mu_2 = 0$.\n\n\n## Step 2: Collect the Data\n\nTwo groups, thirty riders each. Those two `rnorm()` lines are the entire experiment.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nn = 30\nCTA.SD = 1\n\n# Control group (mean ~ 3)\nCTA.Control <- rnorm(n, 3, CTA.SD)\n\n# Experimental group (mean ~ 5)\nCTA.Experimental <- rnorm(n, 5, CTA.SD)\n```\n:::\n\n\nWe also stack the two groups into one data frame, because that is the shape R wants when you use formula syntax later (and the shape your lab data will arrive in).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCTA.df <- data.frame(\n  Condition = c(rep(\"Control\\n(regular timing)\", n),\n            rep(\"Experimental\\n(every 7 min)\", n)),\n  Liking = c(CTA.Control, CTA.Experimental)\n)\n\n# R subtracts groups in factor-level order, so we put Experimental first\n# to match the way we wrote the hypotheses in Step 1.\nCTA.df$Condition <- factor(CTA.df$Condition,\n                           levels = c(\"Experimental\\n(every 7 min)\",\n                                      \"Control\\n(regular timing)\"))\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Both groups on one axis. The overlap in the middle is the part a t-test has to argue about.](Chapter_Independent_t_test_files/figure-html/cta-histograms-1.png){fig-align='center' fig-alt='Two overlaid histograms of CTA liking on a 0 to 8 axis. The control group piles up around 2 to 3 and the experimental group around 5, with a band roughly between 3 and 5.5 where the two overlap.' width=576}\n:::\n:::\n\n\nAlready you should see separation. But eyeballing histograms is not a statistical test (even if it feels persuasive). Notice the overlap around 4: some control riders liked the CTA more than some experimental riders did. Group differences are about where the piles sit, not about every person in one group beating every person in the other.\n\n## Step 3: Compute the Standard Error\n\nFor **Welch's t-test**, which R uses by default, the standard error is:\n\n$$\nS_{M_1-M_2}=\\sqrt{\\frac{S_1^2}{n_1}+\\frac{S_2^2}{n_2}}\n$$\n\nWelch's test does not assume equal population variances. It uses a Welch--Satterthwaite approximation for the degrees of freedom, which R will calculate because we have suffered enough.\n\nIf we instead use the classical pooled-variance version, the standard error is:\n\n$$\nS_{M_1-M_2}=\\sqrt{S_p^2\\left(\\frac{1}{n_1}+\\frac{1}{n_2}\\right)}\n$$\n\nThis represents how much variability we expect in the **difference between means** due to sampling error. The pooled version combines the two sample variances:\n\n$$\nS^2_p =  \\frac{SS_1 + SS_2}{df_1 + df_2}\n$$\n\n\n## Step 4: Compute the t Statistic\n\n$$\nt = \\frac{M_1 - M_2 - (\\mu_1 - \\mu_2)}{S_{M1 - M2}}\n$$\nFor the pooled-variance test, the degrees of freedom are:\n\n$$\ndf = (n_1 - 1) + (n_2 - 1)\n$$\n\nThose formulas are not decoration, so let's run them. This is the same arithmetic your lab asks you to do on paper:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nM1 <- mean(CTA.Experimental)\nM2 <- mean(CTA.Control)\nS1 <- sd(CTA.Experimental)\nS2 <- sd(CTA.Control)\n\nSS1 <- sum((CTA.Experimental - M1)^2)\nSS2 <- sum((CTA.Control      - M2)^2)\n\nSp2       <- (SS1 + SS2) / ((n - 1) + (n - 1))   # pooled variance\nSE_pooled <- sqrt(Sp2 * (1/n + 1/n))             # SE of the difference\nt_by_hand <- (M1 - M2) / SE_pooled\n\nc(Sp2 = Sp2, SE_pooled = SE_pooled, t_by_hand = t_by_hand)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       Sp2  SE_pooled  t_by_hand \n 0.7438095  0.2226821 10.2132925 \n```\n:::\n:::\n\n\nNow let R do the same arithmetic. Here it is in **formula syntax**, `outcome ~ group`, which is what your lab uses and what every regression in Part 2 will use:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# The classical pooled test: matches the hand calculation above, and your lab\nt.test(Liking ~ Condition, data = CTA.df, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Liking by Condition\nt = 10.213, df = 58, p-value = 1.412e-14\nalternative hypothesis: true difference in means between group Experimental\n(every 7 min) and group Control\n(regular timing) is not equal to 0\n95 percent confidence interval:\n 1.828570 2.720064\nsample estimates:\nmean in group Experimental\\n(every 7 min) \n                                 5.033512 \n  mean in group Control\\n(regular timing) \n                                 2.759195 \n```\n:::\n:::\n\n\nSame number. The machine just types faster.\n\nR uses **Welch's t-test** by default because it does not require the two populations to have equal variances. That is usually the safer choice. The pooled formula above is still useful because it makes the basic machinery visible, but we should not force equal variances merely because an ancient statistics ritual told us to.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Welch: drop var.equal and R defaults to the safer test\nCTA.t.test <- t.test(Liking ~ Condition, data = CTA.df)\n\nCTA.t.test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  Liking by Condition\nt = 10.213, df = 57.093, p-value = 1.693e-14\nalternative hypothesis: true difference in means between group Experimental\n(every 7 min) and group Control\n(regular timing) is not equal to 0\n95 percent confidence interval:\n 1.828420 2.720214\nsample estimates:\nmean in group Experimental\\n(every 7 min) \n                                 5.033512 \n  mean in group Control\\n(regular timing) \n                                 2.759195 \n```\n:::\n:::\n\n\nLook at what changed between the two outputs, and what did not. The $t$ statistic is *identical* here, because both groups have exactly 30 people. Only the degrees of freedom moved, from a tidy 58 down to Welch's fractional 57.09. Welch spends a fraction of a degree of freedom as insurance against unequal variances. When the groups are the same size and the spreads are similar, that insurance is nearly free, which is a good reason to just leave it on.\n\nIf trains truly arrive every 7 minutes, we should see a statistically significant increase in liking.\n\n\n## What This Test Assumes\n\nFour things, and they are not equally dangerous.\n\n**Independence.** Each rider answers alone. If you survey five friends traveling together, you have one opinion wearing five coats, and the model, which believes it met five strangers, becomes confident in ways it has not earned. This is the assumption that actually kills studies, and no amount of statistical fanciness resurrects them. When you genuinely cannot avoid it, because you measured the same person twice or sampled whole classrooms, you need a model that knows about the grouping, which is where mixed models come in later.\n\n**Random assignment.** Nothing about the arithmetic knows how riders ended up in their groups. The reason we can talk about the 7-minute schedule *causing* anything is that chance built the groups, so the schedule is the only systematic difference between them. Let people choose their own condition and you have a quasi-experiment, the same t-test, and a much weaker sentence at the end of it.\n\n**Normality, roughly.** The test assumes the sampling distribution of each mean is approximately normal. With 30 people per group the Central Limit Theorem does most of that work for you. Look at the histograms anyway.\n\n**Equal variances.** Only the pooled test needs this one. Welch shrugs, which is precisely why it is the default.\n\n## Step 5: Visual Reporting - Means + 95% CI\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggpubr)\n\nggbarplot(\n  CTA.df,\n  x = \"Condition\",\n  y = \"Liking\",\n  add = c(\"mean_ci\", \"jitter\"),   # mean + 95% CI, plus the raw ratings\n  fill = \"Condition\",\n  palette = c(\"grey80\", \"grey60\"),   # light enough that the dots stay visible\n  ylim = c(1, 7),\n  xlab = NULL,\n  ylab = \"Mean CTA liking (1-7)\",\n  title = \"CTA liking by timing condition\"\n) +\n  theme_bw(base_size = 11) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![The bars are the summary; the dots are the humans.](Chapter_Independent_t_test_files/figure-html/cta-barplot-1.png){fig-align='center' fig-alt='Bar chart of mean CTA liking for the two conditions with 95 percent confidence interval whiskers. The experimental bar sits near 5 and the control bar near 3, and individual jittered dots are scattered over each bar showing the spread of the 30 raters in each group.' width=480}\n:::\n:::\n\n\nThe bars would look exactly the same if every rider in a group had given the identical score. The dots are there so you can check that they did not.\n\n\n## Step 6: Extract the APA Values\n\nFormatting packages can be convenient, but some do not support Welch's t-test. We can extract the values directly and avoid letting a package bully us back into an equal-variance assumption.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napa_values <- data.frame(\n  t = unname(CTA.t.test$statistic),\n  df = unname(CTA.t.test$parameter),\n  p = CTA.t.test$p.value,\n  CI_low = CTA.t.test$conf.int[1],\n  CI_high = CTA.t.test$conf.int[2]\n)\n\nround(apa_values, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       t     df p CI_low CI_high\n1 10.213 57.093 0  1.828    2.72\n```\n:::\n:::\n\n\n\n## Step 7: Cohen's d\n\nStatistical significance tells us whether the effect is likely non-zero.\n\nEffect size tells us **how big it is**.\n\nFor independent samples with equal variances:\n\n$$\nd = \\frac{M_1 - M_2}{S_p}\n$$\n\nWhere:\n\n$$\nS_p = \\sqrt{\\frac{SS_1 + SS_2}{df_1 + df_2}}\n$$\n\nLet's calculate it manually so you see where it comes from. We already built the pooled variance back in Step 4, so $S_p$ is just its square root.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSp <- sqrt(Sp2)              # Sp2 came from the hand calculation in Step 4\ncohens_d <- (M1 - M2) / Sp\n\nc(M_experimental = M1, M_control = M2, Sp = Sp, d = cohens_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nM_experimental      M_control             Sp              d \n     5.0335115      2.7591945      0.8624439      2.6370608 \n```\n:::\n:::\n\n\nThe value tells us how far apart the two means are in pooled standard-deviation units. Context still matters. A conventional adjective cannot tell us whether the change matters for actual riders, budgets, access, or the continued emotional survival of anyone waiting for a bus in February.\n\n::: {.callout-note title=\"Yes, We Just Pooled the Variances We Refused to Pool\"}\nTen lines ago we ran Welch precisely so we would not have to assume equal variances, and now the effect size pools them anyway. That is standard practice, and it is not hypocrisy, because the two numbers have different jobs. The test is an inference and needs to protect itself against unequal spreads. The effect size is a description, and pooling gives a reasonable yardstick when the spreads are similar, as they are here (0.81 and 0.92).\n\nIf the two spreads are very different, standardize by the control group's SD instead. That is **Glass's** $\\Delta$, and it answers a cleaner question: how far did the treatment move people, in units of how much they varied before you touched them?\n:::\n\nBecause let's be honest - trains every 7 minutes would change lives.\n\n\n## Step 8: APA Results Paragraph\n\nParticipants in the every-7-minutes condition ($M =$ 5.03, $SD =$ 0.81) reported greater liking of the CTA than those in the regular-timing control condition ($M =$ 2.76, $SD =$ 0.92), Welch's $t(57.09) =$ 10.21, $p$ < .001, 95% CI [1.83, 2.72], $d =$ 2.64.\n\nIn this simulated experiment, increasing train frequency produced a very large difference in reported attitudes. In real life, the CTA has declined our invitation to be manipulated with `set.seed(343)`.\n\n::: {.callout-important title=\"Welch by Default; Effect Size Beside It\"}\nWelch's t-test does not require the two population variances to be equal, so it is a sensible default for independent groups. Report the mean difference and its confidence interval, then add an effect size. The p-value cannot tell the reader how far apart the groups are.\n:::\n\n## The Short Story\n\n- An independent-samples t-test compares two separate groups: the difference between the means, divided by the standard error of that difference.\n- Welch's version is R's default and the better habit. The pooled version assumes equal variances and is what your lab computes by hand to show you the machinery.\n- Formula syntax (`Liking ~ Condition`) is the shape everything in Part 2 will use. R subtracts groups in factor-level order, so if the sign looks backwards, check your levels before you check your arithmetic.\n- Random assignment, not the t-test, is what licenses a causal sentence.\n- Cohen's $d$ puts the gap in pooled standard-deviation units. Report the interval and the effect size; a lone p-value tells the reader nothing about size.\n\n::: {.callout-note title=\"Which Test Comes Next?\"}\nUse the independent-samples t-test when two *different* groups of people are compared on one measure.\n\nIf you measured the **same people twice**, the groups are not independent and this test is the wrong tool. Continue to the [paired-samples t-test chapter](Chapter_Paired_t_test.qmd), where the fact that Rider 12 appears in both columns stops being a problem and starts being the whole point.\n\nIf you have **more than two groups**, or a predictor that is a number rather than a label, the t-test runs out of road. Part 2 rebuilds all of this as regression, which handles both without complaint.\n:::\n",
    "supporting": [
      "Chapter_Independent_t_test_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}