{
  "hash": "3a78a2fb49adb41c3380810d622e7562",
  "result": {
    "markdown": "---\ntitle: 'Independent Samples t-Test'\ngeometry: margin=.5in\nfontsize: 11pt\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n---\n\n\n\n\n\n\n## The Research Question \n\nWhat would happen if the CTA actually ran every 7 minutes?\n\nWould people like using it more?\n\n### Design\n\nTwo independent groups:\n\n- **Control** = Regular CTA timing (\"scheduled\" is a flexible concept)\n- **Experimental** = Trains arrive every 7 minutes. Like clockwork. Almost suspiciously efficient.\n\n### Dependent Variable\n\nA **1-7 bipolar Likert scale** measuring how much participants like using the CTA to get around Chicago:\n\n- 1 = Absolutely hate using the CTA  \n- 4 = Neutral / It's fine  \n- 7 = Love it, I now defend the CTA on the internet\n\nWe expect:\n\n- Control mean is approximately **3** (mild frustration, classic Chicago baseline)\n- Experimental mean is approximately **5** (\"Wait... this works?\")\n\nNow we walk through how to test this.\n\n\n## Step 1: State the Hypotheses\n\n$$\nH_0: \\mu_1 = \\mu_2 \n$$\n\n$$\nH_1: \\mu_1 \\neq \\mu_2 \n$$\n\nWhere:\n\n- $\\mu_1$ = Experimental (7-minute trains)\n- $\\mu_2$ = Control (regular timing)\n\nUnder the null, $\\mu_1 - \\mu_2 = 0$.\n\n\n## Step 2: collect the Data\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Independent_t_test_files/figure-pdf/unnamed-chunk-1-1.pdf){fig-align='center'}\n:::\n\n::: {.cell-output-display}\n![](Chapter_Independent_t_test_files/figure-pdf/unnamed-chunk-1-2.pdf){fig-align='center'}\n:::\n:::\n\n\n\nAlready you should see separation. But eyeballing histograms is not a statistical test (even if it feels persuasive).\n\n## Step 3: Compute the Standard Error\n\nFor **Welch's t-test**, which R uses by default, the standard error is:\n\n$$\nS_{M_1-M_2}=\\sqrt{\\frac{S_1^2}{n_1}+\\frac{S_2^2}{n_2}}\n$$\n\nWelch's test does not assume equal population variances. It uses a Welch--Satterthwaite approximation for the degrees of freedom, which R will calculate because we have suffered enough.\n\nIf we instead use the classical pooled-variance version, the standard error is:\n\n$$\nS_{M_1-M_2}=\\sqrt{S_p^2\\left(\\frac{1}{n_1}+\\frac{1}{n_2}\\right)}\n$$\n\nThis represents how much variability we expect in the **difference between means** due to sampling error. The pooled version combines the two sample variances:\n\n$$\nS^2_p =  \\frac{SS_1 + SS_2}{df_1 + df_2}\n$$\n\n\n## Step 4: Compute the t Statistic\n\n$$\nt = \\frac{M_1 - M_2 - (\\mu_1 - \\mu_2)}{S_{M1 - M2}}\n$$\nFor the pooled-variance test, the degrees of freedom are:\n\n$$\ndf = (n_1 - 1) + (n_2 - 1)\n$$\n\nNow let R do the arithmetic. R uses **Welch's t-test** by default because it does not require the two populations to have equal variances. That is usually the safer choice. The pooled formula above is still useful because it makes the basic machinery visible, but we should not force equal variances merely because an ancient statistics ritual told us to.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCTA.t.test <- t.test(x = CTA.Experimental,\n                     y = CTA.Control,\n                     alternative = \"two.sided\",\n                     conf.level = 0.95)\n\nCTA.t.test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  CTA.Experimental and CTA.Control\nt = 10.213, df = 57.093, p-value = 1.693e-14\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n 1.828420 2.720214\nsample estimates:\nmean of x mean of y \n 5.033512  2.759195 \n```\n:::\n:::\n\n\n\nIf trains truly arrive every 7 minutes, we should see a statistically significant increase in liking.\n\n\n## Step 5: Visual Reporting - Means + 95% CI\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggpubr)\n\nggbarplot(\n  CTA.df,\n  x = \"Condition\",\n  y = \"Liking\",\n  add = \"mean_ci\",        # mean + 95% CI\n  fill = \"Condition\",\n  palette = \"grey\",\n  ylim = c(1, 7),\n  xlab = NULL,\n  ylab = \"Mean CTA liking (1-7)\",\n  title = \"CTA liking by timing condition\"\n) +\n  theme_bw(base_size = 11) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Chapter_Independent_t_test_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\n\n## Step 6: Extract the APA Values\n\nFormatting packages can be convenient, but some do not support Welch's t-test. We can extract the values directly and avoid letting a package bully us back into an equal-variance assumption.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napa_values <- data.frame(\n  t = unname(CTA.t.test$statistic),\n  df = unname(CTA.t.test$parameter),\n  p = CTA.t.test$p.value,\n  CI_low = CTA.t.test$conf.int[1],\n  CI_high = CTA.t.test$conf.int[2]\n)\n\nround(apa_values, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       t     df p CI_low CI_high\n1 10.213 57.093 0  1.828    2.72\n```\n:::\n:::\n\n\n\n\n## Step 7: Cohen's d\n\nStatistical significance tells us whether the effect is likely non-zero.\n\nEffect size tells us **how big it is**.\n\nFor independent samples with equal variances:\n\n$$\nd = \\frac{M_1 - M_2}{S_p}\n$$\n\nWhere:\n\n$$\nS_p = \\sqrt{\\frac{SS_1 + SS_2}{df_1 + df_2}}\n$$\n\nLet's calculate it manually so you see where it comes from.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nM1 <- mean(CTA.Experimental)\nM2 <- mean(CTA.Control)\nS1 <- sd(CTA.Experimental)\nS2 <- sd(CTA.Control)\n\nSp <- sqrt(((n-1)*S1^2 + (n-1)*S2^2) / (2*n - 2))\ncohens_d <- (M1 - M2) / Sp\n\nc(M_experimental = M1, M_control = M2, Sp = Sp, d = cohens_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nM_experimental      M_control             Sp              d \n     5.0335115      2.7591945      0.8624439      2.6370608 \n```\n:::\n:::\n\n\n\nThe value tells us how far apart the two means are in pooled standard-deviation units. Context still matters. A conventional adjective cannot tell us whether the change matters for actual riders, budgets, access, or the continued emotional survival of anyone waiting for a bus in February.\n\nBecause let's be honest - trains every 7 minutes would change lives.\n\n\n## Step 8: APA Results Paragraph\n\nParticipants in the every-7-minutes condition ($M =$ 5.03, $SD =$ 0.81) reported greater liking of the CTA than those in the regular-timing control condition ($M =$ 2.76, $SD =$ 0.92), Welch's $t(57.09) =$ 10.21, $p$ < .001, 95% CI [1.83, 2.72], $d =$ 2.64.\n\nIn this simulated experiment, increasing train frequency produced a very large difference in reported attitudes. In real life, the CTA has declined our invitation to be manipulated with `set.seed(343)`.\n\n::: {.callout-important title=\"Welch by Default; Effect Size Beside It\"}\nWelch's t-test does not require the two population variances to be equal, so it is a sensible default for independent groups. Report the mean difference and its confidence interval, then add an effect size. The p-value cannot tell the reader how far apart the groups are.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}