{
  "hash": "6c9aa002aece1384249b2d858fd0fb42",
  "result": {
    "markdown": "---\ntitle: \"Advanced: Regression Diagnostics and Influential Weirdos\"\n---\n\n\n\n\n<!-- ---Alex--- Cold open (CH19-P01 + VOICE_GUIDE 15/17), which you approved on\n2026-08-17. Two judgment calls inside it. First, the simulation is echoed with the\nparticipant-60 lines visible, so the reader knows the outlier is planted before the\nreveal. That follows 14b rule 1 and the Ch16 precedent (showing 5*X*Z in the\ngenerating model); the alternative was hiding it for surprise, which the book's\nhonesty rule outranks. The drama survives because the shock is the SIZE of the\ndamage, not the existence of an outlier. Second, the refit now happens twice on\npurpose: here as the hook, and again under Cook's distance as the disciplined\nversion with SEs and p-values. Delete either half if that reads as repetitive. -->\n\n## An Unusually Responsible Therapy Study\n\nWe predict symptom improvement from therapy attendance and baseline symptom severity. Sixty people, two predictors, nothing exotic.\n\nOne of those sixty is a problem, and we are going to build the problem on purpose so you can watch what it does. Participant 60 attends nearly every session and reports a suspiciously enormous improvement, possibly because they misunderstood the scale or wanted the research assistant to stop calling. Here is the whole simulation, including the three lines at the bottom that do the damage.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\nn <- 60\nTherapyData <- data.frame(\n  Sessions = runif(n, 0, 12),\n  Baseline = rnorm(n, 60, 10)\n)\n\nTherapyData$Improvement <-\n  1.8 * TherapyData$Sessions +\n  0.18 * TherapyData$Baseline +\n  rnorm(n, 0, 5)\n\nTherapyData$Sessions[60] <- 12\nTherapyData$Baseline[60] <- 45\nTherapyData$Improvement[60] <- 60\n\nTherapyModel <- lm(Improvement ~ Sessions + Baseline, data = TherapyData)\nsummary(TherapyModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Improvement ~ Sessions + Baseline, data = TherapyData)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-12.4882  -2.9666  -0.4928   2.5910  26.0396 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 11.77323    5.68723   2.070    0.043 *  \nSessions     1.93638    0.21937   8.827 2.96e-12 ***\nBaseline    -0.02332    0.09016  -0.259    0.797    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.865 on 57 degrees of freedom\nMultiple R-squared:  0.5827,\tAdjusted R-squared:  0.568 \nF-statistic: 39.79 on 2 and 57 DF,  p-value: 1.525e-11\n```\n:::\n:::\n\n\nThat is a good-looking model. Attendance predicts improvement, the coefficient is nowhere near zero, the *p*-value turned up in scientific notation, and the model accounts for 58% of the variance in improvement. Write it up, thank the undergraduates, go home.\n\nNow fit the same model to the same study with participant 60 removed. Not a suspicious subgroup, not a condition, not a wave of attrition. One row out of sixty.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nTherapyModel.60 <- update(TherapyModel, data = TherapyData[-60, ])\n\nround(rbind(\n  Everyone  = c(coef(TherapyModel),    R2 = summary(TherapyModel)$r.squared),\n  Without60 = c(coef(TherapyModel.60), R2 = summary(TherapyModel.60)$r.squared)\n), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          (Intercept) Sessions Baseline     R2\nEveryone      11.7732   1.9364  -0.0233 0.5827\nWithout60      7.4684   1.7110   0.0631 0.6245\n```\n:::\n:::\n\nThree things moved, and none of them is the thing you were watching.\n\nThe baseline coefficient **changed sign**. With everyone in, higher baseline severity predicts slightly less improvement. With one person out, it predicts slightly more. Neither version is significant, which is its own kind of embarrassing: the direction of that effect was never being decided by the other fifty-nine people.\n\nThe intercept stopped being significant, going from $p =$ 0.043 to $p =$ 0.106. If you had a hypothesis about the intercept, you no longer have a result.\n\nAnd $R^2$ went **up**, from 0.583 to 0.625. This surprises people, so it is worth saying plainly: deleting participant 60 took proportionally more out of the unexplained pile than out of the total. The residual standard error fell from 5.86 to 4.63. The model did not get better. It got easier.\n\nNotice what did *not* warn you. Nothing errored. Nothing printed a message. The first model is not missing a step, and no amount of rereading its output would have told you that one row was steering it. R fit exactly what you asked for, with the serene indifference of a vending machine.\n\n*A model cannot tell you that one person wrote its conclusion. That is the job you are about to learn.*\n\n## Advanced Topic: Who Is This For?\n\nIn the [Intro to Regression chapter](Chapter_Intro_to_regression.qmd) we asked five questions about the line: linearity, independence, constant variance, approximately normal residuals, and whether one strange person is steering everything while the others watch. This chapter is those five questions with a magnifying glass. You have just seen question five win.\n\nThis chapter is for graduate students and advanced undergraduates who already know how to fit and interpret a regression model. We now ask a more alarming question: **Should we trust the model we just fit?**\n\nRegression will always give you coefficients if the mathematics permits it. It does not pause to ask whether one participant entered a reaction time of 94 years or whether the residuals resemble a startled squid.\n\n::: {.callout-warning title=\"A Significant Model Can Still Be a Bad Model\"}\nA small *p*-value does not certify linearity, equal residual variance, independence, honest measurement, or sensible causal reasoning. It only answers a narrower question under the model's assumptions.\n:::\n\n## Residuals: What the Model Failed to Explain\n\nFor person $i$,\n\n$$\ne_i = Y_i-\\widehat{Y}_i.\n$$\n\nA residual is the observed outcome minus the model's prediction. Positive residuals mean the person scored above the prediction; negative residuals mean they scored below it.\n\nThe ordinary linear model assumes:\n\n$$\nY_i=\\beta_0+\\beta_1X_{1i}+\\cdots+\\beta_kX_{ki}+\\epsilon_i,\n$$\nwhere the errors have an expected value of zero, are independent, and have approximately constant variance. Normality matters primarily for conventional small-sample inference, not because every raw variable must form a perfect bell.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(\n  fitted(TherapyModel), rstandard(TherapyModel),\n  pch = 19, col = \"#0072B2\",\n  xlab = \"Fitted improvement\",\n  ylab = \"Standardized residual\",\n  main = \"Residuals should not organize a protest\"\n)\nabline(h = 0, lwd = 2)\nabline(h = c(-2, 2), lty = 2, col = \"#D55E00\")\n# pos = 2 puts the label to the LEFT: participant 60 sits against the right\n# edge, so labelling to the right runs the text off the plot.\ntext(fitted(TherapyModel)[60], rstandard(TherapyModel)[60], \"60\", pos = 2)\n```\n\n::: {.cell-output-display}\n![](Chapter_Advanced_Regression_Diagnostics_files/figure-html/residual-fitted-1.png){fig-align='center' fig-alt='Scatterplot with fitted improvement from about 10 to 34 on the x axis and standardized residual from about minus 2.3 to 4.7 on the y axis. A solid horizontal line marks zero and dashed orange lines mark plus and minus 2. Most of the sixty blue points form a shapeless cloud between minus 1.5 and 1.5 with no funnel or curve. One point sits alone in the far upper right, labelled 60, at a standardized residual of about 4.7, more than twice as far from zero as anything else in the plot.' width=672}\n:::\n:::\n\n\nLook for curves, funnels, clusters, and isolated points. A random cloud around zero is comforting. A visible pattern means the model has left information lying on the floor.\n\n::: {.callout-note title=\"Raw Residuals Versus Standardized Residuals\"}\nRaw residuals remain in the outcome's units. Standardized or studentized residuals divide by an estimated residual standard deviation, making unusually large residuals easier to identify. Values beyond roughly $\\pm2$ deserve inspection. That is an investigation threshold, not an automatic deletion command.\n:::\n\n## Linearity\n\nLinear regression assumes the mean outcome is a linear combination of the predictors. If the true relationship bends, a straight line may average over the bend and lie everywhere with great consistency.\n\nPossible responses include transformations, polynomial terms, splines, or a model with a more appropriate link function. The graph should guide the question; repeatedly adding powers until an asterisk appears is polynomial fishing.\n\n## Homoscedasticity\n\n**Homoscedasticity** means that residual spread is roughly constant across fitted values. A funnel shape indicates **heteroscedasticity**: the model predicts some portions of the outcome more precisely than others.\n\nHeteroscedasticity does not automatically bias ordinary least-squares slopes, but it can make conventional standard errors and confidence intervals inaccurate. We can reconsider the outcome scale, use heteroscedasticity-consistent standard errors, or fit a model that explicitly represents changing variance.\n\n## Normality of the Errors\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqqnorm(rstandard(TherapyModel), pch = 19, col = \"#0072B2\",\n       main = \"Q-Q plot of standardized residuals\")\nqqline(rstandard(TherapyModel), col = \"#D55E00\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](Chapter_Advanced_Regression_Diagnostics_files/figure-html/residual-qq-1.png){fig-align='center' fig-alt='Normal Q-Q plot with theoretical quantiles from about minus 2.4 to 2.4 on the x axis and sample quantiles from about minus 2.3 to 4.7 on the y axis, with a straight orange reference line. The middle two thirds of the points sit tightly on the line. Above about the 80th percentile the points drift steadily above it, and one point at the far top right sits at about 4.7 where the line is near 1.9, far away from every other point. The lowest point also falls slightly below the line.' width=624}\n:::\n:::\n\n\nA Q–Q plot compares residual quantiles with those expected under a normal distribution. Mild deviations are ordinary. Severe tail departures may signal outliers, a wrong outcome distribution, or a model that has ignored important structure.\n\n::: {.callout-warning title=\"Do Not Test Normality and Surrender\"}\nWith a large sample, a formal normality test can reject harmless deviations. With a small sample, it may miss serious ones. Inspect the residuals, consider the design, and ask whether the inferential procedure is robust enough for the observed problem.\n:::\n\n## Leverage, Influence, and Cook's Distance\n\nAn observation has high **leverage** when its predictor values are unusual. It is **influential** when removing it meaningfully changes the fitted model. A person can have a large residual without much leverage, or high leverage while sitting obediently on the fitted line.\n\nCook's distance combines residual size and leverage. One common expression is:\n\n$$\nD_i=\n\\frac{e_i^2}{p\\widehat{\\sigma}^2}\n\\frac{h_{ii}}{(1-h_{ii})^2},\n$$\n\nwhere $p$ is the number of fitted coefficients and $h_{ii}$ is leverage.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCookD <- cooks.distance(TherapyModel)\nplot(\n  CookD, type = \"h\", lwd = 2, col = \"#0072B2\",\n  xlab = \"Participant\", ylab = \"Cook's distance\",\n  # headroom so the \"60\" label above the tallest spike is not clipped\n  ylim = c(0, max(CookD) * 1.15),\n  main = \"Which participant is driving the statistical bus?\"\n)\nabline(h = 4 / n, lty = 2, col = \"#D55E00\", lwd = 2)\ntext(60, CookD[60], \"60\", pos = 3)\n```\n\n::: {.cell-output-display}\n![](Chapter_Advanced_Regression_Diagnostics_files/figure-html/influence-plot-1.png){fig-align='center' fig-alt='Spike plot with participant number 1 to 60 on the x axis and Cook\\'s distance from 0 to about 1 on the y axis, with a dashed orange reference line at 4 divided by 60, roughly 0.067. Almost every spike is a stub near zero. One spike at participant 60 towers over the plot at about 0.88, labelled 60. A second spike at participant 26 reaches about 0.20, and a third at participant 40 just clears the dashed line. Everyone else falls below it.' width=672}\n:::\n:::\n\n\nRules such as $D_i>4/N$ are screening devices. They tell us where to look, not whom to throw into the volcano.\n\nNotice that the $4/N$ line flags 3 people here, not one. Participants 26 and 40 are over the line too, and they are fine. Participant 60's Cook's distance is 0.88, which is roughly 4 times the next largest. A screening rule hands you a short list of people to think about. It does not rank them, and it does not tell you which ones changed anything.\n\n### The Sensitivity Refit, Done Properly\n\nThe opening of this chapter refit the model without participant 60 as a stunt, to show you that it mattered. This is the same comparison written the way you would actually report it, with the standard errors and p-values attached, because \"the coefficient moved\" is not a finding until the reader can see how much of that movement is noise.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSideBySide <- cbind(\n  b.all    = coef(TherapyModel),\n  SE.all   = coef(summary(TherapyModel))[, \"Std. Error\"],\n  p.all    = coef(summary(TherapyModel))[, \"Pr(>|t|)\"],\n  b.drop   = coef(TherapyModel.60),\n  SE.drop  = coef(summary(TherapyModel.60))[, \"Std. Error\"],\n  p.drop   = coef(summary(TherapyModel.60))[, \"Pr(>|t|)\"]\n)\n\nround(SideBySide, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              b.all SE.all  p.all b.drop SE.drop p.drop\n(Intercept) 11.7732 5.6872 0.0430 7.4684  4.5491 0.1062\nSessions     1.9364 0.2194 0.0000 1.7110  0.1773 0.0000\nBaseline    -0.0233 0.0902 0.7968 0.0631  0.0727 0.3888\n```\n:::\n:::\n\n\nRead it one row at a time.\n\n**Sessions** is the conclusion of the study, and it survives. The slope drops from 1.94 to 1.71, about a 12% reduction, and stays overwhelmingly significant either way. That is what a robust result looks like: the number moves, because every number moves, and the claim does not.\n\n**Baseline** does not survive, and it never had anything to survive with. Its sign depends entirely on participant 60, and it is nowhere near significant in either model. This is the honest version of a null result: not \"baseline severity does not predict improvement,\" but \"this study could not tell you, and one person was setting the direction.\"\n\nThe rule that follows is short, and it is the whole reason the comparison exists. **Report both.** Put the sensitivity refit in the paper, or in the supplement, and say what changed. Do not run this comparison, notice that one version is friendlier to your hypothesis, and report only that one. That is not a sensitivity analysis. That is shopping with extra steps.\n\n::: {.callout-note title=\"What to Say When the Refit Disagrees With You\"}\n\"Excluding one influential case (Cook's $D =$ 0.88), the attendance slope fell from 1.94 to 1.71 and remained significant, while the baseline coefficient reversed sign and was nonsignificant in both models.\"\n\nOne sentence. It costs you nothing, it is more informative than the result it qualifies, and it is much cheaper than having a reader discover it for you.\n:::\n\n## Multicollinearity\n\nWhen predictors are strongly related, the model struggles to separate their unique slopes. Coefficients may become unstable, standard errors inflate, and signs may change when another predictor enters.\n\nFor predictor $j$, the variance inflation factor is:\n\n$$\nVIF_j=\\frac{1}{1-R_j^2},\n$$\n\nwhere $R_j^2$ comes from predicting $X_j$ with the other predictors. A large VIF means the other predictors nearly reconstruct that predictor.\n\nThat definition tells you how VIF is computed but not why anyone cares. For that, look at where it actually lives, which is inside the standard error of the coefficient:\n\n$$\nSE(b_j)=\n\\underbrace{\\frac{\\widehat\\sigma}{\\sqrt{\\sum_i\\left(X_{ij}-\\overline X_j\\right)^2}}}_{\\text{what you would get if } X_j \\text{ stood alone}}\n\\times\n\\underbrace{\\sqrt{\\frac{1}{1-R_j^2}}}_{\\sqrt{VIF_j}}\n$$\n\nRead the two halves separately, because they answer different questions.\n\nThe **left factor** is the standard error you would earn in a world where $X_j$ were unrelated to every other predictor. It improves in the three ways you would expect: a smaller $\\widehat\\sigma$ (less unexplained noise), a larger sample, or more spread in $X_j$ itself. That last one is worth pausing on, since it is the algebraic reason a restricted range hurts you. If everyone in your study scored between 4 and 6 on the predictor, the sum in that denominator is small and nothing can rescue the standard error.\n\nThe **right factor** is the tax. It is exactly $\\sqrt{VIF_j}$, it is never less than 1, and it is the entire contribution of multicollinearity to your uncertainty. When $R_j^2=0$ the tax is $\\sqrt{1}=1$ and you pay nothing. When $R_j^2=.75$ the tax is $\\sqrt{4}=2$ and your standard error doubles.\n\nSo VIF is not a diagnostic that sits beside the model commenting on it. It is a multiplier already inside every standard error the model printed.\n\nIn R the whole thing is one line, and it is the line you will actually use:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# car (Companion to Applied Regression) supplies vif(), plus most of the\n# regression diagnostics psychologists reach for.\nlibrary(car)\n\nvif(TherapyModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSessions Baseline \n1.013679 1.013679 \n```\n:::\n:::\n\n\nBoth come back at 1.01, which is a polite way of saying nothing is wrong here. Sessions and Baseline correlate at $r =$ -0.12. This is what fine looks like, and it is worth seeing once so that trouble is recognizable by contrast.\n\n### Doing It By Hand, Because It Is Two Regressions\n\n`vif()` is not consulting an oracle. It is running the auxiliary regression named in the definition, taking the $R^2$, and dividing. Here is the whole thing, plus a check that the standard-error formula above is not decoration.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Step 1: predict the predictor from the other predictors.\nAuxModel <- lm(Sessions ~ Baseline, data = TherapyData)\nR2j <- summary(AuxModel)$r.squared\n\n# Step 2: that is it. That is the whole formula.\nc(R2j = R2j, VIF.by.hand = 1 / (1 - R2j), VIF.from.car = unname(vif(TherapyModel)[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         R2j  VIF.by.hand VIF.from.car \n  0.01349464   1.01367923   1.01367923 \n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSigmaHat <- summary(TherapyModel)$sigma\nSSj <- sum((TherapyData$Sessions - mean(TherapyData$Sessions))^2)\n\nStandingAlone <- SigmaHat / sqrt(SSj)\n\nc(\n  if.Sessions.stood.alone = StandingAlone,\n  times.sqrt.VIF          = StandingAlone * sqrt(1 / (1 - R2j)),\n  actual.SE.from.lm       = unname(coef(summary(TherapyModel))[\"Sessions\", \"Std. Error\"])\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nif.Sessions.stood.alone          times.sqrt.VIF       actual.SE.from.lm \n              0.2178867               0.2193719               0.2193719 \n```\n:::\n:::\n\n\nThe second and third numbers agree to every digit R will print, because they are the same quantity computed two ways. The standard error `lm()` reported is the standing-alone standard error multiplied by $\\sqrt{VIF}$, and here that multiplier is 1.007, which rounds to nothing at all.\n\n### The Extreme Case: Two Predictors That Are Secretly One\n\nBefore the interesting failures, look at the failure that cannot hide. Suppose we predict school achievement from the proportion of students on free lunch, and, because a paper told us they are distinct indicators of school poverty, we also enter the proportion on paid lunch.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\nn_schools <- 120\n\nSchoolData <- data.frame(FreeLunch = runif(n_schools, .05, .95))\nSchoolData$PaidLunch <- 1 - SchoolData$FreeLunch          # the whole problem\n\nSchoolData$Achievement <- 70 - 25 * SchoolData$FreeLunch + rnorm(n_schools, 0, 6)\n\ncor(SchoolData$FreeLunch, SchoolData$PaidLunch)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1\n```\n:::\n:::\n\n\nA correlation of exactly $-1$. Every school that is 30% free lunch is 70% paid lunch, necessarily, because the two proportions are the same fact written twice. Now put both in the model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nBothModel <- lm(Achievement ~ FreeLunch + PaidLunch, data = SchoolData)\n\nsummary(BothModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Achievement ~ FreeLunch + PaidLunch, data = SchoolData)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-18.8069  -3.3393   0.3135   3.4791  14.1907 \n\nCoefficients: (1 not defined because of singularities)\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   69.976      1.134   61.69   <2e-16 ***\nFreeLunch    -24.385      2.008  -12.14   <2e-16 ***\nPaidLunch         NA         NA      NA       NA    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.526 on 118 degrees of freedom\nMultiple R-squared:  0.5556,\tAdjusted R-squared:  0.5518 \nF-statistic: 147.5 on 1 and 118 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nRead the line above the coefficient table: **`Coefficients: (1 not defined because of singularities)`**. `PaidLunch` came back `NA`. R did not average the two predictors, or split the credit, or pick the better one. It silently deleted a predictor from your model and carried on.\n\nThat is the correct behavior, and the reason is worth stating precisely. The regression is asked to estimate the effect of raising free lunch *while holding paid lunch constant*, and there is no such thing. There is not one school in the data where free lunch moved and paid lunch did not, so the question has no answer, and no amount of sample size will produce one.\n\nR will even tell you the exact dependency it found:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalias(BothModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nModel :\nAchievement ~ FreeLunch + PaidLunch\n\nComplete :\n          (Intercept) FreeLunch\nPaidLunch  1          -1       \n```\n:::\n:::\n\n\nRead that as an equation: `PaidLunch` equals 1 minus `FreeLunch`. It has reconstructed the definition we used to build the variable.\n\nVIF cannot help here either, and it is honest about why:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvif(BothModel)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `vif.default()`:\n! there are aliased coefficients in the model\n```\n:::\n:::\n\n\n$VIF_j = 1/(1-R_j^2)$ and $R_j^2$ is exactly 1, so the formula is dividing by zero. There is nothing to inflate; the predictor has no unique variance at all.\n\n### Now Enter Them One at a Time\n\nHere is the part that makes this worth showing rather than just warning about. Fit each predictor on its own and put the three models side by side.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nFreeOnly <- lm(Achievement ~ FreeLunch, data = SchoolData)\nPaidOnly <- lm(Achievement ~ PaidLunch, data = SchoolData)\n\nSummarize <- function(Model, term) {\n  c(b  = unname(coef(Model)[term]),\n    SE = coef(summary(Model))[term, \"Std. Error\"],\n    t  = coef(summary(Model))[term, \"t value\"],\n    R2 = summary(Model)$r.squared)\n}\n\nround(rbind(\n  Both.in.FreeLunch = Summarize(BothModel, \"FreeLunch\"),\n  FreeLunch.alone   = Summarize(FreeOnly,  \"FreeLunch\"),\n  PaidLunch.alone   = Summarize(PaidOnly,  \"PaidLunch\")\n), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         b     SE        t     R2\nBoth.in.FreeLunch -24.3847 2.0078 -12.1449 0.5556\nFreeLunch.alone   -24.3847 2.0078 -12.1449 0.5556\nPaidLunch.alone    24.3847 2.0078  12.1449 0.5556\n```\n:::\n:::\n\n\nSeparately, each one is a perfectly respectable predictor. Free lunch predicts achievement going down; paid lunch predicts it going up. Either would sail through review on its own.\n\nBut look at what the three rows share. The standard errors are **identical**. The *t* values are identical in size and differ only in sign. $R^2$ is 0.5556 in all three models, including the one where R threw a predictor away. And the two slopes are the same number with the sign flipped, -24.38 against 24.38.\n\nThey are not two findings. They are one finding, and the direction is a decision you made when you chose which proportion to name.\n\n### The Version That Does Not Warn You\n\nPerfect collinearity is the harmless case, because R stops. Now add a rounding error's worth of noise, so the two variables are merely *almost* the same fact.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\n# Same variable, plus measurement error with a standard deviation of 0.01.\nSchoolData$PaidLunch.Measured <- 1 - SchoolData$FreeLunch + rnorm(n_schools, 0, .01)\n\nNearlyBoth <- lm(Achievement ~ FreeLunch + PaidLunch.Measured, data = SchoolData)\n\nround(coef(summary(NearlyBoth)), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                   Estimate Std. Error t value Pr(>|t|)\n(Intercept)        140.8473    55.2712  2.5483   0.0121\nFreeLunch          -95.2407    55.2836 -1.7228   0.0876\nPaidLunch.Measured -71.0554    55.4028 -1.2825   0.2022\n```\n:::\n\n```{.r .cell-code}\nvif(NearlyBoth)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         FreeLunch PaidLunch.Measured \n           762.284            762.284 \n```\n:::\n:::\n\n\nNothing errored. Nothing was set to `NA`. No message appeared above the table. And the model is now a disaster:\n\n- The free-lunch slope was -24.4 on its own. It is now -95.2.\n- **Neither predictor is significant.** Free lunch sits at $p =$ 0.088 and paid lunch at $p =$ 0.202, in data where the effect is real, enormous, and was significant a moment ago.\n- The VIFs are about 762, so the standard errors are inflated by a factor of roughly 28.\n- $R^2$ went from 0.5556 to 0.5617. The second predictor bought essentially nothing and cost you the first one.\n\n**This is what \"they will eat each other\" looks like in a coefficient table.** Two predictors carrying the same information cannot both be credited for it, so each is left holding whatever the other did not explain, which is nearly nothing. The variance is still there. The model simply cannot say whose it is.\n\nA student who ran only this model would conclude that school poverty does not predict achievement. The real effect they missed is about 24 achievement points between a school where nobody qualifies for free lunch and one where everybody does.\n\n### What Trouble Actually Looks Like Across the Range\n\nThe two cases above are the ends of a continuum. Here is the middle, using the same true effect measured four times. `X1` and `Y` are identical in every row; the only thing that changes is how strongly the *other* predictor correlates with `X1`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCollinearDemo <- function(r) {\n  set.seed(343)\n  X1 <- rnorm(200)\n  X2 <- r * X1 + sqrt(1 - r^2) * rnorm(200)\n  Y  <- 2 * X1 + rnorm(200, 0, 4)\n\n  Model <- lm(Y ~ X1 + X2)\n  c(\n    r     = r,\n    VIF   = unname(vif(Model)[1]),\n    SE.X1 = coef(summary(Model))[\"X1\", \"Std. Error\"],\n    p.X1  = coef(summary(Model))[\"X1\", \"Pr(>|t|)\"]\n  )\n}\n\nCollinearTable <- t(sapply(c(0, .5, .9, .99), CollinearDemo))\n\nround(CollinearTable, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        r     VIF  SE.X1   p.X1\n[1,] 0.00  1.0021 0.3344 0.0000\n[2,] 0.50  1.2863 0.3788 0.0001\n[3,] 0.90  5.1322 0.7567 0.0391\n[4,] 0.99 50.2847 2.3684 0.4255\n```\n:::\n:::\n\n\nNothing about the relationship between `X1` and `Y` changed down that table. The effect is genuinely there in all four rows, built by the same line of code from the same numbers. What changed is our ability to see it: at $r = .9$ the effect scrapes past significance at $p =$ 0.039, and at $r = .99$ it is gone entirely, at $p =$ 0.43.\n\nNothing mysterious is happening, and you already have the formula that predicts it. The $\\sqrt{VIF_j}$ tax is doing all of the work, and the table lets you check it.\n\nAt $r = .9$ the VIF is 5.13, so the formula says the standard error should be $\\sqrt{5.13} =$ 2.27 times the standing-alone version. The table says `SE.X1` climbed from 0.334 to 0.757, a ratio of 2.26. Prediction and observation, agreeing to two decimals, on a table generated before anyone mentioned the formula.\n\nThe last row is the useful warning. A VIF of 50 is a $\\sqrt{}$ tax of about 7.1, which means that predictor is being measured with roughly 7.1 times less precision than the design nominally bought. The effect is still exactly 2. You just paid your entire sample size to the other predictor.\n\nThis is also the cost that the [Multiple Regression: Statistical Control chapter](Chapter_Multiple_Regression_Control.qmd) promised you would meet later, where the controlled slope came with a slightly larger standard error than the uncontrolled one. This is later, and this is the meter.\n\n::: {.callout-warning title=\"The 5-and-10 Rule Is Folklore, Not Divine Law\"}\nYou will read that VIF above 5 is concerning and above 10 is serious. Nobody derived those numbers. They are round, they are memorable, and they have no distributional justification.\n\nThe question that has an answer is narrower: **is the standard error on the coefficient I care about small enough to answer my question?** A VIF of 12 on a nuisance covariate you will never interpret is not a problem. A VIF of 3 on your primary predictor, in a study that was already underpowered, might be fatal. Look at the interval, not the threshold.\n:::\n\nMulticollinearity is also not a data-cleaning problem, but it can be a theory problem.\n\nFirst, dropping one of two correlated predictors does make the VIF fall, but it changes the model into a different model that answers a different question, and the slope you are left with is no longer controlled for the thing you dropped. You have not fixed the collinearity. You have stopped asking the question that produced it.\n\nSecond, and this is the one that actually happens: suppose you have two predictors, one is \"free student lunch\" and the second is whether the student is part of a school voucher program. You might enter both into the model cause some paper you read said they are independent and different predictors of SES. Well, the data say otherwise, cause of who the sample you collected happens to be. The theory may say X, but the data say Y. You cannot keep them both if they are the focal predictors, since they will eat each other, exactly as free lunch and paid lunch did above. If they were just covariates you needed to control for, that is okay.\n\nMulticollinearity is not repaired by staring harder at the output. Possible solutions include improving the design, collecting more informative cases, combining redundant measures when theory supports it, or narrowing the question.\n\n## Independence and Clustering\n\nOrdinary regression assumes residuals are independent. Repeated observations from one person, students within classrooms, siblings within families, and responses to the same stimulus are not independent simply because the spreadsheet gave them separate rows.\n\nIf residuals share a source, use a design-aware method such as a mixed-effects model. The [mixed regression chapter](Chapter_Mixed_Regression.qmd) does exactly that: it tells the model which rows belong to the same person, instead of letting it believe it met a room full of strangers.\n\nThis is the one assumption on the list that a diagnostic plot will not rescue you from. Non-independence is a fact about how the data were collected, and you know it before you fit anything. No residual plot reliably reveals clustering you have not told the model about, and no robust standard error repairs it.\n\n## A Diagnostic Workflow\n\n1. Plot the raw data.\n2. Fit the theoretically justified model.\n3. Plot residuals against fitted values.\n4. Inspect Q–Q behavior and residual tails.\n5. Examine leverage and influence.\n6. Check predictor redundancy.\n7. Ask whether observations are independent.\n8. Investigate suspicious cases against the original records.\n9. Report consequential problems and sensitivity analyses.\n\n::: {.callout-important title=\"Deleting the Problem Is Not Diagnosing the Problem\"}\nNever remove an observation merely because it weakens the hypothesis. Correct impossible values, explain defensible exclusions, and compare conclusions with and without influential cases. If one person reverses the entire result, that instability is part of the result.\n:::\n\n## The Mathematics Under the Diagnostic Pictures\n\nOrdinary least squares produces fitted values through the **hat matrix**:\n\n$$\n\\widehat{\\mathbf y}=\\mathbf H\\mathbf y,\n\\qquad\n\\mathbf H=\\mathbf X(\\mathbf X'\\mathbf X)^{-1}\\mathbf X'.\n$$\n\nThe diagonal value $h_{ii}$ is observation $i$'s leverage. Leverage comes from an unusual predictor pattern, not an unusual outcome by itself. A point can have high leverage and still sit obediently on the regression line. It becomes influential when its leverage combines with a meaningful residual.\n\nStudentized residuals scale each residual by an estimate of its own uncertainty. Cook's distance then asks how much the fitted model would change if observation $i$ vanished:\n\n$$\nD_i \\propto\n\\frac{r_i^2}{p}\n\\frac{h_{ii}}{1-h_{ii}}.\n$$\n\nThe exact cutoffs are screening rules, not automatic deletion warrants. Inspect the case, verify the data, refit with and without it, and explain what changed.\n\n## When the Variance Changes\n\nHeteroscedasticity does not usually bias the OLS slope when the mean model is correct, but it can damage the ordinary standard errors. Possible responses include modeling the variance, transforming the outcome when scientifically sensible, using a model family that matches the outcome, or reporting heteroscedasticity-consistent standard errors. The picture tells you a problem exists; theory tells you which response makes sense.\n\nThat last option you will see some papers use has multiple names: \"robust standard errors\" and \"the sandwich estimator\". However, most people using them could not say what is being made robust to what, so here is the machinery.\n\n### Where the Ordinary Standard Errors Come From\n\nEvery standard error `lm()` printed came out of one matrix:\n\n$$\n\\widehat{Var}(\\mathbf b)=\\widehat\\sigma^{2}\\left(\\mathbf X'\\mathbf X\\right)^{-1}.\n$$\n\nTake the square roots of its diagonal and you have the `Std. Error` column. Notice the single $\\widehat\\sigma^{2}$ standing outside the matrix. That is the whole homoscedasticity assumption, written down: **one** error variance, the same for every observation, so it factors out and one number can be estimated by pooling all the residuals.\n\nThe general expression, which does not assume that, is:\n\n$$\nVar(\\mathbf b)=\n\\underbrace{\\left(\\mathbf X'\\mathbf X\\right)^{-1}}_{\\text{bread}}\n\\underbrace{\\left(\\mathbf X'\\boldsymbol\\Omega\\mathbf X\\right)}_{\\text{filling}}\n\\underbrace{\\left(\\mathbf X'\\mathbf X\\right)^{-1}}_{\\text{bread}}\n$$\n\nwhere $\\boldsymbol\\Omega$ is the diagonal matrix of individual error variances $\\sigma_i^2$. **That is the sandwich, and the name is descriptive rather than whimsical:** the same bread on both sides, something else in the middle.\n\nThe two formulas are not rivals. Set every $\\sigma_i^2$ equal to a common $\\sigma^2$, so $\\boldsymbol\\Omega=\\sigma^2\\mathbf I$, and the filling collapses to $\\sigma^2\\mathbf X'\\mathbf X$, which cancels one of the breads and leaves $\\sigma^2(\\mathbf X'\\mathbf X)^{-1}$ exactly. **The ordinary standard errors are the sandwich, under the assumption that every observation is equally noisy.** Robust standard errors are not a different theory. They are the same expression with the assumption removed.\n\n### Estimating the Filling\n\nThe problem is that $\\boldsymbol\\Omega$ contains one variance per person and we have one observation per person, so it cannot be estimated the usual way. White's insight was that we never need $\\boldsymbol\\Omega$ itself, only the sandwiched product $\\mathbf X'\\boldsymbol\\Omega\\mathbf X$, and that squared residuals are good enough for that job even though $e_i^2$ is a hopeless estimate of any individual $\\sigma_i^2$ [@white1980]. The errors average out inside the product.\n\nThe `HC` family is a set of choices about what exactly to put on that diagonal:\n\n| Type | Diagonal entry | What it is doing |\n|---|---|---|\n| `HC0` | $e_i^2$ | White's original. Biased low in small samples. |\n| `HC1` | $\\frac{n}{n-p}\\,e_i^2$ | HC0 with the degrees-of-freedom correction `lm()` already applies. |\n| `HC2` | $\\dfrac{e_i^2}{1-h_{ii}}$ | Corrects for the fact that high-leverage points have artificially small residuals. |\n| `HC3` | $\\dfrac{e_i^2}{(1-h_{ii})^2}$ | Approximates leaving each case out and refitting. The conservative default. |\n\n**That $h_{ii}$ is the same leverage from the hat matrix**, three sections ago. This is the point where the two halves of the chapter meet, and it explains something that otherwise looks like a coincidence. A high-leverage point pulls the line toward itself, which shrinks its own residual and makes it look better behaved than it is. HC2 and HC3 divide that shrinkage back out. HC3 divides by it twice, which is why it is the most conservative of the four and why it reacts hardest to influential cases.\n\nLong and Ervin tested these on thousands of simulated small samples and recommend **HC3 as the default whenever $n$ is below about 250**, which is most of psychology [@longervin2000]. Use HC3 unless you have a specific reason not to.\n\n### Building It Yourself\n\nThree lines of matrix algebra, and no package:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nX <- model.matrix(TherapyModel)   # the design matrix, intercept column included\ne <- residuals(TherapyModel)\nh <- hatvalues(TherapyModel)      # the same leverages as before\n\nBread <- solve(t(X) %*% X)\nFilling <- t(X) %*% diag(e^2 / (1 - h)^2) %*% X   # HC3\n\nHC3.by.hand <- Bread %*% Filling %*% Bread\n\nsqrt(diag(HC3.by.hand))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)    Sessions    Baseline \n  7.5973832   0.2895539   0.1306439 \n```\n:::\n:::\n\n\nNow the package version:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# sandwich: robust and clustered covariance matrices.\n# lmtest: re-tests a fitted model against any covariance matrix you hand it.\nlibrary(sandwich)\nlibrary(lmtest)\n\ncoeftest(TherapyModel, vcov = vcovHC(TherapyModel, type = \"HC3\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nt test of coefficients:\n\n            Estimate Std. Error t value  Pr(>|t|)    \n(Intercept) 11.77323    7.59738  1.5496    0.1268    \nSessions     1.93638    0.28955  6.6875 1.054e-08 ***\nBaseline    -0.02332    0.13064 -0.1785    0.8590    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nIdentical, which is the point of showing both. `vcovHC()` returns the covariance matrix, and `coeftest()` takes your model plus that matrix and re-runs the *t*-tests with it. They are two separate jobs from two separate packages, which is why the call looks the way it does.\n\n**The estimates are untouched, to the last decimal.** Nothing was refit. The slope of `Sessions` is the same number it always was, because the sandwich changes only the second formula, the one about uncertainty. The standard error rises from 0.22 to 0.29, so *t* falls from 8.83 to about 6.69. The conclusion does not change, which is the usual outcome and is not a reason to skip it.\n\nYou can watch the ladder climb, too:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsapply(c(\"const\", \"HC0\", \"HC1\", \"HC2\", \"HC3\"), function(type) {\n  sqrt(diag(vcovHC(TherapyModel, type = type)))\n}) |> round(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             const    HC0    HC1    HC2    HC3\n(Intercept) 5.6872 6.8635 7.0418 7.2201 7.5974\nSessions    0.2194 0.2627 0.2695 0.2757 0.2896\nBaseline    0.0902 0.1177 0.1207 0.1240 0.1306\n```\n:::\n:::\n\n\n`const` is the classical assumption, and it is the smallest in every row. The four HC variants increase in the order the table above predicts, because each one leans a little harder on the leverage correction.\n\n::: {.callout-note title=\"Be Honest About What the Sandwich Is Reacting To\"}\nThis dataset is not actually heteroscedastic. So why did the standard errors grow? Participant 60, and now you have the formula to see exactly how.\n\nThe HC3 filling weights each observation by $e_i^2/(1-h_{ii})^2$. Participant 60 has a residual of about 26 and a leverage of 0.107, against an average leverage of 0.05. Squaring a residual that large is most of it; the leverage correction then multiplies that by a further 1.25.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nHC3weights <- residuals(TherapyModel)^2 / (1 - hatvalues(TherapyModel))^2\n\nround(c(\n  share.participant.60 = unname(HC3weights[60] / sum(HC3weights)),\n  share.next.largest   = unname(sort(HC3weights, decreasing = TRUE)[2] / sum(HC3weights)),\n  share.if.all.equal   = 1 / length(HC3weights)\n), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nshare.participant.60   share.next.largest   share.if.all.equal \n               0.370                0.085                0.017 \n```\n:::\n:::\n\n\n**One row out of sixty supplies 37% of the filling.** If everyone contributed equally each would supply about 1.7%. Refit without participant 60 and the effect vanishes: the HC3 and ordinary attendance standard errors then land within 1% of each other.\n\nThe lesson is not that the sandwich lied. It is that \"my robust standard errors are much larger than my ordinary ones\" is itself a diagnostic finding, and the thing it most often points at is influence rather than spread. Go look at the case before you congratulate yourself for being rigorous.\n:::\n\nFinally, a shortcut worth knowing about now that you have built these plots by hand. `performance::check_model(TherapyModel)` produces most of this chapter's diagnostics as one annotated panel, with reference bands showing what the plots should look like when nothing is wrong. Use it. It is genuinely good, and it is much faster than what we just did.\n\nThe hand-built versions still teach better, for the reason this whole chapter exists: a bundled panel tells you which plot looks unusual, and you still have to be the person who decides whether that matters, checks the case against the original records, and reports what changed. The software is obedient. You still have to be the adult in the room.\n\n## The Four Packages, and Where the Real Derivations Live\n\nThis chapter used four packages, and it is worth knowing what each is for, because they are not interchangeable and their names do not tell you much.\n\n| Package | What it does here | Where it came from |\n|---|---|---|\n| **`car`** | `vif()`, and most of the regression diagnostics psychologists use | Companion to Fox and Weisberg's regression textbook [@fox2019] |\n| **`sandwich`** | `vcovHC()`, the robust covariance matrix itself | Zeileis's HC and HAC implementation [@zeileis2004] |\n| **`lmtest`** | `coeftest()`, which re-tests a fitted model against any covariance matrix you hand it | Zeileis and Hothorn's diagnostic-checking toolkit [@zeileis2002] |\n| **`performance`** | `check_model()`, the all-in-one diagnostic panel | Part of the easystats project [@ludecke2021] |\n\nNote the division of labor between `sandwich` and `lmtest`, since it explains a call that otherwise looks fussy. `sandwich` *computes covariance matrices* and knows nothing about hypothesis tests. `lmtest` *runs tests* and does not care where the covariance matrix came from. That is why the robust *t*-test needs one function from each, and it is also why the same `vcovHC()` result can be handed to `confint()`, to `car::linearHypothesis()`, and to most other things that accept a `vcov` argument.\n\n::: {.callout-tip title=\"Every Package Is Carrying Its Own Bibliography\"}\nEverything in this chapter has a proper derivation somewhere, and R will tell you where. Run `citation(\"sandwich\")` and you get the three papers the package implements, formatted and ready to paste. This works for **any** installed package.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncitation(\"sandwich\")\nvignette(package = \"sandwich\")          # list what is bundled\nvignette(\"sandwich\")                    # open the HC and HAC paper\n```\n:::\n\n\nThe `sandwich` package ships the full Zeileis (2004) paper as a vignette, so the actual derivation of every `HC` type in that table is sitting on your hard drive right now. `lmtest` ships its own. This is not documentation in the \"list of arguments\" sense; these are peer-reviewed journal articles that happen to be installed alongside the code.\n\nTwo habits follow. **Cite the packages you analyze with**, since somebody wrote and maintains them for free and citation is the only currency involved. And when you want the argument behind a method rather than the syntax, look in the package before you look on the internet. The derivation for this chapter's robust standard errors is `vignette(\"sandwich\")`, and it is better than anything a search will hand you.\n:::\n\n## The Short Story\n\n- Diagnostics ask two questions: do the model's leftovers behave as assumed, and is a small number of observations writing the conclusion?\n- **Leverage is not influence.** Leverage is an unusual predictor pattern; influence is when removing the case moves the fit. A point needs both to matter.\n- **Screening thresholds are for finding cases, not deleting them.** $D_i > 4/N$ flagged three people here and only one of them changed anything.\n- **Refit without the influential case and report both models.** If one person reverses the result, that instability *is* the result. Reporting only the friendlier version is shopping with extra steps.\n- **A VIF is a precision meter, not a pass/fail test.** $\\sqrt{VIF}$ is how much your standard error was inflated; the 5-and-10 rule is folklore.\n- **Independence is a design fact, not a residual pattern you can patch.** Clustered data needs a design-aware model, not a robust standard error and some optimism.\n- A significant coefficient is not a certificate. It is one number from a model that has not yet been checked.\n",
    "supporting": [
      "Chapter_Advanced_Regression_Diagnostics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}