{
  "hash": "97fe431a53b90829bc81a5870f97a622",
  "result": {
    "markdown": "---\ntitle: \"Linear Regression\"\ngeometry: margin=.5in\nfontsize: 10pt\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n---\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Introduction to Regression\n\nMany psychological studies ask: how does X *predict* Y? How does ice cream (IV) predict happiness (DV)?\n\nUnlike the t-test (which compares group averages), regression looks at the relationship between **two continuous variables**. *Predicting* just means making an educated guess — if I know how much ice cream you ate, I can guess how happy you are. The guess won't be perfect, but it should be reasonably close.\n\nRegression tells us **how close those guesses tend to be**.\n\nRegression predicts. It does not automatically explain causes. If people who eat more ice cream report greater happiness, ice cream may help, happier people may seek ice cream, hot weather may increase both, or the entire pattern may be driven by one billionaire buying all the pistachio. Design and theory decide which causal stories remain plausible.\n\n**Note**: Regression assumes interval or ratio scale variables. In practice, psychologists use Likert scales all the time anyway.\n\n### The Experiment\n\nI bought several tubs of vanilla ice cream, scooped out different amounts, and handed them to students. After eating, they rated their happiness on a 0–10 \"feelings thermometer.\" Nobody got zero scoops, but some got barely a teaspoon.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Intro_to_regression_files/figure-pdf/simulate-1.pdf){fig-align='center'}\n:::\n:::\n\n\n\n### Why not just use correlation?\n\nYou can — and correlation is often the first step. But correlation only handles **two variables at a time**. Regression lets us add more predictors: ice cream *plus* hot fudge *plus* cookie dough. In other words, regression scales up in ways correlation can't.\n\nHere's the correlation:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(apa)\napa(cor.test(dat$Scoops, dat$Happiness))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"*r*(78) = .60, *p* < .001\"\n```\n:::\n:::\n\n\n\nStrong positive correlation, as expected!\n\n## Regression Theory\n\nCorrelation and regression describe the **same linear relationship** — just differently.\n\n- **Simple linear regression** = 1 DV and 1 IV. The relationship is a straight line representing the **expected mean of Y** for each value of X.\n- **Multiple regression** = 1 DV and 2+ IVs. (Coming later.)\n\n### The Regression Equation\n\nYou probably remember from middle school: $y = Mx + b$\n\nThe modern version:\n\n$$Y = B_0 + B_1X + e$$\n\nWhere:\n\n- $Y$ = predicted value\n- $B_1$ = slope (effect of X)\n- $B_0$ = intercept\n- $e$ = residual (observed − predicted)\n\n## The Ice Cream Model\n\nWe fit regression models with `lm()` (linear model). Formula structure: **DV ~ IV**.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nHappy.Model.1 <- lm(Happiness ~ Scoops, data = dat)\nsummary(Happy.Model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ Scoops, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.1621 -0.9242  0.0332  1.0608  3.3565 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.9799     0.3863   7.715 3.35e-11 ***\nScoops        0.7524     0.1127   6.675 3.25e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.681 on 78 degrees of freedom\nMultiple R-squared:  0.3636,\tAdjusted R-squared:  0.3554 \nF-statistic: 44.56 on 1 and 78 DF,  p-value: 3.246e-09\n```\n:::\n:::\n\n\n\n### Intercept\n\nThe intercept is the predicted happiness **when ice cream = 0**.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrange(dat$Scoops)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.02927577 5.88743768\n```\n:::\n:::\n\n\n\nNobody had zero scoops, so we can't actually interpret this directly. **Never predict outside the range of your data.** (We can fix this by centering X — more on that later.)\n\n### Slope\n\nThe slope is 0.7524359. For each additional scoop, happiness changes by that amount.\n\n### Making a prediction\n\nThe equation: $Y = B_0 + B_1X$\n\nWhat's the predicted happiness for someone who eats **5 scoops**?\n\n- $Y = 2.98 + (0.752 \\times 5)$\n- $Y = 6.742$\n\n## Predicted Values and Residuals\n\nThe line gives one predicted happiness score for every amount of ice cream. Real people do not sit perfectly on that line because humans are noisy, stubborn, and occasionally having a terrible day for reasons unrelated to dessert.\n\nA **residual** is the distance between the observed score and the model's prediction:\n\n$$\ne_i=Y_i-\\widehat{Y}_i.\n$$\n\n- A positive residual means the person was happier than the model predicted.\n- A negative residual means the person was less happy than the model predicted.\n- A residual of zero means the prediction was exactly right, which is suspiciously cooperative behavior from a human.\n\nR stores both pieces inside the fitted model:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat$Predicted <- fitted(Happy.Model.1)\ndat$Residual <- residuals(Happy.Model.1)\n\nhead(dat[c(\"Scoops\", \"Happiness\", \"Predicted\", \"Residual\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Scoops Happiness Predicted   Residual\n1 0.4874424  4.689709  3.346669  1.3430399\n2 2.7996025  3.676425  5.086421 -1.4099958\n3 4.1977287  7.669921  6.138422  1.5314991\n4 4.7945917  6.331497  6.587523 -0.2560254\n5 3.3393869  4.690570  5.492574 -0.8020041\n6 5.2990277  7.685625  6.967079  0.7185465\n```\n:::\n\n```{.r .cell-code}\nmean(dat$Residual)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.283102e-17\n```\n:::\n:::\n\n\n\nThe residuals have a mean of approximately zero because ordinary least squares balances the line through the data. Positive and negative mistakes cancel out.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dat, aes(x = Scoops, y = Happiness)) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"gray45\") +\n  geom_segment(\n    aes(xend = Scoops, yend = Predicted, color = Residual),\n    linewidth = 0.7\n  ) +\n  geom_point(aes(color = Residual), size = 2.5) +\n  geom_point(aes(y = Predicted), shape = 1, size = 2.5) +\n  scale_color_gradient2(low = \"#0072B2\", mid = \"white\", high = \"#D55E00\") +\n  labs(\n    title = \"Residuals Are the Model's Vertical Mistakes\",\n    x = \"Scoops of Ice Cream\",\n    y = \"Happiness\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Chapter_Intro_to_regression_files/figure-pdf/regression-residual-picture-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nThe filled points are observed happiness. The hollow points are predicted happiness. Each vertical segment is one residual. This is the error the model did not explain.\n\n## The Assumptions: What Could Make the Line Lie?\n\nRegression assumptions are claims about the errors left after fitting the line. They are not personality tests that the raw variables must pass before R permits them into the building.\n\nFor now, focus on five questions:\n\n1. **Linearity:** Is a straight line a reasonable summary of the average relationship?\n2. **Independence:** Are the residuals from different observations reasonably independent?\n3. **Constant variance:** Is the vertical spread of residuals roughly similar across fitted values?\n4. **Approximately normal residuals:** Are the residuals reasonably bell-shaped, especially for small-sample tests and intervals?\n5. **Influential observations:** Is one strange person steering the entire line while everyone else watches?\n\n### Residuals Versus Fitted Values\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(\n  fitted(Happy.Model.1),\n  residuals(Happy.Model.1),\n  xlab = \"Fitted happiness\",\n  ylab = \"Residual\",\n  pch = 19,\n  col = grDevices::adjustcolor(\"#1F4E79\", alpha.f = 0.55)\n)\nabline(h = 0, lty = 2, col = \"#D55E00\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](Chapter_Intro_to_regression_files/figure-pdf/regression-residual-fitted-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nWe want a fairly boring cloud centered around zero. A curve suggests the straight-line model missed a nonlinear pattern. A funnel suggests **heterogeneity of variance**, also called **heteroscedasticity**: the model's errors are much more variable for some predicted values than for others.\n\nWhy care? Ordinary regression calculates standard errors as if the residual variance is reasonably constant. Strong heteroscedasticity can make those standard errors and confidence intervals inaccurate. It can also reveal something psychologically interesting. Perhaps ice cream affects people similarly at low doses but produces wildly different reactions after the fourth scoop. Some people achieve joy. Others remember lactose intolerance.\n\n::: {.callout-warning title=\"Heterogeneity May Be a Clue, Not Merely a Violation\"}\nChanging residual spread can mean the uncertainty differs across people or conditions. Do not immediately transform the outcome until the graph stops complaining. First ask what process could create the pattern.\n:::\n\n### The Q-Q Plot\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqqnorm(residuals(Happy.Model.1), pch = 19, col = \"#1F4E79\")\nqqline(residuals(Happy.Model.1), col = \"#D55E00\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](Chapter_Intro_to_regression_files/figure-pdf/regression-qq-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nA **Q-Q plot** compares the ordered residuals with values expected from a normal distribution. Points reasonably near the line are fine. Severe curves, separated tail points, or one observation escaping toward Canada deserve investigation. Minor imperfection is normal because the data were collected from humans, not manufactured by a normal-distribution factory.\n\nR can produce four standard diagnostic plots at once:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(Happy.Model.1)\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![](Chapter_Intro_to_regression_files/figure-pdf/regression-four-diagnostics-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nThe first two are the residual-versus-fitted and Q-Q plots we just learned. The other two help identify unequal spread and influential observations. You do not need to master them yet. The advanced diagnostics chapter returns with more detail and several additional ways for data to misbehave.\n\n## Residual Variance and $R^2$\n\nBefore using ice cream to predict happiness, our best simple guess for everyone was the mean. The total variance describes how far scores spread around that mean. After fitting the model, residual variance describes how far scores spread around the regression line.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nTotalVariance <- var(dat$Happiness)\nResidualVariance <- var(residuals(Happy.Model.1))\n\nc(TotalVariance = TotalVariance,\n  ResidualVariance = ResidualVariance,\n  R_squared_from_variance = 1 - ResidualVariance / TotalVariance,\n  R_squared_from_model = summary(Happy.Model.1)$r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          TotalVariance        ResidualVariance R_squared_from_variance \n              4.3817090               2.7886391               0.3635727 \n   R_squared_from_model \n              0.3635727 \n```\n:::\n:::\n\n\n\n$R^2$ describes the proportion of observed outcome variance explained by the fitted model. It is an effect-size measure for the model, not proof that the model is causal, correct, or ready to be tattooed onto your arm.\n\n## Relationship to Correlation\n\nWhy did we start with correlation if regression is so great? To show they're the same thing, just scaled differently. Run a regression on **standardized** variables:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat$Happiness.z <- scale(dat$Happiness)\ndat$Scoops.z    <- scale(dat$Scoops)\n\nstd.reg <- lm(Happiness.z ~ Scoops.z, data = dat)\nsummary(std.reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness.z ~ Scoops.z, data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.46608 -0.44152  0.01588  0.50675  1.60349 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2.037e-16  8.976e-02   0.000        1    \nScoops.z     6.030e-01  9.033e-02   6.675 3.25e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.8029 on 78 degrees of freedom\nMultiple R-squared:  0.3636,\tAdjusted R-squared:  0.3554 \nF-statistic: 44.56 on 1 and 78 DF,  p-value: 3.246e-09\n```\n:::\n:::\n\n\n\n### What didn't change?\n\nThe **t-statistic and p-value** for the slope. These don't change with any linear rescaling, so you can transform or rescale variables whenever you want without affecting statistical significance.\n\n### What changed?\n\n**The intercept** — it's now **zero**. When all variables are standardized (mean = 0), the regression line must pass through [0, 0]. And the slope changed numerically:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprint(summary(std.reg), digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness.z ~ Scoops.z, data = dat)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-2.466080 -0.441520  0.015876  0.506753  1.603487 \n\nCoefficients:\n                Estimate   Std. Error t value   Pr(>|t|)    \n(Intercept) -2.03715e-16  8.97626e-02 0.00000          1    \nScoops.z     6.02970e-01  9.03290e-02 6.67527 3.2461e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.802862 on 78 degrees of freedom\nMultiple R-squared:  0.363573,\tAdjusted R-squared:  0.355413 \nF-statistic: 44.5592 on 1 and 78 DF,  p-value: 3.24612e-09\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(dat$Happiness, dat$Scoops)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  dat$Happiness and dat$Scoops\nt = 6.6753, df = 78, p-value = 3.246e-09\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.4417814 0.7264454\nsample estimates:\n      cor \n0.6029699 \n```\n:::\n:::\n\n\n\nThe standardized slope equals the correlation. Not a coincidence.\n\nWhen everything is standardized, one unit = one SD. So the correlation tells us: every time X increases by 1 SD, Y increases by $r$ SDs. Standardized regression slopes are called **beta weights ($\\beta$)**.\n\n### Converting slope back to raw units\n\n$$B_1 = r \\frac{sd_y}{sd_x} = \\frac{Cov(x,y)}{Var(x)}$$\n\nYour slope is just the correlation times the ratio of SDs. Makes sense — slope is rise over run:\n\n- Double Y → twice as much rise → $B_1$ doubles\n- Double X → twice as much run → $B_1$ is cut in half\n\n### What about the intercept?\n\nOnce you know $B_1$, you know the angle of the line. But the line must also pass through **[mean(X), mean(Y)]**:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(dat$Scoops)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.993878\n```\n:::\n\n```{.r .cell-code}\nmean(dat$Happiness)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.232601\n```\n:::\n:::\n\n\n\n$$Mean(Y) = B_0 + B_1 \\times Mean(X)$$\n\nSolve for $B_0$ and you're done.\n\n## The Short Story\n\n- Simple linear regression predicts a quantitative outcome from one predictor.\n- The intercept is the predicted outcome when $X=0$.\n- The slope is the expected change in $Y$ for a one-unit increase in $X$.\n- Residuals are observed outcomes minus predicted outcomes: the model's leftovers.\n- $R^2$ is the proportion of observed outcome variance explained by the fitted linear model.\n- With one predictor, the standardized slope equals Pearson's $r$.\n- Prediction is not causation. A straight line cannot randomize participants, control confounds, or stop Reviewer 2 from asking whether heat explains the ice cream.\n\n::: {.callout-important title=\"A Slope Always Has Units\"}\nThe slope is the expected change in $Y$ for a one-unit increase in $X$. Before deciding that it is large, small, heroic, or pathetic, say what one unit of $X$ and one unit of $Y$ actually mean.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}