{
  "hash": "968f53499c8f8e499df99a0712694362",
  "result": {
    "markdown": "---\ntitle: \"P-Values and Multiple Comparisons\"\n---\n\n\n\n\n::: {.callout-warning}\n## Advanced topic\n\nThis chapter assumes that you already understand null hypotheses, Type I and Type II errors, power, effect sizes, and confidence intervals. Undergraduates may continue, but should bring snacks and a responsible graduate student. Graduate students should bring two snacks because they are expected to pretend this is easy.\n:::\n\n## First, Let Us Put a Dead Fish in an MRI\n\nBennett and colleagues placed a mature Atlantic salmon in an fMRI scanner and showed it photographs of people in social situations. The salmon was asked to decide what emotion each person was experiencing. There was a slight methodological complication: **the salmon was dead** [@bennett2010].\n\nThe researchers ran tens of thousands of voxel-by-voxel tests. With an uncorrected threshold of $p < .001$, they found apparently active voxels in the salmon's brain cavity and spinal column. After proper familywise-error and false-discovery-rate corrections, the salmon's social-cognitive abilities vanished. Even relaxed corrected thresholds found nothing, which is generally what we hope to discover about the thoughts of a dead fish.\n\nIf Atlantic salmon become difficult to recruit, Alex can substitute for the fish because he is approximately as brain-dead. The major design problem is that Alex may twitch, complain, demand cookies, and ask whether the scan counts toward tenure.\n\nThe study was deliberately absurd, but the statistical problem was real. If you conduct enough tests, fickle chance receives enough opportunities to manufacture something exciting. A tiny *p*-value attached to one selected result does not tell us how many other tests were run before that result crawled out of the computer wearing a crown.\n\nBefore we control many *p*-values, however, we should establish what one *p*-value means. This seems obvious. It is not. Researchers have spent nearly a century proving that they can misunderstand a definition with remarkable consistency.\n\n## What a P-Value Actually Is\n\nA *p*-value answers this conditional question:\n\n> **Assuming the null hypothesis and the statistical model are correct, how probable are results at least as incompatible with the null hypothesis as the result we observed?**\n\nIn shorthand:\n\n$$\np = P(\\text{data this extreme or more extreme} \\mid H_0, \\text{model})\n$$\n\nSmall *p*-values say that the observed result does not sit comfortably inside the null model. They do not identify which assumption is wrong. Perhaps the null hypothesis is a poor description. Perhaps independence failed, the model was misspecified, the measurement was terrible, or one participant completed the experiment while being chased by a goat Statistics can tell you that the whole package looks strained. It cannot interrogate the goat.\n\n**Statistical significance** is a decision rule. If the *p*-value is at or below a threshold chosen in advance, usually $\\alpha = .05$, we call the result statistically significant. The threshold is a convention, not a cliff in nature. A result with $p = .049$ and one with $p = .051$ are not members of different species.\n\n### The Conditional-Probability Trap\n\nThe most famous mistake is reversing the condition:\n\n$$\nP(D \\mid H_0) \\neq P(H_0 \\mid D)\n$$\n\nThe probability of screaming **given that** a foam-bat-wielding research assistant is chasing you is probably high. The probability that a foam-bat-wielding research assistant is chasing you **given that** you are screaming is not necessarily high. You may have seen your tuition bill.\n\nCohen emphasized that a *p*-value gives $P(D \\mid H_0)$, not the probability that the null is true after seeing the data [@cohen1994]. To calculate $P(H_0 \\mid D)$, we would need additional information, including prior probabilities and an explicit alternative model. Quietly turning one conditional probability around does not make it Bayesian. It makes it wrong.\n\n### A P-Value Is Not Any of These Things\n\nA *p*-value is **not**:\n\n- The probability that the null hypothesis is true.\n- The probability that the research hypothesis is false.\n- The probability that the result happened \"because of chance.\"\n- The Type I error rate for this particular result.\n- The probability that the study will replicate.\n- The size or practical importance of the effect.\n- A tiny certificate declaring the study free of confounds, bias, fraud, or nonsense.\n\nLane-Getaz documented thirteen recurring *p*-value misconceptions in statistics students and experienced researchers [@lanegetaz2005]. Even graduate students who had survived multiple statistics courses often confused *p*-values with the probability of a hypothesis, replicability, effect size, or Type I error. Taking another statistics course helps, but apparently does not exorcise the demon automatically.\n\n## Cohen's Complaint: The Ritual Ate the Science\n\nCohen's title, *The Earth Is Round ($p < .05$)*, mocked the habit of testing a nearly certain or scientifically uninteresting null and then acting impressed when it was rejected [@cohen1994]. In much of psychology, an exact **nil hypothesis**–––a population difference or correlation of precisely zero–––is implausible. With a large enough sample, a trivial departure from zero can become statistically significant.\n\nThat produces two failures:\n\n1. Researchers mistake \"detectable\" for \"important.\"\n2. Researchers treat rejection of one null model as confirmation of their favorite theory, even though confounds, measurement problems, alternative theories, and several Probability Gods remain available.\n\nCohen did not offer a new sacred test to solve this problem. He recommended exploratory data analysis, graphs, effect sizes, confidence intervals, better measurement, power planning, and replication. In other words: look at what happened, estimate how much happened, admit the uncertainty, and see whether it happens again. Annoyingly, the solution is scientific judgment rather than purchasing a newer computer that can do a more powerful fancy test.\n\n## Significant Here, Not Significant There\n\nGelman and Stern identified another extremely common error: concluding that two effects differ because one is statistically significant and the other is not [@gelman2006].\n\nSuppose two independent studies estimate effects of:\n\n$$\n25 \\pm 10 \\qquad \\text{and} \\qquad 10 \\pm 10\n$$\n\nThe first estimate is statistically significant and the second is not. But their estimated **difference** is $15$, with a standard error of:\n\n$$\nSE_{difference} = \\sqrt{10^2 + 10^2} = 14.14\n$$\n\nThe two effects are only about 1.06 standard errors apart. That difference is not statistically significant. \"Treatment A worked but Treatment B did not\" is not evidence that Treatment A worked **better** than Treatment B. Test the comparison you want to claim.\n\nThis matters for interactions, subgroups, replications, and breathless headlines. If an effect is significant for women but not men, younger adults but not older adults, or Tuesday but not Wednesday, you have not established a group difference until you test that difference directly.\n\n## One Test at a Time Creates a Family Problem\n\nSet $\\alpha = .05$ for one true null hypothesis. In repeated use, that test falsely rejects the null about 5% of the time. Now run $j$ independent tests, all with true null hypotheses. The probability of **at least one** false positive is:\n\n$$\nFWER = 1 - (1 - \\alpha)^j\n$$\n\nWith 20 independent tests:\n\n$$\n1 - .95^{20} = .642\n$$\n\nThere is about a 64% chance of at least one false positive. You did not change $\\alpha$ for any individual test. You simply gave fickle chance twenty auditions and published whichever one could sing.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nalpha <- .05\nm_grid <- 1:100\ntheoretical_fwer <- 1 - (1 - alpha)^m_grid\n\nsimulated_at <- c(1, 5, 10, 20, 50, 100)\nsimulated_fwer <- vapply(simulated_at, function(m) {\n  p_values <- matrix(runif(20000 * m), ncol = m)\n  mean(rowSums(p_values <= alpha) > 0)\n}, numeric(1))\n\nplot(\n  m_grid, theoretical_fwer,\n  type = \"l\", lwd = 3, col = \"#1F4E79\",\n  ylim = c(0, 1),\n  xlab = \"Number of tests in the family\",\n  ylab = \"Probability of one or more false positives\"\n)\npoints(simulated_at, simulated_fwer, pch = 19, col = \"#D55E00\")\nabline(h = .05, lty = 2, col = \"gray50\")\nlegend(\n  \"bottomright\",\n  inset = c(.01, .10),\n  legend = c(\"Theoretical FWER\", \"Simulation\"),\n  col = c(\"#1F4E79\", \"#D55E00\"),\n  lty = c(1, NA), pch = c(NA, 19), bty = \"n\"\n)\ntext(78, .075, \"5% reference\", col = \"gray40\", cex = .82)\n```\n\n::: {.cell-output-display}\n![The probability of at least one false positive grows rapidly as more independent true null hypotheses are tested at alpha = .05. Simulated points sit on the theoretical curve.](Chapter_Multiple_Comparisons_files/figure-html/fig-fwer-growth-1.png){#fig-fwer-growth fig-align='center' fig-alt='Line graph with the number of tests in the family from 1 to 100 on the x axis and the probability of one or more false positives from 0 to 1 on the y axis. A dark blue curve starts at 0.05 for a single test, climbs steeply to about 0.40 by 10 tests and about 0.64 by 20, then flattens as it approaches 1, reaching about 0.92 at 50 tests and nearly 1 at 100. Six orange simulated points at 1, 5, 10, 20, 50 and 100 tests sit directly on the curve. A dashed grey horizontal line near the bottom marks the 5 percent reference level, which the curve leaves immediately.' width=672}\n:::\n:::\n\n\nThe independence formula is not exact for correlated tests, such as neighboring fMRI voxels. Dependence changes the arithmetic but does not make the problem disappear. Specialized methods can exploit that dependence; pretending the other tests never happened cannot.\n\n### What Counts as a Family?\n\nA **family** is the set of tests over which you want a joint error guarantee. Defining it requires scientific judgment.\n\n- All pairwise comparisons following one omnibus test often form a family.\n- All outcomes used to support one broad claim may form a family.\n- Thousands of voxels in one brain contrast form a family.\n- Every analysis ever conducted by everyone named Alex does not form one useful family, although it may form a cry for help.\n\nThe family should be defined by the claim and analysis plan, preferably before looking at results. Dividing twenty tests into twenty \"families of one\" after seeing the *p*-values is not a clever solution. It is p-hacking with office supplies.\n\n## Familywise Error Rate: Protect the Whole Family\n\nThe **familywise error rate** (FWER) is the probability of making **one or more Type I errors anywhere in the family**:\n\n$$\nFWER = P(V \\geq 1)\n$$\n\nHere, $V$ is the number of false rejections. FWER control is strict. It is appropriate when even one false positive would be costly or when a small, confirmatory set of claims is being tested.\n\n### Bonferroni\n\nFor $j$ tests, Bonferroni compares each *p*-value with $\\alpha/j$, or multiplies each *p*-value by $j$ and caps the result at 1:\n\n$$\np_{Bonferroni} = \\min(jp, 1)\n$$\n\nBonferroni works under arbitrary dependence, which is useful, but it can sacrifice substantial power when there are many tests. Reviewer 2 always asks for this correction cause they want to kill your power and thus your paper. Don't do it unless you powered for it in advance. \n\n### Holm's Sequential Method\n\nHolm's procedure orders the *p*-values and tests them sequentially [@holm1979]. It controls FWER under the same broad conditions as Bonferroni and is never less powerful. If your entire justification for plain Bonferroni is \"that is the one I remember,\" R remembers Holm for you.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nraw_p <- c(.001, .012, .021, .046, .210, .730)\n\ndata.frame(\n  test = paste(\"Hypothesis\", 1:length(raw_p)),\n  raw = raw_p,\n  bonferroni = p.adjust(raw_p, method = \"bonferroni\"),\n  holm = p.adjust(raw_p, method = \"holm\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          test   raw bonferroni  holm\n1 Hypothesis 1 0.001      0.006 0.006\n2 Hypothesis 2 0.012      0.072 0.060\n3 Hypothesis 3 0.021      0.126 0.084\n4 Hypothesis 4 0.046      0.276 0.138\n5 Hypothesis 5 0.210      1.000 0.420\n6 Hypothesis 6 0.730      1.000 0.730\n```\n:::\n:::\n\n\n## False Discovery Rate: Permit Some Risk Among Discoveries\n\nIn large exploratory analyses, strict FWER control may erase too many real signals. The **false discovery rate** (FDR) instead controls the expected proportion of false positives among the rejected hypotheses:\n\n$$\nFDR = E\\left(\\frac{V}{\\max(R,1)}\\right)\n$$\n\n$V$ is the number of false rejections and $R$ is the total number of rejections. The `max(R,1)` convention sets the proportion to zero when nothing is rejected.\n\nBenjamini and Hochberg's procedure controls FDR under independence and certain forms of positive dependence [@benjamini1995]. It is commonly available in R as `method = \"BH\"`.\n\nFDR of .05 does **not** guarantee that exactly 5% of one study's discoveries are false. Some studies will have none, some will have more, and some will reject nothing. The control applies to the expected false-discovery proportion over repeated uses of the procedure.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata.frame(\n  test = paste(\"Hypothesis\", 1:length(raw_p)),\n  raw = raw_p,\n  holm_fwer = p.adjust(raw_p, method = \"holm\"),\n  bh_fdr = p.adjust(raw_p, method = \"BH\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          test   raw holm_fwer bh_fdr\n1 Hypothesis 1 0.001     0.006  0.006\n2 Hypothesis 2 0.012     0.060  0.036\n3 Hypothesis 3 0.021     0.084  0.042\n4 Hypothesis 4 0.046     0.138  0.069\n5 Hypothesis 5 0.210     0.420  0.252\n6 Hypothesis 6 0.730     0.730  0.730\n```\n:::\n:::\n\n\n### What FDR Is Actually For\n\nFDR gets described as the lenient option, which makes it sound like the correction you reach for when the real ones were inconvenient. That is not what it is. FDR is the right tool for a particular question, and the question is not \"is this specific comparison real?\" It is:\n\n> **Is anything happening here at all, and if so, where should I look next?**\n\nThat is a screening question. It is what you ask of ten thousand voxels, twenty thousand genes, or a battery of forty outcomes you collected because the grant said you could. You are not making forty claims. You are trying to find the handful worth a second study, and you can tolerate a few dead ends in that handful, because the second study is what settles it.\n\nThe obvious worry is that a method willing to tolerate false discoveries will manufacture them out of nothing. So let us hand it nothing.\n\nHere is a brain with no activity in it whatsoever: ten thousand voxels, every null true, every *p*-value pure noise. This is the salmon.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nn_voxels <- 10000\ndead_brain <- runif(n_voxels)   # nothing is happening anywhere, by construction\n\nDeadCounts <- c(\n  uncorrected.p05  = sum(dead_brain < .05),\n  uncorrected.p001 = sum(dead_brain < .001),\n  BH_FDR           = sum(p.adjust(dead_brain, \"BH\") < .05),\n  Holm             = sum(p.adjust(dead_brain, \"holm\") < .05)\n)\n\nDeadCounts\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n uncorrected.p05 uncorrected.p001           BH_FDR             Holm \n             542               10                0                0 \n```\n:::\n:::\n\n\nRead that top row and then remember it is a corpse. An uncorrected threshold of $.05$ finds 542 active voxels in a dead brain. At the salmon paper's own uncorrected threshold of $p < .001$, it still finds 10, which is the same order as what Bennett and colleagues reported, because it is the same arithmetic doing the same thing.\n\n**BH finds zero.** So does Holm. The correction that supposedly waves things through waved nothing through, because there was nothing to wave.\n\nThat is not a lucky seed either. Run two thousand dead brains and count how often BH declares even one discovery:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nany_discovery <- replicate(2000, {\n  any(p.adjust(runif(n_voxels), \"BH\") < .05)\n})\n\nCryWolfRate <- mean(any_discovery)\n\nCryWolfRate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.0445\n```\n:::\n:::\n\n\nAbout 4.4%, which is the guarantee working. When every null is true there is nothing to discover, so the false-discovery proportion is either 0 or 1, and controlling its expectation at $.05$ means declaring anything at all no more than 5% of the time. **Under a global null, FDR control gives you familywise control for free.**\n\nNow give it a brain with something in it: the same ten thousand voxels, two hundred of them genuinely active.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nz <- rnorm(n_voxels)\nz[1:200] <- z[1:200] + 4          # 200 real effects, 9,800 true nulls\nlive_brain <- 2 * pnorm(-abs(z))\n\nReal  <- 1:200\nNoise <- 201:n_voxels\n\nCountUp <- function(adjusted) {\n  c(found = sum(adjusted < .05),\n    real  = sum(adjusted[Real] < .05),\n    false = sum(adjusted[Noise] < .05))\n}\n\nBrainTable <- rbind(\n  Uncorrected = CountUp(live_brain),\n  BH_FDR      = CountUp(p.adjust(live_brain, \"BH\")),\n  Holm        = CountUp(p.adjust(live_brain, \"holm\"))\n)\n\nBrainTable\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            found real false\nUncorrected   690  198   492\nBH_FDR        166  154    12\nHolm           58   58     0\n```\n:::\n:::\n\n\nThis is the entire argument in three rows.\n\n**Uncorrected** reports 690 findings, and 492 of them are noise. Most of that table is garbage and it looks exactly like the real part.\n\n**Holm** makes no mistakes at all: 0 false discoveries out of 58. It also misses 142 of the 200 real effects, which in a screening study means 142 things you will never look at again.\n\n**BH** recovers 154 of the 200 and pays 12 false ones for them. That is the trade, stated plainly: you accept that roughly one in twenty of the things on your follow-up list is a dead end, in exchange for a follow-up list that actually contains the findings.\n\nNote that the observed false-discovery proportion here is 0.072, slightly above the $.05$ you asked for. That is not a bug, and it is the point made two paragraphs above the first table in this section: FDR controls the *expected* proportion across repeated uses, so any single study can land above or below it.\n\n::: {.callout-note title=\"Why the Salmon Is the Right Test of a Correction\"}\nThe dead salmon is usually told as a joke about fMRI. It is better understood as a **calibration check**, and it is one every method in this chapter passes.\n\nA correction is a promise about how often you will be fooled. The cheapest way to test such a promise is to hand the procedure data with nothing in it and confirm that it says nothing. The salmon is a physical version of the simulation above, and both give the same answer: the uncorrected threshold hallucinates, and every corrected one, FDR included, does not.\n\nSo when someone objects that FDR is too permissive for serious work, the reply is that it is permissive about *which* discoveries it lets through, not about *whether* there is anything there. On a dead fish it reports a dead fish.\n:::\n\n## What the Corrections Trade Away\n\nNo method is perfect. Tight false-positive control usually reduces the ability to detect real effects. The useful question is not \"Which correction is best?\" It is \"Which error promise matches this research goal?\"\n\nThe simulation below contains 20 tests per study. Five hypotheses have real standardized signals and fifteen null hypotheses are true. We compare no adjustment, Bonferroni, Holm, and Benjamini--Hochberg over 5,000 simulated studies.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nn_families <- 5000\nn_tests <- 20\nn_real <- 5\n\nz_values <- matrix(rnorm(n_families * n_tests), nrow = n_families)\nz_values[, 1:n_real] <- z_values[, 1:n_real] + 2.5\np_matrix <- 2 * pnorm(-abs(z_values))\n\nadjust_rows <- function(method) {\n  t(apply(p_matrix, 1, function(p) p.adjust(p, method = method) <= .05))\n}\n\nrejections <- list(\n  Unadjusted = p_matrix <= .05,\n  Bonferroni = adjust_rows(\"bonferroni\"),\n  Holm = adjust_rows(\"holm\"),\n  BH_FDR = adjust_rows(\"BH\")\n)\n\nsummarize_method <- function(reject) {\n  true_discoveries <- rowSums(reject[, 1:n_real, drop = FALSE])\n  false_discoveries <- rowSums(reject[, (n_real + 1):n_tests, drop = FALSE])\n  total_discoveries <- true_discoveries + false_discoveries\n  false_discovery_proportion <- ifelse(\n    total_discoveries == 0,\n    0,\n    false_discoveries / total_discoveries\n  )\n\n  c(\n    average_true_discoveries = mean(true_discoveries),\n    probability_any_false_positive = mean(false_discoveries > 0),\n    average_false_discovery_proportion = mean(false_discovery_proportion)\n  )\n}\n\nround(t(vapply(rejections, summarize_method, numeric(3))), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           average_true_discoveries probability_any_false_positive\nUnadjusted                    3.501                          0.526\nBonferroni                    1.503                          0.037\nHolm                          1.539                          0.039\nBH_FDR                        2.076                          0.122\n           average_false_discovery_proportion\nUnadjusted                              0.152\nBonferroni                              0.018\nHolm                                    0.019\nBH_FDR                                  0.039\n```\n:::\n:::\n\n\nThe unadjusted method finds more real signals but also produces at least one false positive far too often. Bonferroni and Holm protect strongly against any false positive, with Holm usually retaining a little more power. BH accepts a higher chance that a study contains some false positives in exchange for finding more real signals, while controlling their expected proportion among the discoveries.\n\n| Goal | Sensible default |\n|---|---|\n| A few planned, confirmatory tests where any false claim is costly | Holm FWER control |\n| A simple method that remains valid under broad dependence | Bonferroni, accepting lower power |\n| Many exploratory tests where some false leads can be tolerated and checked later | Benjamini--Hochberg FDR control |\n| A small number of clearly preregistered primary tests | Test those primary hypotheses as planned; correct the separate exploratory family |\n\n## Multiple Comparisons in Regression\n\nA regression with many coefficients is also a collection of tests. The correct family depends on the claim.\n\nIf one coefficient was the preregistered primary hypothesis and the others were prespecified covariates, automatically correcting every coefficient together may not represent the design. If you added 84 predictors, 31 interactions, six subgroups, and the participant's astrological sign until something became significant, you have a multiple-testing problem plus a confession.\n\nStore the *p*-values you intend to treat as one family and adjust them directly. Here is the kitchen-sink model described above, built small enough to inspect: 100 people, twelve predictors, and only the first two doing anything at all. The other ten are `rnorm()` with a job title.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nn_people <- 100\nkitchen_sink <- as.data.frame(matrix(rnorm(n_people * 12), nrow = n_people))\nnames(kitchen_sink) <- paste0(\"V\", 1:12)\n\n# Only V1 and V2 are real. V3 through V12 are noise.\nkitchen_sink$Focus <-\n  0.45 * kitchen_sink$V1 -\n  0.38 * kitchen_sink$V2 +\n  rnorm(n_people)\n\nsink_model <- lm(Focus ~ ., data = kitchen_sink)\n\ncoefficient_p <- coef(summary(sink_model))[-1, \"Pr(>|t|)\"]\n\nround(data.frame(\n  raw  = coefficient_p,\n  holm = p.adjust(coefficient_p, method = \"holm\"),\n  BH   = p.adjust(coefficient_p, method = \"BH\")\n), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       raw   holm     BH\nV1  0.0000 0.0004 0.0004\nV2  0.0034 0.0379 0.0207\nV3  0.7522 1.0000 0.8242\nV4  0.8672 1.0000 0.8672\nV5  0.3091 1.0000 0.6183\nV6  0.4809 1.0000 0.7888\nV7  0.2578 1.0000 0.6183\nV8  0.5569 1.0000 0.7888\nV9  0.1922 1.0000 0.5766\nV10 0.5916 1.0000 0.7888\nV11 0.0411 0.4105 0.1642\nV12 0.7555 1.0000 0.8242\n```\n:::\n:::\n\n\nRead the `raw` column first and pretend you do not know how the data were made. Three predictors clear $.05$: V1, V2, V11. Two of them are real. The third, V11, is a column of random numbers that happened to line up, at $p =$ 0.041.\n\nThis was not arranged. Ten true nulls tested at $\\alpha = .05$ give about a 40% chance of at least one false positive, so meeting one here is the ordinary outcome rather than bad luck. Run this chunk with a different seed and you will sometimes get none and occasionally get two.\n\nBoth corrections do their job. Holm and Benjamini-Hochberg each keep V1 and V2, the two real effects, and both kill the impostor. Notice also that BH is gentler than Holm on the survivors, which is the trade the previous section measured: it is buying power by promising less.\n\nFor planned contrasts, use software that can adjust the contrast family explicitly. Always report the method, the family of tests, and whether the analyses were confirmatory or exploratory.\n\n## Where You Will Actually Meet This: emmeans\n\nEverything above is theory you will use once a year. This section is the thing you will type next month.\n\nIn this book's pipeline, multiplicity arrives in exactly one place: `pairs(emmeans(...))` after a model with a categorical predictor. The [categorical predictors chapter](Chapter_Regression%20with%20Cat%20Variables.qmd) left a promise here. It ran three unadjusted comparisons behind a significant omnibus *F*, which is Fisher's protected LSD, and it warned that the protection expires at exactly three groups. So let us arrive with four.\n\nThe study is the same distracted-driving design, with one more condition added and a deliberately modest sample, because a correction that never changes anything teaches nothing.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\n\nset.seed(343)\nn <- 20\n\ndrive_data <- data.frame(\n  Condition = factor(\n    rep(c(\"No Distraction\", \"Podcast\", \"Lecture\", \"Texting\"), each = n),\n    levels = c(\"No Distraction\", \"Podcast\", \"Lecture\", \"Texting\")\n  ),\n  RT = c(\n    rnorm(n, 0.70, 0.25),\n    rnorm(n, 0.86, 0.25),\n    rnorm(n, 0.92, 0.25),\n    rnorm(n, 1.08, 0.25)\n  )\n)\n\ndrive_model <- lm(RT ~ Condition, data = drive_data)\nanova(drive_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nResponse: RT\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nCondition  3 2.2645 0.75484  17.744 7.952e-09 ***\nResiduals 76 3.2330 0.04254                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThe omnibus test is significant, so under the old three-group rule we would now be entitled to look at pairs. With four groups there are six pairs, and the entitlement has expired.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndrive_means <- emmeans(drive_model, ~ Condition)\n\npairs(drive_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n contrast                 estimate     SE df t.ratio p.value\n No Distraction - Podcast  -0.2816 0.0652 76  -4.318  0.0003\n No Distraction - Lecture  -0.3269 0.0652 76  -5.011 <0.0001\n No Distraction - Texting  -0.4623 0.0652 76  -7.088 <0.0001\n Podcast - Lecture         -0.0452 0.0652 76  -0.693  0.8993\n Podcast - Texting         -0.1807 0.0652 76  -2.770  0.0348\n Lecture - Texting         -0.1354 0.0652 76  -2.077  0.1701\n\nP value adjustment: tukey method for comparing a family of 4 estimates \n```\n:::\n:::\n\n\n**Read the last line of that output.** It says `P value adjustment: tukey method for comparing a family of 4 estimates`. You did not ask for that. `emmeans` decided that six all-pairwise comparisons constitute a family, applied Tukey, and mentioned it in a footnote below the table you were reading.\n\nThis is the single most important fact in this section, and it cuts both ways. The default is defensible, because Tukey was built for precisely this situation. But a reader who does not know it is there will report Tukey-adjusted *p*-values while describing them as ordinary ones, and a reader who wanted something else will not get it by hoping.\n\n### What Tukey Actually Is\n\nTukey's HSD is the correction psychologists meet most often and explain least often, so it is worth knowing what it does instead of treating it as the button labelled \"post hoc.\"\n\nEvery other method in this chapter takes a pile of *p*-values and adjusts them, without caring where they came from. Tukey does not work that way. It asks a specific question about a specific design: **if all $k$ group means came from the same population, how far apart would the largest and smallest of them drift by chance alone?**\n\nThat quantity has its own distribution, the **studentized range**, usually written $q$. Tukey compares every pair against it. The logic is worth sitting with for a moment, because it is genuinely clever: if you protect the *biggest* gap in the set, every smaller gap is protected automatically. You do not have to buy six comparisons separately, because six comparisons among four means are not six independent questions. They are six views of four numbers.\n\nThat is why Tukey is not just another cautious correction. With equal group sizes and roughly equal variances it controls the familywise error rate **exactly**, rather than by being conservative and hoping. Bonferroni and Holm are valid under *any* dependence structure, which sounds like a stronger property and is really the concession: they are generic because they know nothing about your design, so they cannot take advantage of the fact that your comparisons share means.\n\n**The assumption doing all of that work is that the groups are independent.** The studentized range is derived for $k$ separate samples with one common error variance. That is a between-subjects design, and it is why the honest answer to \"when should I use Tukey?\" contains a design rather than a number of tests.\n\nHere is the same comparison with the correction turned off, and with Holm instead.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairs(drive_means, adjust = \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n contrast                 estimate     SE df t.ratio p.value\n No Distraction - Podcast  -0.2816 0.0652 76  -4.318 <0.0001\n No Distraction - Lecture  -0.3269 0.0652 76  -5.011 <0.0001\n No Distraction - Texting  -0.4623 0.0652 76  -7.088 <0.0001\n Podcast - Lecture         -0.0452 0.0652 76  -0.693  0.4901\n Podcast - Texting         -0.1807 0.0652 76  -2.770  0.0070\n Lecture - Texting         -0.1354 0.0652 76  -2.077  0.0412\n```\n:::\n\n```{.r .cell-code}\npairs(drive_means, adjust = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n contrast                 estimate     SE df t.ratio p.value\n No Distraction - Podcast  -0.2816 0.0652 76  -4.318  0.0002\n No Distraction - Lecture  -0.3269 0.0652 76  -5.011 <0.0001\n No Distraction - Texting  -0.4623 0.0652 76  -7.088 <0.0001\n Podcast - Lecture         -0.0452 0.0652 76  -0.693  0.4901\n Podcast - Texting         -0.1807 0.0652 76  -2.770  0.0211\n Lecture - Texting         -0.1354 0.0652 76  -2.077  0.0824\n\nP value adjustment: holm method for 6 tests \n```\n:::\n:::\n\n\nPut the three side by side.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nadjust_column <- function(method) {\n  as.data.frame(pairs(drive_means, adjust = method))$p.value\n}\n\ndata.frame(\n  contrast = as.data.frame(pairs(drive_means))$contrast,\n  none     = round(adjust_column(\"none\"), 4),\n  tukey    = round(adjust_column(\"tukey\"), 4),\n  holm     = round(adjust_column(\"holm\"), 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  contrast   none  tukey   holm\n1 No Distraction - Podcast 0.0000 0.0003 0.0002\n2 No Distraction - Lecture 0.0000 0.0000 0.0000\n3 No Distraction - Texting 0.0000 0.0000 0.0000\n4        Podcast - Lecture 0.4901 0.8993 0.4901\n5        Podcast - Texting 0.0070 0.0348 0.0211\n6        Lecture - Texting 0.0412 0.1701 0.0824\n```\n:::\n:::\n\n\nFive of the six comparisons say the same thing under all three methods, which is the usual and slightly boring result. The sixth does not. **Lecture versus Texting** is significant unadjusted at $p =$ 0.0412, and survives neither correction: Tukey puts it at 0.17 and Holm at 0.082.\n\nThat single row is the entire chapter in miniature. \"Texting is worse than listening to a lecture\" is a claim you may publish if you looked at that pair alone, and may not publish if you looked at all six and picked this one. The data did not change. The number of chances you gave yourself did.\n\n### Where Holm Helps and Where It Does Not\n\nLook down the Tukey and Holm columns and something awkward appears: Holm gives the smaller number in five of the six rows. If Tukey is the tailored tool for this design, why is the generic one winning?\n\nBecause \"which is more powerful\" is the wrong question, and the answer depends on *where in the list* you are standing.\n\nHolm is a **step-down** procedure. Sort the *p*-values smallest to largest, then multiply the smallest by $m$, the next by $m-1$, the next by $m-2$, and so on. That first step deserves your attention:\n\n> **Holm's adjustment for the smallest *p*-value in the family is exactly Bonferroni.**\n\nNot similar. Identical. Both multiply that one *p*-value by the full family size, and R will confirm it on the strongest comparison in the table above:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSmallestOf <- function(method) {\n  min(as.data.frame(pairs(drive_means, adjust = method))$p.value)\n}\n\nc(\n  raw          = SmallestOf(\"none\"),\n  raw.times.6  = 6 * SmallestOf(\"none\"),\n  holm         = SmallestOf(\"holm\"),\n  bonferroni   = SmallestOf(\"bonferroni\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         raw  raw.times.6         holm   bonferroni \n5.991865e-10 3.595119e-09 3.595119e-09 3.595119e-09 \n```\n:::\n:::\n\n\nHolm is never *worse* than Bonferroni, which is why this chapter recommends it over Bonferroni, but the improvement is entirely in the comparisons after the first. **If your headline finding is the single strongest contrast in the family, Holm has done nothing for you that Bonferroni would not have done.**\n\nThat is the real cost, and it is why Holm hurts most in the design where you can least afford it. Between-subjects studies spend their sample on telling people apart, so the standard errors are large, and the one comparison the paper is about is usually the one at the top of the sorted list, taking the full $\\times m$ penalty.\n\nWithin-subjects designs are the opposite situation. Each person serves as their own control, between-person variance drops out of the error term, and the same number of humans buys much smaller standard errors. There you can usually afford Holm's conservatism, and you often need something like it, because Tukey's studentized range assumes independent groups and repeated measures are not independent. Holm's indifference to dependence stops being a concession and becomes the reason to use it.\n\nSo the two facts point in the same direction:\n\n- **Between-subjects, exploring which means differ:** Tukey. It is built for exactly this and it is exact, not conservative.\n- **Within-subjects, or a handful of theory-chosen contrasts:** Holm. It stays valid when observations are correlated, and the design has usually bought you the power to pay for it.\n\nOne honest footnote on magnitude. Tukey's edge over Bonferroni at the top of the list is real but modest here, about 1.03 times, because four groups do not offer much dependence to exploit. That advantage grows as groups are added, since the number of pairs grows much faster than the number of means. With eight groups you have 28 comparisons carrying only 7 degrees of freedom between them, and Tukey's willingness to notice that starts to matter a great deal.\n\n::: {.callout-tip title=\"Which `adjust=` Do I Want? Answer With Your Design\"}\nPick by what the study is and what you are trying to learn, not by how many tests happen to be on the screen.\n\n- **Between-subjects, all pairwise, working out which conditions differ?** Leave the default. `adjust = \"tukey\"` is built for exactly this and `emmeans` is already applying it. Say so in the write-up.\n- **Within-subjects or repeated measures?** `adjust = \"holm\"`. Tukey's studentized range assumes independent groups, which you do not have, and Holm stays valid under any dependence. The design has usually bought you the power to afford it.\n- **A handful of contrasts your theory named in advance?** `adjust = \"holm\"` again, and the family is those planned contrasts, not every pair the software is willing to generate.\n- **Exactly three groups behind a significant omnibus *F*?** `adjust = \"none\"` is defensible, and only there. That is the protected LSD case from the [categorical predictors chapter](Chapter_Regression%20with%20Cat%20Variables.qmd). At four groups, as above, it is the inflation problem wearing a lab coat.\n- **Screening a large pile of outcomes to decide what to study next?** `adjust = \"fdr\"`, and call the results exploratory, because that is what you have promised. See the next section for what FDR is actually good at.\n\n**The trap to avoid:** reaching for Holm in a between-subjects pairwise design because it sounds more rigorous than the default. On your strongest comparison Holm *is* Bonferroni, so that instinct costs you power at the exact place your paper needs it, and buys nothing Tukey was not already giving you.\n\nWhatever you pick, name it and name the family. \"Pairwise comparisons were Tukey-adjusted across all six condition pairs\" is one clause, and it is the difference between a reader trusting your table and a reader rebuilding it.\n:::\n\n## The Point Is Not to Fear P-Values\n\nP-values are not evil. They are also not tiny judges who determine whether a theory is innocent or guilty. They describe how incompatible the data are with a specified null model, under a pile of assumptions that must remain attached.\n\nA defensible statistical argument uses:\n\n- The design and quality of the measurement.\n- The estimated effect and its confidence interval.\n- The *p*-value as one piece of evidence rather than a personality test for the hypothesis.\n- A correction that matches the family and scientific goal.\n- Transparency about how many analyses were attempted.\n- Replication, because one clever correction cannot make a single study carry an entire theory on its back.\n\nThe dead salmon did not teach us that fMRI is fake. It taught us that if we give chance enough opportunities, eventually even dinner appears to think. Correct the tests, show the effects, admit the uncertainty, and please stop asking deceased seafood to perform social cognition without preregistration.\n\n## The Short Story\n\n- $p = P(\\text{data this weird or weirder} \\mid H_0 \\text{ and the model})$. Never the reverse, and never the probability that your hypothesis is wrong.\n- **\"Significant here, not significant there\" is not a comparison.** If you want to claim two effects differ, test the difference.\n- **A family is defined by the claim**, and defined before you peek. Splitting twenty tests into twenty families of one after seeing the *p*-values is p-hacking with office supplies.\n- **FWER when any single false claim would be costly**, and prefer Holm to Bonferroni, since it is never less powerful. **BH-FDR when you are exploring** and false leads are survivable.\n- **Choose the pairwise correction by design, not by test count.** Between-subjects, working out which conditions differ: Tukey, which is exact for that job because the studentized range is built for independent groups. Within-subjects: Holm, which stays valid when observations are correlated, in a design that has usually bought you the power to pay for it.\n- **On the strongest comparison in a family, Holm *is* Bonferroni.** The step-down only helps the comparisons after the first, so reaching for Holm in a between-subjects pairwise design costs power exactly where the paper needs it.\n- **FDR answers \"is anything here, and where do I look next?\"** It is a screening tool, not a lenient one. On a dead brain it reports a dead brain.\n- FDR of .05 is a promise about the long run, not a guarantee that 5% of *this* study's discoveries are false.\n- **`emmeans` already adjusted your pairwise comparisons.** It defaults to Tukey and says so in a footnote. Know what your software chose before you describe it in a sentence.\n- **Report the method and the family**, every time. One clause does it.\n- No correction rescues a study from bad measurement, and no correction is a substitute for replication.\n- The salmon was dead the whole time.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}