{
  "hash": "cf0c243d790c3a303c8fa81c54ef33c5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Categorical × Categorical Interactions: The 2×2 Design\"\nsubtitle: \"When Both Your Predictors Are Categorical\"\ngeometry: margin=.5in\nfontsize: 10pt\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n  html:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n    df-print: paged\n---\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Where We Are and Where We Are Going\n\nIn the prior chapter you learned how to detect, estimate, and interpret an interaction between a *continuous* predictor and a *categorical* one. In the friendship study, Being Nice (0–10 scale) was continuous and Going Out (Stay in vs. Go out) was categorical. The interaction told you that the **slope** of Being Nice on friendship closeness was different for students who went out compared to those who stayed in.\n\nThat kind of interaction is very common in psychology research. But so is a second kind: interactions where **both predictors are categorical**. You have probably already encountered this design — it is the foundation of the **two-way factorial ANOVA**. A 2 × 2 design (two predictors, each with two levels) is the simplest and most common version.\n\nThis chapter bridges the two frameworks. We will keep the same friendship study and the same hypothesis, but we will make one important change: instead of treating Being Nice as a full continuous variable, we will focus on **just the extremes** — students whose niceness scores are near 0 (the least agreeable people in the sample) and students whose scores are near 10 (the most agreeable). This turns our continuous variable into a two-level categorical variable: **Low Nice** vs. **High Nice**. Combined with Going Out (Stay in vs. Go out), we have a **2 × 2 design**.\n\nThis chapter assumes you have already read the prior chapter material. You know what an interaction is, you know how to interpret the interaction model equation, and you know how to use `anova()` to compare a main effects model to an interaction model. What is new here is what changes — and what stays the same — when both predictors are categorical.\n\n### What Changes from prior chapter\n\nThe biggest conceptual change is this: **there is no continuous variable to center.** In the prior chapter centering was necessary because the intercept needed a meaningful zero point on the continuous scale. When both predictors are categorical, every predictor already takes on a small set of discrete values, and the \"zero point\" is simply the reference category of each variable — a specific cell in the design, not an abstract mean.\n\nEverything else follows from that:\n\n- No centering is needed. Both variables just need dummy coding.\n- The interaction coefficient is no longer a \"difference in slopes.\" There are no slopes here. Instead, $B_3$ is the **difference in group differences** — sometimes called the \"difference of differences.\" We will unpack this carefully.\n- The follow-up to the interaction is **simple effects analysis**: testing, within each level of one variable, whether the levels of the other variable differ significantly. We use `pairs()` from the `emmeans` package instead of `emtrends()`.\n- Effect sizes for pairwise comparisons are expressed as **Cohen's *d***, not unstandardized slopes.\n\nWhat **stays the same**: the interaction is still about \"it depends.\" The visual signature is still non-parallel lines (or unequal gaps in a bar chart). The model comparison is still done with `anova()` and $\\Delta R^2$. The APA write-up still follows the same structure.\n\n### What the 2×2 Looks Like as a Table\n\nBefore we touch any data, it helps to lay out the full design as a 2 × 2 table. Each cell represents a unique combination of the two categorical predictors, and we expect a separate (estimated) mean outcome in each cell.\n\n|  | **Stay in** | **Go out** |\n|---|---|---|\n| **Low Nice** | $\\mu_{11}$: Low Nice × Stay in | $\\mu_{12}$: Low Nice × Go out |\n| **High Nice** | $\\mu_{21}$: High Nice × Stay in | $\\mu_{22}$: High Nice × Go out |\n\nThe interaction question is: **is the difference between High Nice and Low Nice the same in both columns (Going Out groups)?** Or equivalently: **is the difference between Go out and Stay in the same in both rows (Niceness groups)?**\n\nBoth questions ask the same thing. The answer is the interaction.\n\n\n## The Core Concept: The \"Difference of Differences\"\n\n### What It Means When Both Predictors Are Categorical\n\nIn the prior chapter, the interaction coefficient $B_3$ told you how much steeper the slope of Being Nice was for the \"Go out\" group compared to the \"Stay in\" group. Slopes are a continuous concept: the rate at which friendship closeness increases as niceness increases by one unit.\n\nWhen Being Nice is categorical (Low vs. High), there are no slopes. Instead, there is a **gap**: the difference in predicted friendship closeness between High Nice and Low Nice students. The interaction now asks whether that gap is the same size in both Going Out groups.\n\nHere is the idea in formula form. Define:\n\n- **Effect of Niceness for Stay-in students** = $\\mu_{21} - \\mu_{11}$ (High Nice – Low Nice, among those who stay in)\n- **Effect of Niceness for Go-out students** = $\\mu_{22} - \\mu_{12}$ (High Nice – Low Nice, among those who go out)\n\nThe **interaction** is the difference between these two effects:\n\n$$B_3 = (\\mu_{22} - \\mu_{12}) - (\\mu_{21} - \\mu_{11})$$\n\nThis is the \"difference of differences.\" If there is no interaction, the effect of Niceness is the same size in both Going Out groups, and $B_3 = 0$. If there is an interaction, the effect of Niceness is larger in one group than the other, and $B_3 \\neq 0$.\n\nEquivalently (and this is worth pausing on), you can write it the other way:\n\n$$B_3 = (\\mu_{22} - \\mu_{21}) - (\\mu_{12} - \\mu_{11})$$\n\nThis version asks: is the effect of Going Out (Go out – Stay in) the same for High Nice and Low Nice students? The two formulations are mathematically identical and represent the same interaction. Which framing you use depends on which story you want to tell. In our study, we are primarily interested in whether the **benefit of being nice depends on whether you go out** — so we will usually use the first framing.\n\n### Visual Hypotheses: What We Expect to See\n\nAs in the prior chapter, we can sketch out our two competing possibilities before running a single model.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_CatXCat_Interaction_files/figure-html/hypothesis-plots-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nNotice the visualization has changed from the prior chapter. Instead of regression lines across a continuous X-axis, we now have two points connected by a line for each Going Out group. The key visual signature of an interaction is still **non-parallel lines** — but \"non-parallel\" now means the **gaps between the two groups are different sizes** across the niceness levels, rather than different slopes.\n\n- In **Hypothesis A**, the two lines are parallel: the gap between \"Go out\" and \"Stay in\" is the same for Low Nice and High Nice students. Being nice adds a fixed amount regardless of going out.\n- In **Hypothesis B**, the lines fan out: the gap between \"Go out\" and \"Stay in\" is tiny for Low Nice students but enormous for High Nice students. This is our interaction hypothesis: being nice only pays off substantially if you are also out there meeting people.\n\n\n## Before We Run the Models: Dummy Coding Both Variables\n\n### No Centering Required\n\nIn the prior chapter, you had to center the continuous predictor (Being Nice) before building the interaction model. Centering shifted the scale so that zero represented the average person, making the intercept interpretable.\n\nWhen both predictors are categorical, there is nothing to center. Each predictor already takes on discrete values. The \"zero point\" for each predictor is simply its **reference category** — whichever group we designate as the baseline.\n\nThis is actually simpler than the prior chapter. The only setup step is making sure both variables are properly factored in R, with the reference groups ordered first.\n\n### Dummy Coding Both Variables\n\nWe have two categorical predictors, each with two levels:\n\n| Variable | Levels | Reference group (coded 0) | Comparison group (coded 1) |\n|---|---|---|---|\n| **NiceGroup** | Low Nice, High Nice | Low Nice | High Nice |\n| **GoingOut** | Stay in, Go out | Stay in | Go out |\n\nWith this coding, the **four coefficients** in the interaction model have the following meanings:\n\n| Coefficient | What it represents |\n|---|---|\n| $B_0$ (Intercept) | Predicted friends for **Low Nice × Stay in** students — the baseline cell |\n| $B_1$ (NiceGroup: High Nice) | High Nice – Low Nice **among Stay-in students** (simple effect of niceness for stay-in group) |\n| $B_2$ (GoingOut: Go out) | Go out – Stay in **among Low Nice students** (simple effect of going out for low-nice group) |\n| $B_3$ (NiceGroup × GoingOut) | The \"difference of differences\": does the effect of niceness differ by going-out group? |\n\nNotice that $B_1$ and $B_2$ are no longer main effects in the traditional sense — they are **simple effects**, each representing the effect of one variable *holding the other variable at its reference level*. This is the same logic as in the prior chapter, where $B_1$ was the slope for the reference group only. Here, $B_1$ is the niceness gap for the reference going-out group only.\n\n### Recovering All Four Cell Means\n\nOne of the useful features of the 2 × 2 interaction model is that you can reconstruct **every cell mean** directly from the coefficients. Here is the formula for each cell:\n\n| Cell | Formula | Plain meaning |\n|---|---|---|\n| Low Nice × Stay in | $B_0$ | Baseline |\n| High Nice × Stay in | $B_0 + B_1$ | Baseline + niceness effect (Stay in) |\n| Low Nice × Go out | $B_0 + B_2$ | Baseline + going-out effect (Low Nice) |\n| High Nice × Go out | $B_0 + B_1 + B_2 + B_3$ | All four terms |\n\nThe final cell is the most important: for High Nice students who also go out, the prediction is the baseline plus the simple effect of niceness, plus the simple effect of going out, **plus the interaction term**. The interaction term $B_3$ adjusts the prediction for the cell where both variables are at their non-reference level. If there is no interaction ($B_3 = 0$), the effects of the two variables add up independently and the model is purely additive.\n\n\n## The Data\n\nWe return to our 200 first-semester students. Recall that we measured friendship closeness (0–100 feelings thermometer), agreeableness (0–10), and whether they went out regularly.\n\nFor this analysis, we focus on the **extremes of the niceness distribution**: students who scored below 2 on the agreeableness scale (near 0 = **Low Nice**) and students who scored above 8 (**High Nice**). The 120 or so students in the middle of the scale are not used in this analysis — we are focusing on the contrast between the most and least agreeable people in the sample.\n\n\n\nThe resulting dataset has 81 participants spread across four cells:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nFriend.Data %>%\n  group_by(NiceGroup_, GoingOut_) %>%\n  summarise(n = n(),\n            M_Friends  = round(mean(NewFriends), 2),\n            SD_Friends = round(sd(NewFriends), 2),\n            .groups = \"drop\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"NiceGroup_\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"GoingOut_\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"M_Friends\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SD_Friends\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Low Nice\",\"2\":\"Stay in\",\"3\":\"25\",\"4\":\"15.95\",\"5\":\"7.27\"},{\"1\":\"Low Nice\",\"2\":\"Go out\",\"3\":\"16\",\"4\":\"22.60\",\"5\":\"4.97\"},{\"1\":\"High Nice\",\"2\":\"Stay in\",\"3\":\"21\",\"4\":\"19.00\",\"5\":\"7.05\"},{\"1\":\"High Nice\",\"2\":\"Go out\",\"3\":\"19\",\"4\":\"60.31\",\"5\":\"7.32\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe cell counts are not equal — this is typical when you extract extremes from a continuous distribution rather than randomly assigning participants to conditions. In regression (unlike ANOVA), this unequal cell size is handled automatically. The estimates are still valid.\n\nThe cell means already tell an interesting story: Low Nice students have similar friendship scores whether they go out or not (both around 15), while High Nice students who go out have dramatically higher scores than High Nice students who stay in. This pattern matches Hypothesis B.\n\n## A First Look at the Data\n\nBefore running any models, let's visualize the four cells directly.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_CatXCat_Interaction_files/figure-html/first-look-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nThe pattern is striking. The \"Stay in\" line (blue) is almost flat: Low Nice and High Nice students who stay in have virtually the same friendship scores. The \"Go out\" line (orange) rises sharply: High Nice students who go out form far closer friendships than Low Nice students who go out. The two lines are clearly **non-parallel**, which is the visual signature of an interaction. This picture already suggests Hypothesis B.\n\n\n## Building the Models\n\n### Model 1: The Additive Model\n\nWe begin with the main effects (additive) model. This model says the two variables each have an independent effect on friendship closeness, and those effects add up without interacting.\n\n$$\\widehat{NewFriends} = B_0 + B_1 \\cdot NiceGroup + B_2 \\cdot GoingOut + \\varepsilon$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nModel.1 <- lm(NewFriends ~ NiceGroup_ + GoingOut_, data = Friend.Data)\nsummary(Model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = NewFriends ~ NiceGroup_ + GoingOut_, data = Friend.Data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-23.4417  -9.7999   0.2044   9.9769  27.0074 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            9.112      1.980   4.602 1.59e-05 ***\nNiceGroup_High Nice   18.025      2.465   7.314 1.98e-10 ***\nGoingOut_Go out       24.173      2.487   9.718 4.40e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.05 on 78 degrees of freedom\nMultiple R-squared:  0.674,\tAdjusted R-squared:  0.6657 \nF-statistic: 80.64 on 2 and 78 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe additive model estimates a single effect of NiceGroup (averaged across both Going Out groups) and a single effect of GoingOut (averaged across both Niceness groups). These are conventional main effects.\n\nNotice that the R² here (0.674) is already reasonably high, driven primarily by the Going Out main effect. But as we will see, forcing the effects to be additive is a poor fit for the actual pattern in the data.\n\n### Visualizing the Additive Model\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_CatXCat_Interaction_files/figure-html/additive-plot-1.png){fig-align='center' width=432}\n:::\n:::\n\n\nThe additive model forces the two lines to be parallel. The gap between \"Go out\" and \"Stay in\" is identical for Low Nice and High Nice students. But look at the raw data: the \"Go out\" students in the High Nice group (orange, right side) are far higher than what the parallel-line model predicts for them, and the \"Stay in\" students in the same group are not as high as the model suggests. The parallel assumption is clearly wrong.\n\n### Model 2: The Interaction Model\n\nNow we add the interaction term:\n\n$$\\widehat{NewFriends} = B_0 + B_1 \\cdot NiceGroup + B_2 \\cdot GoingOut + B_3 \\cdot NiceGroup \\times GoingOut + \\varepsilon$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nModel.2 <- lm(NewFriends ~ NiceGroup_ * GoingOut_, data = Friend.Data)\nsummary(Model.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = NewFriends ~ NiceGroup_ * GoingOut_, data = Friend.Data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7001  -4.7327  -0.0055   4.3511  18.0093 \n\nCoefficients:\n                                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                           15.950      1.367  11.670  < 2e-16 ***\nNiceGroup_High Nice                    3.045      2.023   1.505  0.13632    \nGoingOut_Go out                        6.649      2.188   3.039  0.00324 ** \nNiceGroup_High Nice:GoingOut_Go out   34.663      3.077  11.265  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.834 on 77 degrees of freedom\nMultiple R-squared:  0.8769,\tAdjusted R-squared:  0.8721 \nF-statistic: 182.8 on 3 and 77 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n### Does the Interaction Model Explain More Variance?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nknitr::kable(anova(Model.1, Model.2), digits = 3,\n             caption = \"Model Comparison: Additive vs. Interaction\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model Comparison: Additive vs. Interaction\n\n| Res.Df|      RSS| Df| Sum of Sq|       F| Pr(>F)|\n|------:|--------:|--:|---------:|-------:|------:|\n|     78| 9522.081| NA|        NA|      NA|     NA|\n|     77| 3595.951|  1|   5926.13| 126.896|      0|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nAdditive model R<U+00B2>:      0.674 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInteraction model R<U+00B2>:   0.877 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nChange in R<U+00B2> (<U+0394>R<U+00B2>):    0.203 \n```\n\n\n:::\n:::\n\n\nThe interaction model explains substantially more variance. The F-test ($\\Delta R^2 =$ 0.203, $F(1, 77) =$ 126.9, $p < .001$) confirms that this improvement is far larger than would be expected by chance. Adding the interaction term was worth it.\n\n\n## Interpreting the Interaction Model\n\n### The Plot First\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_CatXCat_Interaction_files/figure-html/interaction-plot-1.png){fig-align='center' width=432}\n:::\n:::\n\n\nThis is the interaction model's predicted means for each cell. Notice the non-parallel lines: the \"Stay in\" line is nearly flat (very small gap between Low Nice and High Nice), while the \"Go out\" line rises steeply (a large gap between Low Nice and High Nice). Compare this to the additive model's forced parallel lines — the story told by these two models is completely different.\n\n### Walking Through Each Coefficient\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = NewFriends ~ NiceGroup_ * GoingOut_, data = Friend.Data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.7001  -4.7327  -0.0055   4.3511  18.0093 \n\nCoefficients:\n                                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                           15.950      1.367  11.670  < 2e-16 ***\nNiceGroup_High Nice                    3.045      2.023   1.505  0.13632    \nGoingOut_Go out                        6.649      2.188   3.039  0.00324 ** \nNiceGroup_High Nice:GoingOut_Go out   34.663      3.077  11.265  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.834 on 77 degrees of freedom\nMultiple R-squared:  0.8769,\tAdjusted R-squared:  0.8721 \nF-statistic: 182.8 on 3 and 77 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n### The Intercept ($B_0 =$ 15.95)\n\nThe intercept is the predicted friendship score for the **baseline cell**: Low Nice students who Stay in (both predictors at 0). This is a real, specific group of people in the dataset. A completely disagreeable person who never leaves home still forms about 15.95 points on the friendship thermometer — presumably because they live near someone and physical proximity does the work even for unsociable people.\n\n### $B_1$: Effect of High Niceness **Among Stay-in Students** ($B_1 =$ 3.05)\n\n$B_1$ is the difference in predicted friendship between High Nice and Low Nice students **within the Stay-in group**. Looking at the \"Stay in\" line in the plot, this gap is very small — and indeed, $B_1 =$ 3.05, which is essentially zero and non-significant.\n\nFor students who stay home, being highly agreeable provides virtually no additional benefit for friendship formation compared to being low in agreeableness. Without social exposure, personality differences do not matter much.\n\nThis is a **simple effect**: it is the effect of NiceGroup *within one specific level* of GoingOut (the reference level, Stay in). It is not a main effect.\n\n### $B_2$: Effect of Going Out **Among Low Nice Students** ($B_2 =$ 6.65)\n\n$B_2$ is the difference in predicted friendship between Go-out and Stay-in students **within the Low Nice group**. Students low in agreeableness who go out have about 6.65 more friends than their equally disagreeable counterparts who stay in.\n\nThis is also a **simple effect**: the effect of GoingOut *within one specific level* of NiceGroup (the reference level, Low Nice).\n\n### $B_3$: The Interaction Term ($B_3 =$ 34.66)\n\nThis is the heart of the analysis. $B_3$ tells you how much **larger** the effect of niceness is for the Go-out group compared to the Stay-in group.\n\nWe can reconstruct the simple effect of Niceness for each Going Out group:\n\n| Group | Simple effect of Niceness | Formula |\n|---|---|---|\n| Stay in | 3.05 | $B_1$ |\n| Go out | 37.71 | $B_1 + B_3 =$ 3.05 $+$ 34.66 |\n\nThe difference between these two simple effects is $B_3 =$ 34.66. For Go-out students, being highly agreeable is associated with about 37.71 more friends than being low in agreeableness. For Stay-in students, the same comparison yields only 3.05 more friends. The interaction coefficient captures this dramatic difference.\n\nHere is the full cell mean summary:\n\n| Cell | Predicted mean | Derivation |\n|---|---|---|\n| Low Nice × Stay in | 15.95 | $B_0$ |\n| High Nice × Stay in | 19 | $B_0 + B_1$ |\n| Low Nice × Go out | 22.6 | $B_0 + B_2$ |\n| High Nice × Go out | 60.31 | $B_0 + B_1 + B_2 + B_3$ |\n\n\n## Following Up the Interaction: Simple Effects\n\nThe interaction term tells us the two niceness gaps are significantly different between Going Out groups. But we also want to know: **within each Going Out group, is the difference between High Nice and Low Nice statistically significant?**\n\nWe use `pairs()` from the `emmeans` package to test each pairwise comparison within each level of the other variable.\n\n### Simple Effects of Niceness within Each Going-Out Group\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nFit.2 <- emmeans(Model.2, ~ NiceGroup_ | GoingOut_)\npairs(Fit.2, adjust = \"none\") %>% summary(infer = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"contrast\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"GoingOut_\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SE\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"lower.CL\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"upper.CL\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"t.ratio\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Low Nice - High Nice\",\"2\":\"Stay in\",\"3\":\"-3.045108\",\"4\":\"2.022837\",\"5\":\"77\",\"6\":\"-7.07309\",\"7\":\"0.9828742\",\"8\":\"-1.505365\",\"9\":\"1.363215e-01\",\"_rn_\":\"1\"},{\"1\":\"Low Nice - High Nice\",\"2\":\"Go out\",\"3\":\"-37.708151\",\"4\":\"2.318776\",\"5\":\"77\",\"6\":\"-42.32542\",\"7\":\"-33.0908786\",\"8\":\"-16.262094\",\"9\":\"1.281469e-26\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\n- **Stay-in group:** The difference between High Nice and Low Nice students is -3.05 points, which is **not** statistically significant ($p =$ 0.136). For students who stay in, agreeableness does not significantly predict friendship closeness.\n\n- **Go-out group:** The difference between High Nice and Low Nice students is -37.71 points, which is **highly** significant ($p <$ .001). Among students who go out, being highly agreeable is associated with substantially closer friendships than being low in agreeableness.\n\n### Effect Sizes: Cohen's *d*\n\nPairwise comparisons in this framework can be accompanied by Cohen's *d* as an effect size measure. We use the model's residual standard deviation as the pooled standard deviation:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neff_size(Fit.2,\n         sigma = sigma(Model.2),\n         edf   = df.residual(Model.2),\n         method = \"pairwise\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGoingOut_ = Stay in:\n contrast             effect.size    SE df lower.CL upper.CL\n Low Nice - High Nice      -0.446 0.298 77    -1.04    0.148\n\nGoingOut_ = Go out:\n contrast             effect.size    SE df lower.CL upper.CL\n Low Nice - High Nice      -5.518 0.559 77    -6.63   -4.404\n\nsigma used for effect sizes: 6.834 \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\n\nThe Cohen's *d* values confirm the pattern:\n\n- **Stay in:** $d =$ 0.45 — a negligible effect. Being nice does not meaningfully distinguish friendships for students who stay home.\n- **Go out:** $d =$ 5.52 — a large effect. Among students who go out, highly agreeable people form dramatically closer friendships than their less agreeable counterparts.\n\n\n## APA Write-Up\n\nHere is how you would report these results following APA style. The structure parallels the prior chapter: model comparison, interaction coefficient, then simple effects.\n\n\n\n\nCell means and standard deviations are presented in Table 1. Among students who stayed in, friendship closeness was similar regardless of agreeableness group (Low Nice: *M* = 16, *SD* = 7.3; High Nice: *M* = 19, *SD* = 7.1). Among students who went out, High Nice students formed substantially closer friendships than Low Nice students (Low Nice: *M* = 22.6, *SD* = 5; High Nice: *M* = 60.3, *SD* = 7.3).\n\nA hierarchical multiple regression was conducted to examine whether social engagement (Going Out) moderated the relationship between agreeableness group (Low vs. High Nice) and friendship closeness. Niceness group and Going Out (both dummy coded with Low Nice and Stay in as reference groups) were entered in Step 1 as main effects; their product was entered in Step 2. The additive model (Step 1) was statistically significant, $F(2, 78) =$ 80.64, $p < .001$, $R^2 =$ 0.674. Adding the interaction term (Step 2) produced a statistically significant improvement in model fit, $\\Delta R^2 =$ 0.203, $F(1, 77) =$ 126.9, $p < .001$, indicating that the effect of agreeableness on friendship closeness differed significantly depending on whether students went out.\n\nIn the full interaction model ($R^2 =$ 0.877, adjusted $R^2 =$ 0.872), the interaction between Niceness Group and Going Out was statistically significant, $b =$ 34.66, $SE =$ 3.08, $t(77) =$ 11.26, $p < .001$. To interpret the interaction, simple effects of Niceness Group were examined separately within each level of Going Out. Among students who stayed in, agreeableness group did not significantly predict friendship closeness, $b =$ -3.05, $SE =$ 2.02, $t(77) =$ -1.51, $p =$ 0.136, $d =$ 0.45. Among students who went out, High Nice students formed significantly closer friendships than Low Nice students, $b =$ -37.71, $SE =$ 2.32, $t(77) =$ -16.26, $p < .001$, $d =$ 5.52. These results indicate that the benefit of high agreeableness for friendship formation is conditional on social engagement: being a warm and agreeable person leads to substantially closer friendships only among students who are regularly out meeting others.\n\n\n**Things to notice about this write-up:**\n\n- We report **Cohen's *d*** alongside the simple effects, since the comparisons are between two categorical groups. This is the appropriate effect size for a two-group mean difference.\n- The **model comparison** ($\\Delta R^2$, F-test) is still the primary test of the interaction, exactly as in the prior chapter.\n- We describe the interaction in plain language: *\"the benefit of high agreeableness ... is conditional on social engagement.\"*\n- The **main effects** from the interaction model are not heavily emphasized. In the presence of a significant interaction, they represent effects at the reference level of the other variable (simple effects), not population-level averages.\n\n\n## APA-Style Figure\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# APA interaction plot: categorical × categorical\nFig.Data <- as.data.frame(emmeans(Model.2, ~ NiceGroup_ | GoingOut_))\n\nggplot(Fig.Data, aes(x = NiceGroup_, y = emmean,\n                     color = GoingOut_, group = GoingOut_)) +\n  # Raw data (faint)\n  geom_point(data = Friend.Data,\n             aes(x = NiceGroup_, y = NewFriends, color = GoingOut_),\n             alpha = 0.20, size = 1,\n             position = position_jitter(width = 0.12)) +\n  # Confidence intervals\n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL),\n                width = 0.08, linewidth = 0.8) +\n  # Connecting lines\n  geom_line(linewidth = 1.2) +\n  # Cell mean points\n  geom_point(size = 3.5) +\n  scale_color_manual(values = c(\"Stay in\" = \"#5b8db8\",\n                                \"Go out\"  = \"#e07b54\"),\n                     labels = c(\"Stay in\", \"Go out\")) +\n  scale_y_continuous(limits = c(0, 100),\n                     breaks = seq(0, 100, 20)) +\n  labs(x     = \"Agreeableness Group\",\n       y     = \"Predicted Friendship Closeness (0–100)\",\n       color = \"Social Engagement\") +\n  theme_bw() +\n  theme(legend.position   = \"top\",\n        legend.title      = element_text(size = 9),\n        legend.text       = element_text(size = 9),\n        axis.title        = element_text(size = 10),\n        panel.grid.minor  = element_blank())\n```\n\n::: {.cell-output-display}\n![](Chapter_CatXCat_Interaction_files/figure-html/apa-figure-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n*Figure 1.* Predicted friendship closeness as a function of agreeableness group and social engagement. Points represent model-estimated cell means; error bars represent 95% confidence intervals; faint points represent raw data. Among students who went out (*Go out*; orange), highly agreeable students formed substantially closer friendships than less agreeable students (*d* = 5.52). Among students who stayed in (*Stay in*; blue), agreeableness group was not significantly associated with friendship closeness (*d* = 0.45).\n\n\n## Comparison: Continuous × Categorical (the prior chapter) vs. Categorical × Categorical (This chapter)\n\nIt is worth pausing to compare the two approaches we have now seen.\n\n| Feature | Prior chapter (Continuous × Categorical) | This chapter (Categorical × Categorical) |\n|---|---|---|\n| Being Nice | Continuous (0–10) | Categorical (Low vs. High) |\n| Centering | Required | Not needed |\n| Interaction coefficient | Difference in slopes | Difference of differences |\n| Follow-up | `emtrends()` — simple slopes | `pairs()` — simple effects |\n| Effect size | Unstandardized slope (*b*) | Cohen's *d* |\n| Sample used | All 200 participants | ~80 (extremes only) |\n\nThe categorical version uses fewer participants (only the extremes of the niceness distribution), which means less statistical power. The continuous version squeezes more information out of the data because it uses every participant and models the full gradient of niceness effects.\n\nHowever, the categorical × categorical design is conceptually simpler and maps directly onto the two-way factorial ANOVA framework that many researchers in psychology use. Understanding both is essential.\n\n::: {.callout-important title=\"An Interaction Is a Difference of Differences\"}\nFirst compare the groups inside one condition. Then compare them inside the other condition. The interaction asks whether those two differences are different. If you skip that last comparison, you have described two results but have not tested an interaction.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}