{
  "hash": "84ac0cef17f72f37e8804b5c191b8912",
  "result": {
    "markdown": "---\ntitle: \"Reporting Models Without Making the Reader Solve a Puzzle\"\n---\n\n\n\n\n\n## The Analysis Is Not Finished When R Stops Printing\n\nA results section should let a reader reconstruct the statistical argument without opening your R session, reading your mind, or contacting the undergraduate who disappeared with the codebook.\n\nReport:\n\n- What was analyzed.\n- How variables were coded.\n- Which model was fitted and why.\n- Estimates in interpretable units.\n- Uncertainty.\n- Effect size or model fit.\n- Diagnostics and consequential deviations.\n- What the result supports and what it does not.\n\n::: {.callout-important title=\"Lead with the Scientific Result\"}\n“A regression was significant” is about software output. “Each additional hour of sleep predicted about four more memory points” is about the research question. Start with the second sentence.\n:::\n\n## One Reproducible Example\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\nn <- 180\nReportData <- data.frame(\n  Sleep = runif(n, 3, 9),\n  Caffeine = pmax(rnorm(n, 180, 85), 0),\n  Condition = factor(sample(c(\"Control\", \"Training\"), n, replace = TRUE))\n)\n\nReportData$Memory <-\n  38 + 3.8 * ReportData$Sleep -\n  .018 * ReportData$Caffeine +\n  5.5 * (ReportData$Condition == \"Training\") +\n  rnorm(n, 0, 7)\n\nReportModel <- lm(Memory ~ Sleep + Caffeine + Condition, data = ReportData)\n```\n:::\n\n\n\n## Descriptives Before Models\n\nDescribe the sample and variables needed to understand the model. Do not create a 47-column Table 1 containing every variable collected since the lab opened.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nDescriptives <- data.frame(\n  Variable = c(\"Memory\", \"Sleep\", \"Caffeine\"),\n  Mean = c(mean(ReportData$Memory), mean(ReportData$Sleep), mean(ReportData$Caffeine)),\n  SD = c(sd(ReportData$Memory), sd(ReportData$Sleep), sd(ReportData$Caffeine)),\n  Minimum = c(min(ReportData$Memory), min(ReportData$Sleep), min(ReportData$Caffeine)),\n  Maximum = c(max(ReportData$Memory), max(ReportData$Sleep), max(ReportData$Caffeine))\n)\n\nknitr::kable(Descriptives, digits = 2, caption = \"Descriptive statistics\")\n```\n\n::: {.cell-output-display}\nTable: Descriptive statistics\n\n|Variable |   Mean|    SD| Minimum| Maximum|\n|:--------|------:|-----:|-------:|-------:|\n|Memory   |  59.41|  9.98|   35.72|   87.23|\n|Sleep    |   5.81|  1.71|    3.03|    8.89|\n|Caffeine | 187.00| 77.65|    0.00|  385.28|\n:::\n:::\n\n\n\n## Extract Results from the Model Object\n\nNever type changing results manually into a table when R can extract them. Manual transcription creates opportunities to report the coefficient from Model 4, the p-value from Model 6, and the confidence interval from a model no one remembers fitting.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCoefficientTable <- broom::tidy(ReportModel, conf.int = TRUE)\nknitr::kable(\n  CoefficientTable,\n  digits = 3,\n  caption = \"Regression predicting memory performance\"\n)\n```\n\n::: {.cell-output-display}\nTable: Regression predicting memory performance\n\n|term              | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)       |   38.130|     2.487|    15.330|   0.000|   33.221|    43.038|\n|Sleep             |    3.600|     0.319|    11.283|   0.000|    2.970|     4.229|\n|Caffeine          |   -0.013|     0.007|    -1.845|   0.067|   -0.027|     0.001|\n|ConditionTraining |    5.064|     1.092|     4.637|   0.000|    2.909|     7.219|\n:::\n:::\n\n\n\nFor mixed models, use `broom.mixed::tidy()` because fixed effects, random-effect parameters, and model components require more supervision.\n\n### The One-Line Version You Will Actually Use on a Poster\n\n`broom::tidy()` plus `kable()` is the version you should understand, because it shows you that a table is just a data frame you built on purpose. When you need a publication-ready table right now, `sjPlot` (already the plotting package for this course) does the whole thing in one line:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# sjPlot: model tables and plots. tab_model() writes HTML, so this chunk only\n# runs for the web version of the book.\nlibrary(sjPlot)\n\ntab_model(ReportModel)\n```\n:::\n\n\n\nIt gives you estimates, confidence intervals, p-values, $R^2$, and $N$ without you typing a single number. Use it. Just remember that a beautiful table of a bad model is still a bad model: the checklist in the next section governs what belongs in the table, no matter who typeset it.\n\n## What Belongs in a Regression Table?\n\nAt minimum:\n\n- Predictor names readers understand.\n- Unstandardized estimates.\n- Standard errors or confidence intervals.\n- Test statistics and p-values when required.\n- Sample size.\n- Model $R^2$ and adjusted $R^2$ for ordinary regression.\n\nStandardized coefficients may supplement, not automatically replace, coefficients in meaningful original units.\n\n::: {.callout-warning title=\"Asterisks Are Not a Results Section\"}\nStars can help scan a table. They do not describe magnitude, uncertainty, practical importance, or whether the model made sense. Never make the reader infer the entire conclusion from celestial punctuation.\n:::\n\n## The APA Formatting Rules Nobody Tells You\n\nEvery chapter in this book has shown you an APA write-up. None of them stopped to say what the typographic rules actually are, and those rules are what you get points taken off for. Here they are in one place.\n\n| Rule | Wrong | Right |\n|---|---|---|\n| Statistical symbols are italic | t(176) = 11.28 | *t*(176) = 11.28 |\n| No leading zero when the number cannot exceed 1 | *p* = 0.067, *r* = 0.42 | *p* = .067, *r* = .42 |\n| Keep the leading zero when it can | *b* = .60, *M* = .48 | *b* = 0.60, *M* = 0.48 |\n| Two decimals for most statistics | *b* = 3.5997 | *b* = 3.60 |\n| Exact *p*, two or three decimals, with *p* < .001 as the floor | *p* < .05 | *p* = .067, or *p* < .001 |\n| Degrees of freedom in parentheses, attached to the symbol | *F* = 53.83, *df* = 3, 176 | *F*(3, 176) = 53.83 |\n| Spaces around =, < and > | *p*=.067 | *p* = .067 |\n| Confidence intervals in square brackets, comma between | CI = (2.97-4.23) | 95% CI [2.97, 4.23] |\n| Sample size travels with the statistic that needs it | $\\chi^2 = 16.08$ | $\\chi^2(1, N = 1379) = 16.08$ |\n\nThe italic rule is the one people lose points on, and the logic is simpler than it looks: **a Latin letter standing in for a statistic leans; a Greek letter does not.** So *M*, *SD*, *SE*, *N*, *n*, *p*, *r*, *t*, *F*, *b*, *d*, *df*, *OR* and $R^2$ are all italic, while $\\alpha$, $\\beta$, $\\chi^2$ and $\\sigma$ stay upright. The one Latin exception worth memorizing is **CI**, which is an abbreviation of two English words rather than a symbol, and stays upright.\n\nInside math it is handled for you: write `$t(98)$` or `$F(1, 97)$` and LaTeX italicizes the letter itself. Outside math you have to ask, which is why this book writes `*t*-test` rather than `t-test`.\n\nEvery write-up example in this book follows these rules. When your poster does not, the TA will find it, and the TA will be correct.\n\n## Plot Model-Based Predictions\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nPredictionData <- expand.grid(\n  Sleep = seq(3, 9, length.out = 100),\n  Caffeine = mean(ReportData$Caffeine),\n  Condition = levels(ReportData$Condition)\n)\n\nPredictionData$Predicted <- predict(ReportModel, newdata = PredictionData)\n\nplot(\n  ReportData$Sleep, ReportData$Memory,\n  pch = 19, col = rgb(.2, .2, .2, .18),\n  xlab = \"Hours of sleep\", ylab = \"Memory score\",\n  main = \"Model predictions at average caffeine use\"\n)\n\ncolors <- c(\"#0072B2\", \"#D55E00\")\nfor (i in seq_along(levels(ReportData$Condition))) {\n  group <- levels(ReportData$Condition)[i]\n  d <- PredictionData[PredictionData$Condition == group, ]\n  lines(d$Sleep, d$Predicted, lwd = 3, col = colors[i])\n}\nlegend(\"topleft\", legend = levels(ReportData$Condition),\n       col = colors, lwd = 3, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](Chapter_Reporting_files/figure-pdf/reporting-figure-1.pdf){fig-align='center' fig-alt='Scatterplot of memory score against hours of sleep, 180 faint grey points spread widely between about 36 and 87. Two straight prediction lines run across them, both climbing from left to right at the same slope: an orange Training line from about 51 to 73, and a blue Control line about five points below it throughout, from about 46 to 68. The lines are parallel because the model has no interaction term, and the vertical gap between them is the condition effect.'}\n:::\n:::\n\n\n\nFigures should show the comparison the model actually tested. Label axes in meaningful units, show uncertainty when it matters, and do not use a bar chart to hide a continuous distribution.\n\n## Example Write-Up\n\n\n\n\n\n\n\n> A multiple regression examined whether sleep, caffeine consumption, and training condition predicted memory scores, $R^2 =$ .48, adjusted $R^2 =$ .47, $F(3, 176) =$ 53.83, $p < .001$. Holding caffeine and condition constant, each additional hour of sleep predicted an estimated 3.60-point increase in memory performance, 95% CI [2.97, 4.23], $t(176) =$ 11.28, $p < .001$. Training participants scored 5.06 points higher than control participants at the same sleep and caffeine values, 95% CI [2.91, 7.22], $t(176) =$ 4.64, $p < .001$. Caffeine showed a small negative adjusted association that was not statistically distinguishable from zero, $b =$ -0.013 points per milligram, or about 1.3 points lower per 100 mg, 95% CI [-0.027, 0.001], $t(176) =$ -1.84, p = .067. Unstandardized coefficients and 95% confidence intervals appear in Table 2.\n\nEvery number in that paragraph was computed inline from `ReportModel`. Nothing was typed. If the model changes, the paragraph changes with it, which is the entire trick.\n\nUnderneath the numbers there is a template you can reuse for any coefficient: **claim in units, then the statistics in parentheses, then what it does and does not support.** Interpret the coefficients that answer the research question rather than reciting every cell of the table aloud.\n\nNotice what the caffeine sentence does. The estimate is negative, and it is also compatible with zero, so the sentence says both things and does not promote a non-significant coefficient to a finding by describing it confidently. That sentence is the one reviewers read most carefully.\n\nA real write-up also ends with a sentence about diagnostics: what you checked, and whether anything you found changed the interpretation. See the Advanced Regression Diagnostics chapter for what belongs in it.\n\n<!-- ---Alex--- The old version of this paragraph ended with \"Diagnostic plots did not\n     reveal a consequential violation of linearity or constant residual variance.\" I cut\n     that clause rather than filling it in, because it is not true of this model: the\n     errors are simulated homoscedastic, but `lmtest::bptest(ReportModel)` returns\n     p = .003 on this particular draw. Rather than assert a diagnostic the chapter never\n     runs, or bolt a diagnostics section onto a chapter whose brevity the review says is\n     right, I replaced it with a pointer to Ch19. Say the word if you would rather the\n     chapter actually ran the diagnostics here. -->\n\n\n## Reproducibility Checklist\n\n- Use a script or Quarto document.\n- Set random seeds for simulations.\n- Record package versions when reproducibility is important.\n- Keep raw data unchanged.\n- Document exclusions and transformations.\n- Generate tables and figures from fitted objects.\n- Store enough code to reproduce every reported number.\n\n::: {.callout-note title=\"Future You Is an Unreliable Collaborator\"}\nFuture You will not remember why `Model.Final.2.REAL.useThisOne` excludes participants 14 and 88. Write the reason now. Future You is busy, confused, and probably blaming Past You with considerable justification.\n:::\n\n## The Short Story\n\n- **Lead with the scientific result, not the software.** \"Each additional hour of sleep predicted about 3.6 more memory points\" is a finding. \"The regression was significant\" is a status update.\n- **Report the estimate, its uncertainty, an effect size or model fit, and the limits.** A coefficient with no interval is half a result.\n- **Generate every number from the fitted object.** Inline code and `broom::tidy()` cost less than one round of manual transcription, and they cannot report Model 4's coefficient beside Model 6's p-value.\n- **Say what the result does not support.** A coefficient compatible with zero gets described as compatible with zero.\n- **Follow the formatting rules above.** Italics, leading zeros, exact *p*, df in parentheses. They are free points.\n- **Leave a reproducible trail**, because Future You is an unreliable collaborator who will not remember why participant 88 is missing.\n",
    "supporting": [
      "Chapter_Reporting_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}