{
  "hash": "d2f9b7156abb7da267a3b14872fde9f3",
  "result": {
    "markdown": "---\ntitle: \"Paired Data: From the t-test to Regression\"\nfontsize: 11pt\ngeometry: margin=.5in\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n---\n\n\n\n\n\n::: {.callout-warning title=\"Advanced Chapter: The Same People Have Returned\"}\nThis chapter is harder than an ordinary t-test because each person gives us more than one score. Those scores know each other. Pretending they are independent is statistical identity theft.\n\nThe central idea is simple: **paired data contain between-person differences that we can remove or model.** We will reach that idea three ways—a paired t-test, a regression on difference scores, and a regression that represents each participant. The arithmetic changes costumes, but it is the same arithmetic underneath.\n:::\n\n## Why Pair the Scores?\n\nAn **independent-samples** design compares different people. Half the students receive chocolate during a lecture and half receive nothing except the lecture itself, which already seems cruel. Each student contributes one score.\n\nA **repeated-measures** design measures the same students twice. Every student attends one lecture without chocolate and one with chocolate. Each student is now their own control.\n\nA **matched-pairs** design uses different people who were deliberately matched on something important, such as age or baseline ability. This can help, but matched strangers are not magical clones. If you place two undergraduates beside each other because they have the same GPA, one may still be a morning person while the other communicates only through exhausted grunting.\n\nRepeated scores tend to be correlated because stable person characteristics follow people into both conditions. A student who generally looks at the screen for a long time may do that with or without chocolate. Another student may stare out the window in both conditions while contemplating escape. That stable person-to-person variation is useful information.\n\n## A Chocolate-Fixation Study\n\nSuppose we ask whether eating a small piece of chocolate during a lecture changes **fixation time**: the average number of seconds a student's eyes remain on the screen per glance. We measure 48 students twice:\n\n- once with no chocolate;\n- once with chocolate.\n\nThis example is simulated. Do not distribute mystery candy to human participants and announce that a textbook authorized it. Allergies, informed consent, and research ethics remain annoyingly real.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nn <- 48\nparticipant_effect <- rnorm(n, mean = 0, sd = 1.20)\n\npaired_wide <- data.frame(\n  participant = factor(seq_len(n)),\n  no_chocolate = 5.00 + participant_effect + rnorm(n, 0, 0.80),\n  chocolate = 5.75 + participant_effect + rnorm(n, 0, 0.80)\n)\n\npaired_wide$difference <-\n  paired_wide$chocolate - paired_wide$no_chocolate\n\npaired_long <- tidyr::pivot_longer(\n  paired_wide,\n  cols = c(no_chocolate, chocolate),\n  names_to = \"condition\",\n  values_to = \"fixation\"\n)\n\npaired_long$condition <- factor(\n  paired_long$condition,\n  levels = c(\"no_chocolate\", \"chocolate\"),\n  labels = c(\"No chocolate\", \"Chocolate\")\n)\n```\n:::\n\n\n\nThe wide data have one row per person and one column per condition. The long data have two rows per person. Paired t-tests are often easiest with wide data; regression models usually prefer long data. R is not being difficult for sport here. The two shapes answer different bookkeeping needs.\n\n## Look at the Pairs Before Testing Them\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n  paired_long,\n  aes(x = condition, y = fixation, group = participant)\n) +\n  geom_line(alpha = 0.30, color = \"gray55\") +\n  geom_point(alpha = 0.60, color = \"steelblue4\") +\n  stat_summary(\n    aes(group = 1), fun = mean, geom = \"line\",\n    color = \"firebrick\", linewidth = 1.3\n  ) +\n  stat_summary(\n    aes(group = 1), fun = mean, geom = \"point\",\n    color = \"firebrick\", size = 3\n  ) +\n  labs(\n    x = NULL,\n    y = \"Mean fixation time (seconds)\",\n    title = \"Every gray line is one exploited volunteer\"\n  ) +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](Chapter_RM_t_test_to_Regression_files/figure-pdf/plot-pairs-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n\nThe red line shows the mean change. The gray lines show something the means hide: some people change more than others, and a few may move in the opposite direction. If you plot only two bars, all those people are compressed into rectangular coffins.\n\n## The Paired t-test Is a One-Sample t-test in Disguise\n\nFor each person, compute a difference score:\n\n$$\nD_i=Y_{i,\\text{chocolate}}-Y_{i,\\text{no chocolate}}\n$$\n\nThen ask whether the population mean difference is zero:\n\n$$\nt=\\frac{M_D-0}{S_D/\\sqrt{n}}\n$$\n\nThat is just the one-sample t-test from an earlier chapter. The paired t-test does not compare two unrelated piles of scores. It reduces every pair to one difference and tests those differences.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npaired_result <- t.test(\n  paired_wide$chocolate,\n  paired_wide$no_chocolate,\n  paired = TRUE\n)\n\npaired_result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  paired_wide$chocolate and paired_wide$no_chocolate\nt = 4.3366, df = 47, p-value = 7.597e-05\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.4209697 1.1495099\nsample estimates:\nmean difference \n      0.7852398 \n```\n:::\n:::\n\n\n\nThe modern R syntax matters. The formula method of `t.test()` does not accept `paired = TRUE`, so this will fail:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(fixation ~ condition, data = paired_long, paired = TRUE)\n```\n:::\n\n\n\nUse the two paired vectors, as above. Even better, make the pairing visible by calculating the differences yourself:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndifference_result <- t.test(paired_wide$difference, mu = 0)\ndifference_result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  paired_wide$difference\nt = 4.3366, df = 47, p-value = 7.597e-05\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 0.4209697 1.1495099\nsample estimates:\nmean of x \n0.7852398 \n```\n:::\n:::\n\n\n\nThe t statistic, degrees of freedom, and p value match. R has not discovered two separate truths. We asked the same question twice.\n\n### Effect Size\n\nA simple standardized effect for paired data is Cohen's $d_z$:\n\n$$\nd_z=\\frac{M_D}{S_D}\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd_z <- mean(paired_wide$difference) /\n  sd(paired_wide$difference)\n\nd_z\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6259363\n```\n:::\n:::\n\n\n\nThis standardizes the mean change by the standard deviation of the **difference scores**. Say which version of $d$ you used because repeated-measures effect sizes have several denominators. Calling all of them “Cohen's d” and wandering away is how future readers begin sharpening office supplies.\n\n## Why Pairing Can Help\n\nThe variability of a difference score is:\n\n$$\nS_D^2=S_1^2+S_2^2-2rS_1S_2\n$$\n\nWhen the two measurements are positively correlated, the last term subtracts variability. Stable person differences cancel: the consistently attentive student is compared with themself, and the student planning an elaborate escape is also compared with themself.\n\nThis often gives a smaller standard error than an independent-samples analysis. Pairing does not guarantee more power, however. If the repeated scores barely correlate, little stable variation is removed. Pairing also cannot repair a terrible measure. Measuring attention with the number of times someone blinks at the ceiling remains a terrible plan in both conditions.\n\n## The Regression Version: Analyze the Differences\n\nA one-sample t-test is an intercept-only regression:\n\n$$\nD_i=b_0+e_i\n$$\n\nHere, $b_0$ is the mean difference. Testing $H_0:b_0=0$ is exactly the paired t-test.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndifference_model <- lm(difference ~ 1, data = paired_wide)\nsummary(difference_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = difference ~ 1, data = paired_wide)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.6116 -0.5073  0.0122  0.8281  2.8700 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   0.7852     0.1811   4.337  7.6e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.255 on 47 degrees of freedom\n```\n:::\n:::\n\n\n\nCompare the intercept's estimate and t statistic with the paired t-test. Same answer. Regression has merely put on a fake mustache.\n\nThis form is especially useful when you want to predict **change**. For example, you could model whether baseline caffeine consumption predicts the chocolate-minus-no-chocolate difference. Be careful with causal language: predicting change does not automatically mean causing change. A regression coefficient is not an ethics-approved time machine.\n\n## The Long-Data Regression: Give Every Person an Intercept\n\nWe can also keep both observations and explicitly represent each participant:\n\n$$\nY_{ij}=b_0+b_1(\\text{Chocolate}_{ij})+\\text{Participant}_i+e_{ij}\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparticipant_model <- lm(\n  fixation ~ condition + participant,\n  data = paired_long\n)\n\nsummary(participant_model)$coefficients[1:2, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    Estimate Std. Error  t value     Pr(>|t|)\n(Intercept)        2.9047856  0.6337524 4.583471 3.386528e-05\nconditionChocolate 0.7852398  0.1810721 4.336614 7.597238e-05\n```\n:::\n:::\n\n\n\nR creates an indicator for each participant. Those indicators absorb stable differences between people. The coefficient for `conditionChocolate` is the average chocolate-minus-no-chocolate change, and its t test matches the paired t-test in this balanced two-condition design.\n\nDo **not** fit this model and omit the participant term:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwrong_model <- lm(fixation ~ condition, data = paired_long)\n\nc(\n  paired_SE = summary(participant_model)$coefficients[\n    \"conditionChocolate\", \"Std. Error\"\n  ],\n  ignored_pairing_SE = summary(wrong_model)$coefficients[\n    \"conditionChocolate\", \"Std. Error\"\n  ]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         paired_SE ignored_pairing_SE \n         0.1810721          0.2442859 \n```\n:::\n:::\n\n\n\nThe second model acts as if 96 observations came from 96 unrelated people. They did not. We have 48 people wearing two condition labels. Ignoring that structure usually gives the wrong standard error because the model has misunderstood where the variation came from.\n\n## A Mixed Model: People as a Random Effect\n\nCreating 47 participant indicators is manageable here but becomes clumsy with hundreds of people. A mixed-effects model represents participant-to-participant variation with a **random intercept**:\n\n$$\nY_{ij}=b_0+b_1(\\text{Chocolate}_{ij})+u_{0i}+e_{ij}\n$$\n\nThe fixed effect $b_1$ estimates the average condition difference. The random intercept $u_{0i}$ lets each person have their own usual level of fixation.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmixed_model <- glmmTMB::glmmTMB(\n  fixation ~ condition + (1 | participant),\n  data = paired_long,\n  REML = TRUE\n)\n\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: gaussian  ( identity )\nFormula:          fixation ~ condition + (1 | participant)\nData: paired_long\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n    305.6     315.9    -148.8     297.6        92 \n\nRandom effects:\n\nConditional model:\n Groups      Name        Variance Std.Dev.\n participant (Intercept) 0.6453   0.8033  \n Residual                0.7869   0.8871  \nNumber of obs: 96, groups:  participant, 48\n\nDispersion estimate for gaussian family (sigma^2): 0.787 \n\nConditional model:\n                   Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          4.7660     0.1727  27.591  < 2e-16 ***\nconditionChocolate   0.7852     0.1811   4.337 1.45e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n\nWith two complete measurements per person and this simple balanced design, the paired t-test, participant-indicator regression, and random-intercept model give nearly the same substantive answer. Mixed models become far more useful when there are three or more occasions, unequal numbers of observations, missing occasions, or predictors that vary across people and time.\n\n### Intraclass Correlation\n\nThe **intraclass correlation coefficient** (ICC) describes how much outcome variance reflects stable differences between participants:\n\n$$\nICC=\\frac{\\sigma^2_{\\text{participant}}}\n{\\sigma^2_{\\text{participant}}+\\sigma^2_e}\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nparticipant_variance <- as.numeric(\n  lme4::VarCorr(mixed_model)$cond$participant[1, 1]\n)\nresidual_variance <- sigma(mixed_model)^2\n\nICC <- participant_variance /\n  (participant_variance + residual_variance)\n\nICC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4505775\n```\n:::\n:::\n\n\n\nA larger ICC means repeated scores from the same person resemble one another more strongly. It is **intraclass**, not “inter-class.” We are measuring clustering *within* people, not arranging statistical gladiator combat between classes.\n\n## Assumptions That Actually Matter\n\nFor the ordinary paired t-test:\n\n- the pairs are meaningfully matched;\n- different pairs are independent of one another;\n- the outcome is quantitative;\n- the **difference scores** have no severe outliers;\n- for small samples, the population distribution of difference scores is reasonably normal.\n\nThe paired t-test does **not** require the two condition variances to be equal. The analysis operates on one set of differences. Inspect those differences—not two separate normality tests performed as ritual offerings.\n\nFor the mixed model, also examine whether its functional form and variance structure are sensible. `glmmTMB` reports Wald z tests for the fixed effects. Those are large-sample approximations, not messages carved onto stone tablets. The later mixed-model inference chapter shows likelihood-ratio tests, confidence intervals, diagnostics, and the narrow situation in which a Gaussian model may be refit with `lmerTest` for ANOVA-style denominator degrees of freedom.\n\n## More Than Two Repeated Conditions\n\nWith three or more conditions, one difference score can no longer represent the whole design. You could run many paired t-tests, but then the familywise-error creature crawls out from under the desk. Instead, use a repeated-measures model and follow a meaningful overall test with planned contrasts or multiplicity-adjusted comparisons.\n\nFor example:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nthree_condition_model <- glmmTMB::glmmTMB(\n  outcome ~ condition + (1 | participant),\n  data = long_data,\n  REML = TRUE\n)\n\nemmeans::emmeans(three_condition_model, pairwise ~ condition,\n                 adjust = \"holm\")\n```\n:::\n\n\n\nIf participants differ not only in their starting points but also in how they respond across time, they may need random slopes. That problem is waiting in the mixed-design chapter with a tiny clipboard and several unpleasant questions.\n\n## Reporting the Result\n\nFor the present study, a concise report could be:\n\n> Students showed longer fixation times during the chocolate condition ($M =$ 5.55, $SD =$ 1.33) than during the no-chocolate condition ($M =$ 4.77, $SD =$ 1.05). The mean paired difference was 0.79 seconds, 95% CI [0.42, 1.15], $t(47) =$ 4.34, $p$ < .001, $d_z =$ 0.63.\n\nThe statistic cannot prove that chocolate *caused* better attention unless the study was properly randomized and alternative explanations were controlled. It certainly cannot prove that replacing every lecture with a bucket of candy is sound educational policy.\n\n## The Short Story\n\n- Paired data are dependent because the same person contributes multiple scores.\n- A paired t-test is a one-sample t-test on difference scores.\n- An intercept-only regression on those differences produces the same test.\n- A long-data regression can control each participant with participant indicators.\n- A mixed model handles participant variation with random effects and extends more naturally to complicated repeated data.\n- Check the distribution and outliers of the **differences**, not equality of the two condition variances.\n- Never ignore the participant identifier unless you enjoy standard errors built on fiction.\n\nThe grand lesson is not “memorize another command.” It is “tell the model which observations came from the same human.” The humans already know. R needs paperwork.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}