{
  "hash": "b49a7ab32434a730f2cd296aee69aa26",
  "result": {
    "markdown": "---\ntitle: \"Power and Effect Size\"\n---\n\n\n\n\n::: {.callout-note title=\"Some of Today's Code Is Not Your Problem\"}\nA few figures in this chapter are generated with genuinely unpleasant code. Where you see a plot appear without the code attached, that is deliberate: I hid it because you are not expected to learn it, yet. Every function you *are* expected to learn is shown, explained, and used more than once.\n\nIf you find yourself reading the hidden code anyway, good for you! Dorkaos, the Ancient Greek God of Statistics, is watching, and approves.\n:::\n\n::: {.callout-tip title=\"Where the Exam Material Lives in This Chapter\"}\nThis is the longest chapter in the book, so here is the map before you start.\n\n- **First section**: *why* power exists, which comes down to the fact that small samples flatter you. Conceptually the hardest part.\n- **The middle**: the vocabulary that most people put on the exams (Type I and Type II error, $\\alpha$, $\\beta$, power) and how to compute power in R. If you are short on time, start at \"Type I and Type II Error\" and read forward.\n- **Advanced Topics at the end**: for when someone you love runs a pilot study.  Not Optional for graduate students.\n:::\n\n## Probability Is Fickle\n\nBefore we can talk about power, we have to admit something uncomfortable about small samples.\n\nRecall that the standard error is the standard deviation of sample means. Let us build a population for children's hyperactivity scores, the same population from the one-sample *t*-test chapter, with $\\mu = 50$ and $\\sigma = 5$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The population of hyperactivity scores, with the middle 95% shaded.](Ch_07_Power_Effect_Size_files/figure-html/population-pdf-1.png){fig-align='center' fig-pos='H' fig-alt='A normal curve centered on 50. The region between about 40 and 60 is filled in red, and a label above reports that this shaded area holds 95% of children.' width=480}\n:::\n:::\n\n\nAbout 95% of children score between 40.2 and 59.8. Fine. Now let us collect some data.\n\n### Ten Small Studies\n\nSuppose we run ten separate studies, each with $n = 13$ children. Ten data collections, thirteen children each, one hyperactivity score per child.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Ten studies, ten means. None of them is 50, and that is the point.](Ch_07_Power_Effect_Size_files/figure-html/ten-samples-1.png){fig-align='center' fig-pos='H' fig-alt='Histogram of ten study means spread between about 48 and 51, scattered around the true population mean of 50 rather than landing on it.' width=480}\n:::\n:::\n\n\nThe mean of those ten sample means was 49.721, comfortably close to $\\mu = 50$. Good.\n\nNow check the *spread*. Our formula predicts a standard error of\n\n$$\n\\sigma_M = \\frac{\\sigma}{\\sqrt{n}} = \\frac{5}{\\sqrt{13}} = 1.39.\n$$\n\nIn reality, those ten studies produced $SD(\\text{sample means}) =$ 0.73.\n\nThose are not the same number. **Why?**\n\n### The Answer Is Unpleasant\n\nTwo different things are bouncing around here, and they are worth keeping apart, because this is exactly the two-counts trap the standard error chapter warned about.\n\nThe first is not very interesting. We computed a standard deviation from only **ten numbers**, the ten study means. A standard deviation built from ten values is itself a shaky estimate, and some of that gap is just that.\n\nThe second one is the reason this chapter exists. The same disease infects the $S$ that any single study computes from its **thirteen children**. With only thirteen people, you are most likely to grab from the fat middle of the distribution, because that is where most people live. The extremes are rare, so small samples usually miss them. Miss the extremes, and your estimate of spread comes out too small.\n\nLet us prove that second one with brute force. We will run 5,000 separate studies of thirteen children each, and look at the standard deviation each study reports back:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(543)\n\n# Run 5,000 studies. Each one grabs 13 children from a population where we\n# KNOW the true spread is sigma = 5, and reports the SD it happened to see.\nSample.SD <- replicate(5000, sd(rnorm(n = 13, mean = 50, sd = 5)))\n\nhist(Sample.SD,\n     main = \"Histogram\",\n     xlab = \"SD reported by each study \\n(5000 studies, n = 13 each)\",\n     ylab = \"Frequency\")\nabline(v = 5, col = \"red\", lwd = 4)   # the TRUE sigma\n```\n\n::: {.cell-output-display}\n![What 5,000 small studies report as their SD, against the truth in red.](Ch_07_Power_Effect_Size_files/figure-html/sem-fickle-1.png){fig-align='center' fig-pos='H' fig-alt='Histogram of standard deviations reported by 5,000 studies of thirteen children each. The pile is slightly right-skewed and sits noticeably to the left of a thick red vertical line marking the true sigma of 5, showing that most studies report a spread smaller than the real one.' width=480}\n:::\n:::\n\n\nThe red line is the truth, $\\sigma = 5$. Notice the histogram is **not centered on it**. In this simulation 55.6% of studies reported a standard deviation *below* the true value and only 44.4% landed above it. The average study reported 4.89 when the truth was 5.\n\nThat is not a rounding artifact, it is a known bias, and the theory predicts it almost exactly. For samples of 13 from a normal population, the expected value of $S$ works out to 4.897. Our 5,000 simulated studies averaged 4.893. The math and the brute force agree to three decimal places, which is the kind of thing that should make you trust both.\n\nSmall samples systematically underestimate variability. This is the problem Gosset walked into when he stopped using a known $\\sigma$ and started using a sample $S$ as an approximation, and it is why we have a *t*-distribution at all.\n\n::: {.callout-important title=\"This Is the Whole Reason Power Exists\"}\nYour sample gives you one guess about the mean and one guess about the spread. Both guesses bounce around, and the smaller the sample, the harder they bounce. Worse, the guess about the spread does not bounce evenly. It lands low more often than high, in a direction that flatters you.\n\nThe solution is not to stop guessing. The solution is to work out, **before you collect data**, how likely you are to detect an effect given your specific sample size and how big the effect probably is.\n\nThat calculation is called power. Everything else in this chapter is machinery for doing it.\n:::\n\n## Type I and Type II Error\n\nEvery hypothesis test ends in a decision, and every decision can be wrong in exactly two ways.\n\n|  | Treatment works ($H_0$ FALSE) | Treatment does nothing ($H_0$ TRUE) |\n|-----------------|------------------------|------------------------|\n| **Reject $H_0$** | Correct decision (**power**) | **Type I error** ($\\alpha$) |\n| **Fail to reject $H_0$** | **Type II error** ($\\beta$) | Correct decision |\n\n**Type I error** is a false alarm. There is no effect, and you claim there is one. Its long-run rate is $\\alpha$, and you choose $\\alpha$ yourself, usually .05, by simple decree.\n\n**Type II error** is a miss. There *is* an effect, and you fail to find it. Its rate is $\\beta$, and you do **not** get to choose it directly. You have to earn your way out of it.\n\n**Power** is $1 - \\beta$: the probability of detecting an effect that is genuinely there.\n\nNotice the asymmetry. Alpha is a decision you make in about four seconds. Power is something you buy, with participants, and it is expensive.\n\n::: {.callout-warning title=\"What Alpha Does Not Mean\"}\nSetting $\\alpha = .05$ does **not** mean any of the following:\n\n- there is a 5% probability that this particular rejected null is true;\n- 5% of published findings are wrong;\n- your result has a 95% chance of replicating.\n\nIt means that *if* the null hypothesis and its assumptions hold, this **procedure** falsely rejects about 5% of the time in the long run. The *p*-value is a statement about a procedure. It cannot read the hidden state of the universe, and it has never once tried.\n:::\n\n### The Errors Are Not Symmetric in Cost\n\nA Type I error means we run around telling everyone that cookies make children hyperactive when they do not. Parents ban cookies. A generation grows up sad.\n\nA Type II error means cookies *do* make children hyperactive, we fail to notice, and we spend the next decade blaming the children.\n\nWhich error is worse depends entirely on what happens next, which is a question statistics cannot answer for you. A false alarm on a cancer screening costs a biopsy. A miss costs considerably more.\n\nPsychology and neuroscience have historically obsessed over Type I error and treated Type II error as somebody else's problem. Button and colleagues surveyed the neuroscience literature and estimated median statistical power at around 21% [@button2013], which means the typical study had roughly a one-in-five chance of finding an effect that was genuinely there. This is one of several reasons the replication crisis arrived carrying luggage and expecting to stay a while.\n\n## Signal Detection Theory\n\nGiven that I must estimate my standard error from an $S$ that bounces around, I need a way to say how \"big\" an effect is in the first place.\n\nThe one-sample *t*-test chapter ended by handing you a $d$ and refusing to explain it. Here is the explanation.\n\nCohen borrowed the idea from signal detection theory, developed for radar operators in World War II who had to decide whether that blip was a plane or noise. The question there was: how strong must a signal be before you can detect it over the noise? For us, the noise is the control condition and the signal is the effect of the treatment.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Signal detection. The gap between the two peaks, measured in standard deviations, is d.](Ch_07_Power_Effect_Size_files/figure-html/sdt-figure-1.png){fig-align='center' fig-pos='H' fig-alt='Two overlapping bell curves. The left is labelled N for noise and the right N plus S for signal plus noise. A double-headed blue arrow between the peaks is labelled d.' width=600}\n:::\n:::\n\n\n$$\nd = \\frac{\\mu_{(Noise+Signal)} - \\mu_{(Noise)}}{\\sigma_{(Noise)}}\n$$\n\nSignal detection theory also hands us this chapter's 2×2 for free. Here is the hearing-test version of the table above, and it is the *same table*:\n\n|  | There **was** a beep | There was **no** beep |\n|-------------|---------------|-------------------|\n| You said **YES** | Hit | False alarm |\n| You said **NO** | Miss | Correct rejection |\n\nHit, miss, false alarm, correct rejection. Power, Type II error, Type I error, correct decision. Same 2×2, different lab coat. Detecting a treatment effect and detecting a faint beep are the same problem, and the reason both fields drew the same table is that both are asking how far the signal has to sit from the noise before you can trust yourself.\n\n### Cohen's $d$\n\nFor our purposes:\n\n$$\nd = \\frac{M_{H1} - \\mu_{H0}}{S_{H1}}\n$$\n\nYou have seen this formula before, wearing a different hat:\n\n$$\nZ = \\frac{M - \\mu}{S}\n$$\n\nSo Cohen's $d$ is in standard deviation units.\n\nThat denominator carries an assumption worth naming: we are treating the treatment as something that shifts the distribution without changing its spread. Sometimes that is true. Sometimes a treatment helps some people enormously and others not at all, which changes the spread, and then this formula is quietly describing a world that does not exist.\n\n| Size | $d$ |\n|--------|------|\n| Small | .2 |\n| Medium | .5 |\n| Large | .8 |\n| Huge | 1.2 |\n\nThose adjectives are easier to trust once you see them. Each panel below shows two distributions separated by the $d$ in its title:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Small, medium, large, and huge. Note how much overlap survives even at the bottom right.](Ch_07_Power_Effect_Size_files/figure-html/effect-size-visuals-1.png){fig-align='center' fig-pos='H' fig-alt='Four panels of two overlapping bell curves each. At d = .2 the curves are nearly on top of each other; at .5 the peaks are clearly apart; at .8 they are well separated; and at 1.2 they are separated by more than a standard deviation, yet a substantial shared region remains in every panel.' width=624}\n:::\n:::\n\n\n::: {.callout-note title=\"Even a Huge Effect Overlaps\"}\nLook at the bottom-right panel again. That is a *huge* effect, and the two distributions still share an enormous amount of ground.\n\nThat overlap is the point. Two groups can differ by a \"large\" amount and still contain enormous numbers of people who look exactly like each other. An effect size is a statement about distributions, not about individuals, and it has never promised you a clean separation.\n:::\n\n::: {.callout-warning title=\"These Adjectives Are Conventions, Not Laws\"}\nCohen proposed small, medium, and large as rough guidance for a field that had none, and then spent years watching people treat them as physical constants.\n\nA $d$ of .2 for a cheap public health intervention delivered to forty million people may matter enormously. A $d$ of 1.1 in a study of twelve undergraduates may matter not at all. Interpret magnitude in context, or do not interpret it.\n:::\n\n## Power\n\nPower is the likelihood that a study will detect an effect when there genuinely is one. Power $= 1 - \\beta$, where $\\beta$ is the Type II error rate [@cohen1962; @cohen1988; @cohen1992].\n\nHere is the whole thing in one picture.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Power is the slice of the alternative distribution that clears the critical value.](Ch_07_Power_Effect_Size_files/figure-html/power-figure-1.png){fig-align='center' fig-pos='H' fig-alt='Two overlapping bell curves, the null on the left and the alternative on the right. A vertical line marks the critical value, and the portion of the right-hand curve beyond it is shaded to represent power.' width=600}\n:::\n:::\n\n\nRead it left to right. The black curve is the world where the null is true. The red curve is the world where the effect is real. The dashed line is your critical value, the point past which you will reject the null.\n\n- Everything to the right of the dashed line **under the black curve** is $\\alpha/2$: rejecting when you should not have.\n- Everything to the left of the dashed line **under the red curve** is $\\beta$: the effect was real and you missed it.\n- Everything to the right of the dashed line **under the red curve** is power.\n\nMove the dashed line left and you gain power while buying more Type I error. Move it right and the reverse. Push the red curve further right, or make both curves narrower, and power improves without that trade. Which is the entire game.\n\n### Uses of Power\n\n**A priori power** means setting a target likelihood of success (say, power = .80) at a given $\\alpha$ (say, .05), assuming a *true* effect size, and solving for the sample size you need [@cohen1962; @cohen1988; @cohen1992]. This is the useful one. It is also the hard one, because it requires knowing the true effect size, which is the thing you are running the study to find out.\n\nWe used to tell people to go find a meta-analysis. Then it turned out meta-analytic effect sizes are inflated by publication bias [@kicinski2015], because studies that found nothing were never published and therefore never averaged in. A rule of thumb: assume your effect is small-to-medium, $d = .3$ or $.4$, and be pleasantly surprised rather than catastrophically wrong.\n\n**Post-hoc power** means estimating the power you achieved using the effect size you *observed*, your sample size, and your $\\alpha$.\n\nPost-hoc power is meaningless. It is worse than meaningless, because it looks like information.\n\n::: {.callout-important title=\"Post-Hoc Power Is a Ghost\"}\nObserved power is a one-to-one function of your *p*-value. A significant result *always* yields high observed power; a non-significant result *always* yields low observed power. It cannot tell you anything your *p*-value did not already tell you, and it is frequently used to argue \"our null result was just underpowered,\" which is circular reasoning with a calculator [@hoenig2001].\n\nWorse, the effect size feeding it is biased. As we saw at the start of this chapter, small samples underestimate $\\sigma$. A smaller denominator makes $d$ bigger. Your observed effect is flattering you, and post-hoc power then launders the flattery into a number with a decimal point.\n\nCompute power **before** you run the study. Afterwards, report the confidence interval and let it speak.\n:::\n\n## Power and Significance Testing\n\nThere is a subtlety here that trips up nearly everyone, so we will be slow about it.\n\nEverything above drew the curves in **standard deviation** units. But significance testing does not happen in standard deviation units. It happens in **standard error** units. And the standard error shrinks as $N$ grows, because $S_M = S/\\sqrt{n}$.\n\nThe distance between the peaks is the effect size, and it does **not** change with sample size. What changes is how *wide* the curves are.\n\n::: {.callout-tip title=\"Homer Simpson and the Statistically Significant Hair\"}\nIn \"Simpson and Delilah\" (The Simpsons, S2:E2), Homer takes Dimoxinil and wakes up the next morning with a full luscious head of hair. That is an enormous effect size.\n\nIn reality, Minoxidil grows back very little hair, after months of twice-daily application, in a subset of men, most of whom keep checking the mirror hopefully (*speaking from experience*). The effect is genuinely small. It is also statistically significant, because \"most men experience *some* growth beyond noise,\" and noise here is defined in standard error units, not standard deviation units.\n\nStatistically significant is not the same as clinically significant. It is not even the same as noticeable. Homer's hair is a story about effect size. The clinical trial is a story about standard errors.\n:::\n\nWatch the curves narrow while the peaks stay exactly where they are. The effect below is a medium one, $d = .5$, in all four pictures.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The same half-point difference, seen through progressively narrower sampling distributions.](Ch_07_Power_Effect_Size_files/figure-html/se-narrowing-1.png){fig-align='center' fig-pos='H' fig-alt='A grid of panels, each showing the same pair of overlapping curves separated by half a point. Moving through the panels the curves become narrower and taller, so the same fixed difference goes from almost total overlap to clean separation.' width=624}\n:::\n:::\n\n\nThe area representing $1 - \\beta$ grows as we add participants, because the curves get thinner while the distance between them stays fixed.\n\nThis is why effect size is described as independent of sample size and significance is not. That statement is true if you know the population standard deviation $\\sigma$. We never do. We approximate it with $S$, so our observed effect size is itself another guess, subject to the same fickleness we opened this chapter with. Which is why we hope meta-analysis, averaging over many studies, gives a steadier estimate, right up until publication bias mugs it in an alley.\n\n::: {.callout-warning title=\"Advanced: Effect Size and the Pilot Study Trap\"}\nA few lines ago I said sample size is independent of effect size. That is half true, and here is the other half.\n\nLook at the formula again: $d = \\frac{M - \\mu}{S}$. We are estimating **two** things from our sample to guess at one true effect size in the population. In a small sample, both of them bounce around. But there is a hidden way they bounce, and it is not symmetric.\n\nIn a small sample you are unlikely to catch the genuinely abnormal people, because there are not many of them and you did not grab many people. Miss the extremes and your $S$ comes out smaller than it should be. That is bias, not bad luck, and it happens on average.\n\nSo what? Look at where $S$ sits. It is the **denominator**. When the denominator comes out too small, the effect size comes out too big.\n\nHow bad is it? Bad. Under realistic small-sample conditions the observed effect can run **roughly twice** what it should be. I am not asking you to take my word for it, because there is a simulation in the Advanced Topics section at the end of this chapter that shows exactly this happening.\n\nNow think about what that means for a **pilot study**, where the entire point is to run a small sample to decide whether the real study is worth doing. Your pilot is systematically biased toward telling you yes. Then you power your real study on that inflated number, recruit far too few people, and find nothing.\n\nThere is no consensus in the literature beyond \"interpret with caution,\" and I show a couple of the proposed fixes in the advanced section. My own solution is to throw lots of undergraduates into the volcano and hope it does not happen to me.\n:::\n\n## Estimating A Priori Power in R\n\nBase R ships with a power function for *t*-tests. No package required.\n\nIt needs five pieces of information, and you already know all of them by other names:\n\n| Argument | What it is in the words we have been using |\n|---|---|\n| `n` | sample size |\n| `delta` | the effect size, in Cohen's $d$ units (see the tip below) |\n| `sd` | the standard deviation (set this to 1 and `delta` becomes $d$) |\n| `sig.level` | $\\alpha$, your Type I error rate, almost always .05 |\n| `power` | $1 - \\beta$, the chance of catching the effect if it is real |\n\nYou fill in four and leave one as `NULL`. R solves for the blank.\n\n::: {.callout-important title=\"Why Everyone Uses .80, and Why That Is Not Very Impressive\"}\nConvention says aim for power of **.80**. Say that out loud in the other direction: $\\beta = 1 - .80 = .20$, so a study designed to the field's standard **misses a real effect one time in five.** That is the norm, not the failure case.\n\nPlenty of people now argue for **.95**, which drops the miss rate to one in twenty. Excellent idea. Now buy it.\n\nSample size does not scale linearly with power. Going from .80 to .95 does not cost you a few extra participants, it costs a great many, and we will watch exactly how badly it scales later in this chapter. Get your wallet out.\n:::\n\n::: {.callout-tip title=\"How to Make power.t.test Speak Cohen's d\"}\n`power.t.test()` wants a raw mean difference (`delta`) and a standard deviation (`sd`), not a $d$.\n\nThe trick: **set `sd = 1` and put your $d$ in `delta`.** Because $d = \\delta / \\sigma$, setting $\\sigma = 1$ makes the raw difference and the standardized difference the same number.\n\n```r\npower.t.test(delta = 0.4, sd = 1, ...)   # this is d = .4\n```\n\nEverything in this chapter uses that convention. If you ever want to work in raw units instead, supply both the real `delta` and the real `sd` and it will happily oblige.\n:::\n\nThe `type` argument picks which *t*-test you mean:\n\n| `type` | Design | What `n` means |\n|--------|--------|----------------|\n| `\"one.sample\"` | one group vs. a fixed value | total participants |\n| `\"two.sample\"` | two independent groups | participants **per group** |\n| `\"paired\"` | same people measured twice | number of **pairs** |\n\nGetting `n` wrong here is the single most common power mistake. A `two.sample` answer of 64 means **128 people**.\n\n### One-Sample: The Cookies Return\n\nRecall the one-sample study: we feed children cookies and compare their hyperactivity to a hypothesized population value of $\\mu = 50$. The steps were:\n\n1. Assume a population value to test against, here $\\mu = 50$.\n2. Collect a sample of children and feed them cookies.\n3. Compute the sample mean $M$ and standard deviation $S$.\n4. Ask whether $M$ sits farther from 50 than sampling error can comfortably explain.\n\n::: {.callout-note title=\"In a Real Study You Do Not Get to Build the Population\"}\nThe first two lines below manufacture a million children out of nothing, and then the next line grabs 36 of them. That is not what research looks like.\n\nIn the real world there is no `Population` object. You go out and *find* your population, then kidnap, I mean politely ask their parents for permission after your IRB approves the study, and then feed actual children actual cookies and measure what happens.\n\nI simulate because it is free, instant, and nobody's child ends up climbing a curtain. But everything after the sampling step is identical to what you would do with real data.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Simulate our population: a million children we will never meet.\nPopulation <- rnorm(1e6, mean = 50, sd = 5)\n\nset.seed(42)\n\n# Sample 36 kids (for real if you can, but I am lazy, so we simulate it)\n# and give each one a 2-point cookie boost.\nkids.1 <- sample(Population, 36, replace = TRUE) + 2\n\nM_kids <- mean(kids.1)                 # our sample mean\nS_kids <- sd(kids.1)                   # our sample SD\nd_kids <- (M_kids - 50) / S_kids       # Cohen's d: how far from 50, in SD units\n\nround(c(M = M_kids, SD = S_kids, n = length(kids.1), d = d_kids), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     M     SD      n      d \n53.035  4.356 36.000  0.697 \n```\n:::\n:::\n\n\nSuppose we are designing this study fresh and expect a small-to-medium effect, $d = .4$. How many children do we need for 80% power?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAt.Power.80 <- power.t.test(n = NULL,              # <- the unknown we want solved\n                            delta = .4,            # the effect size we expect\n                            sd = 1,                # sd = 1 makes delta mean \"Cohen's d\"\n                            sig.level = 0.05,      # our alpha\n                            power = .80,           # the power we are demanding\n                            type = \"one.sample\",   # which t-test\n                            alternative = \"two.sided\")\nAt.Power.80\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     One-sample t test power calculation \n\n              n = 51.00957\n          delta = 0.4\n             sd = 1\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n:::\n:::\n\n\nThat is one function with one trick, and the trick is the `NULL`. `power.t.test()` takes five quantities that constrain each other, and it solves for **whichever one you leave as `NULL`**. Here we left `n = NULL` and asked how many people we need. Leave `power = NULL` instead and it tells you the power you have. Leave `delta = NULL` and it tells you the smallest effect you could catch. Same function, three different questions, and we will ask all three below.\n\nThe `sd = 1` is worth a second look too. It is not a claim about your data. Setting it to 1 puts `delta` in standard-deviation units, which means you can hand `delta` a Cohen's $d$ directly and R will do the right thing.\n\nWe always **round up**: 52 children. You cannot recruit a fractional child, and rounding down leaves you below your target.\n\nNow the same question at 95% power, which some people have started demanding.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAt.Power.95 <- power.t.test(n = NULL, delta = .4, sd = 1,\n                            sig.level = 0.05, power = .95,\n                            type = \"one.sample\",\n                            alternative = \"two.sided\")\nceiling(At.Power.95$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 84\n```\n:::\n:::\n\n\n84 children. Going from 80% to 95% power cost us 32 additional participants for the same effect. Cohen suggested 80% precisely because it is economical. 95% is called *high power*, and now you can see why it is unpopular with anyone who has to pay for it.\n\n### Solving for Power Instead of N\n\nIf the sample size is already fixed, perhaps because that is how many children were available, or how much money you had, run it the other way.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Same function. This time n is known and power is the NULL.\nAP.Power.N36 <- power.t.test(n = 36, delta = .4, sd = 1,\n                             sig.level = 0.05, power = NULL,\n                             type = \"one.sample\",\n                             alternative = \"two.sided\")\nround(AP.Power.N36$power, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.646\n```\n:::\n:::\n\n\nWith 36 children and a true $d$ of .4, we had a 64.6% chance of detecting the effect. Which means we had a 35.4% chance of missing it entirely, publishing nothing, and concluding cookies are harmless.\n\n### Solving for the Effect Size You Could Detect\n\nThe third useful question: given my sample, what is the *smallest* effect I could reliably find?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Third question, same function. Now delta is the NULL.\nEff.Power.N36 <- power.t.test(n = 36, delta = NULL, sd = 1,\n                              sig.level = 0.05, power = .80,\n                              type = \"one.sample\",\n                              alternative = \"two.sided\")\nround(Eff.Power.N36$delta, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.48\n```\n:::\n:::\n\n\nWith 36 children, the smallest effect we can detect 80% of the time is $d =$ 0.48. Anything smaller than that, we will usually miss.\n\nThis is the calculation to run when a reviewer asks why your null result should be believed. \"We had 80% power to detect effects of $d \\geq$ 0.48, so we can reasonably rule out effects of that size, but not smaller ones\" is a defensible sentence. \"It wasn't significant\" is not.\n\n## Sample Size and Power Are Not Linear\n\nAt a fixed effect size, adding participants buys you power, but not at a constant rate.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Power against sample size at three effect sizes. Each curve rises steeply and then flattens.](Ch_07_Power_Effect_Size_files/figure-html/power-curves-n-1.png){fig-align='center' fig-pos='H' fig-alt='Three side-by-side line plots of power against sample size, one per effect size. Every curve climbs steeply at small sample sizes and then bends over and flattens as it approaches a power of one, with the smallest effect needing by far the most participants.' width=624}\n:::\n:::\n\n\nThe blue line is 80% power; the red line is 95%. Notice how far right the curve for $d = .2$ has to travel before it crosses either one, and how quickly $d = .8$ gets there.\n\n**The larger the effect, the fewer participants you need.** Which is a comforting sentence until you remember that you do not control the effect size, and that most real psychological effects are small.\n\n### Effect Size and Power Are Also Not Linear\n\nFlip it around: hold the sample size fixed and vary the effect.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Power against effect size at three sample sizes. Same shape, different axis.](Ch_07_Power_Effect_Size_files/figure-html/power-curves-d-1.png){fig-align='center' fig-pos='H' fig-alt='Three side-by-side line plots of power against effect size, one per sample size. Each curve rises steeply through the small and medium effect sizes and then flattens near a power of one, and the larger the sample the further left that rise begins.' width=624}\n:::\n:::\n\n\nWith 25 people you need a whopping effect before you are likely to find anything. With 100, medium effects come into range. The curves are S-shaped, not straight, which means there is a region where adding a few participants helps enormously and a region where it barely matters at all.\n\n::: {.callout-note title=\"Power for the Other Two t-Tests Lives With Those Tests\"}\nEverything above used `type = \"one.sample\"`, because the one-sample *t*-test is the only one you have met so far.\n\nThe other two work identically, with one argument changed. Rather than teach them here to a reader who has not seen the tests yet, each one waits in its own chapter:\n\n- **Two separate groups**: the [independent-samples chapter](Ch_08_Independent_t.qmd) closes with `type = \"two.sample\"`, where `n` means *per group*, plus Hedges' correction for the bias small samples put into $d$.\n- **The same people twice**: the [paired-samples chapter](Ch_09_Paired_t.qmd) closes with `type = \"paired\"`, and shows how much cheaper a repeated-measures design is for the same effect.\n\nCome back here for the concepts. Go there for the arithmetic.\n:::\n\n## The Short Story\n\n- Small samples underestimate variability, in a direction that flatters you.\n- Type I error is a false alarm and its rate is $\\alpha$, which you choose. Type II error is a miss and its rate is $\\beta$, which you must earn your way out of.\n- Power is $1 - \\beta$: the probability of finding a real effect. It depends on the effect size, the sample size, and $\\alpha$.\n- Effect size lives in standard deviation units. Significance lives in standard error units. Adding participants narrows the curves without moving the peaks.\n- Compute power **before** you run the study. Post-hoc power is a restatement of your *p*-value wearing a disguise.\n- `power.t.test()` solves for whatever you leave `NULL`. Set `sd = 1` and put $d$ in `delta`.\n- The other two *t*-tests use the same function with `type` changed, and each is powered in its own chapter. For `two.sample`, `n` is per group, so double it. For `paired`, `n` is the number of pairs and `delta` is $d_z$.\n- Non-significant does not mean no effect. Very often it means no chance.\n\n---\n\n## Advanced Power Section \n\nEverything above is what you need to design a study and defend it. What follows is the part that explains *why the field got this so wrong for so long*. You are not required to master it. \n\n## The Observed Effect Size Is Also a Guess\n\nRunning one small pilot study to estimate an effect size used to be standard practice. It is a catastrophe, and we can show exactly how bad it is.\n\nConsider a Mozart-effect study: compare spatial reasoning right after listening to Mozart's Sonata for Two Pianos in D Major, K. 448, against a control group who listened to Bach's Brandenburg Concerto No. 6, matched on modality, tempo, and duelling voices. If the effect is specific to Mozart, Bach should do nothing.\n\nSimulate $\\mu_{Mozart} = 109$, $\\mu_{Bach} = 110$, $\\sigma = 15$ in both, with $n = 30$ per group. The true effect is\n\n$$\nd_{true} = \\frac{110 - 109}{15} = 0.067,\n$$\n\nwhich is to say, nothing. There is no Mozart effect in this simulated world. Now watch what a single study reports.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(666)\nn <- 30\nMozart.Sample <- rnorm(n, 109, 15)\nBach.Sample   <- rnorm(n, 110, 15)\n\nSp_mb <- sqrt(((n-1)*sd(Mozart.Sample)^2 + (n-1)*sd(Bach.Sample)^2) / (2*n - 2))\nObs.d <- abs(mean(Mozart.Sample) - mean(Bach.Sample)) / Sp_mb\nround(Obs.d, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.428\n```\n:::\n:::\n\n\nOur one study observed $d =$ 0.428, against a truth of $0.067$.\n\nNow re-run that same study 5,000 times and look at the distribution of observed effect sizes.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The observed effect size is a guess too, and in a small study it is a wild one.](Ch_07_Power_Effect_Size_files/figure-html/mozart-sim-1.png){fig-align='center' fig-pos='H' fig-alt='Histogram of observed Cohen\\'s d values from many simulated small studies of a tiny true effect. The distribution is wide and straddles zero, so plenty of studies report a moderate positive effect and plenty report a negative one.' width=480}\n:::\n:::\n\n\nThe red line is the truth. Look at how much of the distribution sits far to the right of it.\n\nIn this simulation, an observed $d$ at least as large as our one study's 0.428 occurred 10.62% of the time. Worse, there was a 46.32% chance of observing something above the \"small effect\" threshold of $d = .2$, **in a world where the true effect is essentially zero**.\n\n::: {.callout-warning title=\"Why Pilot Studies Cannot Estimate Effect Sizes\"}\nA small pilot gives you a draw from that histogram. Not the red line. A draw.\n\nIf you then feed that draw into a power analysis, you will compute the sample size needed to detect an effect that does not exist, feel rigorous about it, and run a study doomed before recruitment began.\n\nPilot studies are for testing whether your procedure works, whether participants understand the instructions, and whether the software crashes. They are not for estimating effect sizes. They are far too small to do that, which is what makes them pilots.\n:::\n\n## Safeguard Power\n\nIf you must use an observed effect size from a previous study, do not use the point estimate. Use the **lower bound of its confidence interval**. This is called *safeguard power* [@perugini2014], and it asks the only sensible question: what if the original study was lucky?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# CI for d, using the standard large-sample approximation\nd_ci <- function(d, n1, n2) {\n  se <- sqrt((n1 + n2)/(n1 * n2) + d^2 / (2 * (n1 + n2)))\n  c(lower = d - 1.96 * se, d = d, upper = d + 1.96 * se)\n}\n\npublished <- d_ci(0.50, 80, 80)\nround(published, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlower     d upper \n0.185 0.500 0.815 \n```\n:::\n:::\n\n\nA published effect of $d = .50$ from a reasonably sized study, 80 per group, still has a confidence interval reaching down to 0.185. Powering for the point estimate and powering for that lower bound produce very different studies:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(powered_for_point_estimate =\n    ceiling(power.t.test(delta = 0.50, sd = 1, power = .80,\n                         type = \"two.sample\")$n),\n  powered_for_lower_bound =\n    ceiling(power.t.test(delta = published[\"lower\"], sd = 1, power = .80,\n                         type = \"two.sample\")$n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npowered_for_point_estimate    powered_for_lower_bound \n                        64                        459 \n```\n:::\n:::\n\n\nIf the original estimate was accurate, both studies find the effect. If the original was a lucky draw from the high end of its own sampling distribution, only the second one does. The first returns a null result, and everybody spends eighteen months arguing about whether the replication was competent.\n\n::: {.callout-warning title=\"Now Try It With a Small Original Study\"}\nRun the same calculation on a $d = .50$ reported from 25 participants per group:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nround(d_ci(0.50, 25, 25), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n lower      d  upper \n-0.063  0.500  1.063 \n```\n:::\n:::\n\n\nThe lower bound is **negative**. The confidence interval includes zero, and no honest safeguard-power calculation is possible, because the original study is compatible with an effect in the opposite direction.\n\nThis is not a defect in the method. It is the method working correctly and telling you something you did not want to hear: **that study never established an effect size at all.** It established a range so wide that it contains \"helps a lot,\" \"does nothing,\" and \"actively harms.\"\n\nPowering a replication off a point estimate like that is not a calculation. It is a wish with decimal places.\n:::\n\n## When the Formula Will Not Do: Simulate\n\n`power.t.test()` handles *t*-tests. The moment your design gets more complicated, unequal group sizes, non-normal outcomes, planned attrition, an outcome measured on a bounded scale, the closed-form solution runs out.\n\nThe general-purpose answer is to simulate. Build the world you expect, run your analysis on it thousands of times, and count how often you win.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Build a machine that runs a whole study over and over and reports how\n# often it found the effect. That proportion IS power.\nsimulate_power <- function(n_per_group, true_d, n_sims = 2000, alpha = .05) {\n\n  hits <- replicate(n_sims, {          # run one study, n_sims times over\n\n    # Build two groups from populations we KNOW differ by true_d.\n    # Group 2 is centered on 0, group 1 on true_d, both with sd = 1,\n    # so the gap between them is exactly true_d in standard deviations.\n    g1 <- rnorm(n_per_group, mean = true_d, sd = 1)\n    g2 <- rnorm(n_per_group, mean = 0,      sd = 1)\n\n    # Run the test. This line is TRUE if we caught the effect, FALSE if we missed.\n    t.test(g1, g2)$p.value < alpha\n  })\n\n  # hits is now 2,000 TRUEs and FALSEs. R treats TRUE as 1 and FALSE as 0,\n  # so the mean of them is the proportion of studies that succeeded.\n  mean(hits)\n}\n\nset.seed(343)\nsimulate_power(n_per_group = 30, true_d = 0.5)\n\n# compare to the closed-form answer\npower.t.test(n = 30, delta = 0.5, sd = 1, type = \"two.sample\")$power\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4735\n[1] 0.477841\n```\n:::\n:::\n\n\nRead what that function does one more time, because the logic is the entire idea of power. We *built* a world where the effect is real and we know its exact size. Then we ran the study 2,000 times in that world and counted how often the *t*-test noticed. If it noticed 480 times out of 2,000, our power is .48, and the other 1,040 studies were funded, staffed, and wasted.\n\nThe last two lines are the important habit: the simulation and the formula agree. Always check a simulation against a known answer before you trust it on a problem where you do not have one.\n\nThe simulation agrees with the formula, which is how you know the simulation is trustworthy. Now you can change the generating model to anything you like, skewed outcomes, 20% dropout, a ceiling effect, and get an answer where no formula exists.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimulate_power_with_dropout <- function(n_per_group, true_d,\n                                        dropout = 0.20, n_sims = 2000) {\n  keep <- round(n_per_group * (1 - dropout))\n  replicate(n_sims, {\n    g1 <- rnorm(keep, mean = true_d, sd = 1)\n    g2 <- rnorm(keep, mean = 0,      sd = 1)\n    t.test(g1, g2)$p.value < .05\n  }) |> mean()\n}\n\nset.seed(343)\nsimulate_power_with_dropout(n_per_group = 30, true_d = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4115\n```\n:::\n:::\n\n\nTwenty percent attrition costs real power. Plan for it before it happens, not in the limitations section afterwards.\n\n## Other Tools\n\n`power.t.test()` is deliberately limited. For anything beyond *t*-tests:\n\n- the **`pwr`** package covers correlations, proportions, chi-square, ANOVA, and regression with the same solve-for-`NULL` logic;\n- **G\\*Power** is free stand-alone software and remains the standard for grant applications for people who do not code;\n- **`simr`** does simulation-based power for mixed models;\n- and for genuinely novel designs, the `simulate_power()` pattern above generalizes to anything you can write down.\n\nNIH and NSF require a power analysis with every grant application. In practice it is difficult, because you must estimate an effect size you do not yet know. Assume small, plan for attrition, and remember that the most expensive study is the underpowered one that answers nothing.\n\n::: {.callout-important title=\"Cohen's Compromise\"}\nCohen's recommendation was simple: do the significance test **and** report the effect size.\n\nTwo pieces of information. First, is the result distinguishable from sampling error? Second, does the effect mean anything at all?\n\nHe proposed this in 1962. APA made it standard in 2010.\n\nForty-eight years. Please do not make it take any longer.\n:::\n\n::: {.callout-note title=\"Figure Credit\"}\nThe power and signal-detection illustrations in this chapter are adapted from Kristoffer Magnusson's [textbook-illustration walkthrough](http://rpsychologist.com/creating-a-typical-textbook-illustration-of-statistical-power-using-either-ggplot-or-base-graphics), updated for current ggplot2 syntax.\n:::\n",
    "supporting": [
      "Ch_07_Power_Effect_Size_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}