{
  "hash": "19a159c437530641f6af78b98e99dde8",
  "result": {
    "markdown": "---\ntitle: \"Advanced: Continuous and Higher-Order Interactions\"\n---\n\n\n\n\n## Two Models, One Dataset, Opposite Headlines\n\nWe asked 240 students how much they slept, how much caffeine they drank, and how well they could concentrate. Here is the whole study, invented on the spot, with the interaction built in on purpose so you can see it sitting in the generating model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\nn <- 240\nInterData <- data.frame(\n  Sleep = pmin(pmax(rnorm(n, 6.5, 1.3), 2.5), 10),\n  Caffeine = pmin(pmax(rnorm(n, 220, 100), 0), 500)\n)\n\nInterData$Concentration <-\n  40 +\n  3.5 * InterData$Sleep +\n  0.055 * InterData$Caffeine -\n  0.012 * InterData$Sleep * InterData$Caffeine +\n  rnorm(n, 0, 5)\n\nInterData$Sleep.C <- InterData$Sleep - mean(InterData$Sleep)\nInterData$Caffeine.C <- InterData$Caffeine - mean(InterData$Caffeine)\n```\n:::\n\n\nNow fit the obvious model. Concentration from sleep, caffeine, and their interaction, using the variables exactly as they were measured.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nRawModel <- lm(Concentration ~ Sleep * Caffeine, data = InterData)\n\nround(coef(summary(RawModel)), 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Estimate Std. Error  t value Pr(>|t|)\n(Intercept)    38.02109    4.71938  8.05638  0.00000\nSleep           3.55281    0.69413  5.11835  0.00000\nCaffeine        0.06179    0.02001  3.08855  0.00225\nSleep:Caffeine -0.01226    0.00293 -4.19148  0.00004\n```\n:::\n:::\n\n\nCaffeine helps. The slope is 0.0618, it is significantly greater than zero at $p =$ 0.002, and you can write the sentence yourself: more caffeine, better concentration.\n\nNow subtract the mean from each predictor and fit the same three terms again.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nInteractionModel <- lm(Concentration ~ Sleep.C * Caffeine.C, data = InterData)\n\nround(coef(summary(InteractionModel)), 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                   Estimate Std. Error   t value Pr(>|t|)\n(Intercept)        57.31365    0.33775 169.69342  0.00000\nSleep.C             0.90777    0.28659   3.16756  0.00174\nCaffeine.C         -0.01876    0.00356  -5.27079  0.00000\nSleep.C:Caffeine.C -0.01226    0.00293  -4.19148  0.00004\n```\n:::\n:::\n\n\nCaffeine hurts. The slope is -0.0188, and it is significantly *less* than zero at $p <$ .001.\n\nBoth of those sentences describe the same 240 people. Neither model is wrong, neither is a typo, and nothing was dropped or added between them. Watch what did not move.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nFittedGap <- max(abs(fitted(RawModel) - fitted(InteractionModel)))\n\nc(\n  Interaction.raw      = unname(coef(RawModel)[4]),\n  Interaction.centered = unname(coef(InteractionModel)[4]),\n  R2.raw               = summary(RawModel)$r.squared,\n  R2.centered          = summary(InteractionModel)$r.squared,\n  Largest.fitted.diff  = FittedGap\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Interaction.raw Interaction.centered               R2.raw \n       -1.226242e-02        -1.226242e-02         2.070618e-01 \n         R2.centered  Largest.fitted.diff \n        2.070618e-01         1.563194e-13 \n```\n:::\n:::\n\n\nThe interaction coefficient is identical. $R^2$ is identical. Across all 240 predicted values, the largest disagreement between the two models shows up in the 12th decimal place, which is not a small difference but a zero that has been through floating-point arithmetic. These are not two models. This is one model, wearing two sets of labels.\n\nSo what changed? Only the location of zero. In the first model, the caffeine coefficient is the effect of caffeine **on a student who slept zero hours**. In the second, it is the effect of caffeine **on a student who slept the average amount**, about 6.6 hours. Those are different students, so they get different answers, and the model was never claiming otherwise. We were.\n\n*A coefficient in an interaction model is not an effect. It is an effect at a place.*\n\nThe rest of this chapter is about choosing that place on purpose, saying which one you chose, and noticing when software has quietly chosen for you.\n\n## It Depends, Again\n\nThe earlier interaction chapters asked whether a slope differs across categories. Here both predictors can be continuous. This produces a model that is compact to write and remarkably easy to explain badly [@aiken1991].\n\nCaffeine predicts concentration differently depending on sleep. Caffeine may help a rested student focus while merely allowing an exhausted student to hear colors at a higher frame rate.\n\n### Fast Review: Categorical-by-Continuous Interactions\n\nThe previous interaction chapters used a categorical moderator. With a dummy variable $G$ coded 0 and 1,\n\n$$\nY=\\beta_0+\\beta_1X+\\beta_2G+\\beta_3XG+\\epsilon.\n$$\n\nFor the reference group, $G=0$, so its regression line is\n\n$$\n\\widehat Y=\\beta_0+\\beta_1X.\n$$\n\nFor the comparison group, $G=1$, so its line is\n\n$$\n\\widehat Y=(\\beta_0+\\beta_2)+(\\beta_1+\\beta_3)X.\n$$\n\nTherefore, $\\beta_2$ is the group difference in intercepts when $X=0$, and $\\beta_3$ is the group difference in slopes. A continuous-by-continuous interaction uses the same logic. The only difference is that the moderator can take many values instead of two. We therefore choose meaningful values at which to examine the conditional slope.\n\n## The Continuous-by-Continuous Model\n\n$$\nY=\\beta_0+\\beta_1X+\\beta_2Z+\\beta_3XZ+\\epsilon.\n$$\n\nThe slope of $X$ is:\n\n$$\n\\frac{\\partial Y}{\\partial X}=\\beta_1+\\beta_3Z.\n$$\n\nThat derivative is the entire interaction in one line: the slope of $X$ changes as $Z$ changes.\n\n::: {.callout-important title=\"There Is No Single Main Effect of X\"}\nWhen $XZ$ is in the model, $\\beta_1$ is the slope of $X$ specifically when $Z=0$. If zero is meaningless or outside the data, the coefficient answers a question nobody asked.\n:::\n\n## Does the Interaction Earn Its Place?\n\nBefore interpreting a product term, check that it bought you anything. Fit the model without it and compare.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nAdditiveModel <- lm(Concentration ~ Sleep.C + Caffeine.C, data = InterData)\n\nanova(AdditiveModel, InteractionModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: Concentration ~ Sleep.C + Caffeine.C\nModel 2: Concentration ~ Sleep.C * Caffeine.C\n  Res.Df    RSS Df Sum of Sq      F   Pr(>F)    \n1    237 6940.9                                 \n2    236 6460.0  1     480.9 17.569 3.92e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nIt did. Adding the product term improves fit at $p < .001$, so the claim that caffeine's slope depends on sleep is doing real work rather than decorating the model. Had this comparison come back nonsignificant, the honest move would be to say so and report the additive model, not to hunt for a subgroup in which the interaction reappears.\n\nCentering places zero at the sample mean. It changes the interpretation of the intercept and lower-order slopes. It does **not** change fitted values, residuals, $R^2$, or the interaction coefficient.\n\nCentering is usually helpful for three reasons:\n\n1. $\\beta_1$ becomes the slope of $X$ when the moderator is at its mean instead of at an arbitrary zero.\n2. It can reduce **nonessential multicollinearity** created only by multiplying variables together.\n3. It keeps products from growing into unnecessarily enormous numbers.\n\nCentering does not solve **essential multicollinearity** caused by predictors containing genuinely overlapping information. If sleep and exhaustion measure nearly the same construct, subtracting their means will not make them strangers.\n\nWhatever coding you choose, use it consistently. Do not put centered variables in the product while leaving uncentered versions as the lower-order terms. You would be fitting a mathematical casserole that no longer represents the intended model.\n\n### The Standardized-Beta Trap\n\nSooner or later a reviewer will ask for standardized coefficients on your moderation model. This request is reasonable and the obvious way to satisfy it is wrong, so it is worth meeting the problem here rather than in a revision.\n\nThe correct procedure is to z-score $X$ and $Z$ first, and *then* multiply them. The tempting shortcut is to build the product first and z-score that. These are not the same variable, because the z-score of a product is not the product of z-scores.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nInterData$Sleep.Z    <- as.numeric(scale(InterData$Sleep))\nInterData$Caffeine.Z <- as.numeric(scale(InterData$Caffeine))\nInterData$Concen.Z   <- as.numeric(scale(InterData$Concentration))\n\n# Right: standardize the components, then let R form the product.\nProperBetas <- lm(Concen.Z ~ Sleep.Z * Caffeine.Z, data = InterData)\n\n# Wrong: standardize the product term itself.\nInterData$Product.Z <- as.numeric(scale(InterData$Sleep * InterData$Caffeine))\nWrongBetas <- lm(Concen.Z ~ Sleep.Z + Caffeine.Z + Product.Z, data = InterData)\n\nBetaCompare <- cbind(\n  Proper = coef(ProperBetas),\n  Wrong  = coef(WrongBetas)\n)\n\n# Relabel: the last row is Sleep.Z:Caffeine.Z in one model and Product.Z in the\n# other. They occupy the same position, and that is exactly the point.\nrownames(BetaCompare) <- c(\"(Intercept)\", \"Sleep\", \"Caffeine\", \"Sleep x Caffeine\")\n\nround(BetaCompare, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  Proper   Wrong\n(Intercept)       0.0032  0.0000\nSleep             0.1836  0.7187\nCaffeine         -0.3083  1.0156\nSleep x Caffeine -0.2380 -1.4854\n```\n:::\n:::\n\n\nThe interaction \"beta\" is -0.24 one way and -1.49 the other. Both lower-order betas are wrong in the second column too, and one of them is 1.02, which should be your first clue: a standardized coefficient larger than 1 in a model this simple is usually a confession rather than a finding.\n\nHere is the part that makes this genuinely dangerous. The two models fit **identically**. $R^2$ is 0.2071 in both, and the interaction's *t* is -4.19 in both, so the significance test is untouched. Nothing looks broken. The only thing that changed is the number you would put in the table and describe in words, and it is off by a factor of about 6.2.\n\n::: {.callout-warning title=\"Do Not Trust a Standardized Column You Did Not Build\"}\nIf you want standardized coefficients for an interaction model, **z-score the components first and refit**. Do not read them off a \"standardized\" or \"beta\" column produced by software that standardized the product term along with everything else, because several packages do exactly that and none of them will warn you.\n\nThe check takes ten seconds: refit with z-scored predictors and confirm the numbers match the column you were about to report. If they do not, the column is describing a variable nobody constructed on purpose.\n\nFriedrich made this argument in 1982 and it has needed remaking roughly once per graduate cohort ever since [@friedrich1982]. Cohen, Cohen, West and Aiken work through it at length in their chapter on interactions [@cohen2003].\n:::\n\nLeave a predictor uncentered when zero is scientifically meaningful and you want the lower-order coefficient evaluated there. For example, zero milligrams of caffeine is understandable. Zero hours of sleep is also understandable, but anyone reporting it should probably not be completing your study.\n\n::: {.callout-note title=\"Centering Is Translation, Not Exorcism\"}\nCentering can make lower-order terms interpretable and reduce nonessential correlation between a product term and its components. It does not repair poor measurement, restricted range, or two predictors that are fundamentally redundant.\n:::\n\n## Plot the Model\n\nWe will draw the caffeine slope at low sleep, average sleep, and high sleep. The common $\\pm1SD$ convention is useful because it gives three recognizable values. It is not a law delivered by the Moderation Gods.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleep_values <- c(\n  Low = -sd(InterData$Sleep.C),\n  Average = 0,\n  High = sd(InterData$Sleep.C)\n)\n\ncaffeine_grid <- seq(min(InterData$Caffeine.C), max(InterData$Caffeine.C), length.out = 100)\nplot(\n  InterData$Caffeine, InterData$Concentration,\n  pch = 19, col = rgb(0.3, 0.3, 0.3, 0.22),\n  # y label is \"Concentration\", not \"Predicted concentration\": the dots are raw\n  # observed scores. Only the three overlaid lines are predictions.\n  xlab = \"Caffeine (mg)\", ylab = \"Concentration\",\n  main = \"Caffeine does not have one universal slope\"\n)\n\nline_colors <- c(\"#D55E00\", \"#0072B2\", \"#009E73\")\nfor (i in seq_along(sleep_values)) {\n  newdata <- data.frame(\n    Sleep.C = sleep_values[i],\n    Caffeine.C = caffeine_grid\n  )\n  lines(\n    caffeine_grid + mean(InterData$Caffeine),\n    predict(InteractionModel, newdata = newdata),\n    col = line_colors[i], lwd = 3\n  )\n}\nlegend(\"topright\", legend = paste(names(sleep_values), \"sleep\"),\n       col = line_colors, lwd = 3, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![Points are observed concentration scores. The three lines are model predictions at low, average, and high sleep, defined as one standard deviation below the mean, the mean, and one standard deviation above it.](Ch_21_Advanced_Interactions_files/figure-html/interaction-plot-1.png){fig-align='center' fig-alt='Scatterplot with caffeine in milligrams from 0 to about 470 on the x axis and concentration from about 42 to 75 on the y axis. A wide grey cloud of 240 faint points fills the panel with no obvious tilt of its own. Three straight prediction lines are drawn over it and fan out rather than running parallel. The orange Low sleep line is almost flat, falling only from about 57 to 55. The blue Average sleep line falls from about 61 to 53. The green High sleep line falls most steeply, from about 65 to 50. All three lines converge and cross near 290 milligrams of caffeine.' width=672}\n:::\n:::\n\n\n## Simple Slopes\n\nFor a chosen value $z^*$ of the moderator, the simple slope of caffeine is:\n\n$$\nb_{Caffeine\\mid z^*}=b_1+b_3z^*.\n$$\n\nIts standard error also depends on the covariance between $b_1$ and $b_3$:\n\n$$\nSE(b_1+b_3z^*)=\n\\sqrt{\nVar(b_1)+z^{*2}Var(b_3)+2z^*Cov(b_1,b_3)\n}.\n$$\n\nThis is why we let software test simple slopes. Doing it by hand is possible, but so is churning butter.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emtrends(\n  InteractionModel,\n  specs = \"Sleep.C\",\n  var = \"Caffeine.C\",\n  at = list(Sleep.C = unname(sleep_values))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Sleep.C Caffeine.C.trend      SE  df lower.CL upper.CL\n   -1.18         -0.00428 0.00528 236  -0.0147  0.00613\n    0.00         -0.01876 0.00356 236  -0.0258 -0.01175\n    1.18         -0.03324 0.00462 236  -0.0423 -0.02415\n\nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nUse theoretically meaningful moderator values when possible. Quantiles may be better than $\\pm1SD$ for a skewed moderator. Never probe values outside the observed range merely because the resulting line looks exciting.\n\n### What Software Is Doing When It Tests a Simple Slope\n\n`emtrends()` is not creating a new kind of regression. It is combining coefficients from the fitted model. We can prove this by changing the value represented by zero.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSleepSD <- sd(InterData$Sleep.C)\n\nInterData$Sleep.AtLow <- InterData$Sleep.C - (-SleepSD)\nInterData$Sleep.AtMean <- InterData$Sleep.C\nInterData$Sleep.AtHigh <- InterData$Sleep.C - SleepSD\n\nSlopeAtLow <- lm(\n  Concentration ~ Caffeine.C * Sleep.AtLow,\n  data = InterData\n)\nSlopeAtMean <- lm(\n  Concentration ~ Caffeine.C * Sleep.AtMean,\n  data = InterData\n)\nSlopeAtHigh <- lm(\n  Concentration ~ Caffeine.C * Sleep.AtHigh,\n  data = InterData\n)\n\nrbind(\n  LowSleep = coef(summary(SlopeAtLow))[\"Caffeine.C\", ],\n  MeanSleep = coef(summary(SlopeAtMean))[\"Caffeine.C\", ],\n  HighSleep = coef(summary(SlopeAtHigh))[\"Caffeine.C\", ]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              Estimate  Std. Error    t value     Pr(>|t|)\nLowSleep  -0.004277577 0.005281348 -0.8099405 4.187903e-01\nMeanSleep -0.018759542 0.003559155 -5.2707860 3.064031e-07\nHighSleep -0.033241507 0.004617131 -7.1996017 8.019402e-12\n```\n:::\n:::\n\n\nIn each model, the coefficient for caffeine is evaluated where the newly coded sleep variable equals zero. The fitted values and interaction remain the same. We only rotated the coefficient labels until the question we wanted was sitting in the convenient chair.\n\nYou do not need to test slopes at every possible moderator value. That converts one interaction into a large family of tests and invites the multiple-comparisons demons. Test values required by theory. Plot enough of the observed range to show the shape.\n\n## Moderation Is a Theoretical Label\n\nWhen we say that $Z$ **moderates** the effect of $X$ on $Y$, we mean that the relationship between $X$ and $Y$ changes across values of $Z$. Statistically, this is an interaction. Calling one variable the moderator does not change the equation.\n\nWhich predictor is the moderator depends on the theory. In the caffeine-and-sleep example, we can say sleep moderates the caffeine slope or caffeine moderates the sleep slope. The fitted surface is identical. The story determines which conditional relationship we emphasize.\n\nModeration and mediation both involve three-variable systems, but they are not the same procedure. Moderation asks **when or for whom** a relationship changes. Mediation asks whether a relationship may operate **through** another variable. Sharing the letter *M* does not make them statistical cousins.\n\n## Common Theoretical Patterns\n\nWords such as *synergistic*, *antagonistic*, and *buffering* describe patterns in predicted values. They do not create different estimators. We still fit a product term, inspect the coding, calculate conditional slopes, and plot the model.\n\n### Synergistic Interaction\n\nA synergistic interaction occurs when the combined effect of two predictors is larger than their additive effects would suggest. Imagine that better sleep improves concentration, moderate caffeine improves concentration, and caffeine is especially helpful when a student is rested enough to remember where their mouth is.\n\nWhen both predictors have positive lower-order slopes, a positive product term often creates this pattern. However, the sign depends on coding. Inspect predictions before naming it.\n\n### Antagonistic or Interference Interaction\n\nAn antagonistic interaction occurs when the combined effect is smaller than simple addition predicts. Perhaps using one study app improves performance and using a second app also improves performance, but using both produces 47 notifications and an emergency need to redesign the color theme. The second tool has diminishing returns as use of the first increases.\n\nWhen both lower-order slopes are positive, a negative product term often produces antagonism.\n\n### Buffering Interaction\n\nA buffering interaction usually combines a risk factor with a protective factor. Suppose academic stress predicts worse sleep, but social support weakens that relationship. As support rises, the negative stress slope approaches zero.\n\nThe term *buffering* depends strongly on which variable is defined as the risk and which outcome direction is good. Reverse-score stress into serenity and several coefficient signs reverse even though every fitted value remains unchanged.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nPatternX <- seq(-2, 2, length.out = 80)\nModeratorValues <- c(Low = -1, High = 1)\nPatternColors <- c(\"#D55E00\", \"#0072B2\")\n\nold_par <- par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))\n\nfor (PatternName in c(\"Synergistic\", \"Antagonistic\", \"Buffering\")) {\n  plot(\n    NA, xlim = range(PatternX), ylim = c(-5, 7),\n    xlab = \"Predictor X\", ylab = \"Predicted Y\",\n    main = PatternName\n  )\n\n  for (j in seq_along(ModeratorValues)) {\n    Z <- ModeratorValues[j]\n    if (PatternName == \"Synergistic\") {\n      Y <- 1 + PatternX + Z + .8 * PatternX * Z\n    } else if (PatternName == \"Antagonistic\") {\n      Y <- 1 + PatternX + Z - .8 * PatternX * Z\n    } else {\n      Y <- 1 - 1.2 * PatternX + 1.0 * Z + .7 * PatternX * Z\n    }\n    lines(PatternX, Y, lwd = 3, col = PatternColors[j])\n  }\n  legend(\"topleft\", names(ModeratorValues), col = PatternColors, lwd = 3, bty = \"n\")\n}\n\nplot.new()\ntext(.5, .62, \"Same product-term machinery\", cex = 1.15)\ntext(.5, .48, \"Different theoretical stories\", cex = 1.15)\ntext(.5, .32, \"Check the coding before naming anything\", cex = .95)\n```\n\n::: {.cell-output-display}\n![](Ch_21_Advanced_Interactions_files/figure-html/interaction-patterns-1.png){fig-align='center' fig-alt='Four panels in a two-by-two grid. Three of them plot predicted Y against predictor X from minus 2 to 2, each showing an orange Low moderator line and a blue High moderator line. In Synergistic, both lines rise and the blue one rises much more steeply, so they cross near X of minus 1.3 and the gap widens to the right. In Antagonistic, the orange line rises steeply and the blue one is nearly flat, so they cross near X of 1.3 and the gap is widest on the left. In Buffering, both lines fall, the orange steeply and the blue gently, so the orange drops far below the blue on the right. The fourth panel has no plot in it, only three lines of text reading Same product-term machinery, Different theoretical stories, and Check the coding before naming anything.' width=768}\n:::\n\n```{.r .cell-code}\npar(old_par)\n```\n:::\n\n\n## Reverse-Scoring Changes the Signs, Not the Story\n\nIf $Z^*=-Z$, the signs of its main effect and interactions reverse. Predictions remain identical after the coding is translated correctly. A negative interaction does not inherently mean antagonism, harm, or Reviewer 2. Its meaning depends on variable coding.\n\n::: {.callout-warning title=\"Interaction Labels Are Stories, Not New Statistics\"}\nTerms such as *synergistic*, *antagonistic*, and *buffering* describe theoretical patterns. The model still estimates slopes and products. Decide which story applies only after inspecting coding, predictions, and the scientific context.\n:::\n\n## Three-Way Interactions\n\nA three-way interaction asks whether a two-way interaction changes across a third variable:\n\n$$\nY=\\beta_0+\\beta_1X+\\beta_2Z+\\beta_3W+\n\\beta_4XZ+\\beta_5XW+\\beta_6ZW+\\beta_7XZW+\\epsilon.\n$$\n\nIf $\\beta_7\\neq0$, the $X$-by-$Z$ interaction depends on $W$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(345)\nThreeData <- InterData\nThreeData$Deadline <- factor(\n  sample(c(\"Tomorrow\", \"Next week\"), nrow(ThreeData), replace = TRUE),\n  levels = c(\"Next week\", \"Tomorrow\")\n)\nDeadline01 <- as.numeric(ThreeData$Deadline == \"Tomorrow\")\n\nThreeData$Concentration3 <-\n  60 +\n  2.0 * ThreeData$Sleep.C +\n  .035 * ThreeData$Caffeine.C -\n  3.0 * Deadline01 -\n  .008 * ThreeData$Sleep.C * ThreeData$Caffeine.C +\n  .010 * ThreeData$Sleep.C * ThreeData$Caffeine.C * Deadline01 +\n  rnorm(nrow(ThreeData), 0, 5)\n\nThreeWayModel <- lm(\n  Concentration3 ~ Sleep.C * Caffeine.C * Deadline,\n  data = ThreeData\n)\n\nsummary(ThreeWayModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Concentration3 ~ Sleep.C * Caffeine.C * Deadline, \n    data = ThreeData)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.7898  -3.2580  -0.3208   3.2044  14.2709 \n\nCoefficients:\n                                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                         59.798560   0.465421 128.483  < 2e-16 ***\nSleep.C                              2.653541   0.383840   6.913 4.55e-11 ***\nCaffeine.C                           0.035025   0.004856   7.212 7.72e-12 ***\nDeadlineTomorrow                    -3.066370   0.652950  -4.696 4.54e-06 ***\nSleep.C:Caffeine.C                  -0.009451   0.003852  -2.454   0.0149 *  \nSleep.C:DeadlineTomorrow            -0.336507   0.555119  -0.606   0.5450    \nCaffeine.C:DeadlineTomorrow         -0.004959   0.006891  -0.720   0.4725    \nSleep.C:Caffeine.C:DeadlineTomorrow  0.008943   0.005685   1.573   0.1171    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.054 on 232 degrees of freedom\nMultiple R-squared:  0.4607,\tAdjusted R-squared:  0.4444 \nF-statistic: 28.31 on 7 and 232 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe `*` operator includes all main effects, all two-way interactions, and the three-way interaction. Keep those lower-order terms. Removing them because they are nonsignificant changes the model's meaning and usually creates interpretive debris.\n\nTo interpret a three-way interaction:\n\n1. Plot the predicted two-way relationship at meaningful values of the third variable.\n2. Test the two-way interaction within those values or groups.\n3. Probe simple slopes only where theory requires them.\n4. Report enough numbers that the reader does not have to reconstruct the model with candles and a Ouija board.\n\n### Unpack the Three-Way Interaction\n\nFirst test the sleep-by-caffeine interaction separately within each deadline condition. Then examine caffeine slopes at meaningful sleep values within each condition.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::joint_tests(\n  ThreeWayModel,\n  by = \"Deadline\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDeadline = Next week:\n model term         df1 df2 F.ratio p.value\n Sleep.C              1 232  47.792 <0.0001\n Caffeine.C           1 232  52.020 <0.0001\n Sleep.C:Caffeine.C   1 232   6.020  0.0149\n\nDeadline = Tomorrow:\n model term         df1 df2 F.ratio p.value\n Sleep.C              1 232  33.382 <0.0001\n Caffeine.C           1 232  37.822 <0.0001\n Sleep.C:Caffeine.C   1 232   0.015  0.9034\n```\n:::\n\n```{.r .cell-code}\nThreeWaySlopes <- emmeans::emtrends(\n  ThreeWayModel,\n  specs = c(\"Sleep.C\", \"Deadline\"),\n  var = \"Caffeine.C\",\n  at = list(Sleep.C = unname(sleep_values))\n)\n\nThreeWaySlopes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Sleep.C Deadline  Caffeine.C.trend      SE  df lower.CL upper.CL\n   -1.18 Next week           0.0462 0.00694 232   0.0325   0.0599\n    0.00 Next week           0.0350 0.00486 232   0.0255   0.0446\n    1.18 Next week           0.0239 0.00636 232   0.0113   0.0364\n   -1.18 Tomorrow            0.0307 0.00757 232   0.0158   0.0456\n    0.00 Tomorrow            0.0301 0.00489 232   0.0204   0.0397\n    1.18 Tomorrow            0.0295 0.00627 232   0.0171   0.0418\n\nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nThe three-way coefficient tells us whether the two-way interaction differs between deadline conditions. It does not tell us which simple slope is important, whether the pattern matches the theory, or whether the predicted values are remotely plausible. That requires unpacking.\n\n::: {.callout-warning title=\"A Three-Way Interaction Is Not a Personality Trait\"}\nDo not predict one merely because you are an ambitious graduate student and your committee has not yet confiscated your keyboard. Three-way interactions demand more power, more careful measurement, and a theory precise enough to explain a changing two-way interaction.\n:::\n\n## The Johnson-Neyman Question\n\nSimple slopes at the mean and one standard deviation above and below the mean are convenient. They are not sacred locations handed down by Dorkaos. The **Johnson-Neyman** approach solves for the values of moderator $Z$ where the conditional slope of $X$ changes from statistically distinguishable from zero to not distinguishable from zero.\n\nThe conditional slope is\n\n$$\nb_{X\\mid Z}=b_1+b_3Z.\n$$\n\nIts standard error depends on the variances and covariance of $b_1$ and $b_3$:\n\n$$\nSE(b_{X\\mid Z})=\n\\sqrt{Var(b_1)+Z^2Var(b_3)+2ZCov(b_1,b_3)}.\n$$\n\n### Solving It, Which Is Just a Quadratic\n\nThe boundary we want is where the conditional slope is exactly $t_{crit}$ standard errors from zero:\n\n$$\n\\frac{b_1+b_3Z}{SE(b_{X\\mid Z})}=\\pm t_{crit}.\n$$\n\nSquare both sides, substitute the standard error, and move everything to one side. The $Z$ terms collect into an ordinary quadratic $AZ^2+BZ+C=0$ with\n\n$$\nA=t_{crit}^2Var(b_3)-b_3^2,\\quad\nB=2\\left(t_{crit}^2Cov(b_1,b_3)-b_1b_3\\right),\\quad\nC=t_{crit}^2Var(b_1)-b_1^2.\n$$\n\nThat is the entire Johnson-Neyman method. There is no new estimator here, no new distribution, and nothing that could not be done with the coefficients and covariance matrix you already have. Packages exist that will do this for you, but the machinery is small enough to look at once.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCoefVar <- vcov(InteractionModel)\n\n# Pull these out BY NAME. The rows of vcov() are in model order, so Caffeine.C\n# is the third row here, not the second, and positional indexing silently\n# hands you the variance of the wrong coefficient. Nothing errors. The roots\n# just come out wrong.\nb1  <- coef(InteractionModel)[\"Caffeine.C\"]\nb3  <- coef(InteractionModel)[\"Sleep.C:Caffeine.C\"]\nv11 <- CoefVar[\"Caffeine.C\", \"Caffeine.C\"]\nv33 <- CoefVar[\"Sleep.C:Caffeine.C\", \"Sleep.C:Caffeine.C\"]\nv13 <- CoefVar[\"Caffeine.C\", \"Sleep.C:Caffeine.C\"]\n\nTCrit <- qt(.975, df.residual(InteractionModel))\n\nA <- TCrit^2 * v33 - b3^2\nB <- 2 * (TCrit^2 * v13 - b1 * b3)\nC <- TCrit^2 * v11 - b1^2\n\nJNRoots <- sort(c(\n  (-B - sqrt(B^2 - 4 * A * C)) / (2 * A),\n  (-B + sqrt(B^2 - 4 * A * C)) / (2 * A)\n))\n\n# Roots are on the centered scale; add the mean back to read them as hours.\nJNHours <- JNRoots + mean(InterData$Sleep)\n\nrbind(Centered = JNRoots, Hours = JNHours)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         Caffeine.C Caffeine.C\nCentered  -3.215866 -0.8036323\nHours      3.353304  5.7655371\n```\n:::\n:::\n\n\nThe two boundaries land at 3.35 and 5.77 hours of sleep, and they split the sleep axis into three regions:\n\n- Below about 3.4 hours, caffeine's slope is significantly **positive**.\n- Between 3.4 and 5.8 hours, the slope is not distinguishable from zero.\n- Above about 5.8 hours, the slope is significantly **negative**. For rested students, more caffeine predicts worse concentration.\n\nBefore repeating any of that in a paper, count how many people are actually in each region. This is the step everyone skips.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(cut(\n  InterData$Sleep,\n  breaks = c(-Inf, JNHours, Inf),\n  labels = c(\"Slope positive\", \"Not distinguishable\", \"Slope negative\")\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Slope positive Not distinguishable      Slope negative \n                  1                  53                 186 \n```\n:::\n:::\n\n\nThat changes the write-up considerably. Both boundaries are technically inside the observed range of 2.54 to 9.64 hours, so nothing here is extrapolation in the strict sense. But the significantly-positive region contains 1 participant out of 240. The model is confident about a region where the study essentially has no data, because a confidence band is narrow near the middle of the moderator and the boundary happens to fall where the band is still narrow enough to exclude zero.\n\nSo the honest report is: the upper boundary at 5.77 hours is well supported, with 186 participants above it, and it is the finding. The lower boundary is where the data ran out, not a discovery about sleep-deprived students. **\"Inside the observed range\" is a weaker guarantee than it sounds, and the fix is to report the counts alongside the region.**\n\nThe $\\pm1SD$ convention would have found none of this, and its problem here is more specific than being arbitrary. One standard deviation below the mean is 5.39 hours, which the convention would label \"low sleep\" in a table and which sits *inside* the not-distinguishable region. So the conventional probe reports a nonsignificant slope at \"low sleep\" and significant ones at average and high, in a sample whose sleep actually runs down to 2.5 hours. The label is doing work the number cannot support.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSleepGrid   <- seq(min(InterData$Sleep.C), max(InterData$Sleep.C), length.out = 200)\nSlopeGrid   <- b1 + b3 * SleepGrid\nSlopeSE     <- sqrt(v11 + SleepGrid^2 * v33 + 2 * SleepGrid * v13)\nHoursGrid   <- SleepGrid + mean(InterData$Sleep)\n\nplot(\n  HoursGrid, SlopeGrid, type = \"n\",\n  ylim = range(SlopeGrid - TCrit * SlopeSE, SlopeGrid + TCrit * SlopeSE),\n  xlab = \"Sleep (hours)\",\n  ylab = \"Conditional slope of caffeine\",\n  main = \"Where does caffeine actually do something?\"\n)\n\n# The region between the two roots is where zero stays inside the interval.\nrect(JNHours[1], par(\"usr\")[3], JNHours[2], par(\"usr\")[4],\n     col = \"#EFEFEF\", border = NA)\n\npolygon(\n  c(HoursGrid, rev(HoursGrid)),\n  c(SlopeGrid - TCrit * SlopeSE, rev(SlopeGrid + TCrit * SlopeSE)),\n  col = rgb(0.3, 0.3, 0.3, 0.20), border = NA\n)\n\nlines(HoursGrid, SlopeGrid, lwd = 3, col = \"#0072B2\")\nabline(h = 0, lty = 2, lwd = 2)\nabline(v = JNHours, lty = 2, lwd = 2, col = \"#D55E00\")\ntext(mean(JNHours), max(SlopeGrid + TCrit * SlopeSE) * .92,\n     \"not distinguishable\\nfrom zero\", cex = .85, col = \"gray25\")\nbox()\n```\n\n::: {.cell-output-display}\n![](Ch_21_Advanced_Interactions_files/figure-html/johnson-neyman-plot-1.png){fig-align='center' fig-alt='Line plot with hours of sleep from about 2.5 to 9.6 on the x axis and the conditional slope of caffeine on the y axis, labelled from 0.06 down to minus 0.06. A straight blue line falls steadily from about 0.03 at the left edge to about minus 0.06 at the right, surrounded by a grey 95 percent confidence band that is narrowest around 5 hours and flares at both ends. A horizontal dashed line marks a slope of zero. Two vertical dashed orange lines at about 3.35 and 5.77 hours mark exactly where the edges of the confidence band touch zero, and the strip between them is shaded and labelled not distinguishable from zero. Left of the shaded strip the whole band sits above zero; right of it the whole band sits below zero. The blue line itself crosses zero near 5 hours, in the middle of the shaded strip rather than at either boundary.' width=720}\n:::\n:::\n\n\nNotice that the confidence band is narrowest near the middle of the sleep distribution and flares at both ends. That is not a quirk of this dataset. A conditional slope is estimated most precisely where you have the most data, and the $\\pm1SD$ points are convenient partly because they are still in the crowded part of the moderator.\n\nJohnson-Neyman regions can be useful when the moderator is truly continuous. Do not report a region far outside the observed values of $Z$. The equation is willing to extrapolate into space; your data did not go there. A boundary at 5.8 hours of sleep, with 186 people beyond it, is a finding. A boundary at 22 hours of sleep is a rounding error with ambitions.\n\n\n### The Package That Does All of That in One Call\n\nHere is an R package that will also do this with less code.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(interactions)\n\n# Calculate the J-N intervals and generate the plot\njn_result <- johnson_neyman(\n  model = InteractionModel,\n  pred = Caffeine.C,\n  modx = Sleep.C,\n  alpha = 0.05,          # Significance threshold (default is 0.05)\n  control.fdr = FALSE    # Set to TRUE to control False Discovery Rate if desired\n)\n\n# Print the text output containing the precise cut-off points\nprint(jn_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nJOHNSON-NEYMAN INTERVAL\n\nWhen Sleep.C is OUTSIDE the interval [-3.22, -0.80], the slope of\nCaffeine.C is p < .05.\n\nNote: The range of observed values of Sleep.C is [-4.03, 3.07]\n```\n:::\n\n::: {.cell-output-display}\n![](Ch_21_Advanced_Interactions_files/figure-html/johnson-neyman-package-1.png){fig-align='center' fig-alt='Johnson-Neyman plot with centered sleep on the x axis from about minus 5.5 to 4.5 and the slope of centered caffeine on the y axis from about minus 0.10 to 0.075. A straight line falls from about 0.045 at the left to about minus 0.07 at the right, inside a confidence band that is narrowest in the middle. Two vertical dashed lines at about minus 3.2 and minus 0.8 cut the plot into three parts. Between them the line and band are shaded pink and labelled n.s.; outside them they are shaded blue-green and labelled p less than .05. A horizontal line marks a slope of zero, and a thick black bar along it spans roughly minus 4 to 3, marking the range of sleep values actually observed.' width=720}\n:::\n:::\n\n\n**Check its boundaries against the ones we solved for by hand.** The package reports the interval on the centered scale, because `Sleep.C` is what is actually in the model, so it prints -3.22 and -0.80 where we reported 3.35 and 5.77 hours. Add the mean of 6.57 back and they are the same two numbers. Not close. The same:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(\n  manual.lower  = unname(JNRoots[1]),\n  package.lower = unname(jn_result$bounds[1]),\n  manual.upper  = unname(JNRoots[2]),\n  package.upper = unname(jn_result$bounds[2])\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n manual.lower package.lower  manual.upper package.upper \n   -3.2158656    -3.2158656    -0.8036323    -0.8036323 \n```\n:::\n:::\n\n\nThat agreement is the reason for doing it by hand first. The package is not performing a technique you have not already performed with `vcov()` and the quadratic formula. It is doing the same arithmetic faster and drawing a better plot. Use it, now that you could check it.\n\nThe plot is worth reading closely, because it makes the shading do the work our hand-built version did with a grey rectangle: pink where the caffeine slope is not distinguishable from zero, blue-green where it is. Note also the thick black bar lying along zero. That marks the range of sleep values **actually observed**, and the plot deliberately draws the line and band past both ends of it. The package is showing you exactly the extrapolation this section just warned about, and trusting you to notice the bar.\n\nTwo of its arguments are worth knowing about. `alpha` moves the significance threshold that defines the boundaries, so a stricter alpha widens the middle region where the slope cannot be distinguished from zero. And `control.fdr` switches to an interval that accounts for the fact that a Johnson-Neyman region is quietly an enormous family of simple-slope tests, one at every value of the moderator. Turning it on here pushes the boundaries outward, which is the multiple-comparisons problem from the [multiple comparisons chapter](Ch_20_Multiple_Comparisons.qmd) turning up somewhere almost nobody looks for it.\n\n## Centering Cannot Remove the Interaction\n\nMean-centering changes the value represented by zero and therefore changes the lower-order coefficient labels. It does not change fitted values, residuals, $R^2$, or the interaction coefficient in an ordinary two-way product model. If an interaction disappears merely because you centered correctly, something else in the analysis changed too.\n\n## The Short Story\n\n- The slope of $X$ is $b_1+b_3Z$. That derivative **is** the interaction; everything else in this chapter is bookkeeping around it.\n- $b_1$ is the slope of $X$ where $Z = 0$, so make zero mean something. A coefficient in an interaction model is not an effect, it is an effect at a place.\n- **Center for interpretation, not for exorcism.** Centering moves the labels. It does not change fitted values, $R^2$, or the interaction coefficient, and it cannot make a real interaction go away.\n- Probe at values theory chose, or use Johnson-Neyman, and stay inside the observed data. $\\pm1SD$ is a convention, not a law, and it can miss where the sign actually changes.\n- **Standardize the components before forming the product**, never the product itself. The fit is identical and the reported beta is not.\n- Words like *synergistic*, *antagonistic*, and *buffering* are stories about coding. Reverse-score a variable and the label flips while every prediction stays put, so inspect predictions before naming anything.\n- A three-way interaction is a two-way interaction that changes. It is not a coefficient with extra punctuation, and it costs power, measurement, and a theory precise enough to justify it.\n",
    "supporting": [
      "Ch_21_Advanced_Interactions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}