{
  "hash": "e176dc8a9eebde4ea6dc3ec58f267f5f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Statistical Control: What Are We Actually Removing?\"\ngeometry: margin=.5in\nfontsize: 11pt\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n---\n\n\n\n::: {.callout-warning title=\"Advanced Topic: Your Brain May File a Complaint\"}\nThis is difficult material. Graduate students routinely stare at partial and semi-partial correlations as if the correlations have personally betrayed them. If this chapter requires two readings, that does not mean you are bad at statistics. It means we are removing different pieces of relationships and then giving the leftovers nearly identical names.\n\nKeep asking three questions:\n\n1. What variable are we controlling?\n2. Which variable or variables are we removing it from?\n3. What does the resulting number mean?\n:::\n\n## Statistical Control Is Not a Statistics Jail\n\nIn the previous chapter, [Multiple Regression: Statistical Control](Chapter_Multiple_Regression_Control.qmd), we predicted **Exam Score** from **Study Hours** and **Test Anxiety**. Study Hours and Anxiety were related to one another, which meant their relationships with Exam Score overlapped.\n\nMultiple regression gave us a Study Hours slope while *controlling for* Anxiety. That phrase sounds reassuringly official. It also hides nearly all the interesting work.\n\nWe did not put Anxiety in a tiny statistical jail. We did not force every student to experience precisely 50 units of Anxiety. We used a model to remove the **linear association** Anxiety had with another variable and then studied what remained.\n\nThis chapter takes that process apart. We will use the exact same example and simulated data as the multiple-regression chapter, because changing the variables while explaining an already difficult idea would be rude.\n\nOur main question will remain:\n\n> Do Study Hours predict Exam Score after accounting for Test Anxiety?\n\n## The Same Exam Study\n\nThe expected correlations are:\n\n| Relationship | Correlation | Translation |\n|---|---:|---|\n| Study Hours with Exam Score | $+.45$ | Students who study more tend to score higher. |\n| Test Anxiety with Exam Score | $-.40$ | Students who are more anxious tend to score lower. |\n| Study Hours with Test Anxiety | $-.35$ | Students who study more tend to be less anxious. |\n\nThat last relationship creates the control problem. When Study Hours predicts Exam Score, part of that association may travel through the fact that students who study more also tend to be less anxious.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(MASS)\n\nset.seed(42)\n\nn   <- 100\nrY1 <-  0.45  # Study Hours with Exam Score\nrY2 <- -0.40  # Test Anxiety with Exam Score\nr12 <- -0.35  # Study Hours with Test Anxiety\n\nSigma <- matrix(c(\n   1,   rY1, rY2,\n  rY1,   1,  r12,\n  rY2,  r12,  1\n), ncol = 3)\n\nraw <- as.data.frame(\n  mvrnorm(\n    n,\n    mu = c(0, 0, 0),\n    Sigma = Sigma,\n    empirical = TRUE\n  )\n)\n\ncolnames(raw) <- c(\"Exam\", \"StudyHours\", \"Anxiety\")\n\ndat <- data.frame(\n  Exam       = round(raw$Exam * 12 + 75, 1),\n  StudyHours = round(raw$StudyHours * 3 + 8, 1),\n  Anxiety    = round(raw$Anxiety * 10 + 50, 1)\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nround(cor(dat[c(\"StudyHours\", \"Anxiety\", \"Exam\")]), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           StudyHours Anxiety  Exam\nStudyHours       1.00   -0.35  0.45\nAnxiety         -0.35    1.00 -0.40\nExam             0.45   -0.40  1.00\n```\n\n\n:::\n:::\n\n\n## The Ballantine, Now Made Fresh in R\n\nThe circles below represent variance. The overlapping portions represent shared variance. This diagram is called a **Ballantine** because apparently three overlapping circles needed a name, and statisticians had already used \"Venn diagram\" for something fun at parties.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A Ballantine for Study Hours, Test Anxiety, and Exam Score. The areas are conceptual, not drawn to scale.](Chapter_Control_files/figure-html/ballantine-control-1.png){fig-align='center' width=624}\n:::\n:::\n\n\n- **Region $a$** is Exam Score variance uniquely associated with Study Hours.\n- **Region $b$** is Exam Score variance uniquely associated with Test Anxiety.\n- **Region $c$** is Exam Score variance shared by both predictors. Neither predictor gets exclusive custody.\n- **Region $e$** is Exam Score variance the full model does not explain.\n\nThe full regression model explains $a+b+c$. Our main target in this chapter is region $a$: what Study Hours contributes above and beyond Anxiety.\n\n::: {.callout-note title=\"Circles Are a Metaphor\"}\nThe areas are not drawn to scale, variables are not actually circular, and residuals do not fall onto the floor when we remove them. The diagram helps us track which variance belongs in each calculation. Do not demand anatomical accuracy from it.\n:::\n\n## Residuals: The Leftovers\n\nControl begins with a familiar regression. First, predict Study Hours from Anxiety:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstudy_from_anxiety <- lm(StudyHours ~ Anxiety, data = dat)\nsummary(study_from_anxiety)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = StudyHours ~ Anxiety, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.9379 -1.8870  0.1195  1.4007  8.9786 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 13.25031    1.45120   9.131 9.33e-15 ***\nAnxiety     -0.10503    0.02847  -3.690 0.000369 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.833 on 98 degrees of freedom\nMultiple R-squared:  0.122,\tAdjusted R-squared:  0.113 \nF-statistic: 13.61 on 1 and 98 DF,  p-value: 0.0003691\n```\n\n\n:::\n\n```{.r .cell-code}\ndat$ExpectedStudy <- fitted(study_from_anxiety)\ndat$StudyResidual <- residuals(study_from_anxiety)\n```\n:::\n\n\nFor every student:\n\n$$\n\\text{Study residual} = \\text{Actual Study Hours} - \\text{Expected Study Hours}\n$$\n\nSuppose an entirely hypothetical student named Alex has an Anxiety score of 60, studies 10 hours, and earns a 78 on the exam. There is no connection between this fictional Alex and the author except the name, profession, and desperate wish that ten hours of studying always happened.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalex_anxiety <- 60\nalex_actual_study <- 10\nalex_actual_exam <- 78\n\nalex_expected_study <- unname(\n  predict(study_from_anxiety, newdata = data.frame(Anxiety = alex_anxiety))\n)\n\nalex_study_residual <- alex_actual_study - alex_expected_study\n\nalex_table <- data.frame(\n  Anxiety = alex_anxiety,\n  Expected_Study = round(alex_expected_study, 1),\n  Actual_Study = alex_actual_study,\n  Study_Residual = round(alex_study_residual, 1)\n)\n\nknitr::kable(alex_table)\n```\n\n::: {.cell-output-display}\n\n\n| Anxiety| Expected_Study| Actual_Study| Study_Residual|\n|-------:|--------------:|------------:|--------------:|\n|      60|            6.9|           10|            3.1|\n\n\n:::\n:::\n\n\nGiven an Anxiety score of 60, the model expected Alex to study about 6.9 hours. Alex studied 10 hours, so the Study Hours residual is about $+3.1$. Alex studied that many hours **more than expected given Anxiety**.\n\nA positive residual means \"more than expected.\" A negative residual means \"less than expected.\" A residual of zero means the model finally got one exactly right and will be insufferable about it.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Study Hours predicted from Test Anxiety. Selected vertical lines show residuals: the distance between each student's actual and expected Study Hours.](Chapter_Control_files/figure-html/residual-lines-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nAnxiety has now explained whatever linear association it can explain in Study Hours. The Study Hours residuals are the leftovers. Notice what happens if we correlate those leftovers with Anxiety:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(dat$Anxiety, dat$StudyResidual)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.582582e-18\n```\n\n\n:::\n:::\n\n\nIt is essentially zero. That is not luck. Least-squares regression creates residuals that are uncorrelated with the predictors used to create them.\n\n## Semi-Partial Correlation: Remove Anxiety from One Side\n\nWe will learn **semi-partial correlation first** because it connects directly to multiple regression.\n\nTo find the semi-partial relationship between Study Hours and Exam Score while controlling for Anxiety:\n\n1. Predict Study Hours from Anxiety.\n2. Save the Study Hours residuals.\n3. Leave Exam Score completely alone.\n4. Correlate residualized Study Hours with the original Exam Score.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsr_study <- cor(dat$Exam, dat$StudyResidual)\nsr_study\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3323602\n```\n\n\n:::\n:::\n\n\nThe semi-partial correlation is $sr=0.332$.\n\nIts plain-language question is:\n\n> Do students who study more than we would expect from their Anxiety tend to earn higher Exam Scores?\n\nThe answer is yes. More of the Study Hours that Anxiety cannot explain is associated with better Exam performance.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Left: the zero-order Study Hours–Exam Score relationship. Right: the semi-partial relationship after removing Anxiety from Study Hours only.](Chapter_Control_files/figure-html/semipartial-plots-1.png){fig-align='center' width=816}\n:::\n:::\n\n\n### Why Squaring $sr$ Matters\n\nSquaring a semi-partial correlation gives the unique proportion of **total outcome variance** associated with that predictor:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsr2_study <- sr_study^2\nsr2_study\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1104633\n```\n\n\n:::\n:::\n\n\nTherefore, Study Hours uniquely accounts for about 11% of the total variance in Exam Score after the Anxiety-only model has explained everything it can, including the shared region $c$. In the Ballantine, the additional contribution is region $a$.\n\nThis also equals the change in $R^2$ when Study Hours is added to a model that already contains Anxiety.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanxiety_model <- lm(Exam ~ Anxiety, data = dat)\nfull_model <- lm(Exam ~ Anxiety + StudyHours, data = dat)\n\nr2_anxiety <- summary(anxiety_model)$r.squared\nr2_full <- summary(full_model)$r.squared\ndelta_r2_study <- r2_full - r2_anxiety\n\ndata.frame(\n  Quantity = c(\n    \"R-squared: Anxiety only\",\n    \"R-squared: Anxiety + Study Hours\",\n    \"Change in R-squared\",\n    \"Squared semi-partial correlation\"\n  ),\n  Value = round(c(r2_anxiety, r2_full, delta_r2_study, sr2_study), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Quantity Value\n1          R-squared: Anxiety only  0.16\n2 R-squared: Anxiety + Study Hours  0.27\n3              Change in R-squared  0.11\n4 Squared semi-partial correlation  0.11\n```\n\n\n:::\n:::\n\n\nThe last two values match:\n\n$$\nsr^2 = \\Delta R^2\n$$\n\nThat equation is the main reason semi-partial correlation matters in multiple regression. It tells us exactly how much total explanatory power Study Hours adds **above and beyond** Anxiety.\n\nWe can formally compare the nested models with `anova()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(anxiety_model, full_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Exam ~ Anxiety\nModel 2: Exam ~ Anxiety + StudyHours\n  Res.Df   RSS Df Sum of Sq      F    Pr(>F)    \n1     98 11978                                  \n2     97 10404  1    1574.3 14.678 0.0002263 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe test asks whether adding Study Hours improves prediction enough that we should take the improvement seriously, rather than blaming the Probability Gods for a tiny accidental increase.\n\n## Partial Correlation: Remove Anxiety from Both Sides\n\nPartial correlation takes one additional step. We remove Anxiety from **both** Study Hours and Exam Score:\n\n1. Predict Study Hours from Anxiety and save the residuals.\n2. Predict Exam Score from Anxiety and save those residuals too.\n3. Correlate the two sets of residuals.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexam_from_anxiety <- lm(Exam ~ Anxiety, data = dat)\ndat$ExpectedExam <- fitted(exam_from_anxiety)\ndat$ExamResidual <- residuals(exam_from_anxiety)\n\npr_study <- cor(dat$StudyResidual, dat$ExamResidual)\npr_study\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.362534\n```\n\n\n:::\n:::\n\n\nThe partial correlation is $pr=0.363$.\n\nIts plain-language question is:\n\n> Among the portions of Study Hours and Exam Score that Anxiety cannot explain, how strongly are the remaining portions related?\n\nReturn to Hypothetical Alex. Based on Anxiety alone, the model predicts an Exam Score of about 70.2. Alex actually earned a 78. Therefore, Alex scored about 7.8 points **higher than expected given Anxiety**.\n\nPartial correlation asks whether students who study more than Anxiety predicts also score higher than Anxiety predicts.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Semi-partial correlation leaves Exam Score untouched. Partial correlation removes Anxiety from both Study Hours and Exam Score.](Chapter_Control_files/figure-html/partial-plots-1.png){fig-align='center' width=912}\n:::\n:::\n\n\n### Why Partial Correlation Is Larger\n\nFor these data:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npr2_study <- pr_study^2\npr2_study\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1314309\n```\n\n\n:::\n:::\n\n\nThe squared partial correlation is about 13.1%. This does **not** mean Study Hours suddenly explains 13.1% of total Exam Score variance. Semi-partial correlation already told us that the unique contribution to total variance was 11%.\n\nPartial correlation uses a smaller denominator. Anxiety has already removed the Exam Score variance it can explain. Of the Exam Score variance **remaining after Anxiety**, Study Hours is associated with about 13.1%.\n\nIn Ballantine language:\n\n$$\nsr_1^2 = a\n$$\n\n$$\npr_1^2 = \\frac{a}{a+e}\n$$\n\nThe numerator is the same unique Study Hours region. Partial correlation looks larger because it compares region $a$ with only the Exam variance left after Anxiety is removed. It did not discover a stronger effect. It changed the denominator.\n\n## Semi-Partial Versus Partial\n\n| Quantity | Remove Anxiety from Study Hours? | Remove Anxiety from Exam Score? | What does the square mean? |\n|---|:---:|:---:|---|\n| Zero-order $r$ | No | No | Total variance shared by Study Hours and Exam Score |\n| Semi-partial $sr$ | Yes | No | Unique Study Hours contribution to **total** Exam Score variance; $\\Delta R^2$ |\n| Partial $pr$ | Yes | Yes | Study Hours association with Exam Score variance **remaining after Anxiety** |\n\nIf you remember only one distinction, remember this:\n\n> **Semi-partial leaves Y alone. Partial residualizes both sides.**\n\n\"Semi\" does not mean the analysis tried less hard. It means the control variable was removed from only one member of the target relationship.\n\n## The Moderately Mathy Version\n\nThe residual method is the method I want you to understand. The formulas show why the two correlations differ.\n\nLet:\n\n- $r_{Y1}$ be the Exam Score–Study Hours correlation,\n- $r_{Y2}$ be the Exam Score–Anxiety correlation, and\n- $r_{12}$ be the Study Hours–Anxiety correlation.\n\nThe Study Hours semi-partial correlation controlling for Anxiety is:\n\n$$\nsr_{Y(1.2)} =\n\\frac{r_{Y1}-r_{Y2}r_{12}}\n{\\sqrt{1-r_{12}^2}}\n$$\n\nThe partial correlation is:\n\n$$\npr_{Y1.2} =\n\\frac{r_{Y1}-r_{Y2}r_{12}}\n{\\sqrt{(1-r_{Y2}^2)(1-r_{12}^2)}}\n$$\n\nNotice that the numerators are identical. Both calculations isolate the same unique Study Hours–Exam Score relationship. The partial-correlation denominator also removes the outcome variance associated with Anxiety.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr_y1 <- cor(dat$Exam, dat$StudyHours)\nr_y2 <- cor(dat$Exam, dat$Anxiety)\nr_12 <- cor(dat$StudyHours, dat$Anxiety)\n\nsr_formula <- (r_y1 - r_y2 * r_12) / sqrt(1 - r_12^2)\n\npr_formula <- (r_y1 - r_y2 * r_12) /\n  sqrt((1 - r_y2^2) * (1 - r_12^2))\n\nround(c(\n  Residual_sr = sr_study,\n  Formula_sr = sr_formula,\n  Residual_pr = pr_study,\n  Formula_pr = pr_formula\n), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResidual_sr  Formula_sr Residual_pr  Formula_pr \n      0.332       0.332       0.363       0.363 \n```\n\n\n:::\n:::\n\n\nThe residual and formula routes agree. Statistics has briefly behaved itself.\n\n## How This Becomes the Multiple-Regression Slope\n\nHere is the important connection. Compare three slopes:\n\n1. The Study Hours slope from the full multiple regression.\n2. The slope predicting original Exam Score from residualized Study Hours.\n3. The slope predicting residualized Exam Score from residualized Study Hours.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsemipartial_lm <- lm(Exam ~ StudyResidual, data = dat)\npartial_lm <- lm(ExamResidual ~ StudyResidual, data = dat)\n\nround(c(\n  Full_multiple_regression = coef(full_model)[\"StudyHours\"],\n  Original_Y_on_residualized_X = coef(semipartial_lm)[\"StudyResidual\"],\n  Residualized_Y_on_residualized_X = coef(partial_lm)[\"StudyResidual\"]\n), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Full_multiple_regression.StudyHours \n                                      1.414884 \n    Original_Y_on_residualized_X.StudyResidual \n                                      1.414884 \nResidualized_Y_on_residualized_X.StudyResidual \n                                      1.414884 \n```\n\n\n:::\n:::\n\n\nAll three slopes equal about 1.41 Exam Score points per Study Hour.\n\nThis is not a coincidence. The Study Hours coefficient in multiple regression is built from the Study Hours variation that Anxiety cannot linearly explain. This result is sometimes called the **Frisch–Waugh–Lovell theorem**, which is an impressive name for \"residualize the relevant pieces and you recover the same slope.\"\n\nThe practical interpretation is:\n\n> Among students at the same Anxiety level, one additional Study Hour is associated with about 1.41 additional Exam Score points.\n\nThat is a conditional association. It is not automatically a causal effect.\n\n## Where Standardized Beta Fits\n\nNow we have several numbers describing the Study Hours relationship. This is where students reasonably begin asking whether statistics could have used fewer symbols.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat_z <- as.data.frame(scale(dat[c(\"Exam\", \"StudyHours\", \"Anxiety\")]))\nstandardized_model <- lm(Exam ~ StudyHours + Anxiety, data = dat_z)\nbeta_study <- coef(standardized_model)[\"StudyHours\"]\n\ncomparison <- data.frame(\n  Quantity = c(\n    \"Zero-order correlation (r)\",\n    \"Standardized regression slope (beta)\",\n    \"Semi-partial correlation (sr)\",\n    \"Partial correlation (pr)\",\n    \"Squared semi-partial (sr-squared)\",\n    \"Squared partial (pr-squared)\"\n  ),\n  Value = round(c(\n    r_y1,\n    beta_study,\n    sr_study,\n    pr_study,\n    sr2_study,\n    pr2_study\n  ), 3),\n  Meaning = c(\n    \"Uncontrolled Study Hours–Exam association\",\n    \"Conditional slope in standard-deviation units\",\n    \"Unique Study association scaled by total Exam variance\",\n    \"Unique Study association scaled by remaining Exam variance\",\n    \"Unique contribution to total Exam variance; change in R-squared\",\n    \"Proportion of residual Exam variance associated with Study\"\n  )\n)\n\nknitr::kable(comparison)\n```\n\n::: {.cell-output-display}\n\n\n|Quantity                             | Value|Meaning                                                         |\n|:------------------------------------|-----:|:---------------------------------------------------------------|\n|Zero-order correlation (r)           | 0.451|Uncontrolled Study Hours<U+2013>Exam association                |\n|Standardized regression slope (beta) | 0.355|Conditional slope in standard-deviation units                   |\n|Semi-partial correlation (sr)        | 0.332|Unique Study association scaled by total Exam variance          |\n|Partial correlation (pr)             | 0.363|Unique Study association scaled by remaining Exam variance      |\n|Squared semi-partial (sr-squared)    | 0.110|Unique contribution to total Exam variance; change in R-squared |\n|Squared partial (pr-squared)         | 0.131|Proportion of residual Exam variance associated with Study      |\n\n\n:::\n:::\n\n\nThe standardized beta is $\\beta=0.355$. It tells us how many standard deviations Exam Score changes for a one-standard-deviation increase in Study Hours while Anxiety is held constant.\n\nBeta, $sr$, and $pr$ have the same sign here and test the same unique predictor contribution, but they are **not interchangeable**. They standardize the relationship using different variance. Never report one while calling it another because the decimals looked lonely.\n\n## `ppcor`: A Shortcut\n\nFor a strict correlation question involving one outcome, one target predictor, and a control variable, the `ppcor` package can verify our work:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Semi-partial: remove Anxiety from the SECOND variable, StudyHours\nppcor::spcor.test(\n  x = dat$Exam,\n  y = dat$StudyHours,\n  z = dat$Anxiety\n)\n\n# Partial: remove Anxiety from both Exam and StudyHours\nppcor::pcor.test(\n  x = dat$Exam,\n  y = dat$StudyHours,\n  z = dat$Anxiety\n)\n```\n:::\n\n\nThe order matters for `spcor.test()` because the control variable is removed from the **second** variable. Order matters less conceptually for partial correlation because the control is removed from both target variables.\n\n`ppcor` can accept more than one control variable, but it remains a specialized correlation shortcut. Real analyses quickly acquire several predictors, categorical variables, interactions, missing observations, model comparisons, diagnostics, and Reviewer 2. Use `lm()` as your default. It scales to those problems and shows exactly which model you estimated. Use `ppcor` as a quick check when the question is genuinely simple.\n\n## Statistical Control Is Not Experimental Control\n\n::: {.callout-danger title=\"Control Does Not Manufacture Causality\"}\nWe removed linear associations from numbers. We did **not** randomly assign Anxiety, repair measurement error, eliminate variables we forgot to measure, or reach backward through time.\n\nAfter controlling for Anxiety, the Study Hours coefficient describes the association between Study Hours and Exam Score conditional on Anxiety. Calling it \"the true causal effect of studying\" would require a research design and assumptions much stronger than this regression alone provides.\n:::\n\nAdding a control variable does not guarantee that a slope will shrink. Depending on the correlation pattern, a slope can:\n\n- shrink,\n- grow,\n- reverse direction,\n- become more precise,\n- become less precise, or\n- stare into the abyss and become a suppression effect.\n\nControl variables must be selected using theory and research design. Throwing every available column into a regression is not rigor. It is making the software eat the entire refrigerator because you could not decide what to cook.\n\n## Four Questions Before You Escape\n\n### 1. Caffeine, Sleep, and Exam Scores\n\nYou want to know how much **total Exam Score variance** Caffeine uniquely explains after Sleep Hours are already in the model. Do you want a partial or semi-partial correlation?\n\n### 2. The Entirely Ethical Chainsaw Study\n\nYou want the relationship between Fear and Heart Rate after removing Running Speed from **both** variables. Participants are not actually chased with chainsaws because the IRB has once again ruined science. Partial or semi-partial?\n\n### 3. Reviewer 2 Predicts Rejection\n\nYou want to know how much $R^2$ increases when Formatting Errors are added after Manuscript Length. Which squared correlation should equal that change in $R^2$?\n\n### 4. The Causal Caffeine Disaster\n\nYou observe that Caffeine predicts Exam Score after controlling for Sleep. May you conclude that forcing students to drink six espressos will improve their grades?\n\n::: {.callout-tip title=\"Answers, If You Have Suffered Enough\" collapse=\"true\"}\n1. **Semi-partial.** You want Caffeine's unique contribution to total Exam Score variance.\n2. **Partial.** Running Speed is removed from both Fear and Heart Rate.\n3. **Squared semi-partial correlation.** $sr^2=\\Delta R^2$ when Formatting Errors are added last.\n4. **Absolutely not.** Statistical control does not establish causality, and six espressos may merely establish a new relationship with campus medical services.\n:::\n\n## The Survival Version\n\n- **Residual**: what remains after subtracting a model's predicted value from the observed value.\n- **Semi-partial correlation**: remove the control variable from one target variable; $sr^2$ is the unique addition to total $R^2$.\n- **Partial correlation**: remove the control variable from both target variables; $pr^2$ describes the relationship within the outcome variance that remains.\n- **Multiple-regression slope**: can be recovered by predicting Y from the residualized target predictor.\n- **Standardized beta**: the controlled regression slope in standard-deviation units.\n- **Statistical control**: adjustment for measured associations, not a tiny machine that produces causal truth.\n\nIf you can identify what was removed, what it was removed from, and what denominator remains, you understand statistical control. That places you ahead of many graduate students and at least several published papers.\n",
    "supporting": [
      "Chapter_Control_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}