{
  "hash": "9b7870570e96f1e14bbc9b39016be4e8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Distributions and their Moments'\nfontsize: 11pt\ngeometry: margin=.5in\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n---\n\n\n\n\n## What is a distribution?\n\nA **distribution** is a picture of how values spread out in a population:\n\n- Where do most observations land?\n- How much do they vary?\n- Is it symmetric, or does it have a long tail?\n\nThe average alone cannot answer these questions. Two groups can have the same mean while one forms a tidy mound and the other consists of people at both extremes glaring across an empty middle. A mean without its distribution is a witness who has omitted several important details.\n\n### A real distribution\n\nIncome in the US is a classic **positively-skewed** distribution: most households cluster around moderate incomes, with a few earning *very* large amounts.\n\nThis plot uses binned Census data [@uscensus2024], so the mean and median are approximations. Also: the $200k+ bin is *everything* from $200k to infinity — so if it's the tallest bar, that doesn't mean $200k is the most common income. It just means rich people got lumped together.\n\n\n::: {.cell layout-align=\"center\" width='6.5' height='3'}\n::: {.cell-output-display}\n![](Chapter_Distro_Moments_files/figure-html/unnamed-chunk-1-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n**Think about it:**\n\n1. Why is the curve skewed right?\n2. Which number (mean = 123K, median = 80K, or mode = 32.5K) best represents the \"average\" American? Why?\n\n### Historical sidenote\n\nIn the 1950s, the top marginal tax rate in the US was ~91%. Imagine that money went back into schools, housing, and infrastructure.\n\nPredict: how would the income distribution shift? What would happen to the mean, median, and mode? Be explicit about why each one would (or wouldn't) change.\n\n### Distributions have meaning\n\nGovernments use mean and median income to decide who qualifies for financial aid, housing assistance, school lunch programs, tax credits, and healthcare subsidies.\n\nWhen a distribution is highly skewed, these numbers tell very different stories. A rising *mean* can make a country look richer even when **most** households see no change — the median may stay flat. Understanding the shape helps us see who's actually benefiting from policy decisions.\n\n::: {.callout-important title=\"The Mean Can Be Correct and Still Mislead You\"}\nIn a strongly skewed distribution, a small number of enormous values can drag the mean upward.\n\nThat does not make the mean mathematically wrong. It may simply describe the money rather than the experience of a typical person.\n\nAlways inspect the distribution before allowing the mean to speak for everyone.\n:::\n\n## Gaussian (Normal) Distribution\n\nImagine a broad cognitive score influenced by many small factors: sleep, attention, schooling, mood, caffeine, random neural noise, and whether a chainsaw-wielding researcher was standing behind the participant. When many small influences add together, scores can form a smooth, symmetric mound. That mound is the **normal distribution**.\n\nThe Gaussian distribution (named after Carl Friedrich Gauss, 1777–1855) is the foundation of classical parametric statistics because it describes a huge range of psychological phenomena.\n\nTwo parameters fully define it:\n\n- $\\mu$ (mean) — where the center is\n- $\\sigma$ (standard deviation) — how spread out it is\n\nA normal distribution has skewness of zero and excess kurtosis of zero. However, those two values alone do **not** prove that a distribution is normal; very strange distributions can share the same moments. The mean, variance, skewness, and kurtosis are commonly described through the distribution's **moments**. They summarize important features, but they are not a magical distribution-identification scanner.\n\n::: {.callout-warning title=\"Normality Is a Model, Not a Moral Achievement\"}\n\"Normal\" describes a mathematical distribution. It does not mean healthy, desirable, typical, or free from chainsaw-wielding researchers.\n\nA normal distribution has zero skewness and zero excess kurtosis, but matching those two values does not prove that your data are normal. Plot the distribution. Numbers are capable of lying by omission.\n:::\n\n### Simulating a Population in R\n\nWe'll use the normal distribution as our population. R makes this easy with `rnorm()`.\n\nLet's create a population with:\n\n- $\\mu = 100$ points (cognitive score)\n- $\\sigma = 15$ points\n- $N = 1,000,000$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42) # the answer to the universe\nn  <- 1e6   # 1 million people\nMu <- 100   # population mean\nS  <- 15    # population SD\nNormal.Sample.1 <- rnorm(n, mean = Mu, sd = S)\n```\n:::\n\n\n### Histogram (Base R)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(Normal.Sample.1,\n  breaks = 30,\n  col    = \"lightblue\",\n  border = \"black\",\n  main   = \"Raw Score Histogram\",\n  xlab   = \"Population Distribution\",\n  ylab   = \"Frequency\")\nabline(v = Mu, col = \"black\")\n```\n\n::: {.cell-output-display}\n![](Chapter_Distro_Moments_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nLooks normal. Now let's describe its shape using the 4 moments.\n\n## Moments\n\nFour numbers capture the important features of a distribution: center, spread, symmetry, and peakiness.\n\n### Moment 1: Central Tendency\n\nThe center of a distribution can be described three ways:\n\n**Mean** (the average):\n\n- Standard measure of central tendency\n- Heavily influenced by outliers\n- Most stable estimate from sample to sample\n\n**Median** (the middle number):\n\n- Not sensitive to outliers\n- Best measure when the distribution is skewed\n\n**Mode** (most common number):\n\n- Least stable from sample to sample\n\n### Mean\n\n$$M = \\frac{\\Sigma X}{N}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSumX <- sum(Normal.Sample.1)\nN    <- length(Normal.Sample.1)\nM    <- SumX / N\nM\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100.0086\n```\n\n\n:::\n\n```{.r .cell-code}\n# Or all at once:\nM <- sum(Normal.Sample.1) / length(Normal.Sample.1)\n```\n:::\n\n\nThe mean was 100.01 — close to our target $\\mu$ of 100. But just use the built-in:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(Normal.Sample.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100.0086\n```\n\n\n:::\n:::\n\n\n### Median\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedian(Normal.Sample.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100.0208\n```\n\n\n:::\n:::\n\n\nWant to do it by hand? Here's a custom function (mostly to show you why built-ins exist):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncalculate_median <- function(x) {\n  sorted_x <- sort(x)\n  n <- length(sorted_x)\n  if (n %% 2 == 1) {\n    sorted_x[(n + 1) / 2]\n  } else {\n    (sorted_x[n / 2] + sorted_x[(n / 2) + 1]) / 2\n  }\n}\ncalculate_median(Normal.Sample.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100.0208\n```\n\n\n:::\n:::\n\n\nSame answer. Lots of code. This is why R has built-in functions!\n\n### Mode\n\nNo built-in mode function in R for continuous data — and it's almost never used for normal distributions. Note: `mode()` in R tells you the *type* of an object (numeric, factor, etc.), not the statistical mode.\n\n### Moment 2: Spread\n\nVariance describes how spread out a distribution is. In psychology we mostly use **variance** and **standard deviation** because they work well with normal distributions and parametric statistics.\n\nVariability comes from:\n\n- Individual differences (genetics, mood, experience)\n- Research/environment factors (testing conditions, context)\n- Measurement effects\n\nWhen estimating variance from a sample, we divide by $N - 1$ instead of $N$ to get an unbiased estimate. This is called **degrees of freedom**.\n\n### Variance and SD\n\nPopulation variance (when we have the entire population and know $\\mu$):\n$$\\sigma^2 = \\frac{\\Sigma (X-\\mu)^2}{N}$$\n\nSample variance, using $N-1$ to estimate population variance:\n$$S^2 = \\frac{\\Sigma (X-M)^2}{N-1}$$\n\nR vectorizes this for you, but watch your parentheses. The built-in `var()` uses $M$ and $N-1$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nVariance.M <- var(Normal.Sample.1)\n```\n:::\n\n\nSample variance = 225.47\n\n$$S = \\sqrt{S^2}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSD.calc <- sd(Normal.Sample.1)\n```\n:::\n\n\nSample SD = 15.02\n\n::: {.callout-note title=\"Variance Has Weird Units; SD Comes Back Home\"}\nVariance is measured in **squared units**.\n\n- If reaction time is measured in seconds, variance is measured in seconds squared.\n- If exam scores are measured in points, variance is measured in points squared.\n- If cookie-dough devotion is measured in questionable rating units, variance uses questionable rating units squared.\n\nStandard deviation takes the square root of variance, returning to the original units. That is one reason SD is easier to interpret.\n:::\n\n### A Dot Plot: Where Does One Standard Deviation Live?\n\nThe standard deviation is a measure of the **typical distance of scores from the mean**. It is calculated from every score's distance from the mean. It is not defined by capturing a particular percentage of people.\n\nHowever, when a distribution is approximately normal, standard deviations divide the distribution in a very useful and predictable way:\n\n- About 34% of scores fall between the mean and one SD **below** the mean.\n- About 34% fall between the mean and one SD **above** the mean.\n- Put those pieces together, and about 68% fall within one SD of the mean.\n- About 95% fall within two SDs of the mean.\n\nLet us make that visible with a deeply important psychological construct: love of cookie-dough ice cream.\n\nWe ask 240 people:\n\n> **How much do you like cookie-dough ice cream?**\n\nThey answer on a 1--10 unipolar rating scale:\n\n- **1 = Not at all**\n- **10 = I would trade my mother for cookie-dough ice cream**\n\nThe scale is **unipolar** because it begins with none of the feeling and moves in one direction toward more of it. The opposite endpoint is not “I hate cookie-dough ice cream with the fire of a thousand suns.” That would be a bipolar scale and possibly a cry for help.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Simulated cookie-dough ratings. The dots are people; the lines mark the mean and standard-deviation boundaries. The 34%, 68%, and 95% values describe an approximately normal distribution.](Chapter_Distro_Moments_files/figure-html/cookie-dough-sd-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nIn this particular simulated sample, 76.2% of ratings fall within one SD of the mean and 93.3% fall within two SDs. Those values will not equal exactly 68% and 95%. These are discrete ratings from one sample, not obedient dots hired to impersonate a perfect normal curve. Chance is fickle, and a 1--10 scale also has walls at both ends.\n\nThe important visual intuition is this: **one SD takes us from the mean through the thick central part of a normal distribution. Two SDs cover nearly everybody.** A score farther than two SDs from the mean is unusual, although “unusual” does not automatically mean impossible, important, fraudulent, or possessed.\n\n### Relationship between $M$ and $S$\n\nThe standard deviation is expressed in the same units as the scores, but it does not automatically grow just because the mean grows. For strictly positive **ratio-scale** variables, the **coefficient of variation** can compare spread relative to the mean:\n\n$$CV = \\frac{S}{M}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCV <- SD.calc / M\n```\n:::\n\n\n$CV$ = 0.15.\n\n::: {.callout-warning title=\"The CV Needs a Mean Worth Dividing By\"}\nA problem occurs when the mean is close to zero. Dividing by a tiny mean can produce an enormous and unstable CV. If the mean is zero, the CV is undefined.\n\nTherefore, interpret the CV most confidently when zero has a meaningful interpretation, ratios are sensible, and the mean is not hovering near zero while laughing at you.\n:::\n\n### Moment 3: Skewness\n\n$$Skewness = \\frac{\\Sigma(X-M)^3 /N}{S^{3}}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(moments)\nSK.Calc <- skewness(Normal.Sample.1)\n```\n:::\n\n\nSkewness = 0\n\n### Moment 4: Kurtosis\n\n$$Kurtosis = \\frac{\\Sigma(X-M)^4 /N}{S^{4}} - 3$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nK.Calc <- kurtosis(Normal.Sample.1) - 3\n```\n:::\n\n\nKurtosis = 0\n\n### All Four Moments via Tidyverse\n\nThe tidyverse is a collection of R packages that makes data work readable and consistent. Think of it as data operations in near-plain English: take this data, group it, summarize it, done.\n\nWe need three verbs for now:\n\n- `group_by()` — split data into groups\n- `summarise()` — compute statistics per group\n- `filter()` — keep only rows we want\n\nFirst, put our vector into a **data frame** (R's version of a spreadsheet — rows are observations, columns are variables):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nDF <- data.frame(X = Normal.Sample.1)\n```\n:::\n\n\nNow compute all four moments at once:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(moments)\nDesc.table <-\n  DF %>%\n  summarise(N    = n(),\n            M    = mean(X),\n            S    = sd(X),\n            CV   = S / M,\n            Skew = skewness(X),\n            Kurt = kurtosis(X) - 3)\nround(Desc.table, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      N      M     S   CV Skew Kurt\n1 1e+06 100.01 15.02 0.15    0    0\n```\n\n\n:::\n:::\n\n\n## Distributions and Probability\n\nA distribution isn't just a picture of data — it lets us make **probability statements**.\n\nThe height of the curve at any point tells us how likely values near that point are. This is the **Probability Density Function** (PDF).\n\n### Probability Density Function (PDF)\n\n$$f(x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-\\frac{(x - \\mu)^2}{2 \\sigma^2}}$$\n\nLooks scary. The concept is simple:\n\n- Values near the mean → highest density\n- Values far from the mean → lower density\n- Shape is fully determined by $\\mu$ and $\\sigma$\n\nIn practice, we convert to **z-scores** so that mean = 0 and SD = 1, which makes everything easier.\n\n### Z-scores\n\nA **z-score** tells you how far a value is from the mean in standard deviation units:\n\n- z = 0 → exactly at the mean\n- z = 1 → one SD above the mean\n- z = −1 → one SD below the mean\n\nConverting to z-scores does **not change the shape** of the distribution — it just re-labels the axis.\n\n$$Z = \\frac{X - M}{S}$$\n\n::: {.callout-important title=\"A z-Score Is Not a Probability\"}\nA z-score tells us how far a score is from the mean in standard-deviation units.\n\nIt does **not** directly tell us the percentage of people below that score. To obtain a percentile, we must use the appropriate distribution—usually with `pnorm()` when normality is a reasonable model.\n\nA z-score of 1 means one SD above the mean. It does not mean 1%, 10%, or that the participant has won statistics.\n:::\n\n### Making Z-scores in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nNormal.Sample.Z <- scale(Normal.Sample.1, center = TRUE, scale = TRUE)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nDF.Z <- data.frame(X = Normal.Sample.Z)\nDesc.table.Z <-\n  DF.Z %>%\n  summarise(N = n(), M = mean(X), S = sd(X))\nround(Desc.table.Z, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      N M S\n1 1e+06 0 1\n```\n\n\n:::\n:::\n\n\nThe shape doesn't change:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(Normal.Sample.Z,\n  breaks = 30,\n  col    = \"lightblue\",\n  border = \"black\",\n  main   = \"Z Score Histogram\",\n  xlab   = \"Population Distribution\",\n  ylab   = \"Frequency\")\nabline(v = 0, col = \"black\")\n```\n\n::: {.cell-output-display}\n![](Chapter_Distro_Moments_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n### Finding Probability from Z-scores\n\nTwo functions to know:\n\n- `dnorm()` → height of the curve (density) at a value\n- `pnorm()` → area under the curve to the left of a value (probability)\n\nThe PDF `dnorm()` implements:\n\n$$f(x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-\\frac{(x - \\mu)^2}{2 \\sigma^2}}$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Distro_Moments_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n### How much of the population is below the mean?\n\nExactly 50% — the normal distribution is symmetric. Confirm it:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5\n```\n\n\n:::\n:::\n\n\nWhat proportion falls between 1 and 2 SDs above the mean?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(2) - pnorm(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1359051\n```\n\n\n:::\n:::\n\n\nNo calculus. Just area under the curve.\n\n## Real-World Example: Mental Rotation Test\n\nWe now know how to:\n\n- Describe distributions\n- Standardize scores with z-scores\n- Convert z-scores to probabilities\n\nLet's apply all of it to a real psychological measure.\n\nThe **Mental Rotations Test (MRT)** measures spatial visualization ability. Peters et al. developed a redrawn version and examined factors affecting performance [@peters1995]. Here's a summary by field and gender:\n\n|     | Sciences |     |      |     | Social Sciences & Humanities |      |      |\n|-----|----------|-----|------|-----|------------------------------|------|------|\n|     | n        | M   | SD   |     | n                            | M    | SD   |\n| M   | 817      | 15.23 | 4.42 |   | 517                        | 12.74 | 4.87 |\n| F   | 392      | 11.18 | 4.37 |   | 1358                       | 8.75  | 4.18 |\n\n**Note: the code below is more advanced — you don't need to understand it yet.**\n\n### Step 1: Simulate the population distributions\n\nWe only have summary stats, but because MRT scores are approximately normal we can **simulate each group** using `rnorm()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(123)\n\nparams <- tribble(\n  ~Field,            ~Group, ~n,    ~mean,  ~sd,\n  \"Sciences\",        \"M\",    817,   15.23,  4.42,\n  \"Sciences\",        \"F\",    392,   11.18,  4.37,\n  \"Social Sciences\", \"M\",    517,   12.74,  4.87,\n  \"Social Sciences\", \"F\",    1358,   8.75,  4.18\n)\n\nMRT.2 <- params %>%\n  mutate(data = map2(n, mean, ~rnorm(.x, mean = .y, sd = params$sd[params$n == .x]))) %>%\n  unnest(data) %>%\n  select(Field, Group, Value = data)\n```\n:::\n\n\nCheck that our simulation matches published values:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nMRT.table <-\n  MRT.2 %>%\n  group_by(Field, Group) %>%\n  summarise(N = n(), M = mean(Value), S = sd(Value))\nMRT.table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 5\n# Groups:   Field [2]\n  Field           Group     N     M     S\n  <chr>           <chr> <int> <dbl> <dbl>\n1 Sciences        F       392 11.4   4.47\n2 Sciences        M       817 15.3   4.34\n3 Social Sciences F      1358  8.74  4.16\n4 Social Sciences M       517 12.9   4.88\n```\n\n\n:::\n:::\n\n\n### Step 2: Visualize the distributions\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(MRT.2, aes(x = Value, fill = Group, color = Group)) +\n  geom_histogram(aes(y = ..density..), position = \"identity\", alpha = 0.3, bins = 30) +\n  geom_density(alpha = 0.1) +\n  facet_wrap(~ Field) +\n  labs(title = \"Overlaid Histograms & Density Plots\", x = \"Score\", y = \"Density\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Chapter_Distro_Moments_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n### Step 3: Convert to z-scores (within groups)\n\nStandardize within each group — critical because each group has a different mean and SD.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nMRT.2 <- MRT.2 %>%\n  group_by(Field, Group) %>%\n  mutate(Z = scale(Value))\nMRT.2 %>% head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 4\n# Groups:   Field, Group [1]\n  Field    Group Value   Z[,1]\n  <chr>    <chr> <dbl>   <dbl>\n1 Sciences M      12.8 -0.583 \n2 Sciences M      14.2 -0.247 \n3 Sciences M      22.1  1.58  \n4 Sciences M      15.5  0.0594\n5 Sciences M      15.8  0.119 \n6 Sciences M      22.8  1.73  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(MRT.2, aes(x = Z, fill = Group, color = Group)) +\n  geom_histogram(aes(y = ..density..), position = \"identity\", alpha = 0.3, bins = 30) +\n  geom_density(alpha = 0.1) +\n  facet_wrap(~ Field) +\n  labs(title = \"Overlaid Histograms & Density Plots\", x = \"Z-Score\", y = \"Density\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Chapter_Distro_Moments_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nWhy do the curves overlap now? Because standardizing compares *relative position within each group*, not raw scores.\n\n### Step 4: Z-score to probability\n\nAlex (male, social sciences) got a score of 10. How did he do relative to his peers? (Males, Social Sciences: $M$ = 12.74, $S$ = 4.87)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nZ.Alex <- (10 - 12.75) / 4.87\nZ.Alex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5646817\n```\n\n\n:::\n:::\n\n\nA little over half an SD below the mean. Visually:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nMRT.2.Males.Social.Sciences <- MRT.2 %>% filter(Group == \"M\" & Field == \"Social Sciences\")\n\nggplot(MRT.2.Males.Social.Sciences, aes(x = Z)) +\n  geom_histogram(aes(y = ..density..), position = \"identity\", alpha = 0.3, bins = 30) +\n  geom_density(alpha = 0.1) +\n  labs(title = \"Males in the Social Sciences\", x = \"Z-Score\", y = \"Density\") +\n  theme_bw() +\n  geom_vline(xintercept = Z.Alex, color = 'red')\n```\n\n::: {.cell-output-display}\n![](Chapter_Distro_Moments_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(Z.Alex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2861451\n```\n\n\n:::\n:::\n\n\nOnly better than 28.6% of peers. That's also called a **percentile**.\n\n### Step 5: Same raw score, different meaning\n\nEmma also scored a 10, but she's in a different group (Female, Social Sciences: $M$ = 8.75, $S$ = 4.18).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nZ.Emma <- (10 - 8.75) / 4.18\nZ.Emma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2990431\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(Z.Emma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6175464\n```\n\n\n:::\n:::\n\n\nEmma scored better than 61.75% of her peers.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncurve(pnorm, from = -10, to = 10,\n  main = \"Cumulative Density Function\",\n  xlab = \"z-score\", ylab = \"Probability\",\n  xlim = c(-3.25, 3.25))\nabline(v = Z.Emma, col = \"red\")\nabline(v = Z.Alex, col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](Chapter_Distro_Moments_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nSame raw score. Emma is above average for her group; Alex is below average for his. Raw scores mean nothing without context.\n\n### Big idea\n\n- Raw scores mean nothing without context.\n- Distributions give scores meaning.\n\n## The Short Story\n\n- A distribution shows which values occur and how often.\n- The mean locates the center; variance and standard deviation describe spread.\n- Skewness describes asymmetry; kurtosis describes tail weight and peak shape relative to a reference distribution.\n- Zero skewness and zero excess kurtosis do not prove normality. Strange distributions are capable of wearing fake mustaches.\n- z-scores translate raw scores into standard-deviation units.\n- The same raw score can mean very different things in different reference groups.\n- Always inspect the distribution before asking one summary number to represent several hundred people without supervision.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}