{
  "hash": "14fb5ae6b9720ff229ca2975a8b35611",
  "result": {
    "markdown": "---\ntitle: 'Distributions and their Moments'\n---\n\n\n\n\n\n\n## What is a distribution?\n\nA **distribution** is a picture of how values spread out in a population:\n\n- Where do most observations fall?\n- How much do they vary?\n- Is it symmetric, or does it have a long tail?\n\nThe average alone cannot answer these questions. Two groups can have the same mean while one forms a tidy hill and the other consists of people at both extremes glaring across an empty middle. A mean without its distribution is a witness who has omitted several important details.\n\n### A real distribution\n\nIncome in the US is a classic **positively-skewed** distribution: most households cluster around moderate incomes, with a few earning *very* large amounts.\n\nThis plot uses binned Census data [@uscensus2024], so the mean and median are approximations. Also: the $200k+ bin is *everything* from $200k to infinity---so if it's the tallest bar, that doesn't mean $200k is the most common income. It just means rich people got lumped together.\n\nThat open-ended bin also means our mean below is too *low*. We estimate each bin by its midpoint, and \"$200,000 to infinity\" has no midpoint, so those households get dropped. Census reports a higher mean than we compute here for exactly that reason. The richest households are the ones you cannot put a midpoint on, and they are precisely the ones dragging the real mean upward.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![U.S. household income. The mean sits well to the right of the median, which is what skew does to an average.](Chapter_Distro_Moments_files/figure-pdf/income-distribution-1.pdf){fig-align='center' fig-alt='Histogram of U.S. household income by bin, with a long right tail. Vertical lines mark the approximate mode near thirty thousand dollars, the median near eighty thousand, and the mean well to the right of both, past one hundred thousand.'}\n:::\n:::\n\n\n\n**Think about it:**\n\n1. Why is there a positive skew (the tail points right on the x-axis, toward the larger numbers)?\n2. Which number---mean = $110K, median = $80K, or mode = $32K---best represents the \"average\" American? Why?\n3. Notice the three numbers are not close to each other. If a politician wanted to claim Americans are doing great, which one would they quote? If they wanted to claim the opposite?\n\n### A sidenote for the curious\n\nSuppose a policy substantially reduced the highest incomes and moved that money into schools, housing, and infrastructure.\n\n**Predict:** how would the income distribution shift? What would happen to the mean, median, and mode? Be explicit about why each one would (or would not) change. This is a distribution question, not a political one---the same reasoning works if you run the policy backward.\n\n### Distributions have meaning\n\nGovernments tend to use median income to decide who qualifies for financial aid, housing assistance, school lunch programs, tax credits, and healthcare subsidies.\n\nWhen a distribution is highly skewed, these numbers tell very different stories. A rising *mean* can make a country look richer even when **most** households see no change---the median may stay flat. Understanding the shape helps us see who's actually benefiting from policy decisions.\n\n::: {.callout-important title=\"The Mean Can Be Correct and Still Mislead You\"}\nIn a strongly skewed distribution, a small number of enormous values can drag the mean upward.\n\nThat does not make the mean mathematically wrong. It may simply describe the US income inequality problem rather than the experience of a typical person.\n\nAlways inspect the distribution before allowing the mean to speak for everyone.\n:::\n\n## Gaussian (Normal) Distribution\n\nImagine a general cognitive measure influenced by many small factors: sleep, attention, schooling, mood, caffeine, random neural noise, and whether a bat-wielding researcher was standing behind the participant. When many small influences add together, scores can form a smooth, symmetric hill. That hill is the **normal distribution**.\n\nThe Gaussian distribution (named after Carl Friedrich Gauss, 1777–1855) is the foundation of classical parametric statistics because (*we pretend*) it describes a huge range of psychological phenomena.\n\nTwo parameters fully define it:\n\n- $\\mu$ (mean)---where the center is\n- $\\sigma$ (standard deviation)---how spread out it is\n\nA normal distribution has skewness of zero and excess kurtosis of zero. However, those two values alone do **not** prove that a distribution is normal; very strange distributions can share the same moments. The mean, variance, skewness, and kurtosis are commonly described through the distribution's **moments**. They summarize important features, but they are not a magical distribution-identification scanner.\n\n::: {.callout-warning title=\"Normality Is a Model, Not a Moral Achievement\"}\n\"Normal\" describes a mathematical distribution. It does not mean healthy, desirable, typical, or free from bat-wielding researchers.\n\nA normal distribution has zero skewness and zero excess kurtosis, but matching those two values does not prove that your data are normal. Plot the distribution. Numbers are capable of lying by omission.\n:::\n\n### Simulating a Population in R\n\n::: {.callout-note title=\"You Do Not Know These Words Yet, and That Is Fine\"}\nThe code below asks for a mean and a standard deviation, and I have not taught you either one. On purpose.\n\nRight now this is just a machine for manufacturing a million fake people so we have something to look at. By the end of this chapter you will know exactly what every term in it means, and you can come back and read it again with the smug satisfaction of someone who understands the joke the second time.\n:::\n\nWe'll use the normal distribution as our population. R makes this easy with `rnorm()`.\n\nLet's create a population with:\n\n- $\\mu = 100$ points (cognitive score)\n- $\\sigma = 15$ points\n- $N = 1,000,000$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)  # so your million fake people are the same as my million fake people\nn  <- 1e6     # 1e6 is scientific notation for 1,000,000\nMu <- 100     # population mean\nS  <- 15      # population SD\n\n# rnorm() = \"random normal\". Draw n scores from a normal distribution\n# with the mean and SD we just specified.\nNormal.Sample.1 <- rnorm(n, mean = Mu, sd = S)\n```\n:::\n\n\n\n### Histogram (Base R)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(Normal.Sample.1,\n  breaks = 30,\n  col    = \"lightblue\",\n  border = \"black\",\n  main   = \"Raw Score Histogram\",\n  xlab   = \"Population Distribution\",\n  ylab   = \"Frequency\")\nabline(v = Mu, col = \"black\")\n```\n\n::: {.cell-output-display}\n![One million simulated cognitive scores. This is what we mean by a population: everybody, not a sample of them.](Chapter_Distro_Moments_files/figure-pdf/raw-score-histogram-1.pdf){fig-align='center' fig-alt='Histogram of one million simulated scores, forming a symmetric bell shape centered on 100, with a vertical line marking the population mean and almost all scores falling between 55 and 145.'}\n:::\n:::\n\n\n\nLooks normal. Now let's describe its shape using the 4 moments.\n\n## Moments\n\nFour numbers capture the important features of a distribution: center, spread, symmetry, and peakiness.\n\n::: {.callout-note collapse=\"true\" title=\"Pedantic Fine Print for Graduate Students\"}\nCalling all four of these \"the moments\" is teaching shorthand. Strictly, the mean is the first *raw* moment, the variance is the second *central* moment, and skewness and kurtosis are the third and fourth *standardized* moments. Nobody at a party cares. \n:::\n\n### Moment 1: Central Tendency\n\nThe center of a distribution can be described three ways:\n\n**Mean** (the average):\n\n- Standard measure of central tendency\n- Heavily influenced by outliers\n- Most stable estimate from sample to sample\n\n**Median** (the middle number):\n\n- Not sensitive to outliers\n- Best measure when the distribution is skewed\n\n**Mode** (most common number):\n\n- Least stable from sample to sample\n\n### Mean\n\n$$M = \\frac{\\Sigma X}{N}$$\n\nAdd up every score, divide by how many there are. You have done this since grade school.\n\n::: {.callout-important title=\"Two Symbols for the Mean, and You Will Only Ever Have One of Them\"}\nThere is a mean of the **population**, written $\\mu$ (the Greek letter *mu*, said \"mew\"), and a mean of your **sample**, written $M$.\n\nThey are not two names for the same thing. $\\mu$ is the real answer, the average of every person in the population, and **you will almost certainly never know it.** It exists, it is a fixed number, and it is none of your business. $M$ is what you get when you grab a handful of people and average them. It is your estimate of $\\mu$, and it is the only one of the two you will ever hold in your hand.\n\nThis chapter is a rare exception, because I built the population myself and can therefore cheat. I told R that $\\mu = 100$. In a real study nobody hands you that number, which is exactly why the next several chapters exist.\n\nThe same split is coming for spread: $\\sigma$ for the population, $S$ for your sample. Same relationship, same problem, same resignation.\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSumX <- sum(Normal.Sample.1)         # add up every score\nN    <- length(Normal.Sample.1)      # count how many scores there are\nM    <- SumX / N                     # divide: that is the mean\nM\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 100.0086\n```\n:::\n\n```{.r .cell-code}\n# Or all at once:\nM <- sum(Normal.Sample.1) / length(Normal.Sample.1)\n```\n:::\n\n\n\nThe mean was 100.01---close to our target $\\mu$ of 100, though notice it is not *exactly* 100 even with a million people. But just use the built-in:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(Normal.Sample.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 100.0086\n```\n:::\n:::\n\n\n\n### Median\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedian(Normal.Sample.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 100.0208\n```\n:::\n:::\n\n\n\nWant to do it by hand? This is a good excuse to explain what a **function** actually is, because you have been using them since Chapter 2 without anyone defining the word.\n\nA function is a machine you build once and then use forever. You hand it something, it does its work, it hands something back. `mean()` is a function: you hand it numbers, it hands back their average. So is `sort()`, and `length()`, and every other word in this book followed by parentheses.\n\nYou can build your own with `function()`. The thing in the parentheses is the **argument**, the placeholder for whatever gets handed in. Here is the median, built from scratch:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Define a function called calculate_median that takes one input, x.\ncalculate_median <- function(x) {\n\n  sorted_x <- sort(x)         # step 1: put the scores in order, smallest to largest\n  n <- length(sorted_x)       # step 2: count how many there are\n\n  if (n %% 2 == 1) {          # step 3: is n odd? (%% gives the remainder after dividing)\n\n    sorted_x[(n + 1) / 2]     # odd, so there is one number dead in the middle. Take it.\n\n  } else {\n\n    # even, so there is no single middle. Take the two middle numbers\n    # and average them.\n    (sorted_x[n / 2] + sorted_x[(n / 2) + 1]) / 2\n  }\n}\n\n# Now USE the machine we just built.\ncalculate_median(Normal.Sample.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 100.0208\n```\n:::\n:::\n\n\n\nTwo bits of syntax worth naming, because they show up constantly:\n\n- **`sorted_x[3]`** means \"the 3rd item in `sorted_x`.\" Square brackets pull items out by position.\n- **`%%`** is the remainder operator. `7 %% 2` is 1, because 7 divided by 2 leaves 1 over. So `n %% 2 == 1` is R's way of asking \"is n odd?\"\n\nSame answer as `median()`. Lots of code. This is why R has built-in functions!\n\n### Mode\n\nNo built-in mode function in R for continuous data---and it's almost never used for normal distributions. Note: `mode()` in R tells you the *type* of an object (numeric, factor, etc.), not the statistical mode.\n\n### Moment 2: Spread\n\nVariance describes how spread out a distribution is. In psychology we mostly use **variance** and **standard deviation** because they work well with normal distributions and parametric statistics.\n\nVariability comes from:\n\n- Individual differences (genetics, mood, experience---what they ate for lunch that day)\n- Research/environment factors (testing conditions, context---the researcher wearing a blood-soaked white coat)\n- Measurement effects (fatigue, questions priming answers---don't think about a pink elephant)\n\nWhen estimating variance from a sample, we divide by $N - 1$ instead of $N$ to get an unbiased estimate. This is called **degrees of freedom**.\n\nThat sentence is true and completely unhelpful, so let us do better. There are two questions hiding in it, and students ask both of them every single year.\n\n### Why Square the Deviations?\n\nStart with the obvious idea: to measure spread, average how far each score sits from the mean. Try it.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(2, 4, 4, 4, 5, 5, 7, 9)\nx - mean(x)        # each score's distance from the mean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3 -1 -1 -1  0  0  2  4\n```\n:::\n\n```{.r .cell-code}\nsum(x - mean(x))   # add them all up\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\n\nZero. Not close to zero---zero. It will be zero for every data set you will ever collect, because that is what a mean *is*: the balance point where the negatives and positives cancel exactly.\n\nSo the honest average distance is useless as a measure of spread. Squaring fixes it: every squared deviation is positive, nothing cancels, and bigger deviations count for disproportionately more.\n\n### Why Divide by $N-1$ and Not $N$?\n\nHere is the intuition. Once you know the mean and all but one of the deviations, the last deviation is not free---it is forced to be whatever makes the sum come out to zero. Eight numbers, but only seven of them can vary independently once the mean is fixed. You have $N-1$ independent pieces of information, so you divide by $N-1$.\n\nThat is the explanation. Here is the proof, because code is an awesome way to settle an argument.\n\nThis uses a function you will see constantly from here on: **`replicate()`**. It does exactly what the name says. You give it a number and a block of code, and it runs that code that many times, collecting every answer. `replicate(10000, ...)` means \"do this ten thousand times and keep all ten thousand results.\" It is how we run a study over and over without recruiting a single human.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\n# The truth: a population with variance of exactly 25 (because SD = 5, and 5^2 = 25).\ntruth <- 25\n\n# Run the following block 10,000 times, keeping every answer.\nestimates <- replicate(10000, {\n\n  s <- rnorm(8, mean = 100, sd = 5)   # grab a tiny sample of 8 people\n  deviations <- (s - mean(s))^2       # squared distance of each score from ITS OWN mean\n\n  # Compute the variance two ways and return both.\n  c(divide_by_N   = sum(deviations) / 8,   # the tempting way\n    divide_by_N_1 = sum(deviations) / 7)   # the N-1 way\n})\n\n# estimates now holds 10,000 answers of each kind. Average them.\nround(rowMeans(estimates), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  divide_by_N divide_by_N_1 \n        21.80         24.91 \n```\n:::\n:::\n\n\n\nDividing by $N$ gives an answer that is systematically too small. Dividing by $N-1$ lands closer to the truth. Ten thousand samples do not lie, and now you never have to wonder whether that $-1$ is a typo. I will have lots of typos in other places for you to find. \n\n### Variance and SD\n\nPopulation variance (when we have the entire population and know $\\mu$):\n$$\\sigma^2 = \\frac{\\Sigma (X-\\mu)^2}{N}$$\n\nSample variance, using $N-1$ to estimate population variance:\n$$S^2 = \\frac{\\Sigma (X-M)^2}{N-1}$$\n\n::: {.callout-important title=\"Greek Letters Are the Truth; Roman Letters Are Your Guess\"}\nYou just met the second pair, so here is the rule that runs through the entire rest of this book.\n\n| | Population (the truth) | Sample (your estimate) |\n|---|---|---|\n| Mean | $\\mu$ (mu) | $M$ |\n| Variance | $\\sigma^2$ (sigma squared) | $S^2$ |\n| Standard deviation | $\\sigma$ (sigma) | $S$ |\n\n**Greek letters describe the population.** They are fixed, real, and almost always unknowable.\n\n**Roman letters describe your sample.** They are computed from data you actually collected, they change every time you collect new data, and they are your best available guess at the Greek letter sitting behind them.\n\nSo $M$ is your guess at $\\mu$, and $S$ is your guess at $\\sigma$. When you see a Greek letter in a formula, ask yourself where that number is supposed to come from, because in real research the answer is usually \"nowhere, and that is the problem we are about to solve.\"\n:::\n\nR vectorizes this for you (turns into a string of numbers), but watch your parentheses. The built-in `var()` uses $M$ and $N-1$:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nVariance.M <- var(Normal.Sample.1)\n```\n:::\n\n\n\nSample variance = 225.47\n\n$$S = \\sqrt{S^2}$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSD.calc <- sd(Normal.Sample.1)\n```\n:::\n\n\n\nSample SD = 15.02\n\n::: {.callout-note title=\"Variance Has Weird Units; SD Comes Back Home\"}\nVariance is measured in **squared units**.\n\n- If reaction time is measured in seconds, variance is measured in seconds squared.\n- If exam scores are measured in points, variance is measured in points squared.\n- If cookie-dough devotion is measured in questionable rating units, variance uses questionable rating units squared.\n\nStandard deviation takes the square root of variance, returning to the original units. That is one reason SD is easier to interpret.\n:::\n\n### A Dot Plot: Where Does One Standard Deviation Live?\n\nThe standard deviation is a measure of the **typical distance of scores from the mean**. It is calculated from every score's distance from the mean. It is not defined by capturing a particular percentage of people. But what does **typical distance** mean? *What do truth and god mean, for that matter? Well, to quote the great teacher G'Kar, truth is a river and god is the mouth of that river. Note: if you got that joke, you are a super nerd and we can be friends.*\n\nThe **typical distance** concept applies really only when the distribution is approximately normal and the standard deviations divide the distribution in a very useful and predictable way:\n\n- About 34% of scores fall between the mean and one SD **below** the mean.\n- About 34% fall between the mean and one SD **above** the mean.\n- Put those pieces together, and about 68% fall within one SD of the mean.\n- About 95% fall within two SDs of the mean.\n\nLet us make that visible with an extremely central psychological construct: love of cookie-dough ice cream.\n\nWe ask 240 people:\n\n> **How much do you like cookie-dough ice cream?**\n\nThey answer on a 1--10 unipolar rating scale:\n\n- **1 = Not at all**\n- **10 = I would trade my mother for cookie-dough ice cream**\n\nThe scale is **unipolar** because it begins with none of the feeling and moves in one direction toward more of it. The opposite endpoint is not “I hate cookie-dough ice cream with the fire of a thousand suns.” That would be a bipolar scale and clearly a cry for professional help.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Simulated cookie-dough ratings. The dots are people; the lines mark the mean and standard-deviation boundaries. The 34%, 68%, and 95% values describe an approximately normal distribution.](Chapter_Distro_Moments_files/figure-pdf/cookie-dough-sd-1.pdf){fig-align='center' fig-alt='A jittered dot plot of 240 cookie-dough ratings on a 1 to 10 scale. A solid vertical line marks the mean, dashed lines mark one standard deviation on each side, and dotted lines mark two. Shaded bands label about 34 percent between the mean and each one-SD boundary, about 68 percent within one SD, and about 95 percent within two SDs.'}\n:::\n:::\n\n\n\nIn this particular simulated sample, 76.2% of ratings fall within one SD of the mean and 93.3% fall within two SDs. Those values will not equal exactly 68% and 95%. These are discrete ratings from one sample, not obedient dots hired to impersonate a perfect normal curve. Chance is fickle, and a 1--10 scale also has walls at both ends.\n\nThe important visual intuition is this: **one SD takes us from the mean through the thick central part of a normal distribution. Two SDs cover nearly everybody.** A score farther than two SDs from the mean is unusual, although “unusual” does not automatically mean impossible, important, fraudulent, or possessed by evil spirits.\n\n### Relationship between $M$ and $S$\n\nThe standard deviation is expressed in the same units as the scores, and it does not automatically grow just because the mean grows---although annoyingly, it tends to. For positive **ratio-scale** variables, the **coefficient of variation** can compare spread relative to the mean:\n\n$$CV = \\frac{S}{|M|}$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nCV <- SD.calc / abs(M)\n```\n:::\n\n\n\n$CV$ = 0.15.\n\n::: {.callout-warning title=\"The CV Needs a Mean Worth Dividing By\"}\nA problem occurs when the mean is close to zero. Dividing by a tiny mean can produce an enormous and unstable CV. If the mean is zero, the CV is undefined.\n\nTherefore, interpret the CV most confidently when zero has a meaningful interpretation, ratios are sensible, and the mean is not hovering near zero while laughing at you.\n:::\n\n### Moment 3: Skewness\n\nSkewness is how asymmetrical the hill is. Generally, the farther the value is from zero, the more skewed the distribution. Human data will almost always be somewhat asymmetrical, like most of our faces. When people's ears or eyes are slightly asymmetrical, we generally choose to ignore the problem for reasons---assumptions, really---that we hope are true. More on that later.\n\nThe skewness formula is below for completeness. Almost nobody reports the metric.\n\n$$Skewness = \\frac{\\Sigma(X-M)^3 /N}{S^{3}}$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(moments)\nSK.Calc <- skewness(Normal.Sample.1)\n```\n:::\n\n\n\nSkewness = 0\n\n### Moment 4: Kurtosis\n\nThis is peakiness! You can have flattish, longish hills (**platykurtic**) or skinny, tall hills (**leptokurtic**). I would be remiss to my mother if I did not point out that these are Greek words. *I would also like to point out that nobody has ever confused my body shape with leptokurtotic.*\n\nThe kurtosis formula is below for completeness. Not only does almost nobody report it, I do not think many people know how to make sense of the numbers it spews out.\n\n$$Kurtosis = \\frac{\\Sigma(X-M)^4 /N}{S^{4}} - 3$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nK.Calc <- kurtosis(Normal.Sample.1) - 3\n```\n:::\n\n\n\nKurtosis = 0\n\n### All Four Moments via Tidyverse\n\nThe tidyverse is a collection of R packages that makes data work readable and consistent. Think of it as data operations in near-plain English: take this data, group it, summarize it, done.\n\nWe need three verbs for now:\n\n- `group_by()`---split data into groups\n- `summarise()`---compute statistics per group\n- `filter()`---keep only rows we want\n\nFirst, put our vector into a **data frame** (R's version of a spreadsheet---rows are observations, columns are variables):\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nDF <- data.frame(X = Normal.Sample.1)\n```\n:::\n\n\n\nNow compute all four moments at once:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)   # loads dplyr, ggplot2, and friends\nlibrary(moments)     # gives us skewness() and kurtosis()\n\nDesc.table <-\n  DF %>%                        # take the data frame, then...\n  summarise(N    = n(),                 # count the rows\n            M    = mean(X),             # moment 1: center\n            S    = sd(X),               # moment 2: spread\n            CV   = S / abs(M),          # spread relative to the mean\n            Skew = skewness(X),         # moment 3: lopsidedness\n            Kurt = kurtosis(X) - 3)     # moment 4: tails (minus 3 = \"excess\")\n\nround(Desc.table, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      N      M     S   CV Skew Kurt\n1 1e+06 100.01 15.02 0.15    0    0\n```\n:::\n:::\n\n\n\nThat `%>%` is a **pipe**. Read it as the word \"then.\" It takes whatever is on its left and feeds it into the function on its right, so `DF %>% summarise(...)` means \"take DF, *then* summarise it.\" It saves you from writing `summarise(DF, ...)` with everything crammed inside one set of parentheses, and it gets very handy once you are stacking four or five operations.\n\n::: {.callout-tip title=\"About All Those Plots I Keep Making Without Explaining Them\"}\nYou have now seen several figures built with `ggplot()`, and I have never once told you how it works. That is deliberate. Explaining the grammar of graphics in the middle of a chapter about variance would help nobody.\n\nThere is a whole chapter on `ggplot()` and the tidyverse at the end of the book. When you want to make your own plots rather than read mine, go there. For now, feel free to copy any plotting code you see, change the variable names, and see what happens. That is how everyone learns it anyway.\n:::\n\n## Distributions and Probability\n\nA distribution isn't just a picture of data---it lets us make **probability statements**.\n\nThe height of the curve at any point tells us how likely values near that point are. This is the **Probability Density Function** (PDF).\n\n### Probability Density Function (PDF)\n\n$$f(x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-\\frac{(x - \\mu)^2}{2 \\sigma^2}}$$\n\nLooks scary. The concept is simple:\n\n- Values near the mean $\\rightarrow$ highest density\n- Values far from the mean $\\rightarrow$ lower density\n- Shape is fully determined by $\\mu$ and $\\sigma$\n\nIn practice, we convert to **z-scores** so that mean = 0 and SD = 1, which makes everything easier.\n\n### Z-scores\n\nA **z-score** tells you how far a value is from the mean in standard deviation units:\n\n- z = 0 $\\rightarrow$ exactly at the mean\n- z = 1 $\\rightarrow$ one SD above the mean\n- z = −1 $\\rightarrow$ one SD below the mean\n\nConverting to z-scores does **not change the shape** of the distribution---it just re-labels the axis.\n\n$$Z = \\frac{X - M}{S}$$\n\n::: {.callout-important title=\"A z-Score Is Not a Probability\"}\nA z-score tells us how far a score is from the mean in standard-deviation units.\n\nIt does **not** directly tell us the percentage of people below that score. To obtain a percentile, we must use the appropriate distribution—usually with `pnorm()` when normality is a reasonable model.\n\nA z-score of 1 means one SD above the mean. It does not mean 1%, 10%, or that the participant has won statistics.\n:::\n\n### Making Z-scores in R\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nNormal.Sample.Z <- scale(Normal.Sample.1, center = TRUE, scale = TRUE)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nDF.Z <- data.frame(X = Normal.Sample.Z)\nDesc.table.Z <-\n  DF.Z %>%\n  summarise(N = n(), M = mean(X), S = sd(X))\nround(Desc.table.Z, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      N M S\n1 1e+06 0 1\n```\n:::\n:::\n\n\n\nThe shape doesn't change:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhist(Normal.Sample.Z,\n  breaks = 30,\n  col    = \"lightblue\",\n  border = \"black\",\n  main   = \"Z Score Histogram\",\n  xlab   = \"Population Distribution\",\n  ylab   = \"Frequency\")\nabline(v = 0, col = \"black\")\n```\n\n::: {.cell-output-display}\n![The same one million people after z-scoring. Identical shape, new axis labels. Standardizing moves the ruler, not the data.](Chapter_Distro_Moments_files/figure-pdf/z-score-histogram-1.pdf){fig-align='center' fig-alt='Histogram of the same one million scores converted to z-scores. The bell shape is unchanged from the previous figure, but the horizontal axis now runs from about negative four to positive four and is centered on zero.'}\n:::\n:::\n\n\n\n### Finding Probability from Z-scores\n\nTwo functions to know:\n\n- `dnorm()` $\\rightarrow$ height of the curve (density) at a value\n- `pnorm()` $\\rightarrow$ area under the curve to the left of a value (probability)\n\nThe PDF `dnorm()` implements:\n\n$$f(x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-\\frac{(x - \\mu)^2}{2 \\sigma^2}}$$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The same histogram with the density curve laid over it. `dnorm()` draws that curve; `pnorm()` measures the area underneath it.](Chapter_Distro_Moments_files/figure-pdf/z-score-density-1.pdf){fig-align='center' fig-alt='Histogram of z-scores plotted on a density scale, with a smooth bell-shaped curve drawn over it and a vertical line at zero. The curve follows the tops of the bars closely.'}\n:::\n:::\n\n\n\n### How much of the population is below the mean?\n\nExactly 50%---the normal distribution is symmetric. Confirm it:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5\n```\n:::\n:::\n\n\n\nWhat proportion falls between 1 and 2 SDs above the mean?\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(2) - pnorm(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1359051\n```\n:::\n:::\n\n\n\nNo calculus. Just area under the curve.\n\n### Going the Other Way\n\n`pnorm()` takes a score and hands back a proportion. Half the questions you will actually be asked run the other direction: *what score do you need to be in the top 10%?* That is `qnorm()`.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqnorm(.90)   # the z-score that cuts off the top 10%\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.281552\n```\n:::\n:::\n\n\n\nA z of 1.28. Convert back to raw cognitive-score units with $M + zS$:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n100 + qnorm(.90) * 15\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 119.2233\n```\n:::\n:::\n\n\n\nSo you need about 119 points to crack the top 10%. Cutoffs for gifted programs, clinical screening thresholds, and \"we only interview the top 5% of applicants\" are all this calculation wearing different toupees. \n\nYou can also ask the data directly instead of the theoretical curve. `quantile()` finds the actual score at a given percentile in your sample:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nquantile(Normal.Sample.1, .90)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     90% \n119.2508 \n```\n:::\n:::\n\n\n\nNearly identical, because we built this population to be normal. On real data the two can disagree, and when they do, the data is right and the curve was an assumption.\n\n## Real-World Example: Mental Rotation Test\n\nWe now know how to:\n\n- Describe distributions\n- Standardize scores with z-scores\n- Convert z-scores to probabilities\n\nLet's apply all of it to a real psychological measure.\n\nThe **Mental Rotations Test (MRT)** measures spatial visualization ability. Peters et al. developed a redrawn version and examined factors affecting performance [@peters1995]. Here's a summary by field and gender:\n\n|     | Sciences |     |      |     | Social Sciences & Humanities |      |      |\n|-----|----------|-----|------|-----|------------------------------|------|------|\n|     | n        | M   | SD   |     | n                            | M    | SD   |\n| M   | 817      | 15.23 | 4.42 |   | 517                        | 12.74 | 4.87 |\n| F   | 392      | 11.18 | 4.37 |   | 1358                       | 8.75  | 4.18 |\n\n::: {.callout-warning title=\"Advanced Code Has Arrived Early\"}\nThe code below is more advanced; you do not need to understand it yet. Why am I showing you crazy code now? To make you feel bad about yourself and the terrible life choices you made when you took a statistics class!\n\nActually, I want you to see what R can do. I can go from a table to simulation, graphs, and analysis without a lot of code. Simulating data is my favorite way to make graduate students cry when they propose dissertations because it is the fastest way to discover whether the theory and hypotheses they proposed make any sense. When they do not, the students cry and Dorkaos, our God of Statistics, gains more strength.\n:::\n\n### Step 1: Simulate the population distributions\n\nWe only have summary stats, but because MRT scores are approximately normal we can **simulate each group** using `rnorm()`.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nset.seed(123)\n\nparams <- tribble(\n  ~Field,            ~Group, ~n,    ~mean,  ~sd,\n  \"Sciences\",        \"M\",    817,   15.23,  4.42,\n  \"Sciences\",        \"F\",    392,   11.18,  4.37,\n  \"Social Sciences\", \"M\",    517,   12.74,  4.87,\n  \"Social Sciences\", \"F\",    1358,   8.75,  4.18\n)\n\nMRT.2 <- params %>%\n  mutate(data = pmap(list(n, mean, sd), rnorm)) %>%\n  unnest(data) %>%\n  select(Field, Group, Value = data)\n```\n:::\n\n\n\nCheck that our simulation matches published values:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nMRT.table <-\n  MRT.2 %>%\n  group_by(Field, Group) %>%\n  summarise(N = n(), M = mean(Value), S = sd(Value))\nMRT.table\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 x 5\n# Groups:   Field [2]\n  Field           Group     N     M     S\n  <chr>           <chr> <int> <dbl> <dbl>\n1 Sciences        F       392 11.4   4.47\n2 Sciences        M       817 15.3   4.34\n3 Social Sciences F      1358  8.74  4.16\n4 Social Sciences M       517 12.9   4.88\n```\n:::\n:::\n\n\n\n### Step 2: Visualize the distributions\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(MRT.2, aes(x = Value, fill = Group, color = Group)) +\n  geom_histogram(aes(y = after_stat(density)), position = \"identity\", alpha = 0.3, bins = 30) +\n  geom_density(alpha = 0.1) +\n  facet_wrap(~ Field) +\n  labs(title = \"Overlaid Histograms & Density Plots\", x = \"Score\", y = \"Density\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Raw MRT scores by field and group. The two groups sit in different places on the score axis, and the gap is bigger in the sciences.](Chapter_Distro_Moments_files/figure-pdf/mrt-raw-scores-1.pdf){fig-align='center' fig-alt='Two side-by-side panels, one for Sciences and one for Social Sciences. Each shows overlapping histograms and density curves for two groups on raw mental rotation scores. In both panels the male distribution sits to the right of the female distribution, with substantial overlap between them.'}\n:::\n:::\n\n\n\n### Step 3: Convert to z-scores (within groups)\n\nStandardize within each group---critical because each group has a different mean and SD.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nMRT.2 <- MRT.2 %>%\n  group_by(Field, Group) %>%\n  mutate(Z = scale(Value))\nMRT.2 %>% head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 x 4\n# Groups:   Field, Group [1]\n  Field    Group Value   Z[,1]\n  <chr>    <chr> <dbl>   <dbl>\n1 Sciences M      12.8 -0.583 \n2 Sciences M      14.2 -0.247 \n3 Sciences M      22.1  1.58  \n4 Sciences M      15.5  0.0594\n5 Sciences M      15.8  0.119 \n6 Sciences M      22.8  1.73  \n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(MRT.2, aes(x = Z, fill = Group, color = Group)) +\n  geom_histogram(aes(y = after_stat(density)), position = \"identity\", alpha = 0.3, bins = 30) +\n  geom_density(alpha = 0.1) +\n  facet_wrap(~ Field) +\n  labs(title = \"Overlaid Histograms & Density Plots\", x = \"Z-Score\", y = \"Density\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![The same scores after z-scoring *within* each group. The distributions now sit on top of each other, because every group is now measured against its own mean.](Chapter_Distro_Moments_files/figure-pdf/mrt-z-scores-1.pdf){fig-align='center' fig-alt='The same two panels as the previous figure, but on a z-score axis. All four distributions now center on zero and overlap almost completely, because each group has been standardized against its own mean and standard deviation.'}\n:::\n:::\n\n\n\nWhy do the curves overlap now? Because standardizing compares *relative position within each group*, not raw scores.\n\n### Step 4: Z-score to probability\n\nAlex (male, social sciences) got a score of 10. How did he do relative to his peers? (Males, Social Sciences: $M$ = 12.74, $S$ = 4.87)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nZ.Alex <- (10 - 12.74) / 4.87\nZ.Alex\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.5626283\n```\n:::\n:::\n\n\n\nA little over half an SD below the mean. Visually:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nMRT.2.Males.Social.Sciences <- MRT.2 %>% filter(Group == \"M\" & Field == \"Social Sciences\")\n\nggplot(MRT.2.Males.Social.Sciences, aes(x = Z)) +\n  geom_histogram(aes(y = after_stat(density)), position = \"identity\", alpha = 0.3, bins = 30) +\n  geom_density(alpha = 0.1) +\n  labs(title = \"Males in the Social Sciences\", x = \"Z-Score\", y = \"Density\") +\n  theme_bw() +\n  geom_vline(xintercept = Z.Alex, color = 'red')\n```\n\n::: {.cell-output-display}\n![Alex's place among male social scientists. The red line is him. Most of the distribution is to the right of it.](Chapter_Distro_Moments_files/figure-pdf/alex-position-1.pdf){fig-align='center' fig-alt='Histogram and density curve of z-scores for males in the social sciences, centered on zero. A vertical red line sits a little over half a standard deviation below zero, marking Alex\\'s score.'}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(Z.Alex)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.286844\n```\n:::\n:::\n\n\n\nOnly better than 28.7% of peers. That's also called a **percentile**.\n\n### Step 5: Same raw score, different meaning\n\nEmma also scored a 10, but she's in a different group (Female, Social Sciences: $M$ = 8.75, $S$ = 4.18).\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nZ.Emma <- (10 - 8.75) / 4.18\nZ.Emma\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2990431\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npnorm(Z.Emma)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6175464\n```\n:::\n:::\n\n\n\nEmma scored better than 61.8% of her peers.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncurve(pnorm, from = -10, to = 10,\n  main = \"Cumulative Density Function\",\n  xlab = \"z-score\", ylab = \"Probability\",\n  xlim = c(-3.25, 3.25))\nabline(v = Z.Emma, col = \"red\")\nabline(v = Z.Alex, col = \"blue\")\n```\n\n::: {.cell-output-display}\n![The same raw score of 10, read against two different reference groups. Emma (red) lands above the middle; Alex (blue) lands below it. The score never moved. The comparison group did.](Chapter_Distro_Moments_files/figure-pdf/cdf-alex-emma-1.pdf){fig-align='center' fig-alt='An S-shaped cumulative probability curve rising from zero to one across z-scores of about negative three to positive three. A blue vertical line sits left of center at Alex\\'s z-score, crossing the curve at roughly 0.29. A red vertical line sits right of center at Emma\\'s z-score, crossing at roughly 0.62.'}\n:::\n:::\n\n\n\nSame raw score. Emma is above average for her group; Alex is below average for his. Raw scores mean nothing without context.\n\n### Big idea\n\n- Raw scores mean nothing without context.\n- Distributions give scores meaning.\n\n## The Short Story\n\n- A distribution shows which values occur and how often.\n- The mean locates the center; variance and standard deviation describe spread.\n- Skewness describes asymmetry; kurtosis describes tail weight and peak shape relative to a reference distribution.\n- Zero skewness and zero excess kurtosis do not prove normality. Strange distributions are capable of wearing fake mustaches.\n- z-scores translate raw scores into standard-deviation units.\n- The same raw score can mean very different things in different reference groups.\n- Always inspect the distribution before asking one summary number to represent several hundred people without supervision.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}