{
  "hash": "24c54aef05f24f8425a4d0e850bf629c",
  "result": {
    "markdown": "---\ntitle: \"Mixed Regression: Between People and Within People\"\n---\n\n\n\n\n## Your Paired *t*-Test Was a Mixed Model All Along\n\nThe [paired-samples *t*-test chapter](Ch_09_Paired_t.qmd) gave 48 students one lecture with chocolate and one without, then measured how long their eyes stayed on the screen. Here is that study again, same seed and same 48 students, so this chapter runs from the top without sending you back a chapter to fetch the data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nn <- 48\n\n# Each student has a personal tendency to stare that follows them into BOTH\n# conditions. That shared tendency is the entire reason pairing works.\nparticipant_effect <- rnorm(n, mean = 0, sd = 1.20)\n\npaired_wide <- data.frame(\n  participant  = factor(seq_len(n)),\n  no_chocolate = 5.00 + participant_effect + rnorm(n, 0, 0.80),\n  chocolate    = 5.75 + participant_effect + rnorm(n, 0, 0.80)\n)\n\npaired_wide$difference <-\n  paired_wide$chocolate - paired_wide$no_chocolate\n\n# 48 rows become 96: one row per measurement instead of one row per person.\npaired_long <- tidyr::pivot_longer(\n  paired_wide,\n  cols      = c(no_chocolate, chocolate),\n  names_to  = \"condition\",\n  values_to = \"fixation\"\n)\n\npaired_long$condition <- factor(\n  paired_long$condition,\n  levels = c(\"no_chocolate\", \"chocolate\"),\n  labels = c(\"No chocolate\", \"Chocolate\")\n)\n```\n:::\n\n\nThere are two ways to analyze this. The first is the one you already know. Collapse each student down to a single difference score and ask whether those differences average to zero:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npaired_result <- t.test(\n  paired_wide$chocolate,\n  paired_wide$no_chocolate,\n  paired = TRUE\n)\n\npaired_result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  paired_wide$chocolate and paired_wide$no_chocolate\nt = 4.3366, df = 47, p-value = 7.597e-05\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.4209697 1.1495099\nsample estimates:\nmean difference \n      0.7852398 \n```\n:::\n:::\n\n\nThe second way never computes a difference at all. It hands R all 96 measurements in long format, plus one piece of information the *t*-test was only ever told indirectly, through the row order: which measurements came from the same human.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lme4)      # fits the mixed model\nlibrary(lmerTest)  # adds degrees of freedom and p-values to the fixed effects\n\nchocolate_model <- lmer(\n  fixation ~ condition + (1 | participant),\n  data = paired_long\n)\n\nsummary(chocolate_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: fixation ~ condition + (1 | participant)\n   Data: paired_long\n\nREML criterion at convergence: 297.6\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.87123 -0.50482 -0.02554  0.43379  2.44023 \n\nRandom effects:\n Groups      Name        Variance Std.Dev.\n participant (Intercept) 0.6453   0.8033  \n Residual                0.7869   0.8871  \nNumber of obs: 96, groups:  participant, 48\n\nFixed effects:\n                   Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)          4.7660     0.1727 78.1367  27.591  < 2e-16 ***\nconditionChocolate   0.7852     0.1811 47.0000   4.337  7.6e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\ncondtnChclt -0.524\n```\n:::\n:::\n\n\nFind the `conditionChocolate` row in that output. Then look back at the *t*-test.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchoc_fixed <- summary(chocolate_model)$coefficients\n\ncomparison <- data.frame(\n  method   = c(\"paired t-test\", \"lmer\"),\n  t        = c(unname(paired_result$statistic),\n               choc_fixed[\"conditionChocolate\", \"t value\"]),\n  df       = c(unname(paired_result$parameter),\n               choc_fixed[\"conditionChocolate\", \"df\"]),\n  p        = c(paired_result$p.value,\n               choc_fixed[\"conditionChocolate\", \"Pr(>|t|)\"]),\n  estimate = c(unname(paired_result$estimate),\n               choc_fixed[\"conditionChocolate\", \"Estimate\"])\n)\n\nprint(comparison, digits = 6, row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        method       t df           p estimate\n paired t-test 4.33661 47 7.59724e-05  0.78524\n          lmer 4.33661 47 7.59724e-05  0.78524\n```\n:::\n:::\n\n\nThose are not two answers that happen to agree. They are one answer, printed twice.\n\nThe degrees of freedom are worth a second look, because the two rows got to 47 by completely different routes. The *t*-test knows it has 48 differences and subtracts one. `lmer` has no idea what a difference score is; `lmerTest` works out how much independent information the 96 rows actually contain, using an approximation called **Satterthwaite's method**, and arrives at 47 anyway.\n\n### What `(1 | participant)` Actually Did\n\nThat term is the whole difference between the two calls. It tells R that rows sharing a participant number came from the same person, and that people arrive at a study with their own resting level of staring. Some students watch the screen. Some students watch the door.\n\nIt handles this without estimating 48 separate student coefficients. It estimates the *spread* of the students, a single number, and treats each person's own level as a draw from it:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprint(VarCorr(chocolate_model), comp = c(\"Variance\", \"Std.Dev.\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Groups      Name        Variance Std.Dev.\n participant (Intercept) 0.64532  0.80332 \n Residual                0.78689  0.88707 \n```\n:::\n:::\n\n\nThe `participant` line is how much students differ from each other. The `Residual` line is how much one student bounces around their own level from one measurement to the next. Those are the two piles the 96 numbers get sorted into, and we can ask what fraction of the variance sits in the first pile:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchoc_var <- as.data.frame(VarCorr(chocolate_model))\nicc <- choc_var$vcov[1] / sum(choc_var$vcov)\n\nicc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4505776\n```\n:::\n:::\n\n\nSo roughly 45 percent of the variation in fixation time is students being different students, before chocolate enters the discussion. The paired *t*-test dealt with that variation by subtracting it away and never mentioning it again. The mixed model estimates it and prints it.\n\nThat proportion is also the model's answer to a question the paired *t*-test chapter asked directly: how much do a person's two measurements agree? That chapter measured the agreement head-on, as a plain correlation of 0.46, and called it the $r$ in the $-2rS_1S_2$ term that everything depended on. The two numbers are close without being identical, because they are two different estimates of the same thing: one computed directly from the pairs, one implied by the variances the model fit. The point is that the quantity has stopped being a term in a formula and become a parameter with a variance attached.\n\n\"Each person is their own control\" is a sentence from a methods lecture. `(1 | participant)` is that sentence written as an equation.\n\n### The Fixed Effect Is the Chocolate Effect\n\nThe **fixed effects** are the part of the model that answers the research question, and there are only two:\n\n- `(Intercept)`, 4.77 seconds, is average fixation time with no chocolate.\n- `conditionChocolate`, 0.79 seconds, is what chocolate adds on top of that.\n\nThe second one is not merely close to the *t*-test's mean difference. It is the mean difference, 0.79 seconds, reached from the opposite direction: the *t*-test computed 48 differences and averaged them, while the model never computed a single difference and got there anyway.\n\nFixed effects answer the research question. Random effects are how the model earns the right to answer it using 96 rows that came from 48 people.\n\n### So What Was the Point of All That?\n\nNothing yet, honestly. With two measurements and no other predictors, the paired *t*-test is shorter to type and gives the same answer, so keep using it. The mixed model has not earned anything.\n\nIt earns its keep the moment the design acquires something a difference score cannot hold:\n\n- **A between-person predictor.** Treatment group, age, baseline severity. Subtracting within a person throws the person away, and group is a property of the person.\n- **A missing row.** A student who skipped a session has no difference score at all, so the *t*-test deletes the entire student.\n- **Three or more occasions.** There stops being such a thing as *the* difference.\n- **People who change at different *rates*,** not merely by different amounts. A difference score has nowhere to put a slope.\n\nThe rest of this chapter does the first two. The last two need a bigger model than this chapter builds, and they get their own chapter later in the book.\n\n::: {.callout-note title=\"Where This Chapter Goes, and Where It Stops\"}\nTwo stops, and you just finished the first. Next is the **mixed 2-by-2**: one within-subjects factor, one between-subjects factor, four cells, one interaction. That is the design most repeated-measures studies in psychology actually run, and it is where this chapter stops.\n\nA mixed design combines a **between-subjects** variable with a **within-subjects** variable, which summons fixed effects, an interaction, repeated observations, and random effects all at once. It is not impossible. It is merely statistics arriving with all its relatives and expecting you to provide chairs.\n:::\n\n## The Mixed 2-by-2: Baseline versus Week 6, by Group\n\nSuppose researchers compare cognitive behavioral therapy (**CBT**) with a control condition for reducing depression symptoms. Participants are randomly assigned to CBT or control and complete a depression inventory twice: at baseline and again after six weeks.\n\n- **Occasion** is within subjects: every person appears at baseline and at Week 6.\n- **Group** is between subjects: each person is in CBT *or* control, never both.\n- **Depression score** is the quantitative outcome.\n\nYou have seen this shape before. The [categorical-by-categorical interaction chapter](Ch_17_Categorical_Interaction.qmd) had two categorical predictors and four cells. So does this:\n\n|  | **Control** | **CBT** |\n|---|---|---|\n| **Baseline** | $\\mu_{11}$: Control at baseline | $\\mu_{12}$: CBT at baseline |\n| **Week 6** | $\\mu_{21}$: Control at Week 6 | $\\mu_{22}$: CBT at Week 6 |\n\nThe research question is not whether the groups differ, and not whether scores change. It is whether they change **differently**:\n\n$$B_3 = (\\mu_{22}-\\mu_{12})-(\\mu_{21}-\\mu_{11})$$\n\nFind the change in CBT. Find the change in Control. Compare the two changes. That is the same **difference of differences** the earlier chapter spent itself on, and it has not changed jobs here.\n\n### What Stays the Same, and the One Thing That Changes\n\n| Feature | The earlier categorical 2-by-2 | This mixed 2-by-2 |\n|---|---|---|\n| Categorical predictors | Two | Two |\n| Cells | Four | Four |\n| The interaction | Difference of differences | Difference of differences |\n| Who fills the cells | Different people in every cell | The same person fills two of them |\n| The model | `lm(Y ~ A * B)` | the same, plus a participant random intercept |\n\nThe fixed part of the formula does not change at all. We add the random intercept because the two rows from one person are related, and pretending they came from strangers would count one human twice and let the model become confident in ways it has not earned.\n\n### The Data\n\nThis is simulated data. Real treatment studies require clinical expertise, ethical oversight, careful monitoring, informed consent, and substantially more planning than \"Alex found `rnorm()`.\"\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(3436)\n\nn_per_group <- 50\n\npeople <- data.frame(\n  participant = factor(seq_len(2 * n_per_group)),\n  group = factor(\n    rep(c(\"Control\", \"CBT\"), each = n_per_group),\n    levels = c(\"Control\", \"CBT\")\n  ),\n  # each person's own baseline level, and their own rate of change\n  person_intercept = rnorm(2 * n_per_group, 0, 5.0),\n  person_slope     = rnorm(2 * n_per_group, 0, 0.45)\n)\n\n# every person gets a baseline row and a Week 6 row\nmixed_data <- merge(people, data.frame(week = c(0, 6)), by = NULL)\nmixed_data <- mixed_data[order(mixed_data$participant,\n                               mixed_data$week), ]\n\nmixed_data$depression <-\n  35 +\n  mixed_data$person_intercept +\n  (-0.20 * mixed_data$week) +                     # control drifts down slowly\n  ifelse(mixed_data$group == \"CBT\",\n         -1.20 * mixed_data$week, 0) +            # CBT drops faster: the effect\n  mixed_data$person_slope * mixed_data$week +\n  rnorm(nrow(mixed_data), 0, 2.0)\n\n# the same variable twice: week as a number, occasion as a readable label\nmixed_data$occasion <- factor(\n  mixed_data$week,\n  levels = c(0, 6),\n  labels = c(\"Baseline\", \"Week 6\")\n)\n```\n:::\n\n\nThe data are **long**: one row per person per occasion, 200 rows from 100 people. The participant identifier repeats because the person repeats. If your participant column disappears, stop. Do not proceed directly to the ritual sacrifice.\n\nNotice that the simulation gave every person their own `person_slope`, so the invented humans genuinely do improve at different rates, not merely by different amounts. Measured twice, nobody can tell the difference. The last section of this chapter is about designs where you would want to.\n\n### Look at the Four Cells First\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naggregate(\n  depression ~ occasion + group,\n  data = mixed_data,\n  FUN = function(x) c(M = mean(x), SD = sd(x))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  occasion   group depression.M depression.SD\n1 Baseline Control    35.793859      5.832925\n2   Week 6 Control    33.862191      6.672687\n3 Baseline     CBT    34.224262      5.804333\n4   Week 6     CBT    26.540161      6.450846\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\ngroup_means <- aggregate(\n  depression ~ occasion + group,\n  data = mixed_data,\n  FUN = mean\n)\n\nggplot(\n  mixed_data,\n  aes(x = occasion, y = depression, group = participant, color = group)\n) +\n  geom_line(alpha = 0.15) +\n  geom_line(\n    data = group_means,\n    aes(group = group), linewidth = 1.4\n  ) +\n  geom_point(\n    data = group_means,\n    aes(group = group), size = 2.8\n  ) +\n  labs(\n    x = NULL,\n    y = \"Depression score\",\n    color = \"Group\",\n    title = \"Group averages sitting on top of actual humans\"\n  ) +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![The four cells before any model. Each faint line is one participant's baseline and Week 6 score. The heavy lines connect the group means. Non-parallel lines are the visual signature of an interaction, and here that means unequal change.](Ch_18_Mixed_Regression_files/figure-html/mixed-design-plot-1.png){fig-align='center' fig-pos='H' fig-alt='A line plot with Occasion on the x axis, Baseline and Week 6, and depression score on the y axis running from about 10 to about 53. One hundred faint lines each connect one participant\\'s two scores, colored salmon for Control and teal for CBT, and they slope in both directions. Two heavy lines with round markers connect the group means. Both groups start near 35. The Control mean falls slightly to about 34, while the CBT mean falls steeply to about 27, so the two heavy lines are clearly not parallel.' width=528}\n:::\n:::\n\n\nThe two groups start at nearly the same place, which is what randomization is supposed to buy. By Week 6 the CBT mean has dropped much further. But people do not all begin at the same score or change by the same amount. Some improve a lot, some barely, and some appear to have received therapy from a motivational poster in a dentist's office.\n\nNever decide whether an effect is statistically significant by staring at whether confidence intervals overlap. CI overlap is not the direct test of a difference, and interaction tests are about **differences between differences**. Fit the model that asks the question.\n\n## Why Ordinary Regression Is Not Enough\n\nWe could hand those four cells to `lm()` and it would answer without complaint:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nordinary_model <- lm(depression ~ occasion * group, data = mixed_data)\n```\n:::\n\n\nThat model treats all 200 rows as independent. They are not. Two rows belong to each participant, and two scores from the same person know each other, which is the identity theft the paired *t*-test chapter warned about.\n\nThis structure is called **nesting**:\n\n$$\n\\text{occasions nested within participants}\n$$\n\nThe levels are:\n\n- Level 1: repeated occasions ($j$);\n- Level 2: participants ($i$).\n\nGroup belongs to Level 2 because it does not change within a person. Occasion belongs to Level 1 because it does.\n\nWe will come back to `ordinary_model` once the mixed model is fit, because the comparison is more interesting than the warning.\n\n## The Fixed Effects\n\nThe fixed part is ordinary regression on the four cells:\n\n$$\nY_{ij}=b_0+b_1(\\text{Week 6}_{ij})+b_2(\\text{CBT}_i)\n+b_3(\\text{Week 6}_{ij}\\times\\text{CBT}_i)+\\text{random part}+e_{ij}\n$$\n\nBecause Baseline and Control are the reference levels, each coefficient is one step around the 2-by-2:\n\n| Coefficient | What it estimates |\n|---|---|\n| $b_0$ | Mean depression for Control at baseline |\n| $b_1$ | Week 6 minus baseline, within Control |\n| $b_2$ | CBT minus Control, at baseline |\n| $b_3$ | How much *more* CBT changed than Control |\n\nThe CBT change is $b_1+b_3$. The interaction $b_3$ is the treatment question, and if it is negative then CBT scores fell further than Control scores.\n\nNotice why coding matters. A \"main effect of Group\" is not a universal average group difference here. It is the group difference *at baseline*, before anybody has been treated, which in a randomized trial we hope is nothing at all. Choosing baseline as the reference is what makes that coefficient answer a question worth asking instead of describing the difference during Week Zero Hundred and Twelve, a period known only to the Probability Gods.\n\n## The Random Intercept\n\nThe repeated observations require us to say how people differ. Each participant gets their own starting level:\n\n$$\nY_{ij}=b_0+b_1\\text{Week 6}_{ij}+b_2\\text{CBT}_i\n+b_3(\\text{Week 6}_{ij}\\times\\text{CBT}_i)+u_{0i}+e_{ij}\n$$\n\nThat $u_{0i}$ is the same `(1 | participant)` that reproduced the paired *t*-test at the top of the chapter, doing the same job on a larger design: give participants different intercepts, by estimating the variance of those intercepts rather than 100 unrelated participant coefficients.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmixed_model <- lmer(\n  depression ~ occasion * group + (1 | participant),\n  data = mixed_data,\n  REML=TRUE\n)\n\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: depression ~ occasion * group + (1 | participant)\n   Data: mixed_data\n\nREML criterion at convergence: 1164\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.74720 -0.54546 -0.03384  0.48026  1.76200 \n\nRandom effects:\n Groups      Name        Variance Std.Dev.\n participant (Intercept) 32.536   5.704   \n Residual                 5.927   2.434   \nNumber of obs: 200, groups:  participant, 100\n\nFixed effects:\n                        Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)              35.7939     0.8771 114.2475  40.811  < 2e-16 ***\noccasionWeek 6           -1.9317     0.4869  98.0000  -3.967 0.000138 ***\ngroupCBT                 -1.5696     1.2404 114.2475  -1.265 0.208293    \noccasionWeek 6:groupCBT  -5.7524     0.6886  98.0000  -8.354 4.43e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) occsW6 grpCBT\noccasionWk6 -0.278              \ngroupCBT    -0.707  0.196       \noccsnW6:CBT  0.196 -0.707 -0.278\n```\n:::\n:::\n\n\n::: {.callout-note title=\"REML: The Deliberately Oversimplified Version\"}\nBy default, `lmer()` uses **REML** (*restricted maximum likelihood*) to estimate the model. I am going to hand-wave aggressively here because understanding exactly how REML works requires considerably more statistical machinery than we need.\n\nYou already know **OLS**, which chooses regression coefficients to make the residual errors as small as possible. Mixed-effects models have an additional problem: they also have to estimate **variances**, such as how much participant intercepts vary from person to person.\n\nREML is a method designed to get better estimates of those variance components. Very loosely, it tries to estimate the variance **after accounting for the fact that we already used the data to estimate the fixed effects**. That correction matters especially when samples are not enormous.\n\nFor now, the practical rule is simple:\n\n**When we care about estimating the random-effects structure, we generally use REML. When we later compare models that differ in their fixed effects, we will switch REML off.**\n\nThat is intentionally an oversimplification. Future Us will deal with the details when Future Us actually needs them.\n:::\n\n## Read the Model Without Panic\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixed_effects <- summary(mixed_model)$coefficients\nround(fixed_effects, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        Estimate Std. Error      df t value Pr(>|t|)\n(Intercept)               35.794      0.877 114.248  40.811    0.000\noccasionWeek 6            -1.932      0.487  98.000  -3.967    0.000\ngroupCBT                  -1.570      1.240 114.248  -1.265    0.208\noccasionWeek 6:groupCBT   -5.752      0.689  98.000  -8.354    0.000\n```\n:::\n:::\n\n\nRead the rows in order, and check each one against the table of four coefficients above:\n\n1. `(Intercept)`, 35.79, is the Control group's baseline mean.\n2. `occasionWeek 6`, -1.93, is how much Control changed over six weeks.\n3. `groupCBT`, -1.57, is the baseline difference between groups, and it is not significant, $p =$ 0.208. Randomization did its job.\n4. `occasionWeek 6:groupCBT`, -5.75, is the interaction.\n\nSo CBT scores fell about 5.75 points further than Control scores over the same six weeks. That is the treatment effect. It does not mean CBT lowered every participant's score by that amount. Fixed effects describe an average pattern while the random effects document the inconvenient existence of individuals.\n\nNotice that Control changed too, and significantly, $p$ < .001. People in the control condition got better over six weeks. If we had run a one-group study, measured twice, and found that, we would have congratulated ourselves and possibly written a press release. This is the entire reason the control group exists, and the reason the interaction, not the change, is the research question.\n\n::: {.callout-warning title=\"The p-Values Are Approximations, and This Is Not Your Engine's Fault\"}\nEvery column in that table except the estimate itself rests on an approximation. There is no exact sampling distribution waiting for a model like this one, so the numbers in the `df` column were not counted, they were **estimated**, using Satterthwaite's method, like you saw with Welch's *t*-test. They often come out fractional.\n\nThis is a property of mixed models, not of `lmer`. Change engines and the approximation changes costume rather than disappearing: `glmmTMB`, which you will meet in graduate school, fits the same model and reports Wald *z* statistics with no degrees of freedom at all. Same model, different plumbing, and the same honest uncertainty underneath.\n:::\n\n## How Much Did the Random Intercept Actually Buy You?\n\nThe paired *t*-test chapter ran its analysis wrong on purpose to show what pairing was worth. Do the same thing here. `ordinary_model` is still sitting there, fit by `lm()`, believing it met 200 unrelated people.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm_fixed <- summary(ordinary_model)$coefficients\n\ndata.frame(\n  term        = rownames(fixed_effects),\n  estimate_lm = round(lm_fixed[, \"Estimate\"], 3),\n  estimate_mixed = round(fixed_effects[, \"Estimate\"], 3),\n  SE_lm       = round(lm_fixed[, \"Std. Error\"], 3),\n  SE_mixed    = round(fixed_effects[, \"Std. Error\"], 3),\n  row.names   = NULL\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                     term estimate_lm estimate_mixed SE_lm SE_mixed\n1             (Intercept)      35.794         35.794 0.877    0.877\n2          occasionWeek 6      -1.932         -1.932 1.240    0.487\n3                groupCBT      -1.570         -1.570 1.240    1.240\n4 occasionWeek 6:groupCBT      -5.752         -5.752 1.754    0.689\n```\n:::\n:::\n\n\nThe estimates are **identical**, to every decimal place shown. Ignoring the pairing did not bias a single coefficient. That is worth saying plainly, because it is the part people get wrong: this is not a story about wrong answers.\n\nThe standard errors are a different matter. The interaction's standard error is 1.75 when we pretend the rows are strangers and 0.69 when we admit they are not, roughly 2.5 times larger. And look at what that does to the Control change, `occasionWeek 6`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(\n  p_lm    = round(lm_fixed[\"occasionWeek 6\", \"Pr(>|t|)\"], 3),\n  p_mixed = round(fixed_effects[\"occasionWeek 6\", \"Pr(>|t|)\"], 5)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   p_lm p_mixed \n0.12100 0.00014 \n```\n:::\n:::\n\n\nSame estimate. One analysis finds nothing, the other finds a clear effect. The difference is entirely whether the model was told that the two rows belong to one human.\n\nNow look at the row the random intercept did *not* help: `groupCBT`, where the standard error is the same in both models, out to nine decimal places. That is not a coincidence and it is worth understanding, because it tells you what the random intercept is actually for. `groupCBT` compares two different sets of people at one occasion. There is no repeated measurement inside that comparison, so there is nothing to subtract out, and it has to pay full price for person-to-person variation either way. The random intercept helps *within*-person comparisons. It has nothing to offer a between-person one.\n\nWhere did the extra error come from, then? From the people. 85 percent of the variance here is participants differing from one another, and `lm()` has no mechanism for setting that aside, so it lands in the error term and makes every within-person comparison look less trustworthy than it is. The random intercept is how you get it back.\n\n## The Interaction Is Also a *t*-Test on Change Scores\n\nWith exactly two occasions we can go back to difference scores after all. Subtract baseline from Week 6 for every person, then compare those change scores between the two groups with an ordinary independent-samples *t*-test, which is a test from Part 1 of this book.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchange_data <- tidyr::pivot_wider(\n  mixed_data[, c(\"participant\", \"group\", \"week\", \"depression\")],\n  names_from   = week,\n  values_from  = depression,\n  names_prefix = \"week\"\n)\n\nchange_data$change <- change_data$week6 - change_data$week0\n\n# ref = \"CBT\" so the contrast runs CBT minus Control, matching the model\nchange_result <- t.test(\n  change ~ relevel(group, ref = \"CBT\"),\n  data = change_data,\n  var.equal = TRUE\n)\n\nchange_result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  change by relevel(group, ref = \"CBT\")\nt = -8.3542, df = 98, p-value = 4.425e-13\nalternative hypothesis: true difference in means between group CBT and group Control is not equal to 0\n95 percent confidence interval:\n -7.118870 -4.385998\nsample estimates:\n    mean in group CBT mean in group Control \n            -7.684102             -1.931668 \n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nb3 <- fixed_effects[\"occasionWeek 6:groupCBT\", ]\n\nchange_comparison <- data.frame(\n  method = c(\"t-test on change scores\", \"mixed-model interaction\"),\n  t      = c(unname(change_result$statistic), b3[\"t value\"]),\n  df     = c(unname(change_result$parameter), b3[\"df\"]),\n  p      = c(change_result$p.value,           b3[\"Pr(>|t|)\"]),\n  estimate = c(\n    mean(change_data$change[change_data$group == \"CBT\"]) -\n      mean(change_data$change[change_data$group == \"Control\"]),\n    b3[\"Estimate\"]\n  )\n)\n\nprint(change_comparison, digits = 6, row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                  method        t df           p estimate\n t-test on change scores -8.35423 98 4.42529e-13 -5.75243\n mixed-model interaction -8.35423 98 4.42529e-13 -5.75243\n```\n:::\n:::\n\n\nOne answer, printed twice, for the second time in this chapter.\n\nSo this chapter has now caught the mixed model impersonating two different *t*-tests. A paired *t*-test is a mixed model with a random intercept. A mixed 2-by-2 interaction is an independent-samples *t*-test on change scores. Neither is a coincidence, and neither is a reason to abandon the *t*-tests: in a complete, balanced 2-by-2 like this one they are easier to run and they are right.\n\nThe mixed model is what keeps working when the design stops being complete and balanced, which is the next thing that happens to it.\n\n## Test the Interaction Directly\n\nCoefficient tests are not the only way to ask about the interaction. We can also compare two models: one that lets the groups change differently, and one that does not.\n\nWhen comparing **fixed effects**, refit both with maximum likelihood. This is the switch the REML callout promised, and this is where we throw it, in both models.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nreduced_ml <- lmer(\n  depression ~ occasion + group + (1 | participant),\n  data = mixed_data,\n  REML = FALSE\n)\n\nfull_ml <- lmer(\n  depression ~ occasion * group + (1 | participant),\n  data = mixed_data,\n  REML = FALSE\n)\n\nanova(reduced_ml, full_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: mixed_data\nModels:\nreduced_ml: depression ~ occasion + group + (1 | participant)\nfull_ml: depression ~ occasion * group + (1 | participant)\n           npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nreduced_ml    5 1231.5 1248.0 -610.76    1221.5                         \nfull_ml       6 1179.8 1199.5 -583.87    1167.8 53.776  1  2.247e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThis likelihood-ratio test asks whether allowing the groups to change by different amounts improves model fit. It is not the only defensible test; coefficient tests and other approximations are also used. The important point is to match the test to the question and identify the method, not to collect *p*-values like cursed trading cards.\n\n::: {.callout-note title=\"`anova()` Would Have Caught Us, but Only `anova()`\"}\nHand two REML fits to `anova()` and it refits them with maximum likelihood itself, printing `refitting model(s) with ML (instead of REML)` on its way past. It makes the decision visible in your code instead of leaving it to a message you might scroll past. `anova()` is being the adult in the room. \n:::\n\nAfter model comparison, report estimates from the final model fit with REML when appropriate.\n\n## Follow Up the Interaction\n\nThe interaction says the two changes differ. It does not say what either change was. For that, estimate Week 6 minus baseline separately within each group:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(emmeans)\n\ncell_means <- emmeans(mixed_model, ~ occasion | group,\n                      lmer.df = \"satterthwaite\")\n\ncontrast(\n  cell_means,\n  method = list(\"Week 6 - Baseline\" = c(-1, 1)),\n  adjust = \"none\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngroup = Control:\n contrast          estimate    SE df t.ratio p.value\n Week 6 - Baseline    -1.93 0.487 98  -3.967  0.0001\n\ngroup = CBT:\n contrast          estimate    SE df t.ratio p.value\n Week 6 - Baseline    -7.68 0.487 98 -15.782 <0.0001\n\nDegrees-of-freedom method: satterthwaite \n```\n:::\n:::\n\n\nThese are **simple effects**: how each group changed on its own. Control improved a little, CBT improved a lot, and the interaction is the statement that those two amounts are not the same. Simple effects describe the pattern. They do not replace the interaction test, and reporting only the simple effects is how people accidentally claim an interaction they never tested.\n\nWe can also ask for the four cell means the model implies:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncell_means\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngroup = Control:\n occasion emmean    SE  df lower.CL upper.CL\n Baseline   35.8 0.877 114     34.1     37.5\n Week 6     33.9 0.877 114     32.1     35.6\n\ngroup = CBT:\n occasion emmean    SE  df lower.CL upper.CL\n Baseline   34.2 0.877 114     32.5     36.0\n Week 6     26.5 0.877 114     24.8     28.3\n\nDegrees-of-freedom method: satterthwaite \nConfidence level used: 0.95 \n```\n:::\n:::\n\n\nDo not automatically test every possible pair because the software makes it easy. That is how a sensible research question becomes 28 tests and a dead [salmon](Ch_20_Multiple_Comparisons.qmd) [@bennett2010]. Choose comparisons that answer the theory, and adjust for multiplicity when you conduct a family of tests.\n\n## Reporting the Result\n\nA compact results paragraph could read:\n\n> Depression scores were analyzed with a linear mixed-effects model containing fixed effects of Occasion, Group, and their interaction, plus a participant random intercept. The model was fit by restricted maximum likelihood using `lmer()` from the lme4 package, and *p*-values were obtained from lmerTest using Satterthwaite's approximation to the denominator degrees of freedom. The groups did not differ at baseline, $b =$ -1.57, $p =$ 0.208. The Occasion by Group interaction was negative, $b =$ -5.75, $SE =$ 0.69, $t(98) =$ -8.35, $p$ < .001, indicating that depression declined more from baseline to Week 6 in the CBT condition than in the control condition.\n\nA real report should also provide confidence intervals, the cell means, the exact random-effects structure, software, missing-data handling, and theoretically planned follow-ups. The paragraph above is the skeleton. Please give it organs before submitting it to Reviewer 2.\n\n## Advanced Topics \n\nWhat follows is the part that matters once the data are real rather than simulated: people miss appointments, models need checking, and designs eventually outgrow the one this chapter can handle. The Short Story at the end covers the whole chapter, both halves.\n\n## Missing Repeated Observations\n\nMixed models can use participants who are missing some occasions; they do not require deleting every person with one missing row. This is a major advantage over older complete-case repeated-measures procedures, and with two occasions it is the difference between losing a person and losing half of one.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(347)\n\nmixed_missing <- mixed_data\n# 10% of the Week 6 visits simply do not happen\ngone <- mixed_missing$week == 6 & runif(nrow(mixed_missing)) < 0.10\nmixed_missing$depression[gone] <- NA\n\nmissing_model <- lmer(\n  depression ~ occasion * group + (1 | participant),\n  data = mixed_missing\n)\n\nc(\n  rows_used = sum(!is.na(mixed_missing$depression)),\n  people_used = length(unique(\n    mixed_missing$participant[!is.na(mixed_missing$depression)]\n  ))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  rows_used people_used \n        189         100 \n```\n:::\n:::\n\n\nEvery one of the 100 people is still in the model, contributing whatever they turned up for. A change-score analysis would have deleted all 11 of the people who missed the second visit, because a difference needs both halves, and with it the perfectly good baseline score each of them did provide.\n\nHowever, \"the model ran\" does not mean missing data ceased to matter. Standard likelihood-based mixed-model inference commonly relies on a **missing at random** assumption conditional on variables in the model. If people with worsening symptoms leave the study for reasons the model does not capture, the missingness can bias results. Investigate dropout, include relevant predictors when justified, and conduct sensitivity analyses in serious work.\n\n## Check the Model\n\nEvery model in this book has arrived with a diagnostic ritual attached. This one does too, except the ritual is harder, and I am going to be honest with you about how much of it we are skipping.\n\nHere is the problem. A mixed model has more places for an assumption to hide than a regression does: the residuals, the random effects, and the relationship between them. Worse, the ordinary residuals a mixed model hands you are not the clean, independent, interchangeable things `lm()` produces, so the plots you learned to read in the diagnostics chapter do not mean quite the same thing here. The assumptions **rhyme** with the ones you already know. Checking them does not.\n\nSo we use a package that does the hard part for us. **DHARMa** takes your fitted model, simulates a few hundred fresh datasets from it, and then asks, for each of your real observations, where it falls inside its own simulated crowd. If the model is telling the truth, those positions should be spread evenly between 0 and 1. That is the trick: no matter how strange the raw residuals look, the *simulated* residuals should always be uniform when the model is right, so there is one picture to learn instead of one per situation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(DHARMa)\n\nsim_res <- simulateResiduals(mixed_model)\n\nplotQQunif(sim_res)\n```\n\n::: {.cell-output-display}\n![DHARMa's QQ plot. If the model is right, the points sit on the red diagonal. The three tests printed on the plot check the overall shape, the spread, and whether there are more extreme points than the model expects.](Ch_18_Mixed_Regression_files/figure-html/dharma-qq-1.png){fig-align='center' fig-pos='H' fig-alt='A QQ plot with Expected on the x axis and Observed on the y axis, both from 0 to 1. About two hundred small triangles form a line that follows a red diagonal reference line closely, bowing slightly above it in the lower half and slightly below it in the upper half. Three test results are printed on the plot: KS test p = 0.0541, Dispersion test p = 0.216, Outlier test p = 0.41647, each labeled Deviation n.s.' width=528}\n:::\n:::\n\n\nThe points follow the diagonal with a gentle bow, and the three tests printed on the plot are ones you can ignore for now.\n\nThe second plot asks a different question: are the residuals equally well behaved everywhere, or does the model fit one part of the design better than another?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplotResiduals(sim_res, form = mixed_data$occasion)\n```\n\n::: {.cell-output-display}\n![DHARMa residuals split by occasion. Both boxes should straddle 0.5 with similar spread, which they do. This is where unequal variance across conditions would show up.](Ch_18_Mixed_Regression_files/figure-html/dharma-occasion-1.png){fig-align='center' fig-pos='H' fig-alt='Two boxplots of DHARMa scaled residuals, one for Baseline and one for Week 6, on a y axis from 0 to 1. Both boxes are centered close to 0.5 and have very similar heights, with whiskers reaching nearly 0 and 1 in both. Dashed horizontal reference lines mark 0.25, 0.5 and 0.75. Printed above: Levene Test for homogeneity of variance n.s., Within-group deviation from uniformity n.s.' width=528}\n:::\n:::\n\n\nTwo boxes, both centered near 0.5, both about the same height, and both tests `n.s.` The model is not doing noticeably worse at Week 6 than at baseline. Swap `occasion` for `group` and you can ask the same question about CBT versus Control.\n\nThat is where we stop, and stopping here is a real choice rather than a complete answer.\n\n::: {.callout-warning title=\"This Is the Shallow End, and It Is a Very Deep Pool\"}\nMixed models are an enormous area of statistics, and their diagnostics are an active research area rather than a settled checklist. Two DHARMa plots are the minimum, not the standard.\n\nIf your design is bigger than the one in this chapter, you need more than this chapter. The honest advice is a graduate mixed-models course, and the advanced sections of this book, not a longer checklist from me.\n\nThis is also, genuinely, hard material. First-time graduate students meet it and struggle. If it feels like a lot, that is the material, not you.\n:::\n\n## When Your Design Outgrows This Chapter\n\nEverything here rested on the simplest possible repeated-measures design: each person measured twice, on one within-subjects factor, crossed with one between-subjects factor. For that design, what this chapter showed you works, and it works well.\n\nPush past it and the difficulty does not increase gently. Two within-subjects factors, or measurements at four or six occasions over time, and you are immediately making decisions this chapter never had to make. Which random effects should the model include? What happens when the maximal model refuses to converge, or converges to a variance of exactly zero? Should occasions close together be allowed to resemble each other more than occasions far apart? Those are real questions with contested answers, and getting them wrong changes your results rather than merely annoying you.\n\nHere is the part I am obliged to admit. For a **balanced, complete** repeated-measures design with several within-subjects factors, old-school repeated-measures ANOVA is often *easier* than the mixed model. It was built for exactly that shape of data, it will fit without an argument, and it will not ask you to choose a random-effects structure. You know how I feel about ANOVA. It is still true.\n\nThe catch is what it demands in return. Repeated-measures ANOVA wants every person to have every observation, so one missed session deletes the whole participant, and it leans on **sphericity**: the assumption that the variances of all the pairwise differences between occasions are equal. With exactly two occasions, as in this chapter, sphericity is not merely satisfied, it is vacuous, because there is only one difference and nothing for it to disagree with. From three occasions up it becomes a real constraint, and a violated one costs you.\n\nSo neither tool is the grown-up choice in all situations. The mixed model handles missing rows and unbalanced designs that ANOVA cannot touch. ANOVA handles complicated balanced within-subjects designs without the fight. We did not escape assumptions by learning mixed models. We traded a rigid set for a flexible set that has to be chosen thoughtfully.\n\nIf a repeated-measures ANOVA is the right tool for your design, there is a review of it in the advanced sections of this book. Use whichever tool the design actually calls for, and say in your write-up which one you used and why.\n\n## The Short Story\n\n- A paired *t*-test is a mixed model with one two-level within-subjects predictor and a random intercept. Same estimate, same *t*, same df, same *p*.\n- A mixed design contains at least one between-subjects predictor and one within-subjects predictor.\n- Repeated occasions are nested within people, so ordinary independent-error regression is incomplete.\n- Ignoring that nesting does not bias the coefficients. It ruins the standard errors, which is enough to change the answer.\n- A mixed 2-by-2 has four cells and a difference-of-differences interaction, exactly like the all-between 2-by-2. The one new thing is the participant random intercept.\n- With Baseline as the reference, the Group coefficient is the baseline group difference, which randomization should have made boring.\n- The Occasion by Group coefficient is the difference between the two groups' changes.\n- With exactly two occasions, that interaction is also an independent-samples *t*-test on change scores.\n- Random intercepts let people start at different levels, which is all a two-occasion design can support.\n- Compare fixed-effects structures using models fit with maximum likelihood, not REML.\n- Check a mixed model with **simulated** residuals, from DHARMa, rather than by reading raw residual plots the way you would for an ordinary regression. Two plots is the minimum, not the standard.\n- This chapter covers the simplest repeated-measures design there is. More within-subjects factors, or more occasions, gets hard quickly, and for balanced complete designs old-school repeated-measures ANOVA is often the easier tool.\n- Mixed models can retain partially observed participants, but missingness can still bias the answer.\n- Never count rows and forget to count people. Two hundred observations from 100 people are not 200 independent humans, no matter how urgently the grant deadline approaches.\n\nThe model is \"mixed\" because it combines **fixed** and **random** effects, not because we placed several statistical procedures into a blender and hoped the lid stayed on.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}