{
  "hash": "15570b382c90a82dea82afa289a81d66",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mixed Designs: Between People and Within People\"\ngeometry: margin=.5in\nfontsize: 11pt\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n---\n\n\n\n\\pagebreak\n\n::: {.callout-warning title=\"Advanced Chapter: Several Things Are Happening at Once\"}\nA mixed design combines a **between-subjects** variable with a **within-subjects** variable. That creates fixed effects, an interaction, repeated observations, and random effects. It is not impossible. It is merely statistics arriving with all its relatives and expecting you to provide chairs.\n\nOur strategy is to ask one question at a time: Where are the repeated observations? What does each fixed coefficient mean? How are people allowed to differ? What comparison answers the research question?\n:::\n\n## The Design\n\nSuppose researchers compare cognitive behavioral therapy (**CBT**) with a control condition for reducing depression symptoms. Participants are randomly assigned to CBT or control, then complete a depression inventory at baseline and after 2, 4, and 6 weeks.\n\n- **Group** is between subjects: each person is in CBT *or* control.\n- **Week** is within subjects: each person is measured four times.\n- **Depression score** is the quantitative outcome.\n\nThe central question is not merely whether the groups differ or whether scores change. It is whether they change **differently**:\n\n> Does the slope of depression over time depend on treatment group?\n\nThat is a Week × Group interaction.\n\nThis is simulated data. Real treatment studies require clinical expertise, ethical oversight, careful monitoring, informed consent, and substantially more planning than “Alex found `rnorm()`.”\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(3436)\n\nn_per_group <- 50\npeople <- data.frame(\n  participant = factor(seq_len(2 * n_per_group)),\n  group = factor(\n    rep(c(\"Control\", \"CBT\"), each = n_per_group),\n    levels = c(\"Control\", \"CBT\")\n  ),\n  person_intercept = rnorm(2 * n_per_group, 0, 5.0),\n  person_slope = rnorm(2 * n_per_group, 0, 0.45)\n)\n\nmixed_data <- merge(\n  people,\n  data.frame(week = c(0, 2, 4, 6)),\n  by = NULL\n)\n\nmixed_data <- mixed_data[order(mixed_data$participant,\n                               mixed_data$week), ]\n\nmixed_data$depression <-\n  35 +\n  mixed_data$person_intercept +\n  (-0.20 * mixed_data$week) +\n  ifelse(mixed_data$group == \"CBT\",\n         -1.20 * mixed_data$week, 0) +\n  mixed_data$person_slope * mixed_data$week +\n  rnorm(nrow(mixed_data), 0, 2.0)\n\nmixed_data$occasion <- factor(\n  mixed_data$week,\n  levels = c(0, 2, 4, 6),\n  labels = c(\"Baseline\", \"Week 2\", \"Week 4\", \"Week 6\")\n)\n```\n:::\n\n\nThe data are **long**: one row per person per occasion. The participant identifier repeats because the person repeats. If your participant column disappears, stop. Do not proceed directly to the ritual sacrifice.\n\n## First Look: Means and People\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n  mixed_data,\n  aes(x = week, y = depression, group = participant, color = group)\n) +\n  geom_line(alpha = 0.13) +\n  stat_summary(\n    aes(group = group), fun = mean, geom = \"line\",\n    linewidth = 1.4\n  ) +\n  stat_summary(\n    aes(group = group), fun = mean, geom = \"point\",\n    size = 2.8\n  ) +\n  scale_x_continuous(breaks = c(0, 2, 4, 6)) +\n  labs(\n    x = \"Week\",\n    y = \"Depression score\",\n    color = \"Group\",\n    title = \"Group averages sitting on top of actual humans\"\n  ) +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](Chapter_Mixed_Regression_files/figure-html/mixed-design-plot-1.png){fig-align='center' fig-pos='H' width=528}\n:::\n:::\n\n\nThe bold lines show group means. The faint lines show individual trajectories. The CBT mean declines faster, but people do not all begin at the same score or change at the same rate. Some improve quickly, some slowly, and some appear to have received therapy from a motivational poster in a dentist's office.\n\nNever decide whether an effect is statistically significant by staring at whether confidence intervals overlap. CI overlap is not the direct test of a difference, and interaction tests are about **differences between differences**. Fit the model that asks the question.\n\n## Why Ordinary Regression Is Not Enough\n\nAn ordinary regression such as this is incomplete:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nordinary_model <- lm(depression ~ week * group, data = mixed_data)\n```\n:::\n\n\nIt treats all 400 rows as independent. They are not. Four rows belong to each participant, and observations from the same person tend to resemble one another.\n\nThis structure is called **nesting**:\n\n$$\n\\text{occasions nested within participants}\n$$\n\nThe levels are:\n\n- Level 1: repeated occasions;\n- Level 2: participants.\n\nGroup belongs to Level 2 because it does not change within a person. Week belongs to Level 1 because it does.\n\n## The Fixed Effects\n\nWe begin with the part that resembles ordinary regression:\n\n$$\nY_{ij}=b_0+b_1(\\text{Week}_{ij})+b_2(\\text{CBT}_i)\n+b_3(\\text{Week}_{ij}\\times\\text{CBT}_i)+\\text{random part}+e_{ij}\n$$\n\nBecause Week 0 is baseline and Control is the reference group:\n\n- $b_0$: estimated baseline score for Control;\n- $b_1$: expected change per week for Control;\n- $b_2$: CBT-minus-Control difference at baseline;\n- $b_3$: difference between the CBT and Control slopes.\n\nThe CBT slope is $b_1+b_3$. The interaction $b_3$ is the main research target. If it is negative, CBT scores decline faster than Control scores.\n\nNotice why coding matters. A “main effect of Group” is not a universal average group difference here. It is the group difference when Week equals zero. We chose zero to mean baseline, so the coefficient has a useful interpretation instead of describing the difference during Week Zero Hundred and Twelve, a period known only to the Probability Gods.\n\n## The Random Effects\n\nThe repeated observations require us to describe how people differ.\n\n### Random Intercepts\n\nA random-intercept model allows each participant to have their own starting level:\n\n$$\nY_{ij}=b_0+b_1\\text{Week}_{ij}+b_2\\text{CBT}_i\n+b_3(\\text{Week}_{ij}\\times\\text{CBT}_i)+u_{0i}+e_{ij}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrandom_intercept_model <- glmmTMB::glmmTMB(\n  depression ~ week * group + (1 | participant),\n  data = mixed_data,\n  REML = TRUE\n)\n\nsummary(random_intercept_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian  ( identity )\nFormula:          depression ~ week * group + (1 | participant)\nData: mixed_data\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   2095.3    2119.3   -1041.7    2083.3       394 \n\nRandom effects:\n\nConditional model:\n Groups      Name        Variance Std.Dev.\n participant (Intercept) 30.95    5.564   \n Residual                 4.67    2.161   \nNumber of obs: 400, groups:  participant, 100\n\nDispersion estimate for gaussian family (sigma^2): 4.67 \n\nConditional model:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   35.66006    0.82731   43.10  < 2e-16 ***\nweek          -0.29454    0.06833   -4.31 1.63e-05 ***\ngroupCBT      -1.61122    1.16999   -1.38    0.168    \nweek:groupCBT -1.02796    0.09664  -10.64  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe expression `(1 | participant)` means “give participants different intercepts.” It does not estimate 100 unrelated participant coefficients. Instead, it estimates the variance of the participant intercepts.\n\n### Random Slopes\n\nPeople may also change at different rates. A random-slope model allows each person to have their own Week slope:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrandom_slope_model <- glmmTMB::glmmTMB(\n  depression ~ week * group + (1 + week | participant),\n  data = mixed_data,\n  REML = TRUE\n)\n\nsummary(random_slope_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian  ( identity )\nFormula:          depression ~ week * group + (1 + week | participant)\nData: mixed_data\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   2091.2    2123.1   -1037.6    2075.2       392 \n\nRandom effects:\n\nConditional model:\n Groups      Name        Variance Std.Dev. Corr \n participant (Intercept) 29.3952  5.4217        \n             week         0.1046  0.3233   0.07 \n Residual                 3.9820  1.9955        \nNumber of obs: 400, groups:  participant, 100\n\nDispersion estimate for gaussian family (sigma^2): 3.98 \n\nConditional model:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   35.66006    0.80228   44.45  < 2e-16 ***\nweek          -0.29454    0.07793   -3.78 0.000157 ***\ngroupCBT      -1.61122    1.13459   -1.42 0.155584    \nweek:groupCBT -1.02796    0.11021   -9.33  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe expression `(1 + week | participant)` estimates:\n\n- variance in participants' intercepts;\n- variance in participants' Week slopes;\n- correlation between participant intercepts and slopes.\n\nRandom slopes are often substantively reasonable in longitudinal psychology. People do not all change identically merely because the spreadsheet has aligned their rows. They are humans, not synchronized microwave clocks.\n\nThe random-effects structure should reflect the design and theory, while remaining supported by the data. If a model is singular or refuses to converge, do not repeatedly click Run while shouting encouragement. Inspect the data, scaling, model specification, number of clusters, and whether the random structure is estimable.\n\n## Read the Model Without Panic\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixed_effects <- summary(random_slope_model)$coefficients$cond\nround(fixed_effects, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Std. Error z value Pr(>|z|)\n(Intercept)     35.660      0.802  44.448    0.000\nweek            -0.295      0.078  -3.780    0.000\ngroupCBT        -1.611      1.135  -1.420    0.156\nweek:groupCBT   -1.028      0.110  -9.327    0.000\nattr(,\"ddf\")\n[1] \"asymptotic\"\n```\n\n\n:::\n:::\n\n\nRead the rows in order:\n\n1. `(Intercept)` estimates the Control group's baseline mean.\n2. `week` estimates weekly change in Control.\n3. `groupCBT` estimates the CBT-minus-Control baseline difference.\n4. `week:groupCBT` estimates how much the CBT slope differs from the Control slope.\n\nSuppose the interaction estimate is about $-1.2$. That means the CBT group's depression score declines roughly 1.2 points **more per week** than the Control group's score, on average. It does not mean CBT lowers every participant's score by exactly 1.2 points each week. Fixed effects describe an average pattern while the random effects document the inconvenient existence of individuals.\n\n`glmmTMB` reports Wald z statistics and p-values for the fixed effects. These rely on the fitted likelihood and a large-sample approximation; they do not create an infinite number of participants merely because the output prints a z. Report the method and inspect confidence intervals. If a field specifically requires ANOVA-style denominator degrees of freedom for a **Gaussian** mixed model, the later inference chapter shows the deliberate `lmerTest` detour. “R produced a number and I felt hopeful” is not an inferential method.\n\n## Test the Interaction Directly\n\nTo test whether the interaction improves the model, compare two models with the same random-effects structure:\n\n- a reduced model without Week × Group;\n- a full model with Week × Group.\n\nWhen comparing **fixed effects**, refit both models with maximum likelihood (`REML = FALSE`).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nreduced_ml <- glmmTMB::glmmTMB(\n  depression ~ week + group + (1 + week | participant),\n  data = mixed_data,\n  REML = FALSE\n)\n\nfull_ml <- glmmTMB::glmmTMB(\n  depression ~ week * group + (1 + week | participant),\n  data = mixed_data,\n  REML = FALSE\n)\n\nanova(reduced_ml, full_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: mixed_data\nModels:\nreduced_ml: depression ~ week + group + (1 + week | participant), zi=~0, disp=~1\nfull_ml: depression ~ week * group + (1 + week | participant), zi=~0, disp=~1\n           Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)    \nreduced_ml  7 2148.9 2176.9 -1067.5   2134.9                             \nfull_ml     8 2087.4 2119.3 -1035.7   2071.4 63.539      1  1.572e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThis likelihood-ratio test asks whether allowing the groups to have different slopes improves model fit. It is not the only defensible test; coefficient tests and other approximations are also used. The important point is to match the test to the question and identify the method, not to collect p values like cursed trading cards.\n\nAfter model comparison, report estimates from the final model fit with REML when appropriate.\n\n## Follow Up the Interaction\n\nThe interaction says the slopes differ. We still want the slope within each group.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngroup_slopes <- emmeans::emtrends(\n  random_slope_model,\n  specs = ~ group,\n  var = \"week\"\n)\n\ngroup_slopes\npairs(group_slopes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n group   week.trend     SE  df asymp.LCL asymp.UCL\n Control     -0.295 0.0779 Inf    -0.447    -0.142\n CBT         -1.322 0.0779 Inf    -1.475    -1.170\n\nConfidence level used: 0.95 \n contrast      estimate   SE  df z.ratio p.value\n Control - CBT     1.03 0.11 Inf   9.327 <0.0001\n```\n\n\n:::\n:::\n\n\n`emtrends()` estimates the Week slope separately for Control and CBT. `pairs()` tests their difference, which corresponds to the interaction.\n\nWe can also estimate model-implied group means at the observed weeks:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nestimated_means <- emmeans::emmeans(\n  random_slope_model,\n  specs = ~ group | week,\n  at = list(week = c(0, 2, 4, 6))\n)\n\nestimated_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nweek = 0:\n group   emmean    SE  df asymp.LCL asymp.UCL\n Control   35.7 0.802 Inf      34.1      37.2\n CBT       34.0 0.802 Inf      32.5      35.6\n\nweek = 2:\n group   emmean    SE  df asymp.LCL asymp.UCL\n Control   35.1 0.794 Inf      33.5      36.6\n CBT       31.4 0.794 Inf      29.8      33.0\n\nweek = 4:\n group   emmean    SE  df asymp.LCL asymp.UCL\n Control   34.5 0.816 Inf      32.9      36.1\n CBT       28.8 0.816 Inf      27.2      30.4\n\nweek = 6:\n group   emmean    SE  df asymp.LCL asymp.UCL\n Control   33.9 0.866 Inf      32.2      35.6\n CBT       26.1 0.866 Inf      24.4      27.8\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nDo not automatically test every possible pair at every possible week because the software makes it easy. That is how a sensible research question becomes 28 tests and a dead salmon. Choose comparisons that answer the theory, and adjust for multiplicity when you conduct a family of tests.\n\n## Should Time Be Continuous or Categorical?\n\nTreating Week as numeric assumes a straight-line average trajectory. That is a strong but efficient summary: one slope per group.\n\nIf change may be nonlinear—perhaps treatment helps rapidly and then levels off—treat occasion as categorical:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncategorical_time_model <- glmmTMB::glmmTMB(\n  depression ~ occasion * group + (1 + week | participant),\n  data = mixed_data,\n  REML = TRUE\n)\n\nsummary(categorical_time_model)$coefficients$cond\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          Estimate Std. Error   z value     Pr(>|z|)\n(Intercept)             35.6044655  0.8172028 43.568704 0.000000e+00\noccasionWeek 2          -0.4164512  0.4114638 -1.012121 3.114801e-01\noccasionWeek 4          -1.1898064  0.4402741 -2.702422 6.883630e-03\noccasionWeek 6          -1.7057961  0.4844990 -3.520742 4.303404e-04\ngroupCBT                -1.3749344  1.1556992 -1.189699 2.341647e-01\noccasionWeek 2:groupCBT -2.6145688  0.5818977 -4.493176 7.016878e-06\noccasionWeek 4:groupCBT -4.4122466  0.6226416 -7.086335 1.377106e-12\noccasionWeek 6:groupCBT -6.2538495  0.6851850 -9.127242 7.026650e-20\nattr(,\"ddf\")\n[1] \"asymptotic\"\n```\n\n\n:::\n:::\n\n\nCategorical time estimates separate deviations at Weeks 2, 4, and 6. It is flexible but uses more parameters. Numeric time is compact but imposes shape. Neither coding is morally superior. The choice depends on the research question, plausible change process, timing, and amount of data.\n\nOther options include polynomial terms, splines, or nonlinear models. Do not add a seventh-degree polynomial merely because R accepts it. R will also accept many bad ideas with the serene indifference of a vending machine.\n\n## Missing Repeated Observations\n\nMixed models can use participants who are missing some occasions; they do not require deleting every person with one missing row. This is a major advantage over older complete-case repeated-measures procedures.\n\nHowever, “the model ran” does not mean missing data ceased to matter. Standard likelihood-based mixed-model inference commonly relies on a **missing at random** assumption conditional on variables in the model. If people with worsening symptoms leave the study for reasons the model does not capture, the missingness can bias results. Investigate dropout, include relevant predictors when justified, and conduct sensitivity analyses in serious work.\n\n## Check the Model\n\nAt minimum, examine:\n\n- whether the mean trajectory is represented sensibly;\n- residual-versus-fitted patterns;\n- severe residual outliers;\n- the distribution and influence of clusters;\n- convergence and singular-fit warnings;\n- whether variance changes across time or groups;\n- whether enough participants—not merely enough rows—support the model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndiagnostic_data <- data.frame(\n  fitted = fitted(random_slope_model),\n  residual = resid(random_slope_model)\n)\n\nggplot(diagnostic_data, aes(x = fitted, y = residual)) +\n  geom_point(alpha = 0.35, color = \"steelblue4\") +\n  geom_hline(yintercept = 0, linetype = 2, color = \"firebrick\") +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"black\") +\n  labs(x = \"Fitted value\", y = \"Residual\") +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](Chapter_Mixed_Regression_files/figure-html/mixed-diagnostics-1.png){fig-align='center' fig-pos='H' width=576}\n:::\n:::\n\n\nTraditional repeated-measures ANOVA emphasizes **sphericity**. A mixed model does not require that single sphericity assumption, but it does require a defensible covariance/random-effects structure. We did not escape assumptions. We traded one rigid assumption for a model that must be specified thoughtfully.\n\n## Reporting the Result\n\nA compact results paragraph could read:\n\n> Depression scores were analyzed with a linear mixed-effects model containing fixed effects of Week, Group, and their interaction, plus correlated participant random intercepts and Week slopes. The Week × Group interaction was negative, $b =$ -1.03, $SE =$ 0.11, $z =$ -9.33, $p$ < .001, indicating that depression declined more rapidly in CBT than in the control condition. The p-value used the Wald z approximation reported by `glmmTMB`.\n\nA real report should also provide confidence intervals, descriptive/model-implied means, the exact random-effects structure, software, missing-data handling, and theoretically planned follow-ups. The paragraph above is the skeleton. Please give it organs before submitting it to Reviewer 2.\n\n## The Survival Version\n\n- A mixed design contains at least one between-subjects predictor and one within-subjects predictor.\n- Repeated occasions are nested within people, so ordinary independent-error regression is incomplete.\n- Fixed effects describe average intercepts, slopes, group differences, and interactions.\n- Random intercepts allow people to start at different levels.\n- Random slopes allow people to change at different rates.\n- With baseline coded as Week 0, the Group coefficient is the baseline group difference.\n- The Week × Group coefficient is the difference between group slopes.\n- Compare fixed-effects structures using models fit with maximum likelihood, not REML.\n- Continuous time tests a compact trajectory; categorical time permits separate occasion patterns.\n- Mixed models can retain partially observed participants, but missingness can still bias the answer.\n- Never count rows and forget to count people. Four hundred observations from 100 people are not 400 independent humans, no matter how urgently the grant deadline approaches.\n\nThe model is “mixed” because it combines fixed and random effects—not because we placed several statistical procedures into a blender and hoped the lid stayed on.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}