{
  "hash": "2958ed3452dab98873d646e833d2d865",
  "result": {
    "markdown": "---\ntitle: \"Mixed Regression: Between People and Within People\"\n---\n\n\n\n\n\n## Your Paired *t*-Test Was a Mixed Model All Along\n\nThe [paired-samples *t*-test chapter](Chapter_Paired_t_test.qmd) gave 48 students one lecture with chocolate and one without, then measured how long their eyes stayed on the screen. Here is that study again, same seed and same 48 students, so this chapter runs from the top without sending you back a chapter to fetch the data.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(343)\n\nn <- 48\n\n# Each student has a personal tendency to stare that follows them into BOTH\n# conditions. That shared tendency is the entire reason pairing works.\nparticipant_effect <- rnorm(n, mean = 0, sd = 1.20)\n\npaired_wide <- data.frame(\n  participant  = factor(seq_len(n)),\n  no_chocolate = 5.00 + participant_effect + rnorm(n, 0, 0.80),\n  chocolate    = 5.75 + participant_effect + rnorm(n, 0, 0.80)\n)\n\npaired_wide$difference <-\n  paired_wide$chocolate - paired_wide$no_chocolate\n\n# 48 rows become 96: one row per measurement instead of one row per person.\npaired_long <- tidyr::pivot_longer(\n  paired_wide,\n  cols      = c(no_chocolate, chocolate),\n  names_to  = \"condition\",\n  values_to = \"fixation\"\n)\n\npaired_long$condition <- factor(\n  paired_long$condition,\n  levels = c(\"no_chocolate\", \"chocolate\"),\n  labels = c(\"No chocolate\", \"Chocolate\")\n)\n```\n:::\n\n\n\nThere are two ways to analyze this. The first is the one you already know. Collapse each student down to a single difference score and ask whether those differences average to zero:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npaired_result <- t.test(\n  paired_wide$chocolate,\n  paired_wide$no_chocolate,\n  paired = TRUE\n)\n\npaired_result\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  paired_wide$chocolate and paired_wide$no_chocolate\nt = 4.3366, df = 47, p-value = 7.597e-05\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.4209697 1.1495099\nsample estimates:\nmean difference \n      0.7852398 \n```\n:::\n:::\n\n\n\nThe second way never computes a difference at all. It hands R all 96 measurements in long format, plus one piece of information the *t*-test was only ever told indirectly, through the row order: which measurements came from the same human.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lme4)      # fits the mixed model\nlibrary(lmerTest)  # adds degrees of freedom and p-values to the fixed effects\n\nchocolate_model <- lmer(\n  fixation ~ condition + (1 | participant),\n  data = paired_long\n)\n\nsummary(chocolate_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: fixation ~ condition + (1 | participant)\n   Data: paired_long\n\nREML criterion at convergence: 297.6\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.87123 -0.50482 -0.02554  0.43379  2.44023 \n\nRandom effects:\n Groups      Name        Variance Std.Dev.\n participant (Intercept) 0.6453   0.8033  \n Residual                0.7869   0.8871  \nNumber of obs: 96, groups:  participant, 48\n\nFixed effects:\n                   Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)          4.7660     0.1727 78.1367  27.591  < 2e-16 ***\nconditionChocolate   0.7852     0.1811 47.0000   4.337  7.6e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\ncondtnChclt -0.524\n```\n:::\n:::\n\n\nFind the `conditionChocolate` row in that output. Then look back at the *t*-test.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchoc_fixed <- summary(chocolate_model)$coefficients\n\ncomparison <- data.frame(\n  method   = c(\"paired t-test\", \"lmer\"),\n  t        = c(unname(paired_result$statistic),\n               choc_fixed[\"conditionChocolate\", \"t value\"]),\n  df       = c(unname(paired_result$parameter),\n               choc_fixed[\"conditionChocolate\", \"df\"]),\n  p        = c(paired_result$p.value,\n               choc_fixed[\"conditionChocolate\", \"Pr(>|t|)\"]),\n  estimate = c(unname(paired_result$estimate),\n               choc_fixed[\"conditionChocolate\", \"Estimate\"])\n)\n\nprint(comparison, digits = 6, row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        method       t df           p estimate\n paired t-test 4.33661 47 7.59724e-05  0.78524\n          lmer 4.33661 47 7.59724e-05  0.78524\n```\n:::\n:::\n\n\nThose are not two answers that happen to agree. They are one answer, printed twice.\n\nThe degrees of freedom are worth a second look, because the two rows got to 47 by completely different routes. The *t*-test knows it has 48 differences and subtracts one. `lmer` has no idea what a difference score is; `lmerTest` works out how much independent information the 96 rows actually contain, using an approximation called **Satterthwaite's method**, and arrives at 47 anyway. It will not always land on a whole number, and later in this chapter it does not.\n\n### What `(1 | participant)` Actually Did\n\nThat term is the whole difference between the two calls. It tells R that rows sharing a participant number came from the same person, and that people arrive at a study with their own resting level of staring. Some students watch the screen. Some students watch the door.\n\nIt handles this without estimating 48 separate student coefficients. It estimates the *spread* of the students, a single number, and treats each person's own level as a draw from it:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprint(VarCorr(chocolate_model), comp = c(\"Variance\", \"Std.Dev.\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Groups      Name        Variance Std.Dev.\n participant (Intercept) 0.64532  0.80332 \n Residual                0.78689  0.88707 \n```\n:::\n:::\n\n\n\nThe `participant` line is how much students differ from each other. The `Residual` line is how much one student bounces around their own level from one measurement to the next. Those are the two piles the 96 numbers get sorted into, and we can ask what fraction of the variance sits in the first pile:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchoc_var <- as.data.frame(VarCorr(chocolate_model))\nicc <- choc_var$vcov[1] / sum(choc_var$vcov)\n\nicc\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4505776\n```\n:::\n:::\n\n\n\nSo roughly 45 percent of the variation in fixation time is students being different students, before chocolate enters the discussion. The paired *t*-test dealt with that variation by subtracting it away and never mentioning it again. The mixed model estimates it and prints it.\n\nThat proportion is also the model's answer to a question the paired *t*-test chapter asked directly: how much do a person's two measurements agree? That chapter measured the agreement head-on, as a plain correlation of 0.46, and called it the $r$ in the $-2rS_1S_2$ term that everything depended on. The two numbers are close without being identical, because they are two different estimates of the same thing: one computed directly from the pairs, one implied by the variances the model fit. The point is that the quantity has stopped being a term in a formula and become a parameter with a variance attached.\n\n\"Each person is their own control\" is a sentence from a methods lecture. `(1 | participant)` is that sentence written as an equation.\n\n### The Fixed Effect Is the Chocolate Effect\n\nThe **fixed effects** are the part of the model that answers the research question, and there are only two:\n\n- `(Intercept)`, 4.77 seconds, is average fixation time with no chocolate.\n- `conditionChocolate`, 0.79 seconds, is what chocolate adds on top of that.\n\nThe second one is not merely close to the *t*-test's mean difference. It is the mean difference, 0.79 seconds, reached from the opposite direction: the *t*-test computed 48 differences and averaged them, while the model never computed a single difference and got there anyway.\n\nFixed effects answer the research question. Random effects are how the model earns the right to answer it using 96 rows that came from 48 people.\n\n### So Why Not Just Keep Using Difference Scores?\n\nBecause a difference score needs exactly two numbers to subtract, and real designs break that requirement constantly:\n\n- **Three or more occasions.** Measure at baseline, week 2, week 4, and week 6, and there is no such thing as *the* difference.\n- **A missing row.** A student who skipped the second session has no difference score at all, so the *t*-test deletes the entire student. The mixed model keeps the session they did attend.\n- **A between-person predictor.** Treatment group, age, baseline severity. Subtracting within a person throws the person away, and those variables live on the person.\n- **People who change at different *rates*,** not merely by different amounts. A difference score has nowhere to put a slope.\n\nThe rest of this chapter is what happens when several of those arrive together in a trench coat.\n\n::: {.callout-note title=\"Where This Chapter Gets Harder, and Where It Does Not\"}\nEverything through \"Follow Up the Interaction\" is the required equipment: what a random effect is, what each fixed coefficient means, how to test the interaction, and how to follow it up. That half starts where the paired *t*-test stopped and is not optional.\n\nAfter it comes an **Advanced Topics** break. Continuous versus categorical time, missing occasions, and model checking are genuinely useful and genuinely harder, and nobody needs them to survive a homework. The Short Story at the very end covers both halves.\n\nThe reason the second half exists is that a mixed design combines a **between-subjects** variable with a **within-subjects** variable, which summons fixed effects, an interaction, repeated observations, and random effects all at once. It is not impossible. It is merely statistics arriving with all its relatives and expecting you to provide chairs.\n:::\n\n## The Design\n\nChocolate is finished. Here is a study that breaks all four of those rules at once.\n\nSuppose researchers compare cognitive behavioral therapy (**CBT**) with a control condition for reducing depression symptoms. Participants are randomly assigned to CBT or control, then complete a depression inventory at baseline and after 2, 4, and 6 weeks.\n\n- **Group** is between subjects: each person is in CBT *or* control.\n- **Week** is within subjects: each person is measured four times.\n- **Depression score** is the quantitative outcome.\n\nThe central question is not merely whether the groups differ or whether scores change. It is whether they change **differently**:\n\n> Does the slope of depression over time depend on treatment group?\n\nThat is a Week × Group interaction.\n\nThis is simulated data. Real treatment studies require clinical expertise, ethical oversight, careful monitoring, informed consent, and substantially more planning than “Alex found `rnorm()`.”\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(3436)\n\nn_per_group <- 50\npeople <- data.frame(\n  participant = factor(seq_len(2 * n_per_group)),\n  group = factor(\n    rep(c(\"Control\", \"CBT\"), each = n_per_group),\n    levels = c(\"Control\", \"CBT\")\n  ),\n  person_intercept = rnorm(2 * n_per_group, 0, 5.0),\n  person_slope = rnorm(2 * n_per_group, 0, 0.45)\n)\n\nmixed_data <- merge(\n  people,\n  data.frame(week = c(0, 2, 4, 6)),\n  by = NULL\n)\n\nmixed_data <- mixed_data[order(mixed_data$participant,\n                               mixed_data$week), ]\n\nmixed_data$depression <-\n  35 +\n  mixed_data$person_intercept +\n  (-0.20 * mixed_data$week) +\n  ifelse(mixed_data$group == \"CBT\",\n         -1.20 * mixed_data$week, 0) +\n  mixed_data$person_slope * mixed_data$week +\n  rnorm(nrow(mixed_data), 0, 2.0)\n\nmixed_data$occasion <- factor(\n  mixed_data$week,\n  levels = c(0, 2, 4, 6),\n  labels = c(\"Baseline\", \"Week 2\", \"Week 4\", \"Week 6\")\n)\n```\n:::\n\n\n\nThe data are **long**: one row per person per occasion. The participant identifier repeats because the person repeats. If your participant column disappears, stop. Do not proceed directly to the ritual sacrifice.\n\n## First Look: Means and People\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n  mixed_data,\n  aes(x = week, y = depression, group = participant, color = group)\n) +\n  geom_line(alpha = 0.13) +\n  stat_summary(\n    aes(group = group), fun = mean, geom = \"line\",\n    linewidth = 1.4\n  ) +\n  stat_summary(\n    aes(group = group), fun = mean, geom = \"point\",\n    size = 2.8\n  ) +\n  scale_x_continuous(breaks = c(0, 2, 4, 6)) +\n  labs(\n    x = \"Week\",\n    y = \"Depression score\",\n    color = \"Group\",\n    title = \"Group averages sitting on top of actual humans\"\n  ) +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![Every faint line is one participant measured four times. The two heavy lines are the group means at each week. The whole chapter is about whether those two heavy lines have different slopes.](Chapter_Mixed_Regression_files/figure-pdf/mixed-design-plot-1.pdf){fig-align='center' fig-pos='H' fig-alt='A line plot with Week on the x axis, at 0, 2, 4 and 6, and depression score on the y axis running from about 8 to about 54. One hundred faint lines, one per participant, fan out across that whole range, colored salmon for Control and teal for CBT. Two heavy lines with round markers at each week show the group means. The Control mean drifts down gently from about 36 to about 34. The CBT mean falls steeply from about 34 to about 26. The two heavy lines start close together and end far apart.'}\n:::\n:::\n\n\n\nThe bold lines show group means. The faint lines show individual trajectories. The CBT mean declines faster, but people do not all begin at the same score or change at the same rate. Some improve quickly, some slowly, and some appear to have received therapy from a motivational poster in a dentist's office.\n\nNever decide whether an effect is statistically significant by staring at whether confidence intervals overlap. CI overlap is not the direct test of a difference, and interaction tests are about **differences between differences**. Fit the model that asks the question.\n\n## Why Ordinary Regression Is Not Enough\n\nAn ordinary regression such as this is incomplete:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nordinary_model <- lm(depression ~ week * group, data = mixed_data)\n```\n:::\n\n\n\nIt treats all 400 rows as independent. They are not. Four rows belong to each participant, and observations from the same person tend to resemble one another.\n\nThis structure is called **nesting**:\n\n$$\n\\text{occasions nested within participants}\n$$\n\nThe levels are:\n\n- Level 1: repeated occasions (j);\n- Level 2: participants (i).\n\nGroup belongs to Level 2 because it does not change within a person. Week belongs to Level 1 because it does.\n\n## The Fixed Effects\n\nWe begin with the part that resembles ordinary regression:\n\n$$\nY_{ij}=b_0+b_1(\\text{Week}_{ij})+b_2(\\text{CBT}_i)\n+b_3(\\text{Week}_{ij}\\times\\text{CBT}_i)+\\text{random part}+e_{ij}\n$$\n\nBecause Week 0 is baseline and Control is the reference group:\n\n- $b_0$: estimated baseline score for Control;\n- $b_1$: expected change per week for Control;\n- $b_2$: CBT-minus-Control difference at baseline;\n- $b_3$: difference between the CBT and Control slopes.\n\nThe CBT slope is $b_1+b_3$. The interaction $b_3$ is the main research target. If it is negative, CBT scores decline faster than Control scores.\n\nNotice why coding matters. A “main effect of Group” is not a universal average group difference here. It is the group difference when Week equals zero. We chose zero to mean baseline, so the coefficient has a useful interpretation instead of describing the difference during Week Zero Hundred and Twelve, a period known only to the Probability Gods.\n\n## The Random Effects\n\nThe repeated observations require us to describe how people differ.\n\n### Random Intercepts\n\nA random-intercept model allows each participant to have their own starting level:\n\n$$\nY_{ij}=b_0+b_1\\text{Week}_{ij}+b_2\\text{CBT}_i\n+b_3(\\text{Week}_{ij}\\times\\text{CBT}_i)+u_{0i}+e_{ij}\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrandom_intercept_model <- lmer(\n  depression ~ week * group + (1 | participant),\n  data = mixed_data\n)\n\nsummary(random_intercept_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: depression ~ week * group + (1 | participant)\n   Data: mixed_data\n\nREML criterion at convergence: 2083.3\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.83426 -0.59447  0.02897  0.57344  2.42581 \n\nRandom effects:\n Groups      Name        Variance Std.Dev.\n participant (Intercept) 30.95    5.564   \n Residual                 4.67    2.161   \nNumber of obs: 400, groups:  participant, 100\n\nFixed effects:\n               Estimate Std. Error        df t value Pr(>|t|)    \n(Intercept)    35.66006    0.82731 111.08541  43.104  < 2e-16 ***\nweek           -0.29454    0.06833 298.00000  -4.310 2.22e-05 ***\ngroupCBT       -1.61122    1.16999 111.08541  -1.377    0.171    \nweek:groupCBT  -1.02796    0.09664 298.00000 -10.637  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) week   grpCBT\nweek        -0.248              \ngroupCBT    -0.707  0.175       \nweek:grpCBT  0.175 -0.707 -0.248\n```\n:::\n:::\n\n\n\nThis is the same `(1 | participant)` that reproduced the paired *t*-test at the top of the chapter, doing the same job on a larger design: give participants different intercepts, by estimating the variance of those intercepts rather than 100 unrelated participant coefficients.\n\n\n::: {.callout-note title=\"REML: The Deliberately Oversimplified Version\"}\nBy default, `lmer()` uses **REML** (*restricted maximum likelihood*) to estimate the model. I am going to hand-wave aggressively here because understanding exactly how REML works requires considerably more statistical machinery than we need.\n\nYou already know **Ordinary Least Squares (OLS)**, which chooses regression coefficients to make the residual errors as small as possible. Mixed-effects models have an additional problem: they also have to estimate **variances**, such as how much participant intercepts vary from person to person.\n\nREML is a method designed to get better estimates of those variance components. Very loosely, it tries to estimate the variance **after accounting for the fact that we already used the data to estimate the fixed effects**. That correction matters especially when samples are not enormous.\n\nFor now, the practical rule is simple:\n\n**When we care about estimating the random-effects structure, we generally use REML. When we later compare models that differ in their fixed effects, we will switch REML off.**\n\nThat is intentionally an oversimplification. Future You will deal with the details when Future You actually needs them.\n:::\n\n\n### Random Slopes\n### Random Slopes\n\nWe just allowed each participant to have their own **intercept**. In other words, people can start at different levels of depression.\n\nBut look at what our model is still assuming about **slopes**: everyone changes at the same rate.\n\nSuppose the average participant's depression decreases by 2 points each week. Does that mean *every* participant decreases by exactly 2 points each week?\n\nProbably not.\n\nOne person might improve rapidly:\n\n$$\n\\text{Depression} = 20 - 4(\\text{Week})\n$$\n\nAnother might improve more slowly:\n\n$$\n\\text{Depression} = 25 - 1(\\text{Week})\n$$\n\nAnd someone else might actually get worse:\n\n$$\n\\text{Depression} = 18 + 1(\\text{Week})\n$$\n\nThese people have different **intercepts** (they started at different levels) *and* different **slopes** (they changed at different rates).\n\nA **random-slope model** allows both of these things to happen.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrandom_slope_model <- lmer(\n  depression ~ week * group + (1 + week | participant),\n  data = mixed_data\n)\n\nsummary(random_slope_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: depression ~ week * group + (1 + week | participant)\n   Data: mixed_data\n\nREML criterion at convergence: 2075.2\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.83842 -0.52938  0.01845  0.54118  2.16024 \n\nRandom effects:\n Groups      Name        Variance Std.Dev. Corr \n participant (Intercept) 29.3955  5.4218        \n             week         0.1045  0.3233   0.07 \n Residual                 3.9820  1.9955        \nNumber of obs: 400, groups:  participant, 100\n\nFixed effects:\n              Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)   35.66006    0.80228 97.99835  44.448  < 2e-16 ***\nweek          -0.29454    0.07793 98.00139  -3.780  0.00027 ***\ngroupCBT      -1.61122    1.13460 97.99836  -1.420  0.15876    \nweek:groupCBT -1.02796    0.11021 98.00139  -9.328 3.49e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) week   grpCBT\nweek        -0.149              \ngroupCBT    -0.707  0.105       \nweek:grpCBT  0.105 -0.707 -0.149\n```\n:::\n:::\n\n\n\nThe new part is: `(1 + week | participant)`\n\nRead this as:\n\n> **Allow each participant to have their own intercept AND their own Week slope.**\n\nThe `1` allows participants to start at different levels of depression. The `week` allows participants to change at different rates.\n\nImportantly, we are **not** estimating a completely unrelated regression line for every participant. Instead, the model estimates how much people's intercepts and slopes tend to vary around the overall regression line.\n\nSo our model now contains two kinds of information:\n\n- **Fixed effects** describe the average pattern: for example, how depression changes over time on average and whether that change differs between groups.\n- **Random effects** describe how individual participants vary around that average pattern: some start higher or lower, and some improve faster or slower.\n\nThis is often exactly what we expect in longitudinal studies. People do not all begin in the same place, and they certainly do not all change at exactly the same rate merely because the spreadsheet has politely aligned their rows.\n\n::: {.callout-tip title=\"Random Intercept Versus Random Slope\"}\nA useful way to remember the difference is to picture each participant getting their own regression line.\n\n`(1 | participant)`: **Different starting points, same slope.**\n\n`(1 + week | participant)`: **Different starting points, different slopes.**\n\nIf you can picture those lines, you understand the important idea behind random slopes.\n:::\n\nLater, we will worry about how complicated the random-effects structure should be and what to do when a model has trouble estimating it. For now, the important question is conceptual:\n\n**Do we expect people to differ only in where they start, or also in how they change?**\n\n## Read the Model Without Panic\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixed_effects <- summary(random_slope_model)$coefficients\nround(fixed_effects, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              Estimate Std. Error     df t value Pr(>|t|)\n(Intercept)     35.660      0.802 97.998  44.448    0.000\nweek            -0.295      0.078 98.001  -3.780    0.000\ngroupCBT        -1.611      1.135 97.998  -1.420    0.159\nweek:groupCBT   -1.028      0.110 98.001  -9.328    0.000\n```\n:::\n:::\n\n\nRead the rows in order:\n\n1. `(Intercept)` estimates the Control group's baseline mean.\n2. `week` estimates weekly change in Control.\n3. `groupCBT` estimates the CBT-minus-Control baseline difference.\n4. `week:groupCBT` estimates how much the CBT slope differs from the Control slope.\n\nThe interaction estimate is -1.03. That means the CBT group's depression score declines about 1.03 points **more per week** than the Control group's score, on average. It does not mean CBT lowers every participant's score by exactly that much each week. Fixed effects describe an average pattern while the random effects document the inconvenient existence of individuals.\n\nNotice that the Control slope, `week`, is doing something too: -0.29 points per week, and significant. People in the control condition also improved. If we had run a one-group study we would have congratulated ourselves. This is why the interaction is the research question and the Control slope is the reason we needed a control group.\n\n::: {.callout-warning title=\"The p-Values Are Approximations, and This Is Not Your Engine's Fault\"}\nEvery column in that table except the estimate itself rests on an approximation. There is no exact sampling distribution waiting for a model like this one, so the numbers in the `df` column were not counted, they were **estimated**, using Satterthwaite's method. That is why they are free to come out fractional: the categorical-time model later in this chapter reports degrees of freedom like 252.97, which is not a number of anything.\n\nThis is a property of mixed models, not of `lmer`. Change engines and the approximation changes costume rather than disappearing: `glmmTMB`, which you will meet in graduate school, fits the same model and reports Wald *z* statistics with no degrees of freedom at all. Same model, different plumbing, and the same honest uncertainty underneath.\n:::\n\n## Test the Interaction Directly\n\nTo test whether the interaction improves the model, compare two models with the same random-effects structure:\n\n- a reduced model without Week × Group;\n- a full model with Week × Group.\n\nWhen comparing **fixed effects**, refit both models with maximum likelihood. This is the moment `lmer()`'s REML default has to be switched off by hand, in both models, or the comparison is not a legal one.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nreduced_ml <- lmer(\n  depression ~ week + group + (1 + week | participant),\n  data = mixed_data,\n  REML = FALSE\n)\n\nfull_ml <- lmer(\n  depression ~ week * group + (1 + week | participant),\n  data = mixed_data,\n  REML = FALSE\n)\n\nanova(reduced_ml, full_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData: mixed_data\nModels:\nreduced_ml: depression ~ week + group + (1 + week | participant)\nfull_ml: depression ~ week * group + (1 + week | participant)\n           npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nreduced_ml    7 2148.9 2176.9 -1067.5    2134.9                         \nfull_ml       8 2087.4 2119.3 -1035.7    2071.4 63.539  1  1.572e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nThis likelihood-ratio test asks whether allowing the groups to have different slopes improves model fit. It is not the only defensible test; coefficient tests and other approximations are also used. The important point is to match the test to the question and identify the method, not to collect p values like cursed trading cards.\n\nAfter model comparison, report estimates from the final model fit with REML when appropriate.\n\n## Follow Up the Interaction\n\nThe interaction says the slopes differ. We still want the slope within each group.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngroup_slopes <- emmeans::emtrends(\n  random_slope_model,\n  specs = ~ group,\n  var = \"week\"\n)\n\ngroup_slopes\npairs(group_slopes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n group   week.trend     SE df lower.CL upper.CL\n Control     -0.295 0.0779 98   -0.449    -0.14\n CBT         -1.322 0.0779 98   -1.477    -1.17\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n contrast      estimate   SE df t.ratio p.value\n Control - CBT     1.03 0.11 98   9.328 <0.0001\n\nDegrees-of-freedom method: kenward-roger \n```\n:::\n:::\n\n\n\n`emtrends()` estimates the Week slope separately for Control and CBT. `pairs()` tests their difference, which corresponds to the interaction.\n\nWe can also estimate model-implied group means at the observed weeks:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nestimated_means <- emmeans::emmeans(\n  random_slope_model,\n  specs = ~ group | week,\n  at = list(week = c(0, 2, 4, 6))\n)\n\nestimated_means\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nweek = 0:\n group   emmean    SE df lower.CL upper.CL\n Control   35.7 0.802 98     34.1     37.3\n CBT       34.0 0.802 98     32.5     35.6\n\nweek = 2:\n group   emmean    SE df lower.CL upper.CL\n Control   35.1 0.794 98     33.5     36.6\n CBT       31.4 0.794 98     29.8     33.0\n\nweek = 4:\n group   emmean    SE df lower.CL upper.CL\n Control   34.5 0.816 98     32.9     36.1\n CBT       28.8 0.816 98     27.1     30.4\n\nweek = 6:\n group   emmean    SE df lower.CL upper.CL\n Control   33.9 0.866 98     32.2     35.6\n CBT       26.1 0.866 98     24.4     27.8\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n:::\n:::\n\n\n\nDo not automatically test every possible pair at every possible week because the software makes it easy. That is how a sensible research question becomes 28 tests and a dead [salmon](Chapter_Multiple_Comparisons.qmd) [@bennett2010]. Choose comparisons that answer the theory, and adjust for multiplicity when you conduct a family of tests.\n\n# Advanced Topics\n\nThat is the required equipment. What follows is the part that makes a mixed model worth the trouble on real data: choosing how to represent time, keeping people who missed a session, and checking whether the model you fit is the model you should have fit. The Short Story at the end summarizes both halves, so you are not skipping the summary by stopping here.\n\n## Should Time Be Continuous or Categorical?\n\nTreating Week as numeric assumes a straight-line average trajectory. That is a strong but efficient summary: one slope per group.\n\nIf change may be nonlinear, perhaps because treatment helps rapidly and then levels off, treat occasion as categorical:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncategorical_time_model <- lmer(\n  depression ~ occasion * group + (1 + week | participant),\n  data = mixed_data,\n  control = lmerControl(optimizer = \"bobyqa\")\n)\n\nround(summary(categorical_time_model)$coefficients, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        Estimate Std. Error      df t value Pr(>|t|)\n(Intercept)               35.604      0.817 105.423  43.569    0.000\noccasionWeek 2            -0.416      0.411 252.969  -1.012    0.312\noccasionWeek 4            -1.190      0.440 260.889  -2.702    0.007\noccasionWeek 6            -1.706      0.484 112.671  -3.521    0.001\ngroupCBT                  -1.375      1.156 105.423  -1.190    0.237\noccasionWeek 2:groupCBT   -2.615      0.582 252.969  -4.493    0.000\noccasionWeek 4:groupCBT   -4.412      0.623 260.889  -7.086    0.000\noccasionWeek 6:groupCBT   -6.254      0.685 112.671  -9.127    0.000\n```\n:::\n:::\n\n\n\n::: {.callout-warning title=\"Why That `control =` Argument Is There\"}\nIt is not decoration. Fit this model with `lmer()`'s default optimizer and it reports that it failed to converge, by a margin small enough to be irritating rather than informative.\n\nThis is the situation the random-effects section warned about, and `bobyqa` is the ordinary first thing to try: a different optimizer hunting for the same maximum. It finds it, and the estimates agree with the default fit to three decimals, which is how you know the complaint was about the search and not about the model.\n\nWhat you may not do is make the warning go away by not looking at it.\n:::\n\nCategorical time estimates separate deviations at Weeks 2, 4, and 6. It is flexible but uses more parameters. Numeric time is compact but imposes shape. Neither coding is morally superior. The choice depends on the research question, plausible change process, timing, and amount of data.\n\nOther options include polynomial terms, splines, or nonlinear models. Do not add a seventh-degree polynomial merely because R accepts it. R will also accept many bad ideas with the serene indifference of a vending machine.\n\n## Missing Repeated Observations\n\nMixed models can use participants who are missing some occasions; they do not require deleting every person with one missing row. This is a major advantage over older complete-case repeated-measures procedures.\n\nHowever, “the model ran” does not mean missing data ceased to matter. Standard likelihood-based mixed-model inference commonly relies on a **missing at random** assumption conditional on variables in the model. If people with worsening symptoms leave the study for reasons the model does not capture, the missingness can bias results. Investigate dropout, include relevant predictors when justified, and conduct sensitivity analyses in serious work.\n\n## Check the Model\n\nAt minimum, examine:\n\n- whether the mean trajectory is represented sensibly;\n- residual-versus-fitted patterns;\n- severe residual outliers;\n- the distribution and influence of clusters;\n- convergence and singular-fit warnings;\n- whether variance changes across time or groups;\n- whether enough participants, not merely enough rows, support the model.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndiagnostic_data <- data.frame(\n  fitted = fitted(random_slope_model),\n  residual = resid(random_slope_model)\n)\n\nggplot(diagnostic_data, aes(x = fitted, y = residual)) +\n  geom_point(alpha = 0.35, color = \"steelblue4\") +\n  geom_hline(yintercept = 0, linetype = 2, color = \"firebrick\") +\n  geom_smooth(method = \"loess\", se = FALSE, color = \"black\") +\n  labs(x = \"Fitted value\", y = \"Residual\") +\n  theme_minimal(base_size = 11)\n```\n\n::: {.cell-output-display}\n![Residuals from the random-slope model plotted against its fitted values. We want a shapeless cloud sitting on the red zero line. Through the middle, that is what we get. The black smoother bends at both ends, where it has almost no data to average.](Chapter_Mixed_Regression_files/figure-pdf/mixed-diagnostics-1.pdf){fig-align='center' fig-pos='H' fig-alt='A scatterplot of residuals against fitted values, with fitted values running from about 10 to 51 and residuals from about -6 to +4. The points form a wide, even band centered on zero, densest between fitted values of 25 and 40, with no funnel shape. A dashed red horizontal line marks zero. A black smoothed line lies on zero through the dense middle, but dips to about -1.3 at the far left and rises to about +0.6 at the far right, where only a handful of points exist.'}\n:::\n:::\n\n\n\nThe band is even across the range and centered on zero, with no funnel and no arc, which is what we were hoping for. The smoother's droop at the far left is worth naming rather than worrying about: below a fitted value of 15 there are exactly two observations, and the black line is drawing a conclusion from them. A loess line will always find something to say at the edges of your data, whether or not there is anything there.\n\nTraditional repeated-measures ANOVA emphasizes **sphericity**. A mixed model does not require that single sphericity assumption, but it does require a defensible covariance/random-effects structure. We did not escape assumptions. We traded one rigid assumption for a model that must be specified thoughtfully.\n\n## Reporting the Result\n\nA compact results paragraph could read:\n\n> Depression scores were analyzed with a linear mixed-effects model containing fixed effects of Week, Group, and their interaction, plus correlated participant random intercepts and Week slopes. The model was fit by restricted maximum likelihood using `lmer()` from the lme4 package, and *p*-values were obtained from lmerTest using Satterthwaite's approximation to the denominator degrees of freedom. The Week × Group interaction was negative, $b =$ -1.03, $SE =$ 0.11, $t(98) =$ -9.33, $p$ < .001, indicating that depression declined more rapidly in CBT than in the control condition.\n\nA real report should also provide confidence intervals, descriptive/model-implied means, the exact random-effects structure, software, missing-data handling, and theoretically planned follow-ups. The paragraph above is the skeleton. Please give it organs before submitting it to Reviewer 2.\n\n## The Short Story\n\n- A paired *t*-test is a mixed model with one two-level within-subjects predictor and a random intercept. Same *t*, same df, same *p*, same estimate.\n- A mixed design contains at least one between-subjects predictor and one within-subjects predictor.\n- Repeated occasions are nested within people, so ordinary independent-error regression is incomplete.\n- Fixed effects describe average intercepts, slopes, group differences, and interactions.\n- Random intercepts allow people to start at different levels.\n- Random slopes allow people to change at different rates.\n- With baseline coded as Week 0, the Group coefficient is the baseline group difference.\n- The Week × Group coefficient is the difference between group slopes.\n- Compare fixed-effects structures using models fit with maximum likelihood, not REML.\n- Continuous time tests a compact trajectory; categorical time permits separate occasion patterns.\n- Mixed models can retain partially observed participants, but missingness can still bias the answer.\n- Never count rows and forget to count people. Four hundred observations from 100 people are not 400 independent humans, no matter how urgently the grant deadline approaches.\n\nThe model is “mixed” because it combines fixed and random effects, not because we placed several statistical procedures into a blender and hoped the lid stayed on.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}