{
  "hash": "cd698960b4a3d570657cf4331941daa4",
  "result": {
    "markdown": "---\ntitle: \"Linear Regression\"\n---\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## The Number Correlation Refused to Give You\n\nThe last chapter ended on a complaint. Correlation tells you that two things move together and how tightly they do it, and then refuses to say anything more. It will not tell you *why*, which is a problem for theory. It also will not tell you *how much*, which is a problem for almost everything else.\n\nYou can hear the gap the moment you ask a practical question. If a student studies one more hour a week, how many exam points does that buy? An $r$ of .45 cannot answer that, and not because it is being difficult. It threw the units away on purpose, back when we divided by both standard deviations to force the answer to sit politely between $-1$ and $+1$.\n\nRegression puts the units back. It answers in points per hour, dollars per year, and scoops of ice cream per unit of happiness. Same relationship, same arithmetic underneath, but now the number means something you could act on.\n\nThat is the upgrade, and it is why the next eight chapters are built on this one.\n\n## Introduction to Regression\n\nMany psychological studies ask: how does X *predict* Y? How does ice cream (IV) predict happiness (DV)?\n\nUnlike the *t*-test (which compares group averages), regression looks at the relationship between **two continuous variables**. *Predicting* just means making an educated guess---if I know how much ice cream you ate, I can guess how happy you are. The guess won't be perfect, but it should be reasonably close.\n\nRegression tells us **how close those guesses tend to be**.\n\nRegression predicts. It does not automatically explain causes. If people who eat more ice cream report greater happiness, ice cream may help, happier people may seek ice cream, hot weather may increase both, or the entire pattern may be driven by one billionaire buying all the cookie dough. Design and theory decide which causal stories remain plausible.\n\n**Note**: The *outcome* in ordinary regression should be interval or ratio scale. In practice, psychologists use Likert scales all the time anyway and mostly get away with it, and there is more on that fight later. Predictors are far less picky. Over the next few chapters we will feed regression categorical variables on purpose, and it will thank us for it.\n\n### The Experiment\n\nI bought several tubs of vanilla ice cream, scooped out different amounts, and handed them to students. After eating, they rated their happiness on a 0–10 \"feelings thermometer.\" Nobody got zero scoops, but some got barely a teaspoon.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The raw data: 80 students, their scoops, and how happy they said they were afterward.](Ch_11_Intro_Regression_files/figure-html/simulate-1.png){fig-align='center' fig-alt='Scatterplot of happiness against scoops of ice cream for 80 students. Scoops run from 0 to 6, happiness from 0 to 10. The cloud drifts upward from left to right with a lot of vertical scatter.' width=408}\n:::\n:::\n\n\n### Why not just use correlation?\n\nYou can, and correlation is often the first step. But correlation only handles **two variables at a time**. Regression lets us add more predictors: ice cream *plus* hot fudge *plus* cookie dough. In other words, regression scales up in ways correlation can't.\n\nHere's the correlation:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(apa)\napa(cor.test(dat$Scoops, dat$Happiness))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"*r*(78) = .60, *p* < .001\"\n```\n:::\n:::\n\n\nStrong positive correlation, as expected!\n\n## Regression Theory\n\nCorrelation and regression describe the **same linear relationship**, just differently.\n\n- **Simple linear regression** = 1 DV and 1 IV. The relationship is a straight line representing the **expected mean of Y** for each value of X.\n- **Multiple regression** = 1 DV and 2+ IVs. (Coming later.)\n\n### The Regression Equation\n\nYou probably remember from middle school: $y = Mx + b$\n\nThe modern version comes in two lines, and the difference between them matters more than almost anything else in this chapter.\n\n$$Y = B_0 + B_1X + e$$\n\nThat is what the world does: model, plus miss.\n\n$$\\widehat{Y} = B_0 + B_1X$$\n\nThat is what the model predicts. No $e$, because the model cannot know what it does not know.\n\nWhere:\n\n- $Y$ = observed value, the score the person actually gave you\n- $\\widehat{Y}$ = predicted value, what the line says they should have given you\n- $B_1$ = slope (change in prediction per one-unit increase in X)\n- $B_0$ = intercept\n- $e$ = residual, the gap between the two ($Y - \\widehat{Y}$)\n\nThe hat is the whole distinction. $Y$ is a fact about a person. $\\widehat{Y}$ is a guess about a person. Mixing them up is the single most common way to get lost in regression, and it will keep mattering all the way into the mixed models at the end of Part 2.\n\n## The Ice Cream Model\n\nWe fit regression models with `lm()` (linear model). Formula structure: **DV ~ IV**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nHappy.Model.1 <- lm(Happiness ~ Scoops, data = dat)\nsummary(Happy.Model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness ~ Scoops, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.1621 -0.9242  0.0332  1.0608  3.3565 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.9799     0.3863   7.715 3.35e-11 ***\nScoops        0.7524     0.1127   6.675 3.25e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.681 on 78 degrees of freedom\nMultiple R-squared:  0.3636,\tAdjusted R-squared:  0.3554 \nF-statistic: 44.56 on 1 and 78 DF,  p-value: 3.246e-09\n```\n:::\n:::\n\n\n### Reading the Output Without Panic\n\nThat block is the most-stared-at object in your regression course. You will meet it in every remaining chapter, it will grow extra rows, and at 2 a.m. before an assignment it will look like a ransom note. So here is what each region is, top to bottom.\n\n**Call.** Your own formula, echoed back. Worth an actual glance, because this is where you find out you regressed the wrong variable.\n\n**Residuals.** A five-number summary of the leftovers, the $e$ from the equation above. You are looking for a median near zero and roughly symmetric ends. Ours run from -5.16 to 3.36, which means the model's worst miss was about 5.2 happiness points. Nobody is being lied to catastrophically.\n\n**Coefficients table.** Four columns, one row per term:\n\n- **Estimate** is $B$. The intercept row is $B_0$, the `Scoops` row is $B_1$.\n- **Std. Error** is the standard error *of that estimate*. Same species as the SEM from the standard error chapter: run the study again with 80 different people and the slope would bounce around by roughly this much.\n- **t value** is Estimate divided by Std. Error. That is the one-sample *t*-test logic, wearing a different kimono: how many standard errors is this estimate away from zero?\n- **Pr(>|t|)** is that *t*'s *p*-value, testing the null that this coefficient is really zero (no slope).\n\n**Residual standard error.** The typical size of a miss, in the outcome's own units. Ours is 1.68, so a typical prediction is off by about 1.7 happiness points. The `on 78 degrees of freedom` is the $N-2$ we paid for in the correlation chapter, and for the same reason: two parameters estimated, this time an intercept and a slope.\n\n**Multiple R-squared.** The proportion of outcome variance the model accounts for. There is a whole section on it below.\n\n**F-statistic.** The test of the entire model at once, rather than one coefficient at a time. With a single predictor it is telling you exactly what the slope's *t*-test already told you, and we can prove that:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.for.slope <- summary(Happy.Model.1)$coefficients[\"Scoops\", \"t value\"]\n\nt.for.slope^2                          # square the slope's t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 44.55917\n```\n:::\n\n```{.r .cell-code}\nsummary(Happy.Model.1)$fstatistic[1]   # the model's F\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   value \n44.55917 \n```\n:::\n:::\n\n\nIdentical. With one predictor, $F = t^2$, because \"is this one slope non-zero\" and \"does this model do anything at all\" are the same question asked twice. That stops being true the moment we add a second predictor, which is precisely when $F$ starts earning its keep, in the hierarchical regression chapter.\n\n::: {.callout-tip title=\"The Two Numbers Everyone Skips\"}\nStudents read the Estimate and the *p*-value and stop. The two most useful numbers in that block are the ones they scroll past: the **Std. Error**, which tells you how much to trust the estimate, and the **Residual standard error**, which tells you in plain units how wrong a typical prediction is.\n\nA slope of 0.75 with typical misses of 1.7 happiness points is a very different finding from the same slope with typical misses of 0.2. The *p*-value cannot tell those apart. You can.\n:::\n\n### Intercept\n\nThe intercept is the predicted happiness **when ice cream = 0**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrange(dat$Scoops)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.02927577 5.88743768\n```\n:::\n:::\n\n\nNobody had zero scoops, so we can't actually interpret this directly. **Never predict outside the range of your data.** (We can fix this by centering X, more on that later.)\n\n### Slope\n\nThe slope is 0.752. For each additional scoop, happiness changes by that amount.\n\n### Making a prediction\n\nThe equation: $Y = B_0 + B_1X$\n\nWhat's the predicted happiness for someone who eats **5 scoops**?\n\n- $Y = 2.98 + (0.752 \\times 5)$\n- $Y = 6.742$\n\n## Predicted Values and Residuals\n\nThe line gives one predicted happiness score for every amount of ice cream. Real people do not sit perfectly on that line because humans are noisy, stubborn, and occasionally having a terrible day for reasons unrelated to dessert.\n\nA **residual** is the distance between the observed score and the model's prediction:\n\n$$\ne_i=Y_i-\\widehat{Y}_i.\n$$\n- A positive residual means the person was happier than the model predicted.\n- A negative residual means the person was less happy than the model predicted.\n- A residual of zero means the prediction was exactly right, which is suspiciously cooperative behavior from a human.\n\nR stores both pieces inside the fitted model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat$Predicted <- fitted(Happy.Model.1)\ndat$Residual <- residuals(Happy.Model.1)\n\nhead(dat[c(\"Scoops\", \"Happiness\", \"Predicted\", \"Residual\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Scoops Happiness Predicted   Residual\n1 0.4874424  4.689709  3.346669  1.3430399\n2 2.7996025  3.676425  5.086421 -1.4099958\n3 4.1977287  7.669921  6.138422  1.5314991\n4 4.7945917  6.331497  6.587523 -0.2560254\n5 3.3393869  4.690570  5.492574 -0.8020041\n6 5.2990277  7.685625  6.967079  0.7185465\n```\n:::\n\n```{.r .cell-code}\nmean(dat$Residual)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.283102e-17\n```\n:::\n:::\n\n\nThe residuals have a mean of approximately zero because ordinary least squares (i.e., math that finds the best line) tries to balance the line through the data such that the positive and negative mistakes cancel out.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dat, aes(x = Scoops, y = Happiness)) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"gray45\") +\n  geom_segment(\n    aes(xend = Scoops, yend = Predicted, color = Residual),\n    linewidth = 0.7\n  ) +\n  geom_point(aes(color = Residual), size = 2.5) +\n  geom_point(aes(y = Predicted), shape = 1, size = 2.5) +\n  scale_color_gradient2(low = \"#0072B2\", mid = \"white\", high = \"#D55E00\") +\n  labs(\n    title = \"Residuals Are the Model's Vertical Mistakes\",\n    x = \"Scoops of Ice Cream\",\n    y = \"Happiness\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Every vertical segment is one residual: the gap between what a student reported and what the line predicted for them.](Ch_11_Intro_Regression_files/figure-html/regression-residual-picture-1.png){fig-align='center' fig-alt='Scatterplot with a fitted regression line. Each observed point is joined to the line by a vertical coloured segment, blue where the person was less happy than predicted and orange where they were happier. Hollow points sit on the line at each prediction.' width=672}\n:::\n:::\n\n\nThe filled points are observed happiness. The hollow points are predicted happiness. Each vertical segment is one residual. This is the error the model did not explain.\n\n## Why This Line and Not Some Other Line?\n\nNothing so far has explained where the line came from. R drew one, we believed it. But an infinite number of straight lines could be drawn through that cloud of points, so something had to choose.\n\nHere is the rule. Take any line you like. Measure every vertical miss, square each one, and add them all up. That total is the line's score, and lower is better. The regression line is the line that makes that total as small as it can possibly be. That is the entire idea, and it is what **least squares** means.\n\nWe can check that R did its job. The fitted line's squared misses:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum(residuals(Happy.Model.1)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 220.3025\n```\n:::\n:::\n\nNow some rival lines. The first is the flattest possible one, a slope of zero, which ignores ice cream entirely and predicts the mean happiness for everybody. The other two keep our intercept but guess the slope wrong:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nb0 <- coef(Happy.Model.1)[1]\n\n# Slope of 0: the mean-only model, ice cream tells us nothing\nsum((dat$Happiness - mean(dat$Happiness))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 346.155\n```\n:::\n\n```{.r .cell-code}\n# Too steep\nsum((dat$Happiness - (b0 + 1.5*dat$Scoops))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 745.2635\n```\n:::\n\n```{.r .cell-code}\n# Too flat\nsum((dat$Happiness - (b0 + 0.3*dat$Scoops))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 412.5871\n```\n:::\n:::\n\n\nThe fitted line wins, and it is not close. Every wrong slope costs you, and the further off you guess, the more it costs.\n\n**Why squared, and not just the raw misses?** Because raw residuals sum to zero by construction, as we saw a moment ago. A criterion that adds up to zero for every possible line is a criterion that cannot choose between lines. Squaring kills the signs, which is exactly the trick variance pulled back in the distributions chapter, for exactly the same reason. It also means one enormous miss hurts far more than several small ones, which is a genuine design decision on the part of those who created regression.\n\nHold onto that mean-only number, 346.2. It is the score of a model with no predictor in it: your best guess before ice cream entered the room. The fitted line scores 220.3. The gap between those two numbers is what ice cream bought you, and turning that gap into a proportion is the entire content of the $R^2$ section coming up.\n\n## The Assumptions: What Could Make the Line Lie?\n\nRegression assumptions are claims about the errors left after fitting the line. They are not personality tests that the raw variables must pass before R permits them into the building.\n\nFor now, focus on five questions:\n\n1. **Linearity:** Is a straight line a reasonable summary of the average relationship?\n2. **Independence:** Are the residuals from different observations reasonably independent?\n3. **Constant variance:** Is the vertical spread of residuals roughly similar across fitted values?\n4. **Approximately normal residuals:** Are the residuals reasonably bell-shaped, especially for small-sample tests and intervals?\n5. **Influential observations:** Is one strange person steering the entire line while everyone else watches?\n\n### Residuals Versus Fitted Values\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(\n  fitted(Happy.Model.1),\n  residuals(Happy.Model.1),\n  xlab = \"Fitted happiness\",\n  ylab = \"Residual\",\n  pch = 19,\n  col = grDevices::adjustcolor(\"#1F4E79\", alpha.f = 0.55)\n)\nabline(h = 0, lty = 2, col = \"#D55E00\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Residuals against fitted values. We want a boring cloud around the dashed line, and this one is reasonably boring.](Ch_11_Intro_Regression_files/figure-html/regression-residual-fitted-1.png){fig-align='center' fig-alt='Scatterplot of residuals against fitted happiness values, with a dashed horizontal line at zero. Points scatter above and below the line with no obvious curve or funnel shape.' width=624}\n:::\n:::\n\nThe **residuals-versus-fitted plot** asks whether the model is making similar kinds of errors across the range of values it predicts. Each dot represents one observation.\n\n- **X-axis, Fitted values:** what the regression model **predicted** for each observation.\n- **Y-axis, Residuals:** how wrong that prediction was: **observed - predicted**. A residual of 0 means the model predicted the observation perfectly. Positive residuals mean the observed value was higher than predicted; negative residuals mean it was lower than predicted.\n\nIdeally, we want a fairly boring cloud of points scattered around zero, with roughly the same vertical spread from left to right. **Boring is good here.** It means the model is not making errors in an obvious, systematic way.\n\nA **curve** suggests that the straight-line model missed a nonlinear pattern. For example, if residuals tend to be positive, then negative, then positive again as fitted values increase, the relationship may have a bend that our straight regression line cannot capture.\n\nA **funnel** suggests **heterogeneity of variance**, also called **heteroscedasticity**: the model's errors are much more variable for some predicted values than for others. *Note: This is a word I have been teaching since about 2008 and still cannot reliably say out loud.*\n\nWhy care? Ordinary regression calculates standard errors under the assumption that the residual variance is reasonably constant. Strong heteroscedasticity can therefore make standard errors and confidence intervals inaccurate.\n\nBut changing variance can also reveal something psychologically interesting. Perhaps ice cream affects people similarly at low doses but produces wildly different reactions after the fourth scoop. Some people achieve joy. Others remember lactose intolerance.\n\n::: {.callout-warning title=\"Heterogeneity May Be a Clue, Not Merely a Violation\"}\nChanging residual spread can mean that uncertainty differs across people, conditions, or levels of the outcome. Do not immediately transform the outcome until the graph stops complaining. First ask what process could create the pattern.\n:::\n\n\n### The Q-Q Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqqnorm(residuals(Happy.Model.1), pch = 19, col = \"#1F4E79\")\nqqline(residuals(Happy.Model.1), col = \"#D55E00\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![A Q-Q plot of the residuals. Points near the line mean the residuals are behaving roughly normally.](Ch_11_Intro_Regression_files/figure-html/regression-qq-1.png){fig-align='center' fig-alt='Q-Q plot with sample residual quantiles on the vertical axis and theoretical normal quantiles on the horizontal axis. Points follow the diagonal reference line closely, with mild departure at the lower tail.' width=528}\n:::\n:::\n\n\nA **Q-Q plot** asks whether the residuals have roughly the shape we would expect from a normal distribution. Each dot represents one residual, after the residuals have been sorted from smallest to largest.\n\n- **X-axis:** where a residual *should fall* if the residuals followed a perfect normal distribution. These are called **theoretical quantiles**.\n- **Y-axis:** where the residual *actually falls* in our data. These are the **observed residuals** (or, depending on the software, standardized residuals).\n\nIf the residuals are approximately normal, the observed values should line up with the values expected from a normal distribution, producing dots that fall roughly along a straight line. In other words, the x-axis says, “If these residuals were perfectly normal, how extreme should this observation be?” and the y-axis says, “How extreme was it actually?”\n\nDo not expect perfection. Small wiggles and deviations are normal, because we collected data from humans, not from androids or clones. What we care about are **systematic departures from the line**: strong curves can indicate a distribution with the wrong shape, while points breaking away at either end can indicate unusually heavy tails or potential outliers. One observation escaping toward Canada probably means something went wrong for that one person. All of them running for the border means something went wrong with the whole model.\n\nR can produce four standard diagnostic plots at once:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(Happy.Model.1)\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![The four diagnostic plots R gives you for free. The top two are the ones we just built by hand.](Ch_11_Intro_Regression_files/figure-html/regression-four-diagnostics-1.png){fig-align='center' fig-alt='A two-by-two panel of regression diagnostics: residuals versus fitted, a normal Q-Q plot, a scale-location plot, and a residuals versus leverage plot with Cook\\'s distance contours.' width=672}\n:::\n:::\n\n\nThe first two are the residual-versus-fitted and Q-Q plots we just learned. The other two help identify unequal spread and influential observations. You do not need to master them yet. The advanced diagnostics chapter returns with more detail and several additional ways for data to misbehave.\n\n## Residual Variance and $R^2$\n\nBefore using ice cream to predict happiness, our best simple guess for everyone was the mean. The total variance describes how far scores spread around that mean. After fitting the model, residual variance describes how far scores spread around the regression line.\n\nThose are the two lines we just raced. The mean-only model was the flat one that lost; the fitted line was the one that won. $R^2$ is simply that race expressed as a proportion: of all the spread we started with, what fraction did the line manage to account for?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nTotalVariance <- var(dat$Happiness)\nResidualVariance <- var(residuals(Happy.Model.1))\n\nc(TotalVariance = TotalVariance,\n  ResidualVariance = ResidualVariance,\n  R_squared_from_variance = 1 - ResidualVariance / TotalVariance,\n  R_squared_from_model = summary(Happy.Model.1)$r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          TotalVariance        ResidualVariance R_squared_from_variance \n              4.3817090               2.7886391               0.3635727 \n   R_squared_from_model \n              0.3635727 \n```\n:::\n:::\n\n\n$R^2$ describes the proportion of observed outcome variance explained by the fitted model. It is an effect-size measure for the model, not proof that the model is causal, correct, or ready to be tattooed onto your arm.\n\n## Relationship to Correlation\n\nWhy did we start with correlation if regression is so great? To show they're the same thing, just scaled differently. Run a regression on **standardized** (z-scored) variables:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat$Happiness.z <- scale(dat$Happiness)\ndat$Scoops.z    <- scale(dat$Scoops)\n\nstd.reg <- lm(Happiness.z ~ Scoops.z, data = dat)\nsummary(std.reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness.z ~ Scoops.z, data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.46608 -0.44152  0.01588  0.50675  1.60349 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2.037e-16  8.976e-02   0.000        1    \nScoops.z     6.030e-01  9.033e-02   6.675 3.25e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.8029 on 78 degrees of freedom\nMultiple R-squared:  0.3636,\tAdjusted R-squared:  0.3554 \nF-statistic: 44.56 on 1 and 78 DF,  p-value: 3.246e-09\n```\n:::\n:::\n\n\n### What didn't change?\n\nThe **t-statistic and *p*-value** for the slope. These don't change under any *linear* rescaling: adding constants, multiplying by constants, z-scoring. Shift and stretch the axes all you like and the significance test is untouched.\n\nNonlinear transformations are a different animal. Logs, square roots, and powers change the model itself, along with $t$, $p$, and what the slope even means. The correlation chapter showed this the hard way with ice cream raised to the fourth power, where a perfectly good relationship fell apart the moment we bent the scale.\n\n### What changed?\n\n**The intercept** is now **zero**. When all variables are standardized (mean = 0), the regression line must pass through [0, 0]. And the slope changed numerically:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprint(summary(std.reg), digits = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Happiness.z ~ Scoops.z, data = dat)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-2.466080 -0.441520  0.015876  0.506753  1.603487 \n\nCoefficients:\n                Estimate   Std. Error t value   Pr(>|t|)    \n(Intercept) -2.03715e-16  8.97626e-02 0.00000          1    \nScoops.z     6.02970e-01  9.03290e-02 6.67527 3.2461e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.802862 on 78 degrees of freedom\nMultiple R-squared:  0.363573,\tAdjusted R-squared:  0.355413 \nF-statistic: 44.5592 on 1 and 78 DF,  p-value: 3.24612e-09\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(dat$Happiness, dat$Scoops)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  dat$Happiness and dat$Scoops\nt = 6.6753, df = 78, p-value = 3.246e-09\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.4417814 0.7264454\nsample estimates:\n      cor \n0.6029699 \n```\n:::\n:::\n\n\nThe standardized slope equals the correlation. Not a coincidence.\n\nWhen everything is standardized, one unit = one SD. So the correlation tells us: every time X increases by 1 SD, Y increases by $r$ SDs. Standardized regression slopes are called **beta weights ($\\beta$)**.\n\n### Converting slope back to raw units\n\n$$B_1 = r \\frac{sd_y}{sd_x} = \\frac{Cov(x,y)}{Var(x)}$$\n\nYour slope is just the correlation times the ratio of SDs. Makes sense, since slope is rise over run:\n\n- Double Y → twice as much rise → $B_1$ doubles\n- Double X → twice as much run → $B_1$ is cut in half\n\n### What about the intercept?\n\nOnce you know $B_1$, you know the angle of the line. But the line must also pass through **[mean(X), mean(Y)]**:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(dat$Scoops)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.993878\n```\n:::\n\n```{.r .cell-code}\nmean(dat$Happiness)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.232601\n```\n:::\n:::\n\n\n$$Mean(Y) = B_0 + B_1 \\times Mean(X)$$\n\nSolve for $B_0$ and you're done.\n\n## APA Style Report\n\nHere is how the whole thing gets written up. Every number below is computed from the model rather than typed, which is why it cannot go stale when the data change.\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n> Ice cream consumption significantly predicted happiness, $b =$ 0.75, $SE =$ 0.11, $\\beta =$ .60, $t(78) =$ 6.68, $p < .001$. The overall model explained 36.4% of the variance in happiness, $R^2 =$ .364, $F(1, 78) =$ 44.56, $p < .001$.\n\nThen say what it means in words a human would use:\n\n> Each additional scoop predicted about 0.75 more points of happiness on the 0 to 10 thermometer.\n\nA few things to notice, because this paragraph is the template for every regression write-up in the rest of the book:\n\n- Report $b$ **and** $SE$ **and** $t$ **and** $p$ for the predictor. The slope alone is not a result, it is half of one.\n- Report the model as a whole with $R^2$ and $F$, including both degrees of freedom: $F(1, 78)$. The 1 is the number of predictors, the 78 is $N-2$.\n- That $\\beta$ of .60 should look familiar. It is the correlation from the top of this chapter, which is the payoff we proved a section ago. In simple regression you can report either (or both), but never present them as two separate findings.\n- The plain-English sentence is not optional decoration. Being able to say what your slope means in the units your grandmother would understand is a graded skill, in this course and in every paper you will ever write.\n\n::: {.callout-warning title=\"p < .001 Is a Claim, Not a Default\"}\nThe write-up above says $p < .001$ because this model's *p*-value genuinely is 3.25e-09. Report the exact value to two or three decimals whenever it is larger than .001, and never copy `p < .001` out of an example because it looked authoritative.\n:::\n\n\n## The Short Story\n\n- Simple linear regression predicts a quantitative outcome from one predictor.\n- The intercept is the predicted outcome when $X=0$.\n- The slope is the expected change in $Y$ for a one-unit increase in $X$.\n- The line is chosen by **least squares**: of all possible lines, it is the one with the smallest total of squared vertical misses.\n- In the `summary()` output, Std. Error says how much to trust the estimate and Residual standard error says how wrong a typical prediction is. With one predictor, $F = t^2$.\n- Residuals are observed outcomes minus predicted outcomes: the model's leftovers.\n- $R^2$ is the proportion of observed outcome variance explained by the fitted linear model.\n- With one predictor, the standardized slope equals Pearson's $r$.\n- Prediction is not causation. A straight line cannot randomize participants, control confounds, or stop Reviewer 2 from asking whether heat explains the ice cream.\n\n::: {.callout-important title=\"A Slope Always Has Units\"}\nThe slope is the expected change in $Y$ for a one-unit increase in $X$. Before deciding that it is large, small, heroic, or pathetic, say what one unit of $X$ and one unit of $Y$ actually mean.\n:::\n\n::: {.callout-note title=\"Credit\"}\nI stole Ryne Estabrook way of explaining least squares cause it was better than mine. Also probably other things. \n:::\n",
    "supporting": [
      "Ch_11_Intro_Regression_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}