{
  "hash": "92c4ef2e932fd4e1245532a3e950509c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hierarchical Regression: Testing Whether Your Model Improves\"\ngeometry: margin=.5in\nfontsize: 10pt\nformat:\n  pdf:\n    toc: true\n    toc-depth: 1\n    number-sections: true\n---\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n## Where We Left Off\n\nIn the previous chapter, we used **multiple regression** to predict exam performance from two predictors simultaneously: Study Hours and Test Anxiety. We learned that each predictor has a *unique* effect on exam scores — an effect that persists even after statistically controlling for the other predictor.\n\nBy the end of that chapter, we had fit three models:\n\n- **Model 1:** Exam ~ Study Hours (simple regression, one predictor)\n- **Model 2:** Exam ~ Test Anxiety (simple regression, one predictor)\n- **Model 3:** Exam ~ Study Hours + Test Anxiety (multiple regression, both predictors)\n\nWe showed that Model 3 explained more variance in exam scores ($R^2$) than either predictor alone, and we compared the slopes before and after controlling. But we never formally asked: **does adding Test Anxiety to the model produce a statistically significant improvement?** Or put differently, is the improvement in $R^2$ when we go from Model 1 to Model 3 bigger than we would expect from chance alone?\n\nThat question is the heart of **hierarchical regression** — and it is the focus of this chapter.\n\n## What Is Hierarchical Regression?\n\n**Hierarchical regression** (also called **sequential regression**) is a strategy for building and comparing regression models in a deliberate, theory-driven order. Instead of putting all your predictors in at once, you add them in meaningful *steps* — and at each step, you ask whether the new addition genuinely improved your ability to predict the outcome.\n\nThe word \"hierarchical\" refers to the hierarchy of models, not a hierarchy of people or importance. Each model in the sequence is more complex than the one before it, and you evaluate whether that added complexity is worth it.\n\nThis approach is useful any time you have a specific question about the *incremental value* of a predictor. In our example, the question is precise and testable:\n\n> **Does Test Anxiety explain variance in exam performance above and beyond what Study Hours already explains?**\n\nNotice the phrase \"above and beyond.\" That is the language of hierarchical regression. You are not just asking whether Test Anxiety predicts exam scores (it does — we know this from the simple regression). You are asking whether it adds *something new* to a model that already includes Study Hours.\n\n## Nested Models\n\nTo compare two models formally, they need to be **nested**. Two models are nested when the predictors in the simpler model are a *subset* of the predictors in the more complex model. In other words, the simpler model is contained inside the more complex one.\n\nHere is how nesting works in our example:\n\n| Model | Predictors | Is it nested in...? |\n|---|---|---|\n| Model 1 | Study Hours | — |\n| Model 3 | Study Hours + Test Anxiety | Yes, contains Model 1 |\n\nModel 1 only has Study Hours. Model 3 has Study Hours **plus** Test Anxiety. Because Model 1's predictor (Study Hours) is fully contained within Model 3, these two models are nested. The difference between them is exactly one predictor: Test Anxiety.\n\nThis is what makes the comparison meaningful. When we compare these two models, we are directly asking: **what does Test Anxiety add, given that Study Hours is already in the model?** We are not comparing apples to oranges — we are asking a precise, surgical question about one specific addition.\n\nIf the models were *not* nested — for example, if Model A had Study Hours and Model B had Test Anxiety — we could not make a direct statistical comparison, because the difference between them involves both removing one predictor *and* adding a different one. The formal test we will use below only works for nested models.\n\n## Setting Up the Hierarchical Comparison\n\nIn our example, the research question drives the ordering of the models:\n\n**Step 1 (Block 1):** Enter Study Hours. This is our primary predictor — the one we already know matters, and the one that came first in our theoretical thinking about what drives exam performance.\n\n**Step 2 (Block 2):** Add Test Anxiety. This is the incremental question: does anxiety explain variance in exam scores *above and beyond* what study behavior already tells us?\n\nWe are deliberately **not** starting from scratch with each model. We are building on what came before, which is why this is called hierarchical or sequential entry.\n\nLet's run both models:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Block 1: Study Hours only\nModel.1 <- lm(Exam ~ StudyHours, data = dat)\n\n# Block 2: Add Test Anxiety\nModel.3 <- lm(Exam ~ StudyHours + Anxiety, data = dat)\n```\n:::\n\n\nAnd let's recall what $R^2$ looks like for each:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr2_m1 <- summary(Model.1)$r.squared\nr2_m3 <- summary(Model.3)$r.squared\n\ncat(\"Model 1 (Study Hours only): R² =\", round(r2_m1, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 1 (Study Hours only): R<U+00B2> = 0.203 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 3 (Both predictors):  R² =\", round(r2_m3, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 3 (Both predictors):  R<U+00B2> = 0.27 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Change in R²:               ΔR² =\", round(r2_m3 - r2_m1, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nChange in R<U+00B2>:               <U+0394>R<U+00B2> = 0.067 \n```\n\n\n:::\n:::\n\n\nThe $R^2$ went up when we added Test Anxiety. But $R^2$ **always** goes up when you add a predictor — even a useless one will explain a tiny sliver of variance just by chance. So we need a formal test to decide whether this improvement is meaningful.\n\n## The Change in R²: What Are We Measuring?\n\nBefore we run the test, let's understand what $\\Delta R^2$ (read: \"delta R-squared,\" or \"change in R-squared\") actually represents.\n\nRecall the Venn diagram from the previous chapter. When Study Hours is the only predictor, it explains regions $a + c$ — its unique share of the variance in exam scores, plus the variance it shares with Test Anxiety. When we add Test Anxiety to the model, we pick up region $b$: the variance in exam scores that Test Anxiety explains *uniquely*, after Study Hours has already claimed its portion.\n\n$$\\Delta R^2 = R^2_{\\text{Model 3}} - R^2_{\\text{Model 1}} = \\text{Region } b$$\n\nSo $\\Delta R^2$ is the proportion of variance in exam scores that Test Anxiety explains *uniquely* — the additional predictive power it brings to the table after Study Hours has already been accounted for. This is precisely what we want to know.\n\nThe question is: is this $\\Delta R^2$ of 0.067 ($6.7$% of variance) large enough to conclude that Test Anxiety is a genuinely useful addition? Or could a difference this big arise just from sampling variability, even if Test Anxiety had no real predictive power?\n\n## The F-Test for Model Comparison\n\nThe tool we use to answer that question is an **F-test for model comparison**. It tests the null hypothesis that the added predictor(s) explain *zero additional variance in the population* — that the improvement in $R^2$ is nothing more than noise.\n\n$$H_0: \\Delta R^2 = 0 \\text{ (Test Anxiety adds nothing beyond Study Hours)}$$\n$$H_1: \\Delta R^2 > 0 \\text{ (Test Anxiety adds meaningful predictive power)}$$\n\nThe F-statistic for this test is computed as:\n\n$$F = \\frac{\\Delta R^2 / \\Delta df_{\\text{model}}}{(1 - R^2_{\\text{full}}) / df_{\\text{residual, full}}}$$\n\nWhere:\n\n- $\\Delta R^2$ = the improvement in $R^2$ from the simpler to the more complex model\n- $\\Delta df_{\\text{model}}$ = the number of new predictors added (how many degrees of freedom were \"used up\" by the new predictors)\n- $R^2_{\\text{full}}$ = the $R^2$ of the more complex (full) model\n- $df_{\\text{residual, full}}$ = residual degrees of freedom in the full model ($n - k - 1$, where $k$ is the total number of predictors)\n\nThe numerator captures how much new variance the added predictor explains *per additional parameter*. The denominator captures the average unexplained variance per residual degree of freedom — essentially, the baseline \"noise level\" of the full model. If the ratio is large, the new predictor is explaining more variance than you would expect from noise. If the ratio is close to 1, the new predictor is not doing much better than chance.\n\nYou do not need to compute this by hand. In R, the `anova()` function computes it for you when you feed it two nested models.\n\n### Running the Comparison in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(Model.1, Model.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Exam ~ StudyHours\nModel 2: Exam ~ StudyHours + Anxiety\n  Res.Df   RSS Df Sum of Sq      F   Pr(>F)   \n1     98 11354                                \n2     97 10404  1     950.1 8.8581 0.003684 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nLet's read this output carefully. The `anova()` output when comparing two models shows:\n\n- **RSS** (Residual Sum of Squares): the total unexplained variance in each model. A lower RSS means a better-fitting model.\n- **Df**: the residual degrees of freedom for each model, and the change in degrees of freedom between models.\n- **F**: the F-statistic for the comparison.\n- **Pr(>F)**: the p-value for that F-statistic.\n\nThe key row to focus on is the second one — that is where the comparison lives. The F-statistic tells you whether the drop in residual sum of squares (i.e., the gain in explained variance) between Model 1 and Model 3 is statistically significant.\n\n### What to Look For\n\nWhen you run a hierarchical model comparison, here is what you check:\n\n**1. Is the F-test significant?**\nIf $p < .05$, the added predictor(s) explain a statistically significant amount of additional variance. The improvement in model fit is unlikely to be due to chance. In our case:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nF( 1 , 97 ) = 8.86 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\np = 0.0037 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<U+0394>R<U+00B2> = 0.067 \n```\n\n\n:::\n:::\n\n\nThe F-test is statistically significant ($F(1, 97) =$ 8.86, $p =$ 0.0037). This tells us that adding Test Anxiety to a model that already contains Study Hours produces a statistically significant improvement in fit. The 6.7% additional variance explained is more than we would expect from chance.\n\n**2. How large is $\\Delta R^2$?**\nStatistical significance tells you the improvement is real, but it does not tell you how *big* it is. Always look at $\\Delta R^2$ to judge practical importance:\n\nOur $\\Delta R^2 =$ 0.067, which means Test Anxiety explains an additional 6.7% of the observed variance in Exam Score above and beyond Study Hours. There are no universal small, medium, and large labels for raw $\\Delta R^2$. Whether this improvement matters depends on the outcome, measurement quality, theory, cost, and consequences. A tiny improvement in predicting a rare medical crisis may matter enormously; the same improvement in predicting which student will choose the blue pen may not deserve a parade. Report the number and interpret it in context instead of sending it to the Small/Medium/Large Sorting Hat.\n\n**3. What do the individual coefficients look like in the final model?**\nAfter confirming that the model improved, you examine the full model to interpret the individual slopes. The conclusion is only complete when you can say both *that* the model improved and *how* each predictor contributes.\n\n## Interpreting the Full Model\n\nNow that we have confirmed the model improved significantly, let's look at the final model in full:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(Model.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Exam ~ StudyHours + Anxiety, data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-24.3420  -7.8649  -0.3942   7.4378  22.0359 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  80.2059     7.2176  11.112  < 2e-16 ***\nStudyHours    1.4149     0.3693   3.831 0.000226 ***\nAnxiety      -0.3306     0.1111  -2.976 0.003684 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.36 on 97 degrees of freedom\nMultiple R-squared:   0.27,\tAdjusted R-squared:  0.2549 \nF-statistic: 17.94 on 2 and 97 DF,  p-value: 2.351e-07\n```\n\n\n:::\n:::\n\n\nReading this together with the hierarchical comparison gives us a complete picture:\n\n- **Study Hours** ($b =$ 1.41): Each additional hour of studying per week is associated with a 1.41-point increase in exam score, controlling for anxiety. This is statistically significant.\n\n- **Test Anxiety** ($b =$ -0.33): Each one-point increase in anxiety is associated with a 0.33-point *decrease* in exam score, controlling for study hours. This is also statistically significant, and it is the predictor whose incremental value we just confirmed with the F-test.\n\nThe overall model $R^2 =$ 0.27: together, Study Hours and Test Anxiety explain 27% of the variance in exam performance.\n\n## Visualizing the Model Comparison\n\nIt helps to see the $R^2$ values side by side. Here is a simple summary of where we are:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Model 1 (Study Hours only):       R² =\", round(r2_m1,  3),\n    \" | Adj R² =\", round(summary(Model.1)$adj.r.squared, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 1 (Study Hours only):       R<U+00B2> = 0.203  | Adj R<U+00B2> = 0.195 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 3 (Study Hours + Anxiety):  R² =\", round(r2_m3,  3),\n    \" | Adj R² =\", round(summary(Model.3)$adj.r.squared, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 3 (Study Hours + Anxiety):  R<U+00B2> = 0.27  | Adj R<U+00B2> = 0.255 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Change:                           ΔR² =\", round(r2_m3 - r2_m1, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nChange:                           <U+0394>R<U+00B2> = 0.067 \n```\n\n\n:::\n:::\n\n\nNotice that the **adjusted** $R^2$ also increased from 0.195 to 0.255. Recall that adjusted $R^2$ penalizes models for adding predictors. When adjusted $R^2$ goes up, it means the new predictor is earning its keep — the improvement in fit outweighs the cost of the extra parameter. This is consistent with the significant F-test.\n\nWe can also visualize this as a stacked bar showing how the explained variance is distributed:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](Chapter_Hierarchical_Regression_files/figure-html/variance plot-1.png){fig-align='center' width=528}\n:::\n:::\n\n\nThe orange segment — Test Anxiety's unique contribution ($\\Delta R^2 =$ 0.067) — is what the F-test just confirmed is statistically significant. It represents the additional explanatory power Test Anxiety brings to a model that already contains Study Hours. Adding it was worth it.\n\n## The Logic in Plain Language\n\nLet's step back from the numbers and make sure the core logic is clear.\n\nHierarchical regression is built on a simple and intuitive idea: **if a predictor truly matters, it should explain variance in the outcome that no other predictor in the model can already account for.** If it does not, it is just explaining the same territory as something already in the model — and we should not clutter up our model with redundant predictors.\n\nHere is the sequence of reasoning:\n\n1. **Start with what you already know.** We know Study Hours predicts exam scores. Build a model with it first.\n\n2. **Ask: does the new predictor add something?** We want to know if Test Anxiety explains variance in exam scores *above and beyond* Study Hours. The $\\Delta R^2$ tells us the size of the gain.\n\n3. **Test whether the gain is real.** The F-test evaluates whether that $\\Delta R^2$ could plausibly have arisen by chance. A significant F tells us: no, the improvement is larger than chance fluctuations in $R^2$ would predict.\n\n4. **Interpret the final model.** If the gain is significant, include the new predictor and interpret its slope. If the gain is not significant, you have evidence that the new predictor does not earn its place in the model (at least, not above and beyond what is already there).\n\nThis four-step logic applies no matter how many predictors you are adding. You could be testing whether a single predictor improves fit, or whether a whole *block* of predictors (say, all demographic variables, or all anxiety-related measures) improves fit over a baseline model. The mechanics are the same.\n\n## Blocks of Predictors\n\nOne of the most powerful applications of hierarchical regression is adding **blocks** of predictors — groups of theoretically related variables — all at once. For example, imagine we had three anxiety-related measures instead of one. We could build:\n\n- **Block 1:** Study Hours\n- **Block 2:** Test Anxiety + Generalized Anxiety + Worry (three anxiety measures added simultaneously)\n\nThe F-test for Block 2 would then ask: do these three anxiety measures *together* explain additional variance in exam scores, above and beyond Study Hours? The degrees of freedom for the F-test would be 3 (one per added predictor), and the test is still a single, omnibus comparison — no need to test each anxiety measure separately at this stage.\n\nThis is particularly useful when you want to:\n\n- **Control for covariates** (e.g., age, gender) by entering them in Block 1, then test your predictors of interest in Block 2\n- **Test a theoretical construct** measured by multiple items, rather than testing each item individually\n- **Evaluate competing theories** by building them into successive models and checking which block produces the largest gain in $R^2$\n\n## What Not to Do: The Danger of \"Fishing\"\n\nHierarchical regression is a tool for **theory-driven** model building. The order in which you enter predictors should be decided *before* you look at the results, based on your understanding of the literature and your hypotheses.\n\nIt is tempting to try many different orderings and report the one that looks best. This is a form of \"fishing\" — running multiple comparisons in the hope of finding a significant result — and it inflates the Type I error rate. If you run 20 model comparisons, you should expect one of them to be \"significant\" by chance at the $p < .05$ threshold, even if nothing is real.\n\nThe safe approach: decide on your model sequence based on theory, pre-register it if you can, and report all models you tested — not just the one that \"worked.\"\n\n## APA Write-Up\n\nHere is how to report a hierarchical regression analysis in APA format:\n\n\nPrior to the main analysis, zero-order correlations were examined. Study hours positively correlated with exam performance ($r = .45$, $p < .001$), and test anxiety negatively correlated with exam performance ($r = -.40$, $p < .001$). The two predictors were also significantly correlated with each other ($r = -.35$, $p < .001$).\n\nA hierarchical multiple regression was conducted to examine whether test anxiety explained variance in exam performance above and beyond study hours. Study hours was entered in Step 1, and test anxiety was added in Step 2.\n\nIn Step 1, study hours significantly predicted exam performance, $b =$ 1.8, $SE =$ 0.36, $t(98) =$ 5, $p < .001$, $R^2 =$ 0.203, adjusted $R^2 =$ 0.195.\n\nIn Step 2, the addition of test anxiety produced a statistically significant improvement in model fit, $\\Delta R^2 =$ 0.067, $F(1, 97) =$ 8.86, $p =$ 0.0037. In the final model, both study hours ($b =$ 1.41, $SE =$ 0.37, $t(97) =$ 3.83, $p < .001$) and test anxiety ($b =$ -0.33, $SE =$ 0.11, $t(97) =$ -2.98, $p =$ 0.0037) significantly predicted exam performance. The final model explained 27% of the variance in exam scores, $R^2 =$ 0.27, adjusted $R^2 =$ 0.255.\n\n\nA few things to notice in this write-up:\n\n- Report each *step* as a block, not just the final model. Readers need to see what each step added.\n- Report $\\Delta R^2$ and the F-test for the change — these are the key hierarchical results.\n- After reporting the model comparison, also report the individual slopes from the final model.\n- Use the phrase **\"above and beyond\"** or **\"produced a statistically significant improvement in model fit\"** to signal that a hierarchical comparison is being reported.\n\n::: {.callout-important title=\"The Order Must Come from the Question\"}\n$\\Delta R^2$ belongs to a particular sequence of models. Enter predictors in an order justified by theory or design, not the order that made the Probability Gods finally hand you an asterisk.\n:::\n",
    "supporting": [
      "Chapter_Hierarchical_Regression_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}